### ISSUE TITLE
improve the performance of audio echo

### ISSUE THREAD

**Issue by alexd555** [google/oboe#100]
Hi,
Could you explain how to use this library ?
How much better can it improve the latency than OpenSL ES ?

I have this implementation of audio echo with hpf filter and I want to improve performance and latency.
Maybe, do I need to add threads ?
https://github.com/alexd555/projectA

Could you help ?

Thanks,
Alex

**Comment by dturner** [comment]
Oboe is a wrapper for the AAudio and OpenSL ES APIs. It will use AAudio on devices running Android version 26+ for best performance. 

Could you be more specific about your problem, are you getting audio glitches? Are you trying to improve computational throughout? 

This article might help: https://medium.com/@donturner/debugging-audio-glitches-on-android-ed10782f9c64

**Comment by alexd555** [comment]
I want to improve latency.
What do you mean "glitches" ? Give me example please.

**Comment by dturner** [comment]
A glitch is caused when you cannot supply audio data within the audio callback deadline. https://youtu.be/C0BPXZIvG-Q?t=15m52s

You cannot improve latency. All you can do is use the Oboe library and follow the best practices for setting up an audio stream (sharing mode: exclusive, performance mode: low latency, buffer size: 2 bursts). This will give you optimal audio latency on the widest range of devices.
