### ISSUE TITLE
Question: Rewriting the ndk audio-echo example with oboe

### ISSUE THREAD

**Issue by tomkocse** [google/oboe#1008]
Hi,

I have been developing an app based on the old ndk audio-echo example:
https://github.com/android/ndk-samples/tree/master/audio-echo/

However, I find that it doesn't work on Samsung mobile phone A70, A71. 
To be more specific, the computation of the app becomes very slow after calling the function slCreateEngine() from OpenSLES.
But the problem will be solved if I pause the app by app switching of closing the screen.
I find some bug reports saying that OpenSLES is having problems on Samsung mobile.

I would like to replace the OpenSLES in my app with aaudio or oboe but I find it difficult in rewriting the code.

Could you please tell me if there are any tutorials or similar examples to help me with the coding?
It will be great if there are some example like the ndk audio-echo using aaudio or oboe.

Thank you very much.

**Comment by philburk** [comment]
Hello, We have an echo example for Oboe called Live-Effect.
Instructions for building and running the sample apps is at https://github.com/google/oboe/tree/master/samples

There is also this OpenSL ES to Oboe Migration Guide
https://github.com/google/oboe/blob/master/docs/OpenSLESMigration.md

BTW, if you want to pursue the performance bug then please open a different Issue and provide more information.

Reopen this if you have related questions.
