### ISSUE TITLE
oboe might leak openSL ES objects when closing down

### ISSUE THREAD

**Issue by ggfan** [google/oboe#101]
when using Oboe on Android-25 + Nexus 9, closing down stream causing the following logcat:
E/libOpenSLES: Object::Destroy(0x7829598a00) for engine ignored; 1 total active objects
    Object::Destroy(0x7829598a00) for engine ignored; active object ID 2 at 0x782877fe00

The code could be found [here](https://github.com/ggfan/oboe/tree/loopback/samples), under echo directory

confirmed that this also happens when forcing openSLES on pixel + Android P.

**Comment by philburk** [comment]
Is this related to this pull request:
https://github.com/google/oboe/pull/94

**Comment by dturner** [comment]
Needs verifying

**Comment by dturner** [comment]
Attempted to reproduce the issue by running the LiveEffect (previously known as echo) sample. Started and stopped the sample multiple times and did not encounter any errors in the logs. Assuming fixed thanks to @iamyellow's patch.
