### ISSUE TITLE
oboe::AudioStreamBase::getFramesPerCallback() returns 0 after stream created

### ISSUE THREAD

**Issue by ggfan** [google/oboe#102]
is this function same as gtFramesPerBurst()?

GetFramesPerCallabck() returns 0 for newly created stream! mFramePerCallback does not seems to be set in any place in code.

It should return some value for the current frames per callback, I think.

**Comment by dturner** [comment]
When using AAudio a return value of 0 indicates variable frames per callback. See: https://developer.android.com/ndk/reference/group/audio#group___audio_1ga92412cadd7d8ab73ffbb6efa16b2bb50

Does this happen when using OpenSL ES as well?

**Comment by ggfan** [comment]
No, openSL ES returns the fast path frame count/ burst.  It is not an issue then. Thanks
