### ISSUE TITLE
hello-oboe does not build on Android Studio 4.0.1 and gradle 6.1.1 - says NDK not configured

### ISSUE THREAD

**Issue by sjeast** [google/oboe#1025]
I downloaded the latest oboe code and am trying to build hello-oboe on Android Studio 4.0.1 (on OSX) with gradle 6.1.1 installed. It won't let me build it and says:

  NDK not configured. Download it with SDK manager. Preferred NDK version is '21.0.6113669'. 

  Update NDK version to 21.0.6113669 and sync project

I have downloaded that version of the NDK in the SDK tools. I also have the latest version 21.3.6528147 installed.

For both of these NDK versions I have set the NDK to the appropriate version in Project Structure and in updated the NDA version no in build.gradle - but I always get the same message above and the project refuses to build. 

Even when I change the NDK version to 21.3.6528147 I still get the message about 21.0.6113669 so it is clearly specified elsewhere in the configuration - but if so I can't find it. 

Any pointers on what I am doing wrong would be appreciated.

**Comment by dturner** [comment]
It sounds like you might be importing the wrong folder into Android Studio - are you importing the `samples` folder?

Also, you might want to do File -> Invalidate Caches and Restart as this can fix a few issues.

**Comment by sjeast** [comment]
Ah OK - I was importing the hello-oboe folder - when I import the samples folder then it all seems to work. I did do an invalidate cache too so maybe that helped.
