### ISSUE TITLE
possible issue with stream failing to start occasionally

### ISSUE THREAD

**Issue by strommj** [google/oboe#1029]
Android version(s): 10 (haven't tried 11 yet)
Android device(s): Pixel 3a
Oboe version: 1.4.3
App name used for testing: https://play.google.com/store/apps/details?id=com.musiciansAide.app (app with error). If I experience the behavior again, I will try testing with the oboe Tester
 
**Short description**
Occationally when starting the audio stream, I get error code -889 ErrorUnavailable from `AAudioStream_RequestStart()`, and thus no sound is produced. Restarting the physical device seems to solve this issue.

The bellow is the logging output I have captured:

```
I/AAudio: AAudioStreamBuilder_openStream() called ----------------------------------------
I/AudioStreamBuilder: rate   =      0, channels  = 2, format   = 0, sharing = EX, dir = OUTPUT
I/AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
I/AudioStreamBuilder: usage  =      1, contentType = 2, inputPreset = 6, allowedCapturePolicy = 0
D/AudioStreamInternal_Client: open() original HW burst = 48, minMicros = 2000 => SW burst = 96
I/AAudio: AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------
D/MyApp: AudioEngine: Sample Rate: 48000 FramesPerBurst: 96 BufferSize: 192
D/MyApp: AudioEngine: Channel count: 2 Format: Float Direction: Output
D/MyApp: AudioEngine: Current Buffer Size: 288 BufferCapacity: 3072 SharingMode: Exclusive PerformanceMode: LowLatency
D/AAudio: AAudioStream_requestStart(s#1) called --------------
D/AAudio: AAudioStream_requestStart(s#1) returned -889 ---------
E/MyApp: AudioEngine: Error starting stream. ErrorUnavailable
```

**Steps to reproduce**
I'm hoping you can help me with this, currently I have had suspicions that the Audio Device had something to do with it, but I cannot reproduce it consistently. What are possible causes of getting -889 ErrorUnavailable? I cannot find any information on this other than the error code definition. I realize not being able to reproduce the problem is not ideal, so if you think this is not in cause by oboe then feel free to close this appropriately.

**Expected behavior**
Starts the stream and sends audio to the audio device
**Actual behavior**
Stream creation fails with error, and no audio is transferred
**Device**
Google Pixel 3a

Here is device info for my Pixel 3a:

ro.product.brand = google
ro.product.manufacturer = Google
ro.product.model = Pixel 3a
ro.product.device = sargo
ro.product.cpu.abi = arm64-v8a
ro.build.description = sargo-user 10 QQ3A.200805.001 6578210 release-keys
ro.hardware = sargo
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

**Any additional context**
If it matters, I'm also loading 13 sound files into memory before opening the stream that are all around 190kB. (using `AAssetDataSource`, which I believe is in one of the examples). Perhaps this is related to a ram issue since it's hard to reproduce, but I have no evidence to back this up. I don't remember my phone acting sluggish when this bug has occured. I have been able to reproduce this by turning off my bluetooth and starting the app, but I have not been able to reproduce this (I think it was just a fluke coincidence)

My stream creation looks like this:
```c++
AudioStreamBuilder builder;
builder.setCallback(this);
builder.setPerformanceMode(PerformanceMode::LowLatency);
builder.setSharingMode(SharingMode::Exclusive);
builder.setChannelCount(mChannelCount);

Result result = builder.openStream(&mStream);

if (result == Result::OK && mStream != nullptr) {
    // log info, and any applicable errors
}
```

If applicable, please attach a recording of the sound.

**Comment by philburk** [comment]
The error code seems to be coming from AAudioStream_requestStart().
I have searched the code using this query:
    https://cs.android.com/search?q=AAUDIO_ERROR_UNAVAILABLE&sq=

But I do not see an obvious reason for the failure.

How often does start fail? 10% of the time?

Are you generally using the speakers, or a wired headset, or Bluetooth?

Once it happens does it always fail until you reboot? If so then it sounds like a problem in the service.

If the audio gets stuck, try:
    adb root
    adb shell kill audioserver
then try the app again. Does it work?

I need more detailed logs.

If you get a bugreport https://developer.android.com/studio/debug/bug-report
with more detail then please copy the System Log between the open() and the failure in Start.

Or, even better, attach the whole file to a Buganizer bug. You can file it here:
    https://issuetracker.google.com/issues/new?component=898361&template=1458029

Then let me know the bug number. Do not attach a bugreport file to a public GitHub issue.

**Comment by philburk** [comment]
BTW, I notice you are not stopping or closing the EXCLUSIVE stream when you are in the background.
That can prevent other apps from using that resource.
If you need to make the metronome sound in the background then OK because the user will hear it.
But if the metronome is stopped then close the stream.

**Comment by philburk** [comment]
Also, BTW, nice app! I like the ability to add a triplet or other timing on each beat. Easy UI.

**Comment by strommj** [comment]
I'd say it fails less than 10% of the time (rare) on my device. However, I heard a friend that downloaded the app had this problem upon first install (the Galaxy s9+ phone). I'm trying to get more info from him regarding his context of the issue.

When I have had it happen, my Bluetooth is usually enabled, but I don't have any devices actively connected to the phone. That's why I thought to disable Bluetooth and try opening up the app, which seemed to reproduce the issue, but I haven't been able to repeat this. I also know my phone allows my car to automatically connect, but I'm assuming it closes that connection when I leave. I have since tried to test connecting and disconnecting devices using the oboe tester app and my own app and have not noticed any issues.

When this has happened on my phone, it would persist until I reboot the phone.

Noted about closing the stream, that has been on my to-do list. Was thinking if this had anything to do with it, but perhaps not if it has happened upon first use.

I will try the above that you mentioned, and look into bug-reports.  I can update this issue with more info when I am able to reproduce this again.

**Comment by strommj** [comment]
Update: the issue with the galaxy s9+ was a different issue actually, so currently my pixel 3a is the only one to experience this problem. So I'm back to wondering if closing the stream could cause this? Can multiple exclusive streams exist at the same time, potentially piling up over time and eventually fail like in the above situation?

**Comment by philburk** [comment]
Closing as obsolete.
