### ISSUE TITLE
Inconsistent microphone signal on Android 11 Pixel devices upon device restarts.

### ISSUE THREAD

**Issue by Artaches** [google/oboe#1044]
Android version(s): Android 11
Android device(s): Pixel 3, 3a, 4a
Oboe version: 1.4+
App name used for testing: LiveEffect
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
There seems to be two states the phones can get into, a good (expected behavior) state and bad state. This problem can be seen in the LiveEffect sample app. For example with a Pixel 3a in a good state, selecting mic with ID 20 gives a stereo signal with bottom mic outputting to left headphone channel and top mic outputs to right headphone channel. In a bad state using the same mic ID the are swapped: bottom mic outputs to the RIGHT headphone channel and top mic outputs to the LEFT channel. Also system AGC is turned on when the phone is in bad state.

**Steps to reproduce**
The states are determined upon phone bootup somehow, and we couldn't find any consistent methodology to get into either of the states besides just continuously restarting the phone until the state changes (at times it takes 5-10 restarts).

**Expected behavior**
We expect the signal from a particular microphone to behave identically across device restarts.

**Actual behavior**
The signal from a particular microphone is different across device restarts.

**Device**
Pixel 3, Pixel 3a, Pixel 4a.

**Comment by Artaches** [comment]
Upon further investigation, it seems like the position of the mics has been swapped between good/bad states. You can query the position vector via `https://developer.android.com/reference/android/media/MicrophoneInfo` class.
On a Pixel 3a (Android 11), we get the following values from MicrophoneInfo.getPosition():
Good state:
    ID=20: (0.0269, 0.0058, 0.0079)
    ID=21: (0.0546, 0.1456, 0.00415)
Bad state:
    ID=20: (0.0546, 0.1456, 0.00415)
    ID=21: (0.0269, 0.0058, 0.0079)

**Comment by Artaches** [comment]
We see the exact same behavior on the Pixel 3:
Good state:
ID=20: (0.0269, 0.0058, 0.0079)
ID=21: (0.0546, 0.1456, 0.00415)
Bad state:
ID=20: (0.0546, 0.1456, 0.00415)
ID=21: (0.0269, 0.0058, 0.0079)

**Comment by philburk** [comment]
@Artaches - thanks for the report. The clue about device 20/21 getting reversed is very helpful.

I am testing on a Pixel 3a running S master. It is probably very similar to R (Android 11).

There are two devices for "built-in-microphone", IDs 20 and 21.

When I select them manually and then make a recording I can see that they have reversed channel assignments.
For device 20 the bottom mic is channel[0] and the top mic is channel[1]. For device 21 they are reversed and the gain is higher. That sounds consistent with the two states you are experiencing.

![oboe_bug_1044_mics_20_21](https://user-images.githubusercontent.com/5175913/97476541-bcee4a80-190b-11eb-9574-39afa43196fb.png)


It seems the default assignment of mic configurations on bootup is changing. Probably a race condition.

**Comment by philburk** [comment]
I talked to someone on the HAL team. The device ID is not guaranteed to be the same after you reboot. So it is possible for the positions to switch.

BUT, if you select the default device (UNSPECIFIED) then you should always get the same result.

@Artaches - Are you using the default "Auto Select" in Live Effect or are you selecting a specific device?

**Comment by Artaches** [comment]
We are selecting a specific mic device ID. On Android 10 we've never seen the ID switch, so we've come to rely on the ID's in our app. For Android 11 as a workaround we're now checking the position vectors to detect the mic IDs switching; in which case we are simply switching to the other ID.

**Comment by philburk** [comment]
You can also check the micInfo.getAddress(). It may be "bottom" or "back", etc.

**Comment by Artaches** [comment]
Default device (UNSPECIFIED) doesn't work well for us since if users are using TRRS or BT headsets then "UNSPECIFIED" defaults to externals mics, which is something we don't want. For our application we need a consistent method to getting stereo from the internal mics. So far we've been relying for the most part on the mic IDs to identify the mic locations / stereo signal support.
Are the positions vectors or the getAddress() output guaranteed to be reliable for identifying the physical microphones? Also, is there a way for us to know when mic ID supports a stereo signal from two internal mics?

**Comment by philburk** [comment]
The Mic IDs for built-in mics can easily change when rebooting. External mic IDs can change when plugged in again.

> Are the positions vectors or the getAddress() output guaranteed to be reliable for identifying the physical microphones? 

Yes. That is the intention. If they are not then that would be a bug.

> Also, is there a way for us to know when mic ID supports a stereo signal from two internal mics?

Not that I know of.
