### ISSUE TITLE
Creating multiple Obeo/AAudio streams

### ISSUE THREAD

**Issue by bazookam7** [google/oboe#1051]
Hi,
I have some queries regarding Obeo/AAudio.
How to create multiple obeo/AAudio streams? Can I get any working sample.
Should we create separate callbacks for respective multiple streams or just use one master callback ?
(considering the audiostreams can have different properties like sample rate,etc)
How to measure the latency when using multiple streams? (measuring means get the actual time value)

**Comment by philburk** [comment]
> How to create multiple obeo/AAudio streams?

Generally, the answer is that you should **not** create multiple streams. It prevents you from getting EXCLUSIVE MMAP streams in AAudio and also adds lots of system overhead.

If you have lots of sounds then it is better to mix them in your own app and then play the mixed result using a single stream.
If some of your sounds are at different sample rates then you can use the resampler directly to resample your sounds before the final mix.  If you have several sounds that are at one rate then you could use a submix to combine them and then resample the submix.

Also, if the sound is static, like a WAV sample, then you can resample it when you load it and then play it at the default sample rate. DrumThumper does that.

https://github.com/google/oboe/blob/master/src/flowgraph/resampler/README.md

The only reason to use multiple streams is if you need to target multiple devices. You might, for example, send one sound to the speakers and a different sound to the headset.

> Should we create separate callbacks for respective multiple streams or just use one master callback ?

They should be different callback objects for each stream.

> How to measure the latency when using multiple streams?

Different devices will have different latency. You can use stream->getTimestamp() to estimate latency but do not call that from a callback.

https://github.com/google/oboe/blob/867df1c8f8239c043466395e972efc7a0645ef67/samples/hello-oboe/src/main/cpp/HelloOboeEngine.cpp#L42

Also OboeTester can be used to measure latency.

**Comment by rpattabi** [comment]
> you should not create multiple streams
> reason to use multiple streams is if you need to target multiple devices

Thanks for this recommendation. This makes me rethink about our implementation. In our app, we resorted to use multiple streams though only one stream is required at any time. Please see this brief about what we do:

1. The app has two modes. Listening mode detects pitch of the incoming sound. The other mode, Playing mode, plays a sound.
1. App starts with listening mode and we create input stream. Whenever user wants to play, we stop the input stream and open output stream. So at this stage there are two streams, input stream in stopped state and the output stream in started state.
1. When the user stops the playback, we stop the output stream and start the existing input stream. In short, as the modes are switched, we continue to stop and start input and output streams whichever is appropriate.

Originally we attempted to create a new stream on mode change and close the other stream. But we found that the initial latency makes the app's response a bit slow. So we decided to retain the created streams while keeping one of them in stopped state.

We don't request exclusive stream as we found that we don't need the lowest latency. So not getting exclusive MMap stream is not a problem for us.

Could you let me know downsides of such implementation if any? Thank you.

**Comment by philburk** [comment]
The input device and the output device are two devices. So you need two streams. That is the "multiple device" situation.
My recommendation is to avoid opening multiple streams to the same device. Some people, for example, open a stream for every sound and let the audio server do the mixing. But that is very inefficient. The app can do the mixing with much less overhead.

> Could you let me know downsides of such implementation if any? 

That should be fine. But just make sure that the streams are stopped AND CLOSED when your app is in the background and not being used. Keeping an open stream may keep the DSP open and drawing power. Also an open stream can hold resources that may be needed by another app.

**Comment by rpattabi** [comment]
It makes very good sense. Thank you for the detailed explanations.

**Comment by darth07** [comment]
Can we use these streams for streaming over rtp ?
