### ISSUE TITLE
oboe volume is lower than the AudioRecord or AudioTrack

### ISSUE THREAD

**Issue by jie545098983** [google/oboe#1052]
Android version(s):android 9
Android device(s):xiao mi 6

pic1 is use AudioRecord to get the data
![pic1](https://user-images.githubusercontent.com/9657467/97292858-c2ee1800-1886-11eb-9ae2-9154b4f7a071.png)

pic2 is use Oboe to get the data
![pic2](https://user-images.githubusercontent.com/9657467/97299158-7c50eb80-188f-11eb-9a80-49feac9d4858.png)

how can i raise the volume to the same level as the AudioRecord？ And i feed the same data to oboe, it sounds lower than feed to  audiotrack

**Comment by dturner** [comment]
@android-usb Please could you take a look and try to repro in SmokeRecorder

**Comment by jie545098983** [comment]
why does oboe record the voice is so low?

**Comment by mgood7123** [comment]
> why does oboe record the voice is so low?

AudioRecord could be normalizing the recorded data

**Comment by android-usb** [comment]
This is the case only if the DEFAULT input preset is chosen in the builder (or no preset is chosen). The Java API selects a default which gives good amplitude & quality irrespective of performance . Oboe chooses the most performant option (VoiceRecognition apparently).

If any (non-default) input preset is explicitly selected, it will be the same in Oboe as (Java) AudioRecord. Selecting "Generic" as the input preset in Oboe will show the same signal as the default in (Java) AudioRecord.

*Some* information regarding the semantics of the various AudioSource/InputProfile constants can be found here: https://developer.android.com/reference/android/media/MediaRecorder.AudioSource
