### ISSUE TITLE
Getting the dreaded "couldn't find "libnative-lib.so" when trying to use pre-built binaries.

### ISSUE THREAD

**Issue by interstar** [google/oboe#1054]
Android version(s): 6.0
Android device(s): Xaomi Pad4
Oboe version: 1.4.3

I had a working project based on forking the original example RhythmGame. Which included building Oboe from source.

Now I've moved to a new project, where I'm trying to just use the pre-built binaries, by following the instructions here : https://github.com/google/oboe/blob/master/docs/GettingStarted.md#option-1-using-pre-built-binaries-and-headers 

It compiles but immediately crashes when trying to run on the device with this error : 

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.synaesmedia.ritmos2020-E0ARGWvoFbPWChq3M4DECw==/base.apk"],nativeLibraryDirectories=[/data/app/net.synaesmedia.ritmos2020-E0ARGWvoFbPWChq3M4DECw==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
```

So is this a dependency which should have been downloaded with the Oboe pre-built binaries? Or something that's missing from the current ndk? (Seems to be 21.3.6528147)  Or something else?

**Comment by interstar** [comment]
BTW :here's my Gradle build

```
plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "net.synaesmedia.ritmos2020"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
            }
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        prefab true
    }
    ndkVersion '21.3.6528147'

}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'
    implementation 'com.google.oboe:oboe:1.4.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```

**Comment by dturner** [comment]
`libnative-lib.so` is the shared library name associated with your own project. It will be specified in your own `CMakeLists.txt`. Please could you post that and I can take a look.

**Comment by interstar** [comment]
My CMakeLists.txt is just this :
```

find_package (oboe REQUIRED CONFIG)
target_link_libraries(app oboe::oboe) # You may have other libraries here such as `log`.
```

**Comment by dturner** [comment]
Oh, I see what you've done - you've copied the `CMakeLists.txt` contents [from here](https://github.com/google/oboe/blob/master/docs/GettingStarted.md). Those instructions just tell you what you need to *add* to your existing `CMakeLists.txt` in order to add Oboe as a dependency. They're not complete instructions because we have no idea how you're building your project. 

That said, the instructions could be clearer so I've updated them to include a complete example. Here it is for convenience below: 

```
cmake_minimum_required(VERSION 3.4.1)

# Build our own native library
add_library (native-lib SHARED native-lib.cpp )

# Find the Oboe package
find_package (oboe REQUIRED CONFIG)

# Specify the libraries which our native library is dependent on, including Oboe
target_link_libraries(app log oboe::oboe)
```

Please could you try that and let me know if it fixes the problem.

**Comment by interstar** [comment]
Thanks.

Yes. I didn't have any CMakeLists.txt before, so I assumed that those extra lines were sufficient. 

However, I tried using the new version, and I'm still getting the same error :  

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.synaesmedia.ritmos2020, PID: 9311
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/net.synaesmedia.ritmos2020-IqaxPhUkEWdQET2ChyGXuw==/base.apk"],nativeLibraryDirectories=[/data/app/net.synaesmedia.ritmos2020-IqaxPhUkEWdQET2ChyGXuw==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)


```

Just to be clear, the CMakeLists.txt is in the "app" directory, the same as my build.gradle, Is this the right place for it?

**Comment by dturner** [comment]
It sounds like `libnative-lib.so` is not being built, presumably because you haven't specified the path to `CMakeLists.txt` inside your `build.gradle`. Try adding: 

```
externalNativeBuild {
        cmake {
            path '/path/to/CMakeLists.txt'
        }
    }
```

If that fails please check out the samples here: https://github.com/android/ndk-samples/

I'm closing this because it's not an issue with Oboe.
