### ISSUE TITLE
Question, on configure streams in sample LiveEffect for effect with latency.

### ISSUE THREAD

**Issue by Olofforsberg** [google/oboe#1055]
Hi

I have built a cool audio effect with a deep neural network. Now I want to test it within the oboe framework. I have managed to export my model to pure c++ environment and integrated it within oboe so my project builds alright. My first approach was to use the sample LiveEffect and within the FullDuplexPass class, I added my model as a private member. In the onBothStreamsReady member function, I pass the audio through my network and then copy the output to the void* outputData.

I set the sample rate to 8000Hz and buffer size to 32000 and the frames per callback to 8000 and run the sample on my phone, I use the logging in debug to see that my network takes around 15 ms with this settings for processing the audio, and I get the following message:
W/AudioTrack: releaseBuffer() track 0x7ae4a21c00 disabled due to previous underrun, restarting

If I keep the same setting but reduce the frames per callback to 4000 then my latency is 7 ms for just the neural network processing of the audio and if I would half it again to 2000 my network takes about 5 ms and I still get the error with underrun. 

So I am getting underrun since my network is to slow? making the output streams buffer getting empty. Is there a way to configure the stream settings so I would not get the underrun error. Could you share some pointers for how I would go about it. Is it a bad idea to use a callback for my use case, with an effect that takes quite long to process the audio?

I am ok with having some latency for now, just interesting to see if I can make the network process audio frames in this way.

**Comment by philburk** [comment]
8000 frames at 8000 Hz sample rate is one second. That is way too long for a callback.

If you can process 8000 frames in 15 msec then your neural network is plenty fast for real-time.

I recommend the following:

Use builder.setPerformanceMode(PerformanceMode::None) as a start until you can get a stable output. Then worry about low latency later.

Use the smallest possible framesPerCallback. If you do not need a fixed block size then do not specify framesPerCallback and just let Oboe callback with however many frames it needs.

Try a higher sample rate.

Try replacing the neural network with a simple gain change. "sample*=0.5;"
If that does not work then the neural network timing is not the problem.

Your maxCallbackSize will be stream->getFramesPerBurst() unless you set framesPerCallback.

setBufferSizeInFrames() should be 2*maxCallbackSize

Your capacity should be bigger than 2*maxCallbackSize

**Comment by philburk** [comment]
I have not heard back so I assume you solved the problem.
