### ISSUE TITLE
There is a loud rasping sound when recording in demo

### ISSUE THREAD

**Issue by EspoirX** [google/oboe#1058]
Android version(s):10
Android device(s):HUAWEI
Oboe version:  demo

There is a loud rasping sound when recording in demo

**Comment by dturner** [comment]
"demo" is not one of our apps or samples. Please be more specific: 

- What app are you using? 
- What steps do you follow to reproduce the problem? 
- What do you expect to happen? 
- What actually happens?
- What Android device are you using? 

There's a reason why we have a bug template.

**Comment by philburk** [comment]
Some Huawei devices have broken mono input. Which specific model are you using?
Try stereo.
Try recording with OboeTester.

**Comment by philburk** [comment]
Reopen with more details if needed.
