### ISSUE TITLE
Bluetooth microphone not recording

### ISSUE THREAD

**Issue by PedroStrongs** [google/oboe#1059]
Hi, I tried the SDK with different headsets (wired) and using the bluid in microphone always worked without problem, also when I used the internal microphone of the smartphone. The problem shows when I tried to use a bluetooth microphone, then nothing happens, no sound is recorded.

**Comment by philburk** [comment]
When you file a bug, please provide more information so we don't have to write all these questions.

I edited your subject line to indicate the problem, "not recording".

What Android device, OS version?

What BT device? Web link?

What app? Your own? someone else's?

What is "bluid"?

Try recording using OboeTester, enable BluetoothSCO on the main screen, 
then use Record and Play and select the BT SCO device.

**Comment by philburk** [comment]
The problem is likely due to not calling startBluetoothSco().
Please try this.
https://developer.android.com/reference/android/media/AudioManager#startBluetoothSco()

If that does not work then reopen with more information.
