### ISSUE TITLE
LiveEffects app on Xperia 10 II generates no sound

### ISSUE THREAD

**Issue by hisaha** [google/oboe#1060]
Device: SONY Xperia 10 II
Android version: Android 10 (Build number is 59.0.B.2.397)
Oboe version: 83e283f (2020/10/30 18:35)
Log file: [xperia10II.log](https://github.com/google/oboe/files/5473276/xperia10II.log)

[Short description]

Live Effect app on Xperia 10 II generates no sound.

[Steps to reproduce]

Step 0. Attache wired headset tXperia10 II
Step 1. Launch Live Effect
Step 2. Press start button
Step 3. No sound on the headset.

[Expected behavior]

Headset play some effected sound from its microphone.

[Actual behavior]

No sound is played.

[Log and my investigation]

I have attached the log file with selecting audio input and output device as wired headset.
I also confirmed the headset is working fine with other recording app.

I also have tried other input/output device, but the result is the same.

I have found the log like below. Routing to low-latency-record may failed...

2020-11-02 16:03:10.180 854-17058/? D/audio_hw_primary: enable_audio_route: apply mixer and update path: low-latency-record
2020-11-02 16:03:10.180 854-17058/? D/audio_route: Apply path: low-latency-record
2020-11-02 16:03:10.182 854-17058/? D/audio_hw_primary: select_devices: done
2020-11-02 16:03:10.189 854-17058/? E/audio_hw_primary: start_input_stream: cannot set hw params: Invalid argument
2020-11-02 16:03:10.189 854-17058/? D/audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-record

Would you please tell me some advice to debug this issue?

Thank you much for reading.

**Comment by philburk** [comment]
> cannot set hw params: Invalid argument

Unfortunately, error messages such as that are common the HAL.

I will investigate a possible problem with the full duplex mode in Oboe.

**Comment by hisaha** [comment]
Thanks for your investigation.

I have changed the PerformanceMode from LowLatency to None in LiveEffect.cpp, it works perfectly.

Before is,

```
oboe::AudioStreamBuilder *LiveEffectEngine::setupCommonStreamParameters(
    oboe::AudioStreamBuilder *builder) {
    // We request EXCLUSIVE mode since this will give us the lowest possible
    // latency.
    // If EXCLUSIVE mode isn't available the builder will fall back to SHARED
    // mode.
    builder->setAudioApi(mAudioApi)
        ->setFormat(mFormat)
        ->setSharingMode(oboe::SharingMode::Exclusive)
        ->setPerformanceMode(oboe::PerformanceMode::LowLatency);
    return builder;
}
```

After is,

```
oboe::AudioStreamBuilder *LiveEffectEngine::setupCommonStreamParameters(
    oboe::AudioStreamBuilder *builder) {
    // We request EXCLUSIVE mode since this will give us the lowest possible
    // latency.
    // If EXCLUSIVE mode isn't available the builder will fall back to SHARED
    // mode.
    builder->setAudioApi(mAudioApi)
        ->setFormat(mFormat)
        ->setSharingMode(oboe::SharingMode::Exclusive)
        ->setPerformanceMode(oboe::PerformanceMode::None);
    return builder;
}
```

If the LiveEffect app have the option of PerformanceMode in GUI, it is really better for the specific smartphone.

Thanks.

**Comment by philburk** [comment]
@hisaha - Thanks for reporting this. It would help to know if the Sony Experia is using AAudio MMAP. I don't think so but I am not sure.

When the phone is failing to record sound in Low Latency mode, could you please enter:

    adb shell dumpsys media.aaudio

and paste the result.

You might also want to experiment with OboeTester. You can try TEST INPUT.  The red VU meters should move when you clap. You can turn on or off MMAP. You can also change PerformanceMode, InputPreset etc.

Also the new "DATA PATHS" test might give us some good data. But it is designed to work over speakers and mics.
You can Share the test result by email to yourself and then attach the report as a file. Do not paste. It is a long report.

**Comment by philburk** [comment]
It uses the Qualcomm SDM665 Snapdragon 665

**Comment by FeiWang888** [comment]
@philburk Do you plan to fix the bug in v1.5.2?

Here is my output from the command.
adb shell dumpsys media.aaudio
------------ AAudio Service ------------
Stream Handles:
AAudioClientTracker:
  client: pid = 934 has 0 streams
  client: pid = 16890 has 0 streams
AAudioEndpointManager:
Exclusive MMAP Endpoints: 0
  ExclusiveSearchCount:  189
  ExclusiveFoundCount:   3
  ExclusiveOpenCount:    52
  ExclusiveCloseCount:   52
  ExclusiveStolenCount:  2

Shared Endpoints: 0
  SharedSearchCount:     83
  SharedFoundCount:      8
  SharedOpenCount:       6
  SharedCloseCount:      6

**Comment by FeiWang888** [comment]
@philburk Do you plan to fix the bug in v1.5.2?

Here is my output from the command.
M-W9YN:~ frank$ adb shell dumpsys media.aaudio
Can't find service: media.aaudio
M-W9YN:~ frank$ adb shell
SOV43:/ $ dumpsys media.aaudio
Can't find service: media.aaudio

**Comment by FeiWang888** [comment]
Can we have the API to know if the mmap is supported or not, so we can put the right value to the setPerformanceMode method?

**Comment by myj420** [comment]
i have the same question。my devices is onplus 6T 。when i use         ->setPerformanceMode(oboe::PerformanceMode::LowLatency);
preset is          builder->setInputPreset(oboe::InputPreset::Generic);
it will silent  no sound。 when i change the setInputPreset or ->setPerformanceMode(oboe::PerformanceMode::none); it work's fine 。could you tell me why？

**Comment by hisaha** [comment]
@philburk I have the same result of FeiWang888 on my SONY Xperia 10 II.

@FeiWang888 I think isMMapSupported function of AudioExtensions class maybe some hint to detect mmap is supported with the target device.

@myj420 I am also interested in onplus 6T. Do you have plan to check the mmap is supported with OboeTester?

**Comment by dturner** [comment]
I'm afraid we don't have an Experia 10 to test on so this is impossible for us to reproduce. Please open a new bug if you're able to reproduce the issue on other devices. 

We are working on CTS tests to pick up these anomalies in future. We've also added the quirk label so we can find this in future.
