### ISSUE TITLE
Input callbacks unusually delayed suddenly

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#1066]
Android version(s): 7.1.1
Android device(s): Moto E (4) Plus
Oboe version: Commit ee39453 (Thu Sep 17 17:36:38 2020 -0700)
App name used for testing: [Shruti Carnatic Tuner](https://play.google.com/store/apps/details?id=org.kuyil.shruti) (Unable to reproduce on OboeTester)
 
**Description**
We open input stream with callback. This actually works on all our devices perfectly. On Moto E4+, though it works most of the times, occasionally we see that the callbacks occur with excessive delay. This continues until we restart the stream.

In the logcat, we see this entry:

```
11-04 16:14:55.427   333 18416 E AudioFlinger_Threads: read failed: framesRead=-2147483631
```

Soon after, we see that callbacks are delayed. Based on our samplerate and frames per callback, we should get a callback roughly every 20 ms, but after the above mentioned error entry, we get callbacks only once in every ~1500 ms.

**Device**

ro.product.brand = motorola
ro.product.manufacturer = motorola
ro.product.model = Moto E (4) Plus
ro.product.device = nicklaus_f
ro.product.cpu.abi = armeabi-v7a
ro.build.description = nicklaus_f-user 7.1.1 NMA26.42-169 300 release-keys
ro.hardware = mt6735
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = 

**Any additional context**

Logcat is [here](https://gist.github.com/rpattabi/ba340a7f200d7541e95c4ee98135fb91). This is filtered with audio related tags. If full logcat would help, please email to shruti@kuyil.org. We can also provide dumps of audioflinger, procstats, meminfo, etc.

We couldn't figure out if this is a oboe bug or device quirk by looking into the logs. We'll update if we could reproduce the problem without using oboe. Please let us know if you need any additional info.

**Comment by dturner** [comment]
Given the age of the device and operating system there's not much we can do here, however, we noticed that in your log output there was an error for hotword detector which may have triggered a failure in the input stream. Please could you try turning off hotword detection and retest?

**Comment by rpattabi** [comment]
Thanks a lot for mentioning about the presence of hotword detector. We didn't realize that. We're trying to reproduce the problem with "Hey Google" detection switched off. We think similar issue appears on newer devices e.g. Samsung S9+ (Android 10) as per our users, but we couldn't confirm it as we don't have access to those devices.

However, this hotword failure you pointed out happened more than 10 minutes before actual audio issue started happening. We see that the log in gist got truncated well before the time around the actual issue (`11-04 16:14:55.427` as in the `read failed` entry mentioned above). Here's the [full log](https://gist.githubusercontent.com/rpattabi/ba340a7f200d7541e95c4ee98135fb91/raw/ceffd0200e9aaf08d059ca9777ce12f70c57fc5e/motoe4--shruti-input-read-failed.log).

**Comment by rpattabi** [comment]
Closing this issue since we think this is due to Google Assistant's "Hey Google" detection.

With Google Assistant disabled or disabling "Hey Google" detection, this issue could not be reproduced so far. This is also verified by one of our users on Samsung Galaxy J5 (Android 9).

Please suggest a workaround if any. I think most apps like ours shall resort to some kind of workaround as there seems to be several such devices with such a problem. As this occurs rarely, reproducing and confirming the problem is not easy.

We provided the suspected list below. It would be great if it is possible for oboe to provide an option to prevent hotword detection interfering with the app (similar to QuirksManager).

```
Android: 28 (9)  
Device: OPPO CPH1933 (OPPO OP4B79L1) / Oppo A5 2020 
Build: CPH1933EX_11_A.51  
Fingerprint: OPPO/CPH1933/OP4B79L1:9/PKQ1.190714.001/1587540528:user/release-keys 

Android: 28 (9)  
Device: asus ASUS_X01AD (asus ASUS_X01A_1) / Asus ZenFone Max M2 (ZB633KL) / Max M2 (ZB632KL)
Build: OPM1.WW_Phone-16.2018.2005.64-20200426  
Fingerprint: asus/WW_X01AD/ASUS_X01A_1:9/WW_Phone-202004261144/16.2018.2005.64-20200426:user/release-keys  

Android: 29 (10)  
Device: samsung SM-G975F (samsung beyond2) / Samsung Galaxy S10+  
Build: QP1A.190711.020.G975FXXU8DTH7  
Fingerprint: samsung/beyond2lteeea/beyond2:10/QP1A.190711.020/G975FXXU8DTH7:user/release-keys  

Android: 29 (10)  
Device: samsung SM-G965F (samsung star2lte) / Samsung Galaxy S9+

Android: 28 (9)
Device: samsung SM-J530F (samsung j5y17lte) / Samsung Galaxy J5
Build: PPR1.180610.011.J530FXXS7CTF1
Fingerprint: samsung/j5y17ltexx/j5y17lte:9/PPR1.180610.011/J530FXXS7CTF1:user/release-keys

Android: 29 (10)
Device: samsung SM-N986B (samsung c2s) / Galaxy Note20 Ultra
Build: QP1A.190711.020.N986BXXU1ATI2
Fingerprint: samsung/c2sxxx/c2s:10/QP1A.190711.020/N986BXXU1ATI2:user/release-keys

and of course, Moto E4 Plus (Android 7.1.1)
```

**Comment by dturner** [comment]
Many thanks for the detailed follow up here. Really good to know.
