### ISSUE TITLE
Building the library is way too complex

### ISSUE THREAD

**Issue by jwatte** [google/oboe#1072]
Please consider bundling it up as a "single header library" -- compare to stb_image.h for a very nice way of shipping a library that's easy to integrate!

**Comment by mgood7123** [comment]
> Please consider bundling it up as a "single header library" -- compare to stb_image.h for a very nice way of shipping a library that's easy to integrate!

just `#include oboe/oboe.h` or related

**Comment by philburk** [comment]
This file includes all the necessary Oboe headers.
https://github.com/google/oboe/blob/master/include/oboe/Oboe.h

**Comment by dturner** [comment]
Thanks for the feedback and the suggestion. I'd be interested to hear about your build environment and use case. Also, is it difficult to include the Oboe pre-built binaries and headers into your project? These can be obtained by: 

* Downloading the latest AAR file from the releases page: https://github.com/google/oboe/releases 
* Rename the `.aar` to `.zip` and extract everything
* The oboe binaries/headers can be found under `prefab/modules/oboe`

![image](https://user-images.githubusercontent.com/873212/100001070-77158c80-2dba-11eb-9087-3fc7ec31bd2f.png)
