### ISSUE TITLE
Shouldn't oboe check the availability of input preset `Unprocessed`?

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#1074]
I came to know that some devices may choose not to support `Unprocessed` input preset. Device manufacturers need to convey the availability through this property on AudioManager: [PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED](https://developer.android.com/reference/android/media/AudioManager#PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED) (since API 24).

I tried to find out what is being done in oboe for this. The following are the key points: (Please correct me if any of this understanding is wrong)

For OpenSL,
* oboe's [AudioStreamOpenSLES](https://github.com/google/oboe/blob/master/src/opensles/AudioStreamOpenSLES.cpp#L213) logs that only `VoiceRecognition` is supported.
* But [AudioInputStreamOpenSLES](https://github.com/google/oboe/blob/52aca5741e256f2a51594ec818d1991de05cbfcd/src/opensles/AudioInputStreamOpenSLES.cpp#L29) has conversion for input preset to appropriate `SL_ANDROID_XXX` constants including `Unprocessed`. It also has [this code](https://github.com/google/oboe/blob/52aca5741e256f2a51594ec818d1991de05cbfcd/src/opensles/AudioInputStreamOpenSLES.cpp#L159) which seems to validate the given input preset before fallback to `VoiceRecognition`. I presume this means for OpenSL, if `Unprocessed` is not supported, it will fallback to `VoiceRecognition`.

However for AAudio,
* I could not find any such validation from oboe for input preset. One exception is that [AudioStreamAAudio](https://github.com/google/oboe/blob/52aca5741e256f2a51594ec818d1991de05cbfcd/src/aaudio/AudioStreamAAudio.cpp#L217) ensures that `VoicePerformance` falls back to `VoiceRecognition` for pre-Android Q. The possibility that `Unprocessed` may not be supported by the device is not considered.
* From checking AOSP's AAudio implementation, it doesn't look like the unavailability of `Unprocessed` is considered there neither.

If the above understanding is correct, oboe's AAudio code does not consider the possibility of `Unprocessed` being unavailable on some devices.
 
Should the apps verify the availability prior to opting for `Unprocessed` or oboe shall do it similar to what is done for unavailability of `VoicePerformance`?

PS:  I'm unaware of the devices that does not support `Unprocessed`. The code provided in an oboe issue [comment](https://github.com/google/oboe/issues/95#issuecomment-390771989), seem to mention Samsung Galaxy S8 does not support `Unprocessed`.

**Comment by rpattabi** [comment]
The following devices return false for `PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED`:

* Moto E4 Plus (Android 7.1.1)
* Xiaomi Note 4 (Android 7.1.1)
* Nokia 5.1 Plus (Android 10)

Inspite of that, through oboe we could set the input preset as `Unprocessed` and they seem to work okay. So I'm wondering what's the deal with this property `PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED`. Even [Android CDD](https://source.android.com/compatibility/11/android-11-cdd#5_11_capture_for_unprocessed) mentions the importance of this property clearly, yet it seems irrelevant on these devices. Not sure it is the same case with other devices and manufacturers.

**Comment by philburk** [comment]
Thank you for pointing this out. I am adding this to the OboeTester Device Report.

> oboe's AudioStreamOpenSLES logs that only VoiceRecognition is supported.

Right. Fixed in #1077 

> Should the apps verify the availability prior to opting for Unprocessed

Yes, if they care about the specific requirements specified in the CDD.

Oboe is native only. It does not call into Java. So it cannot check for PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED.

> The following devices return false for PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED:
> Inspite of that, through oboe we could set the input preset as Unprocessed and they seem to work okay. 

If a device meets ALL the requirements of the CDD for UNPROCESSED then they can declare it as SUPPORTED.
If they do NOT declare SUPPORTED then they are "still STRONGLY RECOMMENDED to satisfy as many of the requirements for the signal path for the unprocessed recording source." So UNPROCESSED may work pretty well but may not meet all the requirements on those devices.

**Comment by rpattabi** [comment]
So UNPROCESSED is available since Android 7 and yet this property will be false if the device is not adhering to ALL the requirements. Thank you for the clarification.
