### ISSUE TITLE
Continuous Tick sound when played via callback.

### ISSUE THREAD

**Issue by faiziakbr** [google/oboe#1086]
Hello there,

I am facing **tick** sound issue when i play real time audio coming from UDP socket. My **AudioStreamBuilder** settings are

```
playbackBuilder.setDirection(oboe::Direction::Output);
    playbackBuilder.setAudioApi(oboe::AudioApi::AAudio);
    playbackBuilder.setSampleRate(Constants::SAMPLE_RATE);
    playbackBuilder.setChannelCount(oboe::ChannelCount::Mono);
    playbackBuilder.setFormat(oboe::AudioFormat::I16);
    playbackBuilder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
    playbackBuilder.setSharingMode(oboe::SharingMode::Exclusive);
    playbackBuilder.setFramesPerCallback(1024);
    playbackBuilder.setCallback(this);
```

and my CallBack looks like this

```
oboe::DataCallbackResult
NativePlayback::onAudioReady(oboe::AudioStream *oboeStream, void *audioData, int32_t numFrames) {
    auto *outputData = static_cast<int16_t *>(audioData);


    LOGE("NUM FRAMES: %d and CirBuffer SIZE: %d", numFrames, circBufff.length());
    if (circBufff.length() >= numFrames) {
        for (int i = 0; i < numFrames; i++) {
            int16_t x = 0;
            if(circBufff.remove(&x)) {
                outputData[i] = x;
            } else {
                LOGE("NOT ENOUGH DATA");
            }
        }
    }

    return oboe::DataCallbackResult::Continue;
}
```

Please hear this sound and kindly identify what is wrong here.
https://drive.google.com/file/d/1SUcS4qKbnmQTCXEsN6VX2t6RoQ06Ak4w/view?usp=sharing

I have tested this on some devices like: OnePlue 7, Samsung A51, A20 and the tick is there.

I have made sure that i have enough Frames required by the callback.

PS: I am not facing this issue on OPPO mobile running android Q.

**Comment by philburk** [comment]
> setFramesPerCallback(1024)

That is quite large and could cause problems, particularly if you end up with a low latency stream. Your callback function looks like it can handle any number of frames. It is not doing an FFT or other fixed block size operation. So I would remove your call to setFramesPerCallback().

Also try removing these calls. 

>    playbackBuilder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
>    playbackBuilder.setSharingMode(oboe::SharingMode::Exclusive);

You don't really need low latency because you are streaming over the network. Higher latency would actually be a good thing.

Also try adding this to avoid the internal sample rate converter, which sometimes ticks:

    playbackBuilder.setSampleRateConversionQuality(SampleRateConversionQuality::Medium);

Please add a note here if it works. Reopen if it doesn't.

**Comment by faiziakbr** [comment]
Hi Phil,

I have done as you have mentioned. But still i am facing this issue on my OnePlus 7, Samsung A51, A20 and **No issue on OPPO Reno2**. 

My updated configurations are:

```
playbackBuilder.setDirection(oboe::Direction::Output);
    playbackBuilder.setAudioApi(oboe::AudioApi::AAudio);
    playbackBuilder.setSampleRate(Constants::SAMPLE_RATE);
    playbackBuilder.setChannelCount(oboe::ChannelCount::Mono);
    playbackBuilder.setFormat(oboe::AudioFormat::I16);
//    playbackBuilder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
//    playbackBuilder.setSharingMode(oboe::SharingMode::Exclusive);
//    playbackBuilder.setFramesPerCallback(1024);
    playbackBuilder.setInputPreset(oboe::InputPreset::VoiceCommunication);
    playbackBuilder.setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Medium);
    playbackBuilder.setCallback(this);
```

**Comment by faiziakbr** [comment]
Thanks Phil,

I was able to figure out the issue of these specific devices.

**Comment by Tschigger** [comment]
> Thanks Phil,
> 
> I was able to figure out the issue of these specific devices.

So, would you mind sharing how you resolved the issue?

**Comment by philburk** [comment]
@faiziakbr - Yes, please share. I reopened the bug so we can record the solution.

**Comment by faiziakbr** [comment]
@Tschigger can you please share all the properties you have set for AudioStreamBuilder?

Also are you facing this issue with specific devices or on all devices? are you playing data from a file, network?

**Comment by Tschigger** [comment]
In my case the continuous tick has nothing to do with Oboe. The cause is a periodic lag that happens when sending the data over UDP. Every 4.096 seconds, I get lag spikes of exactly 170-180 ms, which caused the buffer on the receiving device to deplete.

Since you mentioned you resolved the issue, I found it plausible that you faced the same issue and found the cause for these periodic lags.

**Comment by faiziakbr** [comment]
@Tschigger I have a check on my RingBuffer and the numFrames, required by Oboe to play the data properly. If my RingBuffer doesn't have enough data to fulfill the requirement of numFrames than I play Silence (zeros) to avoid any un-ordinary sound.

What i am unable to understand is that UDP is fast enough to send data and you are getting glitch? **LowLatency** property is definitely not required in case of Network. 

I will give you an abstract of what i am doing.
First, I set the **setFramesPerCallback** to get 10ms of data at 48000 sample rate, then i encode the data with Opus and send it over UDP. 
On the receiving side, I decode the Data and put the decoded Data in a RingBuffer. From this ringBuffer the Oboe fetches the required data and play it.

I didn't faced any issue on UDP that i had to play silence even after a 1 hour or above of this scenarios.

Do tell me if you need clarity regarding this issue. Happy to help also do tell me if you have solved this issue in another way.

**Comment by Tschigger** [comment]
> What i am unable to understand is that UDP is fast enough to send data and you are getting glitch?

Well, the UDP calls are made on time, it's just the client not receiving the data on time :). It's probably some issue with either scheduling on the Android system (and the UDP packets are stuck in the kernel somehow) or the router/Wifi. Tested the client on multiple OSes and had the same issue (periodic lag) with all of them. Either way, it's out of my scope, I'm just increasing my ring buffer.

In my case it has definitely nothing to do with Oboe. I just thought that maybe you faced the exact same problem and solved it.

**Comment by Tschigger** [comment]
>What do you mean by "scheduling on the Android System". As far as I have experimented UDP is quite fast as compared to WebRtc DataChannel and TCP.

The calls to send the UDP packets are being made on time (as measured), but I do not know if they actually leave the device on time. It could be possible (in theory) that after calling `sendTo`, the kernel on Android does not actually send the packets on time due to scheduling/threading issues. I don't know enough about this nor do I have the time to get into it, so I just increased the buffer.

**Comment by faiziakbr** [comment]
@Tschigger since you have resolved this issue I am going to close it.
