### ISSUE TITLE
FilterAudioStream does not provide Input Preset of the underlying stream in case of fallback

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#1090]
When a specific InputPreset is specified in Audio Stream Builder, oboe may choose to fallback to a different preset if it's unavailable on a device. For instance, when opening OpenSLES stream, if setting a given preset fails, it falls back to Voice Recognition. Similarly, the recently introduced Voice Performance preset fallsback to Voice Recognition on older devices.

When such fallback happens, `FilterAudioStream` still has the input preset as provided in the builder, but not the actual one in the underlying stream. This is misleading for the developers to think that the requested input preset is available on the device.

The following code may have to copy input preset as well to address this problem.

https://github.com/google/oboe/blob/9a62b978fb8ab118fe7d2a803c34b2816b786909/src/common/FilterAudioStream.h#L55-L57

Additionally, the following sections in `AudioStreamBuilder.cpp` may also need to consider `InputPreset` as it can also be left `kUnspecified`:

 https://github.com/google/oboe/blob/9a62b978fb8ab118fe7d2a803c34b2816b786909/src/common/AudioStreamBuilder.cpp#L82-L87

https://github.com/google/oboe/blob/9a62b978fb8ab118fe7d2a803c34b2816b786909/src/common/AudioStreamBuilder.cpp#L124-L136

**Comment by philburk** [comment]
Thanks!  I reproduced this on an S10e running P.

1. launch OboeTester
1. tap TEST INPUT
1. select InPreset = Performance
1. select SRATE 44100
1. select SRC Quality "Medium"
1. tap OPEN

EXPECT
Actual InPreset = VoiceRec

ACTUAL
Actual InPreset = Performance

The same problem occurs with OpenSL ES but for a different reason.

**Comment by philburk** [comment]
Fixed as you suggested. Thanks.

By the way, isCompatible() does not check InputPreset because the FilterAudioStream does not provide a conversion for that InputPreset. It only converts data rates, formats, channels and callback sizes. So it is OK.
