### ISSUE TITLE
configuration querying

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#1097]
can Oboe query certain information for use by Backend's such as

1. `Description copied from: is_realtime
Return true if the callback from the underlying mechanism/API (CoreAudio, JACK, ASIO etc.) occurs in a thread subject to realtime constraints. Return false otherwise.`

2. `Description copied from: enumerate_devices()
Returns a collection of DeviceStatuses identifying devices discovered by this backend since the start of the process.
Any of the names in each DeviceStatus may be used to identify a device in other calls to the backend, though any of them may become invalid at any time.`

3. `Description copied from: available_sample_rates(const std::string &device)
Returns a collection of float identifying sample rates that are potentially usable with the hardware identified by device . Any of these values may be supplied in other calls to this backend as the desired sample rate to use with the name device, but the requested sample rate may turn out to be unavailable, or become invalid at any time.`

4. `Description copied from: available_buffer_sizes(const std::string &device)
Returns a collection of uint32 identifying buffer sizes that are potentially usable with the hardware identified by device . Any of these values may be supplied in other calls to this backend as the desired buffer size to use with the name device, but the requested buffer size may turn out to be unavailable, or become invalid at any time.`

5. `Description copied from: available_input_channel_count(const std::string &device)
Returns the maximum number of input channels that are potentially usable with the hardware identified by device . Any number from 1 to the value returned may be supplied in other calls to this backend as the input channel count to use with the name device, but the requested count may turn out to be unavailable, or become invalid at any time.`

6. `Description copied from: available_output_channel_count(const std::string &device)
Returns the maximum number of output channels that are potentially usable with the hardware identified by device . Any number from 1 to the value returned may be supplied in other calls to this backend as the output channel count to use with the name device, but the requested count may turn out to be unavailable, or become invalid at any time.`

7. `Description copied from: enumerate_midi_devices
Detailed MIDI device list - if available`

8. `Description copied from: enumerate_midi_options
Returns a vector of strings that describe the available MIDI options.
These can be presented to the user to decide which MIDI drivers, options etc. can be used. The returned strings should be thought of as the key to a map of possible approaches to handling MIDI within the backend. Ensure that the strings will make sense to the user.`

9. `Description copied from: available_period_sizes(const std::string &driver, const std::string &device)
Returns a vector of supported period-sizes for the given driver`

**Comment by philburk** [comment]
Information about the underlying device is available from the Java APIs.  We decided not to duplicate those APIs in native.

You can do the queries in Java and then pass the information down to your native app using JNI.

https://developer.android.com/reference/android/media/AudioManager
https://developer.android.com/reference/android/media/midi/MidiManager

> Description copied from: is_realtime Return true if the callback from the underlying
> mechanism/API (CoreAudio, JACK, ASIO etc.) occurs in a thread subject to realtime constraints.

All audio callbacks are subject to real-time constraints. This is particularly true for LowLatency streams, which may have 2 msec periods. (Oboe only support AAudio and OpenSL ES on Android.)
