### ISSUE TITLE
write latency

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#1098]
regarding `Audio latency is high for blocking write() because the Android O DP2 release doesn't use a FAST track. Use a callback to get lower latency.`

is this ONLY present on Android O DP2 releases, and is otherwise fixed in Android O, Android O DP1, Android P, Android Q, and Android R?

**Comment by philburk** [comment]
There are two data paths in AAudio. The Legacy path through AudioFlinger and the newer MMAP path on Android 8.1+.
Only a few devices support MMAP, eg. Pixel, Samsung S9+, Huawei Note20, and many other flagship devices.

You can get low latency on the MMAP path, INPUT or OUTPUT, with or without a callback.
You can only get low latency on the OUTPUT Legacy path when using a callback.
You can get low latency on the INPUT Legacy path with or without a callback.
This is true on all Android versions to date.

For OpenSL ES, we implement the non-callback blocking write mode in Oboe using our own FIFO. OpenSL ES is running at low latency but the FIFO adds some latency.
