### ISSUE TITLE
Use of AudioDeviceCallback to select device in samples requires API 23

### ISSUE THREAD

**Issue by philburk** [google/oboe#1102]
The device selection code in the samples and in OboeTester use AudioDeviceCallback.
That was added in API 23 so the samples will not run on Lollipop ( API 21,22)

**Comment by dturner** [comment]
This affects `hello-oboe` and `LiveEffect`, but not `MegaDrone` and `RhythmGame`. 

Not sure how we want to deal with this. Perhaps remove the device selection from `hello-oboe` to make it a simpler, backward compatible "Hello World" example.

**Comment by dturner** [comment]
Conditionally show the audio device spinners on API23+

**Comment by dturner** [comment]
It isn't even possible to set the audio device id using OpenSL ES so we may want to only show the spinners on API 27 (when AAudio became recommended API)
