### ISSUE TITLE
[hello-oboe] Extremely distorted sound after switching to bluetooth headphones

### ISSUE THREAD

**Issue by dturner** [google/oboe#1104]
After connecting bluetooth headphones to hello-oboe the sound became extremely loud and distorted.

**Steps to reproduce**
- Run hello-oboe (ensure that no wireless headphones are already connected)
- Tap the screen and verify that sound is produced through the built-in speaker
- Connect bluetooth headphones (I used GID6B Google branded headphones)
- Tap the screen

**Expected outcome**
- Clean square wave is produced in each ear at reasonable volume

**Actual outcome**
- Loud distorted square wave is heard in both ears ([recording here](https://voca.ro/1aRwAArM2CON)). 

**Device info**
ro.product.brand = google
ro.product.manufacturer = Google
ro.product.model = Pixel 3
ro.product.device = blueline
ro.product.cpu.abi = arm64-v8a
ro.build.description = blueline-user 11 RQ1A.201205.003 6906706 release-keys
ro.hardware = blueline
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

**Other info**
If I turn down the volume on the phone to one step above mute then it sounds normal. It's like `int16`s are being interpreted as `float`s so the amplitude is way off.

**Comment by dturner** [comment]
I thought this was a one off but it's reproducible 100% of the time.

**Comment by dturner** [comment]
@ggfan Please could you try to repro and report back

**Comment by robertwu1** [comment]
I assume this was fixed with https://github.com/google/oboe/commit/7b3d34ab18b1051950693daee7e45836e18b32a7. Closing as I never reproed this since the change.
