### ISSUE TITLE
Feature request: even smaller latencies

### ISSUE THREAD

**Issue by zenhund74** [google/oboe#1111]
I'm surprised that the introduction of the new AAudio core doesn't bring better latencies than around 60ms .
Everyone agrees that low latency audio should be at least under 20ms even better under 10ms. Professional Audio latencies e.g. for giving a voice input over headset some reverb, compressors etc. should be around or lower than 4ms.

I totally agree that android as a mobile platform has limits, but even an ASIO4ALL driver on a pc can go down to 128 samples and results in 5ms or for 256 samples respectively in 10ms.

Isn't there a way to buy latency via increased DSP load? Could one add a cheap DAC via USB-OTG to reduce the latencies? Is there a DAC compatibility list for OBOE?

**Comment by philburk** [comment]
> latencies than around 60ms .

What device are you seeing that on? What stream settings?

The latency varies significantly by device. On Pixel phones and many other flagship devices, you can get round-trip latencies under 20 msec. We are working with phone manufacturers across the ecosystem to lower their latency.

Also a small change in an app can result in much higher latency. Here are some tips on achieving lower latency:

https://github.com/google/oboe/blob/master/docs/FAQ.md#i-requested-a-stream-with-performancemodelowlatency-but-didnt-get-it-why-not

**Comment by zenhund74** [comment]
Hello Phil,

thank you for your reply. I'm using an LG V30 as a testing device. Quite an
average phone and no flagship device. Also I'm using a C# wrapper for Unity
3D so my stream settings look like this:

using (AudioStreamBuilder audioStreamBuilder = new AudioStreamBuilder
            {
                Format = AudioFormat.Float,
                ChannelCount = 2,
                SampleRate = 48000,
                Callback = mixer1,
                AudioApi = AudioApi.Unspecified,
                PerformanceMode = PerformanceMode.LowLatency,
                SharingMode = SharingMode.Exclusive,
                BufferCapacityInFrames = 128,
                IsFormatConversionAllowed = true,
                Direction = Direction.Output
            })
            {
                Result result = audioStreamBuilder.OpenStream(out
audioStream1);
                Debug.Assert(result == Result.OK);
            }

And I'd still like to ask the question if it would be thinkable to build a
cost effective USB headset adapter with a fast and supported audio chipset,
that could lower the latency on all phones?

With kind regards, Jens.



Am Mi., 25. Nov. 2020 um 19:44 Uhr schrieb Phil Burk <
notifications@github.com>:

**Comment by philburk** [comment]
>  if it would be thinkable to build a cost effective USB headset adapter with a fast and supported
> audio chipset, that could lower the latency on all phones?

If the USB is handled by the DSP, as it is on Pixel phones, Samsung flagship phones, etcetera, then the USB headset only adds 1-3 msec of latency.  If the USB data has to go through a separate HAL then it can add more latency but changing the headset will not solve that problem.

Note that on some devices, the speaker protection algorithm can add up to 20 msec of latency. On those phones, USB is may be the lowest latency path.
