### ISSUE TITLE
FxLab UI state not being restored

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#1119]
Android version(s): Android Pie
Android device(s): Samsung Galaxy S8
Oboe version: master
App name used for testing: FxLab
 
**Short description**
UI state is not restored upon onPause and onResume

for example: leaving, but not killing, the application, and then going back into the application

**Steps to reproduce**
add an effect, leave the app, open the app

**Expected behavior**
the effect should still be present with its current state

**Actual behavior**
the effect is gone, as if the app was fully restarted

**Comment by philburk** [comment]
I can reproduce this on a Pixel 2 running P.

This is related to #1120

**Comment by android-usb** [comment]
Fixed by pr/1139
