### ISSUE TITLE
Multiple "get time" methods need consolidating

### ISSUE THREAD

**Issue by dturner** [google/oboe#112]
We have a method for getting the current time in `AudioClock` but it's not public. We should consolidate all "get time" methods into a single, publicly accessible method.

**Comment by philburk** [comment]
AudioClock is used inside Oboe.
We could make that public and replace the other clock implementations in the various samples.

**Comment by atneya-nair** [comment]
AudioClock methods can be easily replaced by std library functions, no need to expose additional API when unnecessary.
