### ISSUE TITLE
FxLab Effect UI state is not restored upon placement in list

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#1120]
Android version(s): Android Pie
Android device(s): Samsung Galaxy S8
Oboe version: master
App name used for testing: FxLab
 
**Short description**
Effect UI state is not restored upon placement in list

**Steps to reproduce**
add an effect, add another effect, change some parameters in the effect, move the effect to another position in the list

**Expected behavior**
the effect's UI's current state should persist

**Actual behavior**
the effect's UI is reset to its initial state

**Comment by android-usb** [comment]
I think think this is a dup of 1119

**Comment by philburk** [comment]
I can reproduce this on a Pixel 2 running P.

**Comment by mgood7123** [comment]
> I think think this is a dup of 1119

im not sure it is, as the state is not restored under `2 conditions`

condition 1: an effect being re-ordered

condition 2: app being backgrounded and foregrounded (onPause and onResume)
