### ISSUE TITLE
Building with OBOE_NO_INCLUDE_AAUDIO defined causes compile errors

### ISSUE THREAD

**Issue by android-usb** [google/oboe#1122]
oboe/src/aaudio/AudioStreamAAudio.cpp:463:30: error: use of undeclared identifier 'AAUDIO_OK'
    aaudio_result_t result = AAUDIO_OK;
                             ^
oboe/src/aaudio/AudioStreamAAudio.cpp:486:23: error: use of undeclared identifier 'AAUDIO_OK'
        if (result != AAUDIO_OK && result != AAUDIO_ERROR_TIMEOUT) {
                      ^
oboe/src/aaudio/AudioStreamAAudio.cpp:486:46: error: use of undeclared identifier 'AAUDIO_ERROR_TIMEOUT'
        if (result != AAUDIO_OK && result != AAUDIO_ERROR_TIMEOUT) {
                                             ^
oboe/src/aaudio/AudioStreamAAudio.cpp:552:31: error: use of undeclared identifier 'AAUDIO_STREAM_STATE_STARTING'
            && aaudioState == AAUDIO_STREAM_STATE_STARTING) {
                              ^
oboe/src/aaudio/AudioStreamAAudio.cpp:553:27: error: use of undeclared identifier 'AAUDIO_STREAM_STATE_STARTED'
            aaudioState = AAUDIO_STREAM_STATE_STARTED;

**Comment by philburk** [comment]
These errors can be triggered by adding "-DOBOE_NO_INCLUDE_AAUDIO" to CMAKE_CXX_FLAGS in OboeTester CMakeLists.txt.
