### ISSUE TITLE
Execution failed for task ':hello-oboe:externalNativeBuildDebug'

### ISSUE THREAD

**Issue by chaabanihoussem** [google/oboe#1125]
Hello ,

I downloaded oboe library and installed ndk 21.0.6113669 as recommended by android studio, and I am trying to build the project and I get this error:

Execution failed for task ':hello-oboe:externalNativeBuildDebug'.
> Expected output file at C:\Users\houssem\AndroidStudioProjects\oboe\samples\hello-oboe\build\intermediates\cmake\debug\obj\arm64-v8a\libhello-oboe.so for target hello-oboe but there was none

Any help will be very recommended,

Thank you !

**Comment by ggfan** [comment]
There might be something missed during the installation.  I just tried it on windows, it builds ok.

A couple of things to check out:

- you are probably using Android studio 4.1.x? 
- The NDK needs to be installed into the specific directory(should be under your $sdk/ndk/, studio will search NDK version there), if you let sdkmanager (tools -> sdk manager -> NDK(side by side), make sure enable "Show Package Details" at that UI) install NDK, it will be installed to the right place. could you double check your NDK is in the right directory?

You may find the related documentation [here](https://developer.android.com/studio/projects/configure-agp-ndk).

**Comment by chaabanihoussem** [comment]
Hi 
Thank you for your reply.
It was an anti malware issue. I have a software detected all .so as malware and deleting all these file.
This issue is closed.
Thank you for this amazing library :D
