### ISSUE TITLE
Live Effect with sound changing

### ISSUE THREAD

**Issue by Trayvor** [google/oboe#1127]
I use oboe to make app like Live Effect in samples, but I need to change output sound. How can I do that? 

Now my app have the same code like in Life Effect sample.

**Comment by philburk** [comment]
You can modify the code in FullDuplexPass.h to implement your own algorithm.
Currently it only scales the input by a constant. See this line:

https://github.com/google/oboe/blob/1a4c5460f17ceb2ad239cdcb40c67809bf71df87/samples/LiveEffect/src/main/cpp/FullDuplexPass.h#L46
