### ISSUE TITLE
[LiveEffect] How to passing onAudioReady back to Java native

### ISSUE THREAD

**Issue by febryituery** [google/oboe#1128]
Hai,
i've got some problem regarding how to handling onAudioReady data back to Java native. because i need some of that data to processing in asynctask. 

```
int32_t totalFramesRead = 0;
        do {
            oboe::ResultWithValue<int32_t> result = getInputStream()->read(mInputBuffer.get(),
                                                                           numFrames,
                                                                           0 /* timeout */);
            if (!result) {
                // Ignore errors because input stream may not be started yet.
                break;
            }
            actualFramesRead = result.value();
            totalFramesRead += actualFramesRead;
        } while (actualFramesRead > 0);
        // Only counts if we actually got some data.
        if (totalFramesRead > 0) {
            mCountCallbacksToDrain--;
        }
```
is there any way to pass that data? thank you

**Comment by philburk** [comment]
The onAudioReady method is only used with callbacks. In your code you are not using a callback. That is a "blocking read".

You can call the Oboe read() method from a JNI function. Pass a Java float or short array to the JNI function.
Then convert it to a C array like this:
http://www.iitk.ac.in/esc101/05Aug/tutorial/native1.1/implementing/array.html

Then call:    getInputStream()->read(javaBuffer, ...

Note that if you are doing your processing in Java then you might as well just use a Java AudioRecord with the LOW_LATENCY flag. Java threads do not have the same high performance as the native callback threads so you may need to read larger chunks and have higher capacity to avoid overflows.
