### ISSUE TITLE
Audio timing and large buffers

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#1134]
does AAudio/Oboe have any bugs relating timing and large buffers? (particularly 5k or more frames per data callback)

this may be related to https://github.com/google/oboe/issues/1116 but I am not sure

in particular if I use a buffer size of 4k and above, the timing difference becomes more noticeable as the buffer size increases from 4k to 8k

eg the audio goes off-beat most of the time even after AAudio re-synchronizes it

DO NOTE that this is NOT an issue with small buffers such as FramesPerDataCallback(192) and FramesPerDataCallback(512)

and my DSP load average is 4% to 6%

also this happens even if i omit the dsp load code

```C++
auto start = std::chrono::high_resolution_clock::now();
channelRack.write(&hostInfo, in, &mixer, out, out->ports.samplesPerChannel);
auto end = std::chrono::high_resolution_clock::now();
processingTime = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
bufferLength = static_cast<double>((static_cast<double>(out->ports.samples) * 1000000000.0f) / static_cast<double>(_backend->sample_rate()));
DSPLoadDouble = (static_cast<double>(processingTime) / static_cast<double>(bufferLength)) * 100.0f;
DSPLoadInt = processingTime > bufferLength ? 100 : static_cast<int>(DSPLoadDouble);
```

also, I am using sample based timing

```C++
for (int32_t i = 0; i < samples; i ++) {
    if (pattern != nullptr) {
        if (pattern->hasNote(hostInfo->engineFrame)) {
```

```C++
uint64_t wrap(uint64_t frame, uint64_t min, uint64_t max) {
    return min + ((frame-min) % (max - min + 1));
}

bool hasNote(uint64_t frame) {
    if (noteData.isEmpty()) return false;
    uint64_t wrappedFrame = wrap(frame, 0, grid.samples_per_note * grid.notes_per_bar);
    for (int i = 0; i < noteData.readAvailable(); ++i) {
        auto * pair = noteData.at(i);
        if (pair != nullptr) {
            auto &sampleToPlayNoteOn = pair->first;
            if (wrappedFrame == sampleToPlayNoteOn) {
                noteindex = i;
                if (pair->second == true) return true;
            }
        }
    }
    return false;
}
```

```C++
aaudio_result_t result = AAudio_createStreamBuilder(&builder);
if (result != AAUDIO_OK) {
    LOGE("FAILED TO CREATE STREAM BUILDER: %s", AAudio_convertResultToText(result));
    return result;
}

AAudioStreamBuilder_setDataCallback(builder, onAudioReady, this);
AAudioStreamBuilder_setErrorCallback(builder, onError, this);

AAudioStreamBuilder_setBufferCapacityInFrames(builder, 1024*16);
AAudioStreamBuilder_setFramesPerDataCallback(builder, 1024*8);

AAudioStreamBuilder_setPerformanceMode(builder, AAUDIO_PERFORMANCE_MODE_LOW_LATENCY);

outputFormat = AAUDIO_FORMAT;
AAudioStreamBuilder_setFormat(builder, outputFormat);

result = AAudioStreamBuilder_openStream(builder, &stream);

if (result != AAUDIO_OK) {
    LOGE("FAILED TO OPEN THE STREAM: %s", AAudio_convertResultToText(result));
    return result;
}
```

**Comment by philburk** [comment]
> this may be related to #1116 but I am not sure

Yes, it is related. But it is an extreme case. 8K frames is huge. That is 170.66 msec at 48000 Hz. Does your algorithm require such huge blocks? Are you doing FFTs?

@mgood7123 - What happens if you do not specify a callback size?

> AAUDIO_PERFORMANCE_MODE_LOW_LATENCY

There is no point in asking for LOW_LATENCY with such a huge buffer. Try asking for AAUDIO_PERFORMANCE_MODE_NONE.

**Comment by mgood7123** [comment]
> > this may be related to #1116 but I am not sure
> 
> Yes, it is related. But it is an extreme case. 8K frames is huge. That is 170.66 msec at 48000 Hz. Does your algorithm require such huge blocks? Are you doing FFTs?
> 
> @mgood7123 - What happens if you do not specify a callback size?
> 
> > AAUDIO_PERFORMANCE_MODE_LOW_LATENCY
> 
> There is no point in asking for LOW_LATENCY with such a huge buffer. Try asking for AAUDIO_PERFORMANCE_MODE_NONE.

i am building a DAW and I want to be capable of playing 30 to 100 audio tracks simultaneously (at the same time at any given moment)

**Comment by philburk** [comment]
> capable of playing 60 to 120 audio tracks

Great, but why do you need such a huge buffer?

For a DAW you will want low latency. Open ONE low latency stream and mix your 60-120 tracks using your own mixer in the callback. If you do not need a fixed callback size then just use the burst size that you get from Oboe.

**Comment by mgood7123** [comment]
> > capable of playing 60 to 120 audio tracks
> 
> Great, but why do you need such a huge buffer?
> 
> For a DAW you will want low latency. Open ONE low latency stream and mix your 60-120 tracks using your own mixer in the callback. If you do not need a fixed callback size then just use the burst size that you get from Oboe.

I tried with the default 192 buffer then 512 buffer but I get a lot of under-runs on both

**Comment by philburk** [comment]
If you get underruns then call stream->setBufferSizeInFrames() to increase the buffer size.

If your processing is too heavy then you will get glitches even if the audio is configured correctly.

This is an old question so I am closing it.
