### ISSUE TITLE
The right way to import this repo in my project

### ISSUE THREAD

**Issue by lattice0** [google/oboe#1141]
This repo shows oboe + a lot of usage examples that are interconnected with each other. I've tried to extract `DrumThumper` only but it depends on parselib and iolib, which themselves depend on oboe at the right location set in their CMakeLists.txt. Every time I try, I see that one project depends on another which depends on another.

I want to use those examples but keep them as they are so I can update when this repo is updated.

Given these, what would be the best way to include oboe in a project? I feel that this is missing and the structure of the oboe project itself is non standard (I guess).

**Comment by robertwu1** [comment]
Take a look at minimal oboe for an easy example
