### ISSUE TITLE
[question] Audio buffering, need tech note

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#1144]
can AAudio have more than two buffers?

eg it is often recomended to set the frames to half the capacity of the buffer so Audio can double buffer

```
buffer capacity: 384
frames per data callback: 192

| 192 | 192 |
|WRITE|READ |
```

but is it possible to quadruple buffer by setting the buffer to a fourth of the capacity?

```
buffer capacity: 384
frames per data callback: 96

|  96 |  96 |  96 |  96 |
|WRITE|WRITE|WRITE|READ |
```

**Comment by philburk** [comment]
A "buffer" can contain one or more "bursts", depending on the BufferCapacity.
This deserves a tech note.

**Comment by philburk** [comment]
DUP of #666
