### ISSUE TITLE
Error with undeclared identifier '__ANDROID_API_R__' in  AudioStreamAAudio.cpp

### ISSUE THREAD

**Issue by sletz** [google/oboe#1148]
With latest Oboe source form GitHub we get: `Error with undeclared identifier '__ANDROID_API_R__' in  AudioStreamAAudio.cpp`, when compiling ou Oboe/Faust code. 

Moving the following lines:

```
#ifndef __ANDROID_API_R__
#define __ANDROID_API_R__ 30
#endif
```

from QuirksManager.cpp to QuirksManager.h solves the problem.

Is this a known issue?

**Comment by philburk** [comment]
@sletz - Not a known issue. Thanks Stephane for reporting this.

**Comment by sletz** [comment]
Thanks. Will it be merged on master branch at some point ?

**Comment by philburk** [comment]
Yes. I will get Paul or Don to approve then merge it this week. Do you need it sooner? It is trivial so if you approve it I will merge it.

**Comment by sletz** [comment]
For me the sooner, the better, thanks.

**Comment by philburk** [comment]
OK. I will consider that an implied Approval.
