### ISSUE TITLE
Can't get audio from MIC

### ISSUE THREAD

**Issue by williamkibira** [google/oboe#115]
Hi , i am trying to get audio from my microphone and do a little processing on it and also play it back within the same call back . So far all i have is silence and it looks i have not data in the incoming audio buffer .
Here are the methods i have used to initialize the code and and capture audio .
Setting Up the recording stream:

```
void AudioHandler::setUpRecorderStreamParameters(oboe::AudioStreamBuilder *builder) {
    builder->setAudioApi(oboe::AudioApi::Unspecified);
    builder->setDeviceId(captureDeviceId);
    builder->setChannelCount(channelCount);
    builder->setBufferCapacityInFrames(bufferSize);
    builder->setFormat(oboe::AudioFormat::I16);
    builder->setSampleRate(sampleRate);
    builder->setDirection(oboe::Direction::Input);
    builder->setSharingMode(oboe::SharingMode::Exclusive);
    builder->setPerformanceMode(oboe::PerformanceMode::LowLatency);
    builder->setCallback(this);
}
```
Setting up Play back

```
void AudioHandler::setUpPlaybackStreamParameters(oboe::AudioStreamBuilder *builder) {
    builder->setAudioApi(oboe::AudioApi::Unspecified);
    builder->setDeviceId(playbackDeviceId);
    builder->setChannelCount(channelCount);
    builder->setBufferCapacityInFrames(bufferSize);
    builder->setSharingMode(oboe::SharingMode::Exclusive);
    builder->setDirection(oboe::Direction::Output);
    builder->setPerformanceMode(oboe::PerformanceMode::LowLatency);
}
```
Starting Recording and Play back
```
void AudioHandler::createRecordingStream() {
    oboe::AudioStreamBuilder builder;
    setUpRecorderStreamParameters(&builder);
    oboe::Result result = builder.openStream(&captureStream);
    if (result == oboe::Result::OK && captureStream != nullptr) {
        if (captureStream->getChannelCount() != channelCount) {
            // LOG HERE TO SHOW WE MESSED UP REALLY BAD ON CHANNEL COUNT
            LOGW("Requested %d channels but received %d", captureStream->getChannelCount(),
                 channelCount);
        }
        captureStream->setBufferSizeInFrames(bufferSize);
        if (captureStream->requestStart() != oboe::Result::OK) {
            LOGE("Error starting stream. %s", oboe::convertToText(result));
        }
    }
}

void AudioHandler::createPlayBackStream() {
    oboe::AudioStreamBuilder builder;
    setUpPlaybackStreamParameters(&builder);
    oboe::Result result = builder.openStream(&playbackStream);
    if (result == oboe::Result::OK && playbackStream != nullptr) {
        if (playbackStream->getChannelCount() != channelCount) {
            // LOG HERE TO SHOW WE MESSED UP REALLY BAD ON CHANNEL COUNT
            LOGW("Requested %d channels but received %d", playbackStream->getChannelCount(),
                 channelCount);
        }
        if (playbackStream->requestStart() != oboe::Result::OK) {
            LOGE("Error starting stream. %s", oboe::convertToText(result));
        }
    }
}

```

Inside the call back i have nothing in the audio data and i get zeros only

```
oboe::DataCallbackResult AudioHandler::onAudioReady(oboe::AudioStream *audioStream, void *audioData, int32_t numFrames) {
    int32_t channelCount = audioStream->getChannelCount();

    if (audioStream->getFormat() == oboe::AudioFormat::Float) {
        memset(static_cast<uint8_t *>(audioData), 0,
               sizeof(float) * channelCount * numFrames);
        // ... Some processing here then proceed to playback
        oboe::ErrorOrValue<int32_t> status = playbackStream->write(audioData,numFrames,0);
        int32_t framesRead = (!status) ? 0: status.value();
        LOGI("FRAMES READ %d", framesRead);
        LOGI("DATA VALUE FOUND %d",((uint8_t*)audioData)[0]);
    } else {
        memset(static_cast<uint8_t *>(audioData), 0,
               sizeof(int16_t) * channelCount * numFrames);
        LOGI("DATA VALUE FOUND %d",((uint8_t*)audioData)[0]);
    }
    return oboe::DataCallbackResult::Continue;
}
```
Is there something i have to do different to get this to work ? , i am porting something originally done in port audio and passing the audio buffer to kiss_fft .

**Comment by SchmadenSchmuki** [comment]
Not shure if I get it right, but the following seems strange to me:
Your callback is set to your inputstream, still the first thing you do in onAudioReady, is to set all audioData-information to 0.
For an inputstream I would expect that you copy from audioData or processed the related data.
So, to me, it looks like you immediately overwrite (set to 0) any data you get from your inputstream.
(Also, in your setUpRecorderStreamParameters-method you set the format to oboe::AudioFormat::I16, so the if-section (which contains the write call) of your if-else-statement should never be reached.)
Greetings Schmaden

**Comment by williamkibira** [comment]
For the other parts , i was trying to getting something working when it did
not work the first time but, for the first thing you commented about , how
would i go about collected data from the microphone if at all using the
call back is wrong ?

**Comment by SchmadenSchmuki** [comment]
I didn't mean to not use a callback.
I just wanted to say I think the memset instructions

memset(static_cast<uint8_t *>(audioData), 0,
              sizeof(float) * channelCount * numFrames);

and

memset(static_cast<uint8_t *>(audioData), 0,
              sizeof(int16_t) * channelCount * numFrames);

set all the audiodata (the callback provides to you from the microphone) to 0.
With an inputstream/inputcallback void* audioData is where the recorded audiodata is provided, so setting all the information there to 0 results in being able to handle the recorded data.
I may be wrong but that's what I wanted to say and how I think it is.
Grettings Schmaden

**Comment by williamkibira** [comment]
I see , that makes sense although i still get nothing from the microphone
when i remove the two memset calls , and remove format specification in the
recording stream builder .

**Comment by williamkibira** [comment]
Any chance you could show me a sample that does microphone capture , would
be really grateful if i could see a correct implementation for microphone
audio capture , at least to show how the stream is constructed and audio
data is captured .

**Comment by williamkibira** [comment]
here is what i have so far now 
**Audio Callback**
```
oboe::DataCallbackResult
AudioHandler::onAudioReady(oboe::AudioStream *audioStream, void *audioData, int32_t numFrames) {
  if (audioStream->getFormat() == oboe::AudioFormat::Float) {
  }else{

 }
 playbackStream->write(audioData,numFrames,0);
 return oboe::DataCallbackResult::Continue;
}
```
Recording parameters
```
void AudioHandler::setUpRecorderStreamParameters(oboe::AudioStreamBuilder *builder) {
    builder->setAudioApi(oboe::AudioApi::Unspecified);
    builder->setDeviceId(captureDeviceId);
    builder->setChannelCount(channelCount);
    builder->setBufferCapacityInFrames(bufferSize);
    builder->setSampleRate(sampleRate);
    builder->setDirection(oboe::Direction::Input);
    builder->setSharingMode(oboe::SharingMode::Exclusive);
    builder->setPerformanceMode(oboe::PerformanceMode::LowLatency);
    builder->setCallback(this);
}
```
Playback parameters
```
builder->setAudioApi(oboe::AudioApi::Unspecified);
    builder->setDeviceId(playbackDeviceId);
    builder->setChannelCount(channelCount);
    builder->setBufferCapacityInFrames(bufferSize);
    builder->setSharingMode(oboe::SharingMode::Exclusive);
    builder->setDirection(oboe::Direction::Output);
    builder->setPerformanceMode(oboe::PerformanceMode::LowLatency);
```
I just get a scratchy sound out put .

**Comment by dturner** [comment]
Does your app have the recording permission? You'll need to [specify it in the manifest](https://github.com/googlesamples/android-audio-high-performance/blob/master/aaudio/echo/src/main/AndroidManifest.xml#L7) and [request it at run time](https://github.com/googlesamples/android-audio-high-performance/blob/master/aaudio/echo/src/main/java/com/google/sample/aaudio/echo/MainActivity.java#L159).

**Comment by dturner** [comment]
We're currently working on an "echo" sample which records audio from the built-in microphone, does some signal processing and then outputs it to the built-in speaker or headphones. @ggfan is the primary author, his fork containing this sample (which is a work-in-progress) is here: https://github.com/ggfan/oboe/tree/echo

**Comment by ggfan** [comment]
yeah, will continue work on that to get it work out. you probably could try to set the callback size, leave the buffer size/capacity size for the recording stream as is:  the recording buffer size is pretty big, if do not set framesPerCallback, that is going to be huge delay/latency.

Make sure you are setting the input stream & output streams to Float; earlier in the code they seems to be set to I16 and your callback handler expecting it to be Float (default might be I16, not Float, but I would just set to what I need rather than depends on default for anything )

I also try to throw away certain amount of audio at the very beginning: the recording stream does not seem to be stable at the very starting ( I throw away half second's worth of audio data; different platforms would be different, and .5 second is a number as good as any number you could guess, still experimenting on it).

**Comment by williamkibira** [comment]
I see , that would explain the scratch squeaky sound i am getting .
I will try to preset the audio formats to use for input and play back so as
to see what th results might be .

Will report my finding on these experiments as well .

**Comment by williamkibira** [comment]
The microphones are working fine , i'm guessing the above stated procedure
fixes the noise i get when i start the application , it actually works like
an echo application but, a really bad and unstable one .

I will take you up on this although i wanted to pass the audio buffer to
`kissfft`  Thanks for the tip .

**Comment by dturner** [comment]
If you are still having issues please reopen this issue
