### ISSUE TITLE
Can we make different delays between record-play using oboe

### ISSUE THREAD

**Issue by Anshul1507** [google/oboe#1158]
Hey, Can we use oboe in delaying(varying) recording track? 
Ex: User set a delay of 1s/2s/3s .. etc, and user can listen back his audio in parallel just like Delayed Auditory Feedback.

**Comment by philburk** [comment]
A delay line is implemented using a large circular array of samples.

Oboe library does not provide delay as a feature. We normally try to reduce delay. ;-)

But there are two examples of of adding delay. One in OboeTester "ECHO INPUT TO OUTPUT".
The [InterpolatingDelayLine](https://github.com/google/oboe/blob/master/apps/OboeTester/app/src/main/cpp/InterpolatingDelayLine.cpp) can be used to add delay. (It does not yet do interpolation.)

There is also a [DelayLineEffect](https://github.com/google/oboe/blob/master/apps/fxlab/app/src/main/cpp/effects/DelayLineEffect.h) in FXLab.
