### ISSUE TITLE
Provide a mechanism for Oboe to access the JNI environment

### ISSUE THREAD

**Issue by dturner** [google/oboe#116]
This would allow Oboe to query Java APIs for optimal stream properties (e.g. sample rate and buffer size). This would remove the dependency on the caller knowing what the optimal stream properties are, and instead would just require them to call a single native method.

**Comment by p-i-** [comment]
Cross-referencing to https://github.com/google/oboe/issues/95

**Comment by philburk** [comment]
We could pass a JNIEnv to Oboe and let Oboe extract what it needs.
Or write some Java code that gets the best parameters and passes them to Oboe.
What parameters are needed?

- framesPerBurst (192?)
- sampleRate (48000, 44100?)

**Comment by dturner** [comment]
Encapsulates #27

**Comment by p-i-** [comment]
Could we also have the *native data-type* (e.g. SInt16 or Float32)?  Then I think we will have the lowest possible level of access possible.

My suggestion (as someone unfamiliar with android dev, mind you) on #95 was:

```
enum DATA_TYPE {
    SINT16, FLOAT32, FLOAT64
};

struct HardwareStreamProps {
    int inOut; // 1 for input 0 for output
    std::string name; // e.g. "Inbuilt Mic"
    int sampleRate; // is this ever noninteger??
    DATA_TYPE dataType;
    int nChannelsPerFrame;
    int nFramesPerBuffer;
};

std::array<HardwareStreamProps> enumerateHardwareStreamProps(void* jniEnv);
```

**Comment by dturner** [comment]
@p-i- Much of this information is held already in the `AudioDeviceInfo` class. 

> We could pass a JNIEnv to Oboe and let Oboe extract what it needs.

Thinking about this some more, this makes the most sense because we can have Oboe access objects like `AudioTrack` for the getTimestamp method on API 24+

**Comment by niklasdahlheimer** [comment]
Really looking forward for this feature to query timestamps. Is there any chance you could implement this in the next weeks?

**Comment by jarlg** [comment]
I see a better interfacing with JNI not only as useful, but necessary. I agree accessing e.g. optimal stream properties would improve the ergonomics of using Oboe, but what about handling attaching/detaching of the JVM?

A natural use case is that one starts an Oboe recording (calling microphone.requestStart, then processing in onAudioReady) for a certain time, which then calls back into Java upon finishing. Calling back means attaching the JVM---which is fine---and later going through the trouble of properly detaching it. A natural home for detaching would be the onExit-method, mentioned in the docs but unimplemented(removed?). Since onAudioReady needs to return Stop, we cannot detach before returning either. What is currently the prefered way to detach from the JVM in such a scenario?

I think a library that necessarily is accessed through the JNI should necessarily implement and interface with it. If anyone is aware of resources regarding the above, tips would be much appreciated!

**Comment by niklasdahlheimer** [comment]
@dturner Any news about this? Is it postponed for a while or do you make progress?

**Comment by dturner** [comment]
I did make some limited progress and have pushed this to the [addjavaenv branch](https://github.com/google/oboe/tree/addjavaenv). I added a test app which passes the `Activity` object to the native code. This native code then [queries the native buffer size using JNI](https://github.com/google/oboe/blob/addjavaenv/tests/OboeTest/app/src/main/cpp/native-lib.cpp#L11).

That said, we now have a way of setting the default properties for a stream using `oboe::DefaultStreamValues::BufferSize` so it's much easier to do this in Java. 

I haven't had time to look at attaching/detaching from the JVM, setting up audio device callbacks (e.g. when headphones are inserted) or querying for timestamps. Please feel free to have a crack at this 😃

**Comment by niklasdahlheimer** [comment]
A few thoughts/questions:

1. As far as I can see there is no DefaultStreamValues::BufferSize. Only `SampleRate`, `FramesPerBurst` and `ChannelCount`. Or did you mean `BufferCapacityInFrames`?

2. I've played around a little with you test app. The query of the native buffer size works fine. But that method needs to be called from Java to get the `JNIEnv` passed. As you mentioned, the next step would be to attach to the JVM, I spend a few hours in trying, but had no luck finding a way to query the JVM object, so I could query the `JNIEnv` from there and so on.
But maybe thats not what you planned? At some point the stream has to be invoked from Java anyway. So whats about to pass the `JNIEnv` and the `jobject` to a wrapper-function in the oboe-builder and call `setSampleRate()` and `setFramesPerCallback()`

3. Whats your idea of querying timestamps from the Java environment for the oboe stream? I mean, its possible to build an `AudioTrack` and query it's timestamps but these timestamps have nothing to do with the timestamps of the oboe stream, do they? How are you going to attach to the oboe stream?

**Comment by dturner** [comment]
> As far as I can see there is no DefaultStreamValues::BufferSize. Only SampleRate, FramesPerBurst and ChannelCount. Or did you mean BufferCapacityInFrames?

Sorry I meant `oboe::DefaultStreamValues::FramesPerBurst` (and have updated my previous comment). This is the same as the "native buffer size" and is the smallest discrete amount of audio data which is processed by the audio device.  

> I've played around a little with you test app. The query of the native buffer size works fine. But that method needs to be called from Java to get the JNIEnv passed. As you mentioned, the next step would be to attach to the JVM, I spend a few hours in trying, but had no luck finding a way to query the JVM object, so I could query the JNIEnv from there and so on.
But maybe thats not what you planned? At some point the stream has to be invoked from Java anyway. So whats about to pass the JNIEnv and the jobject to a wrapper-function in the oboe-builder and call setSampleRate() and setFramesPerCallback()

In my mind the largest area of complexity comes from a stream being destroyed and recreated e.g. when headphones are inserted. When a stream is disconnected the client receives a call to `AudioStreamCallback::onErrorAfterClose` on the audio thread and the client will need to recreate the stream ([example](https://github.com/google/oboe/blob/master/samples/hello-oboe/src/main/cpp/PlayAudioEngine.cpp#L280)).

To create a stream with the lowest latency Oboe needs to know the optimal properties of the current audio device. This is all taken care of in AAudio (with a small  exception for input streams) but in OpenSL ES it's not. This is why we added the ability to set default stream values so that the biggest use case, connecting to built-in audio devices, is taken care of. 

What needs to happen when (re-)creating a stream is: 

1) [Attach to the JVM](https://stackoverflow.com/questions/12900695/how-to-obtain-jni-interface-pointer-jnienv-for-asynchronous-calls) - It seems that it's OK to hold a global reference to the JVM and attach a C++ thread to it so this may be more useful than passing JNIEnv from Java
2) Query Java for the current audio device
3) Query the properties of that audio device. For built-in: use the AudioManager properties, for USB: use AudioDeviceInfo.getSampleRates(), choose the highest sample rate, for Bluetooth: ??
4) Use this info to create the stream

> Whats your idea of querying timestamps from the Java environment for the oboe stream? I mean, its possible to build an AudioTrack and query it's timestamps but these timestamps have nothing to do with the timestamps of the oboe stream, do they? How are you going to attach to the oboe stream?

In API 24 a method was introduced `AcquireJavaProxy` ([example usage](https://github.com/googlesamples/android-audio-high-performance/blob/master/SimpleSynth/app/src/main/cpp/audio_player.cc#L306)) this returns the `AudioTrack` object for the current oboe stream, which can then be queried for timestamps via JNI.

There's a lot of work here but I think a first stage would be to verify that attaching to the JVM from the audio thread works when disconnecting a stream.

**Comment by philburk** [comment]
I think this timestamp proxy would be a good tech note.

**Comment by dturner** [comment]
Update the hello-oboe sample to demo how to get fast track using USB audio device

**Comment by philburk** [comment]
Can we close this?
