### ISSUE TITLE
dlclose could cause segfaults

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#1160]
As per [NDK Known Issues](https://github.com/android/ndk/wiki/Changelog-r22#known-issues), calling `dlclose` could cause segfaults on M or newer:

> Issue 360: thread_local variables with non-trivial destructors will cause segfaults if the containing library is `dlclose`ed on devices running M or newer, or devices before M when using a static STL. The simple workaround is to not call dlclose.

I don't know if unloading aaudio lib in this code could cause the mentioned segfaults:
https://github.com/google/oboe/blob/f7ecdb62fb1a27af4e00eef4bfb092047955b698/src/aaudio/AAudioLoader.cpp#L26-L31

PS: I also mentioned it as the review comments here a while ago: https://github.com/google/oboe/commit/65983d66e8846ddf19003a7332ee123dca4b5618#r45333188 (not sure if github notifies review comments of older commits, so wrote this issue)

**Comment by philburk** [comment]
Thanks for the notification.  I checked libaaudio and libaudioclient and there are no uses of thread_local. It is pretty rare in Android.

But, AAudioLoader is a Singleton that is statically allocated. So we can safely remove the dlclose() without causing a resource leak.

**Comment by rpattabi** [comment]
Thanks for the details. I didn't realize that this destructor never gets called. I agree, it is still better to remove `dlclose()`.
