### ISSUE TITLE
OpenSL ES should use an array of callback buffers

### ISSUE THREAD

**Issue by philburk** [google/oboe#1165]
Android version(s): all
Android device(s): all
Oboe version: 1.5

**Short description**
In https://b.corp.google.com/issues/154868033#comment9 Glenn Kasten wrote:

  AudioStreamOpenSLES.h:    constexpr int kBufferQueueLength = 2; // double buffered for callbacks
but:
  AudioStreamOpenSLES.h:    std::unique_ptr<uint8_t[]>    mCallbackBuffer;
To actually take advantage of kBufferQueueLength > 1, we'll need to change mCallbackBuffer to be an array.
Note that bqCallbackGlue() is called after each buffer is consumed, but does not indicate which buffer was consumed.
You need to keep track of that yourself.  For example, for kBufferQueueLength = 2, then:
  fill a with data [which could be zeroes initially]
  Enqueue(a)
  fill b with data [which could be zeroes initially]
  Enqueue(b)
  bqCallbackGlue() is called when a is consumed
  fill a with data
  Enqueue(a)
  bqCallbackGlue() is called when b is consumed
  fill b with data
  Enqueue(b)
  etc.

**Comment by flamme** [comment]
We can have an array of buffers and queue the buffer cyclically.
