### ISSUE TITLE
Bug in example: getTimestamp(), FilterAudioStream.h needs a NULL check on framePosition

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#1166]
I was ready to write a crash report on Oboe 1.5.0, when I realized that my code calling getTimestamp(CLOCK_MONOTONIC, 0, 0) was wrong. I thought I probably copied it quite some time ago from example code and indeed, PlayAudioEngine.cpp of the hello-oboe sample contains it as well:

mIsLatencyDetectionSupported = (mPlayStream->getTimestamp(CLOCK_MONOTONIC, 0, 0) !=
                                        oboe::Result::ErrorUnimplemented);

In FilterAudioStream.h, this leads to a crash in:
 *framePosition = childPosition * mRateScaler;
or perhaps
getTimeStamp(clockId, &childPosition, timeNanoseconds);
if something is done using timeNanoseconds in that call.

Don't know why it survived in my app all the time and only started crashing with 1.5.0, but perhaps some null pointer checks are in order here. At least the sample code should be changed.

**Comment by philburk** [comment]
Thanks! You are right that FilterAudioStream.h needs a NULL check on framePosition.

> getTimestamp(CLOCK_MONOTONIC, 0, 0)

I cannot find that code in hello-oboe. I suspect you are using an old copy of the sample code.

**Comment by extreamsd** [comment]
Ah, you are right. I copied 1.5.0 on top of 1.4.x and 1.4.x (or perhaps an even older version) had PlayAudioEngine.cpp which is not part of 1.5.0 anymore.
