### ISSUE TITLE
Java AudioEffect not working with Oboe

### ISSUE THREAD

**Issue by faiziakbr** [google/oboe#1167]
Android version(s): 10
Android device(s): OnePlus 6

I have tried to apply Java AudioEffect using sessionID from **AudioManager** getting help from this [LINK](https://github.com/google/oboe/blob/master/docs/notes/effects.md) but I always get Null Pointer Exception when using **AcousticEchoCanceler.create(sessionId);** but when I pass the sessionId of Java AudioRecord **getAudioSessionId()** it works.

My Code is:

```
 val audioManager: AudioManager = context.getSystemService(Context.AUDIO_SERVICE) as AudioManager
 val sessionId = audioManager.generateAudioSessionId()
```
  C code is
  ```
   recordingBuilder.setSessionId(static_cast<oboe::SessionId>(sessionId));
    oboe::Result recordStreamResult = recordingBuilder.openStream(&recordStream);
```

I have tried this code on **OnePlus 6** and **Motorola one Macro**

**Comment by philburk** [comment]
To clarify, does the recording stream open and work OK?

Is the Null Pointer Exception in Java  under the call to AcousticEchoCanceler.create(sessionId) or in another thread?
Can you attach the stack dump? Attach a separate file if it is a longer than ~20 lines.

Does AcousticEchoCanceler.create(sessionId) return a null? That is legal and should be checked.
https://developer.android.com/reference/android/media/audiofx/AcousticEchoCanceler#create(int)

Does your code work on other devices?

**Comment by faiziakbr** [comment]
Hi PhilBurk

Thanks for replying. I have resolved the issue of: Why my AcousticEchoCanceler.create(sessionId) returned null even though it was available.

Here is the code

```
val audioManager: AudioManager = context.getSystemService(Context.AUDIO_SERVICE) as AudioManager
        val sessionId = audioManager.generateAudioSessionId()
        //This is the line that enables AEC when MODE is set
        audioManager.mode = AudioManager.MODE_IN_COMMUNICATION 
```

When mode is explicitly set to MODE_IN_COMMUNICATION then AcousticEchoCancelation start working. From here you can enable or disable it.

```
val isAecAvailable = AcousticEchoCanceler.isAvailable()
        val acousticEchoCanceler = AcousticEchoCanceler.create(sessionId)
        acousticEchoCanceler.enabled = true

        if (acousticEchoCanceler != null)
            Log.e(TAG, "AEC STATUS:  ${acousticEchoCanceler.enabled}")
        else
            Log.e(TAG, "AEC  IS NULL")
```

Currently, I am using Oboe version: 1.5 stable
