### ISSUE TITLE
Is there typo in FullDuplexPass?

### ISSUE THREAD

**Issue by Cova8bitdots** [google/oboe#1176]
Android version(s):
Android device(s):
Oboe version: 1.5.0
App name used for testing: LiveEffect
 
**Short description**
(Please only report one bug per Issue. Do not combine multiple bugs.)
This issue is not so high priority bug.
I found oboe plugin was updated from 1.4.3 to 1.5.0, and I checked difference between in these version codes.

I have a question about updated LiveEffect sample code.
In `FullDuplexPass.h`, there is code which controls the length of input and output streams.
It seems that `numOutputSamples` should be calculated from `numOutputFrames` in argument, however, `numInputFrames` is used for calculate.

https://github.com/google/oboe/blob/fdac78658c422932f96eea3efe1e5d93198de990/samples/LiveEffect/src/main/cpp/FullDuplexPass.h#L40-L41

I think this is typo, isn't it?

Thank you

**Comment by enkeyz** [comment]
Would like to take this.

**Comment by philburk** [comment]
Fixed in #1179. Thanks enkeyz

**Comment by enkeyz** [comment]
You're welcome.
