### ISSUE TITLE
'builder_setUsage' set to VoiceCommunication cannot work

### ISSUE THREAD

**Issue by chenj-freedom** [google/oboe#1189]
Hello! First of all, big thanks for this lib which is awesome.

The problem I encounter using Oboe (v1.4.3) is related to function 'builder_setUsage'.
when I set the param of <builder_setUsage> to 'Usage::Media', everything is ok. But when I set the param of <builder_setUsage> to 'Usage::VoiceCommunication', it can not hear anything.

I have checked my system volume and the volume for each category has been set to the maximum. I've also tested it on a number of devices, such as Pixel 4XL, Galaxy Note9, and more, and got the same results.

What can I do to fix the problem?
Thank you very much in advance for your support :)

**Comment by philburk** [comment]
Thanks. I will investigate. Are there any devices where Usage:VoiceCommunication does work?

We need to fix this:    OboeTester needs a menu to set Usage and ContentType #1024

**Comment by philburk** [comment]
OboeTester now has a menu to set Usage and ContentType.
We also have the Data Paths test in OboeTester and CTS Verifier.
