### ISSUE TITLE
Question: Is it possible to use Obeo for live audio IO while recording video/audio at the same time

### ISSUE THREAD

**Issue by WassimErriha** [google/oboe#1193]
Hello Obeo Team! Sorry for posting a question to this issue tracker, but I'm unable to get much help elsewhere. 
I am working on an Android music collaboration app where musicians can plug their instruments in, listen to a track from a list and play along with it. Although the app is entirely in Java, everything is working fine. The audio/ video is handled by MediaRecorder and the latency is adjusted manually by the user before mixing. The issue I'm trying to get around is the ability to play the instrument "live" during the recording process. For this I use Obeo's LiveEffect module to obtain a low latency audio.  This seems to work OK until I start recording video and audio with MediaRecorder. This is when the live audio produces a noticeable delay. 
I'm new to C++ programming and I lack a deeper understanding of how the Android platform's audio works. Can someone please explain to me why this is such a bad idea. And if so, is there something that I can do to work around this.
Thank you so much for your time!

**Comment by philburk** [comment]
If you are recording live video and audio with MediaRecorder then you should also record the musician with MediaRecorder. Otherwise it will be hard to synchronize the result.

**Comment by WassimErriha** [comment]
Hi @philburk.  Sorry if the question seems vague. 
Both video and audio are recorded with MediaRecorder. The issue is that while the user is playing along to a backing track for instance, they can only hear the backing track but not the instrument they are playing through their headphones. So because of this, they need to keep one ear off so that they can hear what they are playing while following along with the backing track. After the recording session concludes, the user then offsets their recording with the backing track manually. Once the offset is made, the two audio tracks are mixed.
what I'm currently trying to do is to make it possible for the user to listen to the backing track AND the instrument they are playing at the same time. this is why I'm using Oboe to get a low latency audio steam. This audio stream is not being recorded. it is just a "live" stream of the user's instrument.
At the moment, the audio stream obtained by Oboe works without any latency when it's running by itself. The problem only happens when I start MediaRecorder. This is when the "live" stream gets delayed. 
After the MediaRocrder is stopped, the delay is gone.
My assumption is that MediaRecorder shouldn't be blocking Oboe from doing Audio I/O. But if so, what can I do to change this behavior. 
This is tested on a Samsung Galaxy S10 running android 11.

**Comment by WassimErriha** [comment]
@dturner any input on this ? 
I can provide more information if the question is not clear.

**Comment by WassimErriha** [comment]
What I want to understand is if it's possible to record with MediaRecorder while also using Obeo to play the sound "live" to the user. is this a limitation of the Android system or is it just a matter of debugging ? can the same input stream be used by Oboe and MediaRecorder simultaneously?

**Comment by UniverseHan** [comment]
@WassimErriha Did you solve this problem? Why this issue was closed?

**Comment by dturner** [comment]
> can the same input stream be used by Oboe and MediaRecorder simultaneously?

AFAIK no. What is probably happening is that when you start the MediaRecorder audio/video capture it stops Oboe's input stream from being a low latency stream, which is why you hear additional latency/delay.  

What you're talking about is live monitoring whilst also recording video. It may be better to just record the video using `MediaRecorder` and record the audio of the user playing using Oboe. That way you can play both the backing track and the recorded audio using Oboe.

**Comment by WassimErriha** [comment]
@UniverseHan  No. As Don mentioned,  this is probably not a good way to go about this ... I had to disable the live audio.

**Comment by WassimErriha** [comment]
@dturner

> What you're talking about is live monitoring whilst also recording video. It may be better to just record the video using MediaRecorder and record the audio of the user playing using Oboe. 

I think you are right. I'll have to record the audio using Oboe instead. This might add the complexity of trying to sync the audio to the video afterwards, or maybe not. I'll have to test it first. 
I'm looking at modifying the LiveEffect sample to record the stream into a file. Any pointers on how I can do that ? Is there sample that demonstrates how to record to a file that I can take a look at ?
Thanks!

**Comment by simvirakaiml** [comment]
@WassimErriha take a look at this one https://github.com/HeroSony/oboe_fx_recorder.

**Comment by sunwell1994** [comment]
> > can the same input stream be used by Oboe and MediaRecorder simultaneously?
> 
> AFAIK no. What is probably happening is that when you start the MediaRecorder audio/video capture it stops Oboe's input stream from being a low latency stream, which is why you hear additional latency/delay.
> 
> What you're talking about is live monitoring whilst also recording video. It may be better to just record the video using `MediaRecorder` and record the audio of the user playing using Oboe. That way you can play both the backing track and the recorded audio using Oboe.

One potential issue is the workload of the video recording. The increasing workload can bring significant latency to Oboe recording.

**Comment by sunwell1994** [comment]
> > can the same input stream be used by Oboe and MediaRecorder simultaneously?
> 
> AFAIK no. What is probably happening is that when you start the MediaRecorder audio/video capture it stops Oboe's input stream from being a low latency stream, which is why you hear additional latency/delay.
> 
> What you're talking about is live monitoring whilst also recording video. It may be better to just record the video using `MediaRecorder` and record the audio of the user playing using Oboe. That way you can play both the backing track and the recorded audio using Oboe.

The timestamp from Video which is based on SystemClock.elapsedRealtimeNanos() is much different AAudiostream.gettimestamp(). How to sync the two clock?
