### ISSUE TITLE
1.5.1 Tag

### ISSUE THREAD

**Issue by sonicdebris** [google/oboe#1197]
I see there's a 1.5.1 version bump commit: https://github.com/google/oboe/commit/85f6061c46652897b99504732b664de2a84e9f2e
and I would like to use this revision to include fixes with samsung's input. Shall there be a corresponding `1.5.1` tag?

**Comment by philburk** [comment]
Making "tag" is easy but doing a "release" is more work?
Would a 1.5.1 tag be enough for you?

**Comment by sonicdebris** [comment]
We're not using the prefab package yet, so a tag would be enough, and not really critical in itself (I can always reference the commit). If releases imply some additional testing or review it would be nice to be able to rely on that for peace of mind, but again it's not critical, we'll do some regression testing on our app anyway.

**Comment by dturner** [comment]
I've added https://github.com/google/oboe/releases/tag/1.5.1

@philburk Do you think it's worth doing a full release? There's a [quirk for the S20](https://github.com/google/oboe/commit/9b184fcc2f6c23a1caacda550b483acdcc996ee9) and [remove call to dlclose](https://github.com/google/oboe/commit/2ca99f6dd20b8116ff4301a90a3924b8fbb1d44d) but not much else in /src.

**Comment by philburk** [comment]
Thanks Don!

@donturner - Let's merge #1200 and then review the Issues to see if there is anything else critical we want to fix for 1.5.2.

**Comment by philburk** [comment]
I created v1.5.2 milestone. Closing this because the requested tag was created.
