### ISSUE TITLE
How AAudio stream is connected to HAL ?

### ISSUE THREAD

**Issue by darth07** [google/oboe#1206]
As audio HAL opens pcm nodes to send the audio to a particular sound card. How does AAudio streams connects with the audio HAL or which is the function from AAudio that uses pcm write/read ?
Can I get some help in this ?

**Comment by philburk** [comment]
This comment describes the internal workings of AAudio. App developers should not need this level of detail. Are you writing an app or are you an OEM or SOC manufacturer? If you are working on vendor code you can get help through your Technical Account Manager.

AAudio MMAP streams connect with the HAL through the MMapStreamInterface in AudioFlinger.
It is used by [AAudioServiceEndpointMMAP.cpp](https://cs.android.com/android/platform/superproject/+/master:frameworks/av/services/oboeservice/AAudioServiceEndpointMMAP.cpp;l=131;drc=4719048ce0e6f8656a417a2f2fe6fbb848ed2ba7).

AAudio MMAP does not use pcm write/read. It writes directly to a DSP MMAP buffer.
AAudio Legacy goes through the HAL and uses the read/write calls in tinyalsa.

**Comment by darth07** [comment]
> AAudio MMAP streams connect with the HAL through the MMapStreamInterface in AudioFlinger.
> It is used by [AAudioServiceEndpointMMAP.cpp]
I was using my AAudio app in shared mode on hikey960 board but it always goes through the legacy path and it is unable to open MMAP stream  as it shows error  from [AAudioServiceEndpointMMAP.cpp](https://cs.android.com/android/platform/superproject/+/master:frameworks/av/services/oboeservice/AAudioServiceEndpointMMAP.cpp;l=131;drc=4719048ce0e6f8656a417a2f2fe6fbb848ed2ba7) openMmapstream - D/AAudioServiceEndpointMMAP: open() - openMmapStream() returned status -38
I followed [https://source.android.com/devices/audio/aaudio](https://source.android.com/devices/audio/aaudio) this link and did the changes except kernel changes which i think is not required for shared mode.
Any suggestions to make it follow MMAP path ?

**Comment by philburk** [comment]
The AAudio MMAP mode is only supported on a few high end devices. It requires quite a bit of work. Are you developing a product? If then please contact us through your Technical Account Manager.

Perhaps the feature is being declared but is not really supported. What does this return?

    adb shell getprop  aaudio.mmap_policy

> not required for shared mode.

If you are only implementing SHARED mode then you might as well use the Legacy path.
What latency are you getting when running OboeTester?

**Comment by darth07** [comment]
> The AAudio MMAP mode is only supported on a few high end devices. It requires quite a bit of work. Are you developing a product? If then please contact us through your Technical Account Manager.

Currently testing AAudio MMAP on hikey960 board with android 10 version. It will be later used for qualcolmm boards for a product.

>adb shell getprop  aaudio.mmap_policy
> 
This returns 2 as in device-common.mk file it is hardcoded as PRODUCT_PROPERTY_OVERRIDES += aaudio.mmap_policy=2

> not required for shared mode. 
> If you are only implementing SHARED mode then you might as well use the Legacy path.

I am currently implementing exclusive mode.
> What latency are you getting when running OboeTester?

It is showing timestamp.latency as approx ~ 67 / 130 / 143 ms

**Comment by darth07** [comment]
Sorry for the late reply 
I was trying it on **qualcolm 8195** 
adb shell getprop  aaudio.mmap_policy returns  **2**
![Screenshot (20)](https://user-images.githubusercontent.com/76944392/116539873-0ba28e80-a907-11eb-8fec-beca492d0f0e.png)
The oboetester app gives timestamp latency as - 3.3/11.7/21.4 ms
It shows MMAP as yes but exclusive as NO and also shows burst 96 capacity 1536 , MMAP,SH 
samplerate is set to 48000 and channels 2.

**Comment by philburk** [comment]
To get exclusive mode you need. aaudio.mmap_policy set to 2
and you need to implement the secure file descriptor using anon_inode:dmabuffer.
That is beyond the scope of Oboe so I am closing this Oboe issue.
If you are an OEM then please contact us through your technical account manager.
