### ISSUE TITLE
Run unit tests on top 3 Android phones

### ISSUE THREAD

**Issue by dturner** [google/oboe#121]
We need to verify that all the samples work correctly (low latency streams, no audio glitches) on devices down to API 16.

**Comment by ggfan** [comment]
Latest Code in main branch + Android -17 , failed to create recording stream with Error:
```
com.google.sample.oboe.echo E/libOpenSLES: Configuration error: unknown key
com.google.sample.oboe.echo W/libOpenSLES: Leaving AndroidConfiguration::SetConfiguration (SL_RESULT_PARAMETER_INVALID)
com.google.sample.oboe.echo E/OboeAudio: SetConfiguration(PERFORMANCE_MODE, 2) returned 2
com.google.sample.oboe.echo E/AUDIO-APP: Failed to create recording stream. Error: ErrorInternal
```
Any idea? I will mix the branches to see whether it is oboe or app

**Comment by ggfan** [comment]
recording stream issue should be addressed by this PR https://github.com/google/oboe/pull/125

**Comment by dturner** [comment]
Find the 3 most popular Android phones, run unit tests on them

**Comment by dturner** [comment]
Test results:

Samsung Galaxy S9 (SM-G960F) 8.0.0: All tests pass
Samsung Galaxy S6 (SM-G920F) 6.0.1: All tests pass
Google Nexus 6P 8.1.0: All tests pass
Google Pixel XL 8.1.0: All tests pass

A note about testing on Samsung devices: the `run-as` command doesn't work on Samsung devices ([more info](https://stackoverflow.com/questions/37413667/run-as-could-not-set-capabilities-operation-not-permitted)) and when executing the test binary using `adb shell` the owner does not have record permissions, this causes tests to fail and/or hang. 

To solve this I do the following: 

- Execute `tests/run_tests.sh` to build a binary for the currently connected device. 
- Copy the binary `tests/build/testOboe` into a wrapper app which requests the recording permission. I will publish this wrapper app when it's in a suitable state.

**Comment by dturner** [comment]
OK so for clarity these aren't the "top 3" Android phones but they are the most popular phones I can actually get my hands on. Hoping to get a more comprehensive set of test devices as time goes on but for now this should be sufficient with HTC, Samsung and Huawei covered by those 4 devices.
