### ISSUE TITLE
Possible contradiction in the Getting Started Guide

### ISSUE THREAD

**Issue by mjbattistello** [google/oboe#1211]
In the **Getting Started Guide** ( oboe/docs/GettingStarted.md), there seems to be a contradiction.

Inside onAudioReady() there is the following comment:
        // **We requested AudioFormat::Float so we assume we got it.**
        // For production code always check what format
        // the stream has and cast to the appropriate type.

And later on the guide, under the Playing Audio subtitle, it says:
If you did not specify a channelCount, sampleRate, or format then you need to query the stream to see what you got. The format property will dictate the audioData type in the AudioStreamDataCallback::onAudioReady callback. **If you did specify any of those three properties then you will get what you requested.**

**In the first place says _"we assume we got it"_ (seems it is not guaranteed), and in the second _"you will get what you requested"_ (seems it is guaranteed).**

Thanks!

**Comment by philburk** [comment]
Thanks for reporting that. Some of that doc was written before the official release. I will fix it.

The correct message is that if you specify sample rate, format or channel count then either the stream will not open, or you will get what you asked for.

**Comment by philburk** [comment]
Done.
