### ISSUE TITLE
WavStreamReader needs to read float samples

### ISSUE THREAD

**Issue by philburk** [google/oboe#1212]
It currently only supports 16-bit PCM (int16) format. But this is not obvious and can result in unexpected behavior and distortion as we saw in #1204.

Here is the code that needs to change:

https://github.com/google/oboe/blob/108a2cd854cc298e348b73a2638abd42bc1a6c32/samples/parselib/src/main/cpp/wav/WavStreamReader.cpp#L128

For any other unsupported format it should zero the output buffer so that people play silence and not uninitialized memory, which can be mistaken for a "tick" sound.

**Comment by android-usb** [comment]
Support new sample formats (PCM8, PCM24, PCM32, Float32) in WavStreamParser.
