### ISSUE TITLE
Glitches in hello-oboe when minimizing or maximizing app (Samsung Galaxy S20 FE)

### ISSUE THREAD

**Issue by chriscoomber** [google/oboe#1220]
Android version(s): 11
Android device(s): Galaxy S20 FE (SM-G780F/DS)
Oboe version:
App name used for testing: hello-oboe
 
**Short description**
When minimizing the app (using the home button to go to home screen) while sound is playing, a crunching sound is heard. When maximizing the app again (by clicking on the app in recent apps menu) a short crunching sound is heard.

**Steps to reproduce**
Run the hello-oboe app.
Touch your finger on the screen to cause sound to play.
With your other finger, minimize the app either by the home button or the recent apps button.
Open the app again from the recent apps menu.

**Expected behavior**
I use youtube as the standard. When minimizing the app while a video is playing the audio just gracefully cuts off, and when maximizing the app it is silent.

**Actual behavior**
Audio glitch (crunch) when minimizing the app and when maximizing the app. The latter is more noticeable as it comes from silence.

**Device**
We have also seen this on Samsung Galaxy S9 and I think I saw it on my Moto 5GS, though I'm charging it now to double check (edit: yep I see it using the app I mention below - didn't test hello-oboe).

**Any additional context**
I'm actually not too interested in hello-oboe, but I'm more interested in my app which uses Oboe. You can test this right now - the free version of the app can play the sample pieces included in the app. https://play.google.com/store/apps/details?id=com.organum.playscore

I've configured the stream to continue during configuration change (screen rotation) but be closed when the app goes invisible (onPause or onStop - one of the two) using `ProcessLifecycleOwner.get()`. It appears that when the stream is closed that we get the crunch, but I don't understand why we get a corresponding crunch when re-opening the app, as a totally new stream is created. Since it can be reproed in hello-oboe, I'm assuming this isn't something I've just implemented wrongly, though I'm open to being proven wrong - I'm just interested in getting rid of this crunch!

I've also tested waiting for the stream to stop before closing it using `waitForStateChange` - at the cost of blocking the Android UI thread while we wait - but to no avail.

Super bizarrely, I don't get any of the crunches when using the built-in screen + audio output recorder to try to record you an example of this happening. Perhaps that's because the stream is shared in that case (though hello-oboe does seem to request an exclusive stream).

**Comment by chriscoomber** [comment]
Thinking about this a little more, I suppose I shouldn't be too surprised that when the stream is closed we get a small glitch as the sample suddenly goes to 0; i.e. the wave is suddenly cut off. However, it's worth checking that what we're hearing is just that. Also, this doesn't account for hearing spurious audio when the stream is re-opened again.

Regarding the glitch when closing the stream (from cutting off the wave immediately), is it my job as the Oboe user to fade the audio out before stopping/closing the stream? I really just want the behaviour that YouTube has, where when you minimize the app whilst a video is playing, the sound just stops gracefully.

**Comment by chriscoomber** [comment]
OK, thanks for the help. Did you hear a crunch when returning to the app? It's possible this only reproes on some devices. That was the main issue. It appeared like Oboe was playing stale bits of the buffer (from before the stream was closed) upon opening a new stream.

**Comment by dturner** [comment]
Just retested on Pixel 4 and Samsung Galaxy S9+ (SM-G965F) both exhibited no crunches on pause or resume. Interestingly I had an old version of hello-oboe on the S9 (maybe from Oboe 1.4.3) which I tested before building and running the newest version - it crashed on pause with a lot of looping glitches. 

Are you running the latest version of Oboe i.e. `master` branch? We fixed a few race conditions recently which could occur when closing an audio stream which might account for the behaviour you're seeing.

**Comment by chriscoomber** [comment]
Sorry for the huge delay in responding.

So I think of the two "glitches" I describe in the issue (one on minimizing the app and one on re-maximizing the app) the former is just an abrupt stop, which is explained by the fact that I've got no code to ramp down the audio, I'm just closing the stream. **So let's not worry about the first glitch.**

The latter glitch (on re-maximizing the app) is more of a problem, though.

I just did some testing on hello-oboe using a pristine checkout of oboe:master from just now. **On my device** (Samsung Galaxy S20FE) **I was able to hear this glitch** using the default settings (i.e. press finger down to get audio from hello-oboe, click the recent-apps button in the nav bar, and then click on hello-oboe again to re-maximize it; you hear a short snippet of audio that sounds like the end of the audio from before).

My non-expert opinion is that when the app comes back into the foreground, it opens an audio stream, and it gets the dirty buffer from the stream that was just closed, which already has some wave data in. I'm not sure why that data isn't being zeroed out before reaching the audio device, but somehow neither hello-oboe nor oboe are doing this, and one buffer's worth of data from before the app was minimized is reaching the audio device.

I played around with a few settings and found the following:

- Default settings (i.e. device built-in speaker, Audio API AAudio) : hear glitch
- When using the device's screen+sound record feature (default settings in hello-oboe, but after turning on screen recording): no glitch
- When using earphone speaker (by changing settings in hello-oboe): no glitch
- When using bluetooth speaker (default settings in hello-oboe, but after connecting bluetooth speaker): no glitch
- When using Audio API OpenSL ES (by changing settings in hello-oboe): no glitch

I'm not completely sure how useful some of these are. Hello-oboe doesn't remember your settings when you minimize and re-maximize, meaning if you were using non-default settings when you re-maximize the app the settings get changed (back). So if the glitch were caused by re-using a "dirty" stream in some way, then it's not surprising that non-default settings avoid the glitch (since it is forced to make a fresh stream due to the changed settings).

But the case with the bluetooth speaker, and with the screen+sound recording feature turned on are interesting. I'm afraid I don't have another device to test with. I think this issue is still a legitimate issue, but only for the glitch on re-maximizing the app, and even then might be device-specific.

**Comment by philburk** [comment]
I tried the minimize/maximize of Hello-Oboe on a Samsung A51 (Exynos) running R. I do not have an S20.

According to https://www.phonemore.com/specs/samsung/galaxy-s20-fe/sm-g780fds/
that phone has an Exynos 990.

I can think of two bug that might cause the glitch. One is the uninitialized MMAP buffer at the HAL level.   The DSP starts reading the buffer before the app starts writing data so if it was uninitialized it would make noise until the app cleared it.  We could clear that buffer in the audio service just in case the HAL did not clear it.

Or there could be some phantom event in the input queue that is making the app think a finger was touched down very briefly. But that would probably make the same glitch on OpenSL ES, etc. So I think it is an uninitialized buffer.

**Comment by philburk** [comment]
I now initialize the AAudio MMAP buffer in S. Not much else we can do so I will close this.
