### ISSUE TITLE
Audio Stream transfer timeout 

### ISSUE THREAD

**Issue by hiteshzamad** [google/oboe#1232]
I am getting Audio Stream transfer timeout error while writing to audio stream.

**Comment by dturner** [comment]
We'll need more information to triage this issue. Please use the bug template to supply all the information about your runtime environment and open a new issue.

**Comment by hiteshzamad** [comment]
I am reading a wav file using fread in c++ as int16_t buffer array.
simultaneously i want to play the int16_t array using c++.
I have used audio_stream.write(buffer, buffer_size, nano_second);
Is it a proper way of doing it ??

**Comment by dturner** [comment]
Please avoid duplicate posting, it gets very confusing. I think I'm answering your question here: https://github.com/google/oboe/discussions/1235
