### ISSUE TITLE
Increase A2DP fame rate with oboe

### ISSUE THREAD

**Issue by shark8594** [google/oboe#1240]
Hi,

I was wondering if there was a way to increase the A2DP frame rate from the default value of 344Hz by feeding encoded audio frames at a faster rate to lower layers?. I was able to accomplish this by modifying the BTC layer, looking for an alternate way to do this that does not involve changing the stack itself. Thanks!

**Comment by philburk** [comment]
There is no way to do this using Oboe. It sounds like you are doing low-level work internal to Android.
Please contact the Android team through your Technical Account Manager (TAM).
