### ISSUE TITLE
how can i check Microphone occupied？

### ISSUE THREAD

**Issue by myj420** [google/oboe#1242]
A compatible problem about multiple app record

We are using oboe to record. On some phones, it didn’t return any error or failure when we open or start the input stream, but it didn’t really work.The question is how to get an exact result when open or start the input stream.

For example, we start a recorder app on background which uses the AudioRecord, and  when we start the input stream of oboe (most using SLES api) in another app(such as LIveEffect), it returns oboe::OK, we call the getState(), it returns oboe::StreamState::Started, but it doesn’t really work. And we found one log which is 
 
 E/AudioRecord: start() status -38
in the logcat.

Here is a brief result of different device:
Samsung S10+ Android 11 AAudio OK, OpenSLES OK
Xiaomi Mi 9 Android 10 AAudio OK, OpenSLES returns OK but not work
Huawei Hornor Android 8.1 AAudio returns OK but not work, OpenSLES returns OK but not work

**Comment by philburk** [comment]
If another app is using the mic then a second app cannot open it.
Unfortunately there is a known bug OpenSL ES.  
b/136590252 - OpenSL ES does not return an error if an input stream is opened when unavailable

This is not something we can fix. 
Do you need OpenSL ES on Android 10 or 11?

**Comment by myj420** [comment]
Thanks for your reply.  We do not use OpenSL ES on  Android 10 or 11，but we need to support the early android version. seems like we can only use Java API AudioRecord to check the microphone available on the early android version; 
  And we found another problem about AAudio only on the OnePlus 6T's Android 10.
When we use oboe::Inputpreset::Generic to open a mono input stream with AAudio, it doesn't work correctly too(we can't get the available PCM data from OnAudioReady). But it is OK with other preset, opening the stereo input stream, or using the OpenSL ES API.
Do you have any idea about it?

**Comment by philburk** [comment]
> When we use oboe::Inputpreset::Generic to open a mono input stream with AAudio, it doesn't work correctly

We have added the Data Paths test to OboeTester and to CTS Verifier.
So hopefully these sorts of device bugs can be caught before being shipped.
