### ISSUE TITLE
How to handle audio output device change?

### ISSUE THREAD

**Issue by MandarinSmell** [google/oboe#1244]
I'm trying to make Flutter plugin, and trying to bring Oboe library to Android side to perform the least latency when playing sound. My plugin is that it loads audio files, and converts it to PCM. Then developers can play sound at anytime, anywhere, so they can perform keyboard thing as well too.

I could perform mixing, manipulating playback, panning quite well. Device can play sound with minimum delays (I really love it). But problem happens when I change audio output device.

For example, I open app, and it plays sound well without any problems. But if I connect wired headphones to device, meaning preferred output device is now changed headphones from device speaker, it stops playing any sounds. Also, if I disconnect headphones again, it should play sound through device speaker, but it also doesn't play any sound.

It's same for opposite, if I start app with headphones connected to device, it can play sound with proper panning effect. But as soon as I disconnect headphones from device, it stops playing sound. So I have questions. I asked it this in [StackOverflow](https://stackoverflow.com/questions/67092859/how-to-handle-speaker-change-with-android-oboe-library), but I couldn't get answer, so I'm here to ask.

1. Does this mean, whenever users change audio output device, I have to close AudioStream and re-open it?
2. If yes for 1, is there any ways to handle this? Or can I make Oboe automatically picks audio device whenever it gets changed?

**Comment by android-usb** [comment]
Thanks for your question. Yes, if the audio device(s) change while the stream is open, you must restart it for the new device.

Have a look at the DrumThumper sample app. Specifically:
- the DeviceListener subclas in DrumThumperActivity.kt
- the resetOutput() method in DrumThumperActivity.kt
- restartStream() JNI function in DrumPlayer.kt & DrumPlayerJNI.cpp
