### ISSUE TITLE
Test plugging in/unplugging headphones on A51 whilst running Oboe app

### ISSUE THREAD

**Issue by dturner** [google/oboe#1249]
Use Shruti app.

If we get crash or ANR take a bug report.

**Comment by dturner** [comment]
Test steps: 

- Install [Shruti Carnatic Tuner app from Google Play](https://play.google.com/store/apps/details?id=org.kuyil.shruti)
- Run app and tap on "Sa" to hear a tone
- Insert headphones, listen for output on headphones, remove headphones, listen for output on built-in speaker

I tried plugging in and unplugging headphones in both the 3.5mm jack and the USB-C socket (via a Pixel USB headphone dongle). For both connection methods I tried rapidly plugging in and unplugging the headphones. As an estimate I did it about 50 times. 

I did not receive any crashes or ANRs. 

The only peculiarity I did notice was that with the USB-C connection the audio would often not switch over to the headphones, it just stayed on the built-in speaker - like the stream was not disconnected. 

Details of test device: 
```
Galaxy A51 
ro.product.brand = samsung
ro.product.manufacturer = samsung
ro.product.model = SM-A515F
ro.product.device = a51
ro.product.cpu.abi = arm64-v8a
ro.build.description = a51nsxx-user 11 RP1A.200720.012 A515FXXU4DUB2 release-keys
ro.hardware = exynos9611
ro.hardware.chipname = exynos9611
ro.arch = exynos9610
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]
```

**Comment by philburk** [comment]
This was probably du to this bug:
[b/173928197](http://b/173928197) | P3 | AAudio shared MMAP streams do not disconnect properly on RQ1A when headset plugged in
