### ISSUE TITLE
Error: use of undeclared identifier 'assert'

### ISSUE THREAD

**Issue by GlydeX** [google/oboe#1250]
Android version(s): 28
Android device(s): OnePlus 8
Oboe version: 1.5.0
App name used for testing: RhytmGame

 
**Short description**
Building error: ~\oboe\src\flowgraph\resampler\SincResampler.cpp:25:5: error: use of undeclared identifier 'assert'
The same error also occurs for classes PolyphaseResamplerMono.cpp, PolyPhaseResampler.cpp where "assert" is present.

**Any additional context**
Android Studio Version: 4.1.3
NDK Version: 22.1.7171670
Android Plugin Gradle Version: 3.5.1
Gradle Version: 5.4.1

**Comment by GlydeX** [comment]
Problem solved by importing the <cassert> in each class where this problem is present.

**Comment by philburk** [comment]
I don't see a PR for this fix. I assume the change was made locally. I am reopening it so we can make the change in the GitHub repo.

**Comment by GlydeX** [comment]
Yes I just changed it on my pc, I'm not sure if everyone is facing that problem but I hope that solution will work for those who encountered this.

**Comment by romanbsd** [comment]
it happens with NDK 22.1.7171670

**Comment by philburk** [comment]
This seems to have already been fixed in Oct 2020 in PR #1042.
So the fix should already be in the 1.5.0 release.

@GlydeX - please confirm

**Comment by philburk** [comment]
I think this has been fixed.

**Comment by GlydeX** [comment]
Sorry for the late reply! Yes, I confirm this bug is now fixed.
