### ISSUE TITLE
High latency on Samsung Galaxy A30

### ISSUE THREAD

**Issue by djelassiibrahim** [google/oboe#1252]
Android version(s): 10
Android device(s): Samsung Galaxy A30
Oboe version: 1.4.3
App name used for testing: Similar to drumthumper with integration of usb service
 
**Short description**
High latency around 90 ms when launching usb service on Galaxy A30. Please note that we've tested the same app on other devices like Xiaomi note 8 pro, infinix smart 5 and others ! There was no problem of high latency (latency is very acceptable around 16 ms). However, this appears only on Samsung Galaxy A30 when launching usb service to send command to play musical notes. Else, latency is low.

**Expected behavior**
Low latency when launching usb service (around 16 ms).

**Actual behavior**
High latency when launching usb service (around 90 ms ).

**Device**
Galaxy A30

**Comment by philburk** [comment]
@djelassiibrahim - What is the external USB device? Does it support sample rates > 48000?

In some cases, Android will choose a high sample rate for the USB connection. The sample rate conversion then results in high latency.

What do you get if you do the following:
If you are on Linux or a Macintosh, connect the device and please share the result for the following script. This gets properties of the device. 

```
for p in \
    ro.product.brand ro.product.manufacturer ro.product.model \
    ro.product.device ro.product.cpu.abi ro.build.description \
    ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
    do echo "$p = $(adb shell getprop $p)"; done
```

**Comment by philburk** [comment]
I measured round-trip latency on a Note10 Lite and an A51 running Exynos chips.
The latency was around 139 msec.
When I use the 3.5mm adapter the latency is around 15 msec.

**Comment by djelassiibrahim** [comment]
Hello
Thanks for your support. 
As I said, the problem was when launching the USB service. We've fixed it by increasing the max time for calling this function of USB reading. We've putted 10 ms instead of 0 ms.
