### ISSUE TITLE
Engine Failed to Open Streams!

### ISSUE THREAD

**Issue by vredzhepov** [google/oboe#1259]
Android version(s):
5.1.1
Android device(s):
SM-G361H
Oboe version:
1.5.1
App name used for testing: 
LiveEffect sample
 
**Short description**
After pressing the "Start" button application says "Engine Failed to Open Streams!"

**Steps to reproduce**
1. Clone source code repository
2. Select tag 1.5.1
3. Build LiveEffect sample
4. Upload LiveEffect application
5. Press the "Start" button

**Expected behavior**
 Audio loops from input stream to output stream when the button "Start" pressed

**Actual behavior**
After pressing the "Start" button application says "Engine Failed to Open Streams!"

**Any additional context**
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/com.google.oboe.samples.liveEffect.MainActivity: Attempting to start
I/OboeAudio: openStream() OUTPUT -------- OboeVersion1.5.1 --------
    AAudioLoader::open() could not find libaaudio.so
    loadSymbols() could not find libaaudio.so
W/OboeAudio: SharingMode [AudioStreamBuilder::setSharingMode()] is not supported on OpenSLES streams.
    PerformanceMode [AudioStreamBuilder::setPerformanceMode()] is not supported on OpenSLES streams running on pre-Android N-MR1 versions.
I/OboeAudio: AudioStreamOpenSLES::open() chans=2, rate=0
W/OboeAudio: configurePerformanceMode() not supported until N_MR1
D/OboeAudio: AudioStreamOpenSLES:configureBufferSizes(44100) initial mFramesPerBurst = 0, mFramesPerCallback = 0
    AudioStreamOpenSLES:configureBufferSizes(44100) final mFramesPerBurst = 960, mFramesPerCallback = 960
W/AUDIO-APP: Stream is NOT low latency.Check your requested format, sample rate and channel count
I/OboeAudio: openStream() INPUT -------- OboeVersion1.5.1 --------
    AAudioLoader::open() could not find libaaudio.so
    loadSymbols() could not find libaaudio.so
W/OboeAudio: SharingMode [AudioStreamBuilder::setSharingMode()] is not supported on OpenSLES streams.
    PerformanceMode [AudioStreamBuilder::setPerformanceMode()] is not supported on OpenSLES streams running on pre-Android N-MR1 versions.
D/OboeAudio: AudioOutputStreamOpenSLES(): requestStop() called
    AudioOutputStreamOpenSLES(): setPlayState_l() called
    AudioOutputStreamOpenSLES(): requestFlush_l() called
    AudioOutputStreamOpenSLES::close()
    AudioOutputStreamOpenSLES(): setPlayState_l() called
W/AUDIO-APP: Successfully closed streams

**Comment by philburk** [comment]
Thanks for the detailed report. That phone is described here:
https://www.gsmarena.com/samsung_galaxy_core_prime-6716.php

There are warnings in the log about things that OpenSL ES does not support.
But I do not see any error messages that would lead to not opening the stream.

We need to try this on an emulator.

**Comment by dturner** [comment]
It could be that the LiveEffect sample is opening an output stream with float format, then attempting to open an input stream with that same format. This fails because float is only available on API 23+. 

Solution may be to enable format conversion for the LiveEffect sample. 

@philburk Unfortunately the emulator doesn't support input streams

**Comment by dturner** [comment]
This should be fixed with https://github.com/google/oboe/pull/1334
