### ISSUE TITLE
How to record audio while played back by oboe at the same time. 

### ISSUE THREAD

**Issue by rene-dohan** [google/oboe#1260]
I am using library that uses oboe to play audio and I would like to record it. Is it somehow possible ?
This is example https://github.com/sheraz-nadeem/oboe_recorder_sample that can record from various sources but I don't see how to make it record what my app plays also by using oboe.

**Comment by dturner** [comment]
Pretty sure I answered this exact question on StackOverflow: https://stackoverflow.com/questions/67477171/how-to-record-audio-while-played-back-by-oboe-at-the-same-time/67485808#67485808
