### ISSUE TITLE
Unable to open float stream even with setFormatConversionAllowed = true on API <21

### ISSUE THREAD

**Issue by dturner** [google/oboe#1261]
Steps to repro: 

Run the following code on API < 21 device or emulator: 

```
AudioStreamBuilder builder;
builder.setFormat(AudioFormat::Float);
builder.setFormatConversionAllowed(true);
Result result = builder.openStream(mAudioStream);
```

Expected result: 
Stream opens successfully

Actual result: 
Stream fails to open with result being `ErrorInvalidFormat`

**Comment by philburk** [comment]
@dturner - Has this been fixed?

**Comment by dturner** [comment]
I was unable to reproduce this.  Perhaps there was something screwy going on with my emulator at the time. Either way, I've added format conversion to hello-oboe to prove that it is WAI.
