### ISSUE TITLE
Consider dropping support for older APIs 

### ISSUE THREAD

**Issue by dturner** [google/oboe#1263]
Lollipop (API 21) and above gives over 94% coverage (according to Android Studio stats): 

![image](https://user-images.githubusercontent.com/873212/118114307-50d2c000-b3df-11eb-8cb7-45c945133510.png)

And Marshmallow (API 23) gives 85%: 

![image](https://user-images.githubusercontent.com/873212/118114857-0f8ee000-b3e0-11eb-84ec-c9cab1f33ef6.png)

I currently have zero devices which run an API <23 which means the only way I can test changes on API 16-22 is through the emulator. This is unreliable and has a [bunch of open issues](https://github.com/google/oboe/issues?q=is%3Aissue+is%3Aopen+emulator). 

I wonder if we should just drop support for these older APIs so we can spend more time improving Oboe for modern devices.

WDYT @philburk @android-usb ?

**Comment by philburk** [comment]
Our first release was in 2018. That was three years ago. One could argue that dropping support for a few years worth of APIs is justified. We could maintain a moving window of APIs that we support. Each year going forward we can drop one more old year.

I just found an old personal phone running 4.1.1! Jelly Bean. So I can try the old issues.

I think we should try to fix the known issues. At least the ones related to the QuirksManager not doing Float conversion. That should be easy. Then we can punt the ones we can't fix and declare that we only support later versions.

It would be nice to support at least 90% of devices. So I think we should still try to support API 21+ (L).

**Comment by philburk** [comment]
I tried to get OboeTester to run on a Galaxy Nexus running API 16 but there were too many incompatibilities.

 I was able to launch HelloOboe.  There was no sound and I saw this error in the log. Looks like #1261 

com.google.oboe.samples.hellooboe E/AUDIO-APP: Error creating playback stream. Error: ErrorInvalidFormat

**Comment by philburk** [comment]
I created a label for "version" related issues. Click [version](https://github.com/google/oboe/issues?q=is%3Aissue+is%3Aopen+label%3Aversion+)

**Comment by paulorrfilho** [comment]
My app's minimum SDK is 23, anything below that falls apart for me, I would be ok with that. I gathered about 600 testers for my upcoming port to Android and only 2 of them had a phone with SDK < 23. I guess the Android Studio statistics are a bit skewed towards older SDK as there are many non-phone devices in that SDK range.

**Comment by triplef** [comment]
FWIW we’re targeting API 27 (Android 8.1).

**Comment by Diljeet** [comment]
My solution to this problem is
if (oboe::AudioStreamBuilder::isAAudioRecommended()) // or check for the api level
      builder.setFormat(AudioFormat::Float);

and in onAudioReady we should convert to 16 bit i.e. I16 format if float format is not available
converting float samples to short samples is pretty easy, this is done to support older devices
i can open the stream in android 4.4 device with this technique, which is not opening otherwise with float format

**Comment by peterdk** [comment]
I have like 4000 users on Android 4.4 and increasing numbers above that. I target API 18 with my app.
I would be happy to see oboe support 4.4+ or maybe 5.1+ as minimum, but lower then that would be a pity. I prefer to keep my app working for as many users as possible.

**Comment by philburk** [comment]
We have decided to support as old a version of Android as possible as long as it does not conflict with supporting new versions.
We can only test easily on Marshmallow and above. So we can only guarantee Oboe on API 23 (M, 6.0).
But Oboe may well work on older versions of Android.

**Comment by dturner** [comment]
If we're agreed on supporting API 21 we should update our docs and minSDK for samples to this. Suggest we do this for the 1.7 release.
