### ISSUE TITLE
Any way to stream Java mediaplayer playback stream to oboe?

### ISSUE THREAD

**Issue by OneBadNinja** [google/oboe#1271]
Greetings everyone

I am fairly new to Android and Oboe development, but I have a small mediaplayer app with transport controls that plays audio files on the device using the Android MediaPlayer framework. I have this working just fine as a standalone Java Android app, but I would like to add some custom DSP to the audio outside of the standard effects provided by the AudioEffect classes. This is a personal library of effects I've written in C++ so I've been reading up on Oboe as a result. 

Looking through the examples I've come across the LiveEffectEngine which seems ideal if I could replace the stream from the capture device with the audio stream from the MediaPlayer session. I've also come across the following article on here https://github.com/google/oboe/blob/master/docs/notes/effects.md which says if I have an audioSessionId I can pass this to an oboe capture stream builder and from my understanding this would be able to use this stream as an input (please correct me if I'm wrong). MediaPlayer can supply an audioSessionId for a file it is playing via its `mediaPlayer.getAudioSessionId()` method, so what I've done is attempt to use this as the sessionID when creating the capture stream. 
Here is my code

```
            oboe::AudioStreamBuilder * LiveEffectEngine::setupRecordingStreamParameters(
                    oboe::AudioStreamBuilder *builder) {
                // This sample uses blocking read() because we don't specify a callback
                builder->setSessionId(mInputSessionID) // we take audio in from an audio session (via Java)
                        ->setDirection(oboe::Direction::Input)
                        ->setDeviceId(oboe::kUnspecified)
                        ->setChannelCount(mInputChannelCount)
                        ->setErrorCallback(mErrorCallback.get());
                return setupCommonStreamParameters(builder);
            }
```

where `mInputSessionID` is that obtained from the MediaPlayer instance. I also have

```
            oboe::AudioStreamBuilder *LiveEffectEngine::setupPlaybackStreamParameters(
                    oboe::AudioStreamBuilder *builder) {
                builder->setDataCallback(mDataCallback.get())
                                ->setErrorCallback(mErrorCallback.get()) //
                                ->setDeviceId(oboe::kUnspecified) // will this default to the default playback
                        ->setDirection(oboe::Direction::Output)
                        ->setChannelCount(mOutputChannelCount) // todo set it to the correct channelc ount based on output device
                        ;

                return setupCommonStreamParameters(builder);
            }

            oboe::AudioStreamBuilder *LiveEffectEngine::setupCommonStreamParameters(
                    oboe::AudioStreamBuilder *builder) {
                // We request EXCLUSIVE mode since this will give us the lowest possible
                // latency.
                // If EXCLUSIVE mode isn't available the builder will fall back to SHARED
                // mode.
                builder->setAudioApi(oboe::AudioApi::Unspecified)
                        ->setSharingMode(oboe::SharingMode::Exclusive)
                        ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
                        ->setFormat(cFormat)
                        ->setFramesPerDataCallback(cPeriodSize)
                        ->setSampleRate(cSampleRate)
                        ->setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Best);
                return builder;
            }
```

I am setting a fixed period size for block-based processing. Running this there are no complaints and the streams are built successfully. The data callback is currently the default LiveEffectCallback, ie with 0.95 gain applied to the input stream. 

Now, I do not seem to be getting any audio output when playing audio files. I have placed breakpoints in the ```onBothStreamReady``` callback for the liveEffectEngine and I am always receiving input buffers filled with zeros. Furthermore any audio output I hear is from the mediaPlayer instance in Java which itself is also streaming to the audio outputs from what I understand (I suppose there is the mediaPlayer.setVolume() function for this that I could zero if this wouldn't affect the data passed to oboe?).

Has anyone done anything similar to this before? Is a feature like this (streaming from Java MediaPlayer to oboe for fx processing) supported by Oboe? I'm getting the impression it may be a bit unconventional. Alternatively, I suppose I could try to use libsndfile to play some audio files instead but I would prefer if I could use a built in android player for handling the content (potentially including video files), whose audio streams I could pass through some custom DSP via the Oboe framework.  Could anyone please point me in the right direction? :)

Many thanks in advance!

J

**Comment by philburk** [comment]
The LiveEffect demo shows how to synchronize low latency hardware input and output streams. For streaming you probably do not need super low latency and you do not need to synchronize a hardware input stream. So I would ignore the LifeEffect sample. Also you probably do not even need Oboe.

You might be better off using ExoPlayer and then defining a custom [AudioProcessor](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/AudioProcessor.html). Your processing code is in C++ so just call it using JNI from your Java processor. It does not have to be in a separate thread. You can still use the Java output that ExoPlayer uses.

**Comment by OneBadNinja** [comment]
Phil this is excellent! Looks just like what I need many thanks!
