### ISSUE TITLE
On the Android platform, recording fails

### ISSUE THREAD

**Issue by mmabluesky** [google/oboe#128]
hi  ，When I run lifeEffect this sample, the following error appears, the Android version is 7.1

I tried to add “SLuint32 performanceMode = static_cast<SLuint32>(PerformanceMode ::None)”
 ，but nothing

what should I do ?
![tim 20180625170017](https://user-images.githubusercontent.com/17948377/41840922-8c6866b2-7899-11e8-818c-216a10e5d802.png)

**Comment by philburk** [comment]
What is that error related to FileNotFoundException?
Could you please show more of the error log? Also please just show as text. The red on black is hard to read.

I see what might be an error in Oboe.
https://github.com/google/oboe/blob/master/src/opensles/AudioStreamOpenSLES.cpp#L128
The "!=" should probably be an "==". Try changing that. I will also investigate.

> I tried to add “SLuint32 performanceMode = static_cast(PerformanceMode ::None)”，but nothing

Did you do that "opensles/AudioStreamOpenSLES.cpp"? That would be an error. Oboe and OpenSL ES use different constants for their performance modes.

Try just commenting out the call to configurePerformanceMode().  Does it work then?

What device are you using?

Does the code work on earlier or later Android versions?

**Comment by philburk** [comment]
There is a pull request that might fix this.
https://github.com/google/oboe/pull/125

**Comment by mmabluesky** [comment]
@philburk  ，soory ，I tried to do that, but it was useless  ，
by the way，My Android version is 7.0, model Huawei glory 8

**Comment by mmabluesky** [comment]
@philburk ，sorry，I tried to do that, but it was useless ，
by the way，My Android version is 7.0, model Huawei glory 8

**Comment by AndroidDeveloperLB** [comment]
I don't see any error, and I run Android P DP3, yet the sample doesn't seem to do anything when I connect headphones to it, press "start" and make some noise.
The only time it does anything, is the feeback-loop when nothing is connected to it.

How come?

**Comment by AndroidDeveloperLB** [comment]
Is it supposed to record?
For me it only makes sound at real time.
Is there any sample of recording to file, out of all of the samples?

**Comment by philburk** [comment]
@mmabluesky Why did it start working? Did you try the pull request #125 ?

**Comment by mmabluesky** [comment]
@philburk  yes ， you have tryed the pull request #125

**Comment by mmabluesky** [comment]
@philburk ，yes ， I have tryed the pull request #125

**Comment by mmabluesky** [comment]
Hi  @philburk 
I can get the collected audio data through the portaudio callback. Now, I want to use oboe to replace portaudio. In the onAudioReady callback function, I use write(audioData, static_cast<size_t>(numFrames)) to capture the audio data. Write directly to my shared cache, this approach feels no problem, but I didn't get the result I wanted, can you help me?
![tim 20180627115852](https://user-images.githubusercontent.com/17948377/41952440-6fce957a-7a02-11e8-9124-20e48eb32be5.jpg)

**Comment by ggfan** [comment]
https://github.com/google/oboe/pull/125 should fix it. PerformanceMode was added to OpenSLES from N MR1, need to double check it: your 7.1 is N MR1

**Comment by dturner** [comment]
> but I didn't get the result I wanted, can you help me?

What result did you want? Please post full details of what you're trying to do, what you expect to happen as well as your phone model, Android API level and any other information which might help us understand your problem.

**Comment by mmabluesky** [comment]
Hi , @dturner 
I want to ask, when recording audio, I directly write the audiData  in the callback into my own circular cache.  Is this correct ?   I tried to do this, but the recorded audio seems to have some problems. Not to support the introduction of audioData, but also add some operations,

**Comment by mmabluesky** [comment]
@dturner 
Just like portAudio's data callback, I can get the correct recording audio for the same operation. What I can confirm is that some of the initialization operations before oboe are all correct,   but the audio callback here I don't know if my processing method is correct?
By the way, my system version Android 8.0, model Huawei glory 8

**Comment by dturner** [comment]
Please file a new issue with clear steps to reproduce your issue.
