### ISSUE TITLE
Add support for setPackageName(n)

### ISSUE THREAD

**Issue by philburk** [google/oboe#1282]
There are new functions in AAudio:

- AAudioStreamBuilder_setPackageName()
- AAudioStreamBuilder_setAttributeTag()

Add Oboe access.
Also maybe set default AttributionTag to "Oboe" for Media Metrics.

**Comment by dturner** [comment]
Don't call these functions unless the user explicitly sets values for package name or tag.

**Comment by dturner** [comment]
@robertwu1 Look at `AAudioLoader` which contains the linkages.

**Comment by robertwu1** [comment]
I was playing around with some changes here: https://github.com/google/oboe/commit/e2ff8fb292b81b6cdf9db3e4a469f4eccd56fba9 and I realized that doing this now is not a good idea for multiple reasons.

1. Users need to manually install NDK 23, the beta one.
2. We would need to update all samples to use Android 12, which is still in beta.

I don't see any reason to change this until Android 12 is officially out.
