### ISSUE TITLE
50+ bugreports for Vivo users: can't create stream IllegalArgument

### ISSUE THREAD

**Issue by peterdk** [google/oboe#1293]
Android version(s): 10 and 11
Android device(s): Vivo devices, 11 different models
Oboe version: 1.5
App name used for testing: Mini Piano Lite (umito.android.minipiano)

 
**Short description**
I get a lot of bugreports from users where the builder.openStream() fails with ErrorIllegalArgument, it turns out that all of them (really, all of them) are from Vivo devices. I see 11 devices , all android 10 and 11.

**Steps to reproduce**

``` 
    oboe::AudioStreamBuilder builder;
    builder.setDirection(oboe::Direction::Output);
    builder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
    builder.setSharingMode(oboe::SharingMode::Shared);
    builder.setFormat(oboe::AudioFormat::I16);
    builder.setChannelCount(oboe::ChannelCount::Stereo);
    builder.setDataCallback(this->callback);
    builder.setErrorCallback(this->errorCallback);

    oboe::Result result = builder.openStream(stream);
    if (result != oboe::Result::OK) {
        notifyException("Oboe: Failed to create stream. Error: %s",
                        oboe::convertToText(result));
        return false;
    }
```
**Expected behavior**
Stream gets created and works. As on all non Vivo devices.
**Actual behavior**
Get a  `Oboe: Failed to create stream. Error: ErrorIllegalArgument`
**Device**
Vivo 1901
Vivo 1904
Vivo 1907
V2037
vivo 2015
vivo 1806
V2026
V2043
vivo 1915
vivo 1935
I don't have a vivo device myself, so can't test. 
**Any additional context**
I have bugreports from 46 users, 117 events. And since the audio is vital to the app, the app just fails for them.

**Comment by philburk** [comment]
You are not doing anything unusual in your stream parameters. This seems so specific to Vivo that I will just report it directly to Vivo and MediaTek. Thanks for reporting this.

**Comment by philburk** [comment]
This is being tracked in Google and at MediaTek as b/190760894

**Comment by philburk** [comment]
Vivo has responded:
> We tested on device vivo 2015.   umito.android.minipiano works normally.

Here is the log from the open.

OboeAudio: openStream() OUTPUT -------- OboeVersion1.5.0 --------
AAudio  : AAudioStreamBuilder_openStream() called ----------------------------------------
AudioStreamBuilder: rate   =      0, channels  = 2, format   = 1, sharing = SH, dir = OUTPUT
AudioStreamBuilder: device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 0
AudioStreamBuilder: usage  =      1, contentType = 2, inputPreset = 6, allowedCapturePolicy = 0
[snip]
AAudio  : AAudioStreamBuilder_openStream() returns 0 = AAUDIO_OK for s#1 ----------------

If they cannot reproduce the error then there is not much we can do. If you can capture a bugreport file then you can file an Android bug and attach the file.
