### ISSUE TITLE
FifoBuffer.cpp "error: use of undeclared identifier 'memcpy'"

### ISSUE THREAD

**Issue by jplatipus** [google/oboe#13]
I get compilation "error: use of undeclared identifier 'memcpy'"
Adding the memory.h include fixes this.

I put in a pull request for the fix from master (the error happens for me in the master branch).

**Comment by dturner** [comment]
Hi jplatipus, 

Many thanks for submitting this fix. I have just realised you didn't sign the contributor's agreement (CLA). Please could you do so by following the instructions here: https://github.com/google/oboe/blob/master/CONTRIBUTING.md

Thanks very much, 

Don

**Comment by dturner** [comment]
Ignore me. I see you have signed the agreement, I'm just getting a strange error message: "Failure: CLAs are signed, but unable to verify author consent". Ignoring for now.

**Comment by jplatipus** [comment]
I went ahead and followed the link, and filled in the form.

Best regards,

Jacques (jplatipus)

**Comment by dturner** [comment]
Thanks for the quick response. Hopefully the issue won't arise again.
