### ISSUE TITLE
getDeviceId consistently returns 0 when FilterAudioStream is in use

### ISSUE THREAD

**Issue by chrismanchester** [google/oboe#1306]
When attempting to report audio routes in use from Oboe, we noticed that our getDeviceId calls consistently return 0, even just after re-starting a stream in response to plugging in a new output device.

I noticed that adding `mDeviceId = mChildStream->getDeviceId();` to the constructor of FilterAudioStream fixes this issue.

**Comment by philburk** [comment]
I was able to reproduce this with the following steps in OboeTester:

Launch OboeTester
Tap TEST OUTPUT
Select SRate 16000
Tap OPEN then START
Notice "devId = 2" in the middle of the screen. May be a differ N>0.
Tap CLOSE
Select SRC:Medium. (medium quality sample rate conversion)
Tap OPEN then START

EXPECT:
See "devId=2"

ACTUAL
See "devId=0"

The FilterAudioStream is a proxy class for AudioStream. it is used when we do sample rate conversion in Oboe.
It is supposed to pass commands and properties from the underlying stream. It looks like we missed the device ID property.
