### ISSUE TITLE
Facing screen layout issue on Wear device

### ISSUE THREAD

**Issue by ssarathbe** [google/oboe#1308]
Facing screen layout issue on Wear device

tried installing this apk on the Wear device, looks like apk screen layout is completely visible on the wear device display, it not even have scroll view.

looks like we need to add below two configs to Manifest.xml file
            android:theme="@android:style/Theme.DeviceDefault"
            android:configChanges="orientation|keyboardHidden|screenLayout"

please help to fix and publish this apk to support for wear devices as well

-moulisarath

**Comment by dturner** [comment]
Which app are you referring to?
