### ISSUE TITLE
OBOE recorder and player is causing voice muffling or distortion.

### ISSUE THREAD

**Issue by Ahad00711** [google/oboe#1314]
Basically, I have a architecture where I use the OBOE recorder and player and when I record the data and send data using Data channel to other phone then data send by these phones become muffled or distorted.
These are that threee devices.
```
1-Vivo V19  (Android 10)
2-Huawei Y9 prime  (Android 9)
3-One plus Nord N10 (Android 10)
```
But when I process the data by the WebRTC and then send it using the Audio channel then everything works fine. 
Can you tell me how to resolve the issue.

**Comment by dturner** [comment]
Please run the LiveEffect sample on those devices. 

If the issue is reproducible using LiveEffect we can investigate further.
