### ISSUE TITLE
No error when output stream fails to start

### ISSUE THREAD

**Issue by jgartman** [google/oboe#1316]
Android version(s): 11
Android device(s): Tab S7, Note 10+
Oboe version: 1.6.0
App name used for testing: OboeTester
 
**Short description**
This is a follow up issue to #1315.  When that issue occurs and oboe workarounds are enabled, the call to `AudioStream start` does not return an error.  However, the stream never transitions to the started state.  The start call returns but it seems to remain in the starting state indefinitely.  When workarounds are disabled a timeout will occur. 

**Steps to reproduce**
Enable oboe workarounds and follow the steps to reproduce #1315.

**Expected behavior**
`AudioStream start` will return an error if the stream fails to start.

**Actual behavior**
`AudioStream start` return Result::OK but the stream is not started.

**Device**
Tab S7:

```
ro.product.brand = samsung
ro.product.manufacturer = samsung
ro.product.model = SM-T970
ro.product.device = gts7xlwifi
ro.product.cpu.abi = arm64-v8a
ro.build.description = gts7xlwifixx-user 11 RP1A.200720.012 T970XXU2BUE2 release-keys
ro.hardware = qcom
ro.hardware.chipname = SM8250
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [1]
[aaudio.mmap_policy]: [1]
```

**Comment by philburk** [comment]
> However, the stream never transitions to the started state.

Does the stream run but just stays in the STARTING state? This may be similar to #37.

Or does the stream not run?

I recommend calling the asynchronous requestStart() instead of the synchronous start() method. The start() is vulnerable to problems in the state transitions.

**Comment by jgartman** [comment]
Thanks for your response @philburk.  The stream doesn't seem to actually run, the data callback is never called.  However, the streams internal state is set to STARTED.  Seems like my original post above was incorrect on that.  Usually when a stream transitions to the started state there's a message like this in logcat:

```
2021-06-25 15:14:30.855 24124-26067/com.philips.hc.ultrasound.lumify D/AAudioStream: setState(s#1) from 3 to 4
```
That message doesn't appear when this issue occurs but if you get the streams state afterwards it is STARTED.  I haven't debugged but I assume this is the code that's forcing it into the STARTED state:

```
#if OBOE_FIX_FORCE_STARTING_TO_STARTED
        if (OboeGlobals::areWorkaroundsEnabled()
            && aaudioNextState == static_cast<aaudio_stream_state_t >(StreamState::Starting)) {
            aaudioNextState = static_cast<aaudio_stream_state_t >(StreamState::Started);
        }
#endif // OBOE_FIX_FORCE_STARTING_TO_STARTED
```
When I tried to requestStart and then waited for the state transition I still see the issue, I assume the same code is still used in that case.

**Comment by philburk** [comment]
> This is a follow up issue to #1315. 

The bug #1315 was a serious race condition in AAudio that made it impossible to restart a Legacy stream. That was fixed in S. No error is reported to Oboe.  This issue is a side effect of that bug.

Perhaps we could make the workaround above conditional on the arrival of a callback, or on the completion of a blocking read/write. If the stream is dead then you would get the expected timeout.

**Comment by jgartman** [comment]
Thanks Phil, I think we'd be able to do either of those things in our app to detect the problem if you don't want to make Oboe changes for this.

**Comment by philburk** [comment]
Internal bug [b/192095564](http://b/192095564) | P1 | AAudio stream may not restart because of race in Legacy code
was fixed.
