### ISSUE TITLE
DrumThumper does not show up in Play Store for Shield running N

### ISSUE THREAD

**Issue by philburk** [google/oboe#1317]
Use NVIDIA Shield Tablet running N 7.0 (API 24)
Go to Play Store
Search for:  drumthumper

EXPECT: see DrumThumper app
ACTUAL: no DrumThumper app

Perhaps this could be reproduced on an emulator.

**Comment by android-usb** [comment]
Haven't updated the Play Store app since changing the build levels in the project.

**Comment by android-usb** [comment]
Update uploaded. Checked it and it is available.
