### ISSUE TITLE
NOTICE file contains the license text

### ISSUE THREAD

**Issue by hyandell** [google/oboe#1343]
**Short description**

The NOTICE file for the project contains a duplicate of the Apache-2.0 license text. Typically the NOTICE file would be used to provide additional content to the Apache-2.0 license, such as this file: https://github.com/apache/commons-lang/blob/master/NOTICE.txt

At the moment it's kinda asking for the text of the Apache-2.0 to be included twice. 

I mention this in case this wasn't the intent - perhaps the build is using NOTICE for another meaning than Apache-2.0's section 4(d).

**Comment by philburk** [comment]
I looked a a dozen repos in https://github.com/google
and I could not find any NOTICE files.
Maybe we can just delete ours.

**Comment by dturner** [comment]
@hyandell Thanks very much for spotting this. 

@philburk The `NOTICE` file was added by you in this commit: https://github.com/google/oboe/commit/0199e810a4e638b76e2929b46499ea23c57368dc. Can you remember why? 

I checked our releasing guidelines and [new project template](https://github.com/google/new-project) and it's not required.

**Comment by dturner** [comment]
This was added for internal compliance. @philburk to investigate changing its contents to remove this redundancy.
