### ISSUE TITLE
Bug: "RhythmGame" sample doesn't stop playing when leaving it

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/oboe#136]
As the title says.
I think it also has issues when changing orientation.

**Comment by dturner** [comment]
Good spot. The issue with orientation has been fixed in https://github.com/google/oboe/commit/f393890cd8a832740a6ea35752eac88a33354ca2. 

The simplest thing to do for RhythmGame is to destroy and recreate the engine when the user leaves the app, however, the correct thing to do would be to pause the stream, store the game state and restore it when the user returns to the game. This will likely not be a quick fix.

**Comment by AndroidDeveloperLB** [comment]
Can you please add explanation of the game, in the repository and/or sample app itself ?
I don't understand how to play it.

**Comment by dturner** [comment]
Does this help? https://github.com/google/oboe/blob/master/samples/RhythmGame/README.md

Also, there's an accompanying codelab: https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html

**Comment by AndroidDeveloperLB** [comment]
Oh... so I have to tap after each clap?
Maybe update the sample then? It's quite empty...
Maybe put a score, to show how many times the user did it well? Or give points based on how quick he is...
:)

**Comment by dturner** [comment]
I hear you - it's not that easy to understand unless you read the README or do the codelab. Keeping a score would be easy, although displaying it on screen would require a font rendering library for the OpenGL surface, or a separately updated `TextView`. If you want to add one and submit a pull request I'll definitely consider merging it.

**Comment by dturner** [comment]
I'm pretty sure it's working as intended. You hear 3 claps, you then have to copy those 3 claps on the first beat of the next bar. A perfect game would go like this: 

Game: clap clap clap pause
User: tap tap tap 

Each time the user taps the screen will flash orange (early), purple (late) or green (on time). After 3 taps the screen won't flash any more. 

More:https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html?index=..%2F..%2Fio2018#1

**Comment by AndroidDeveloperLB** [comment]
Oh, I thought it's this way:
Game: clap
User: as soon as possible: clap

This reminds me of the "Simon says" game, yet instead of 4 types, you have just one, and instead of changing between them, it will change the number of claps instead.
Is this true?

In the link you've shown, it says " second bar" . What is the second bar? I don't think I saw it.

Anyway, I will try the game again...
Thank you.

**Comment by dturner** [comment]
A bar is a musical term: https://simple.wikipedia.org/wiki/Bar_(music). It just means a short musical section. In this case the second bar is the time window in which the user should copy the pattern.

**Comment by AndroidDeveloperLB** [comment]
Hm. Maybe you should put the instructions on the game sample too?
Also, I tried what you wrote, and also on the website, and I still don't get how to play it.
I tap either during or after the 3 claps. It still shows red background, and it doesn't clap anymore after that.

**Comment by AndroidDeveloperLB** [comment]
I also don't see any " second bar"

**Comment by dturner** [comment]
The instructions *are* on the game sample: https://github.com/google/oboe/blob/master/samples/RhythmGame/README.md#audio-timeline

The 2nd bar simply refers to the time period after the first bar. 

What device are you testing on?

**Comment by AndroidDeveloperLB** [comment]
I've tested on Pixel 2 with Android P DP4 (and DP3 when I wrote to you).
When you say "bar" you mean some time after the clap is heard?

I've now tried to follow the instructions on the new link.
I need to press 3 times only after hearing the claps, but not right away. It's in fact after hearing a sound that is like an error sound.
I got the 3 green lights, but then nothing occurs.
Is that it?
Or there's something more?

**Comment by dturner** [comment]
> I got the 3 green lights, but then nothing occurs.
> Is that it?

Yep, that's it. The point of this sample is not to be a finished, user-friendly game with excellent gameplay but to show how to synchronize the UI with the audio timeline.

**Comment by AndroidDeveloperLB** [comment]
ok thanks.
Please fix the bug though.

**Comment by AndroidDeveloperLB** [comment]
And consider putting explanation in the sample itself.

**Comment by dturner** [comment]
Fixed

**Comment by AndroidDeveloperLB** [comment]
Confirmed.
However, you didn't add information about the game inside the game.
