### ISSUE TITLE
Request: update sdks, replace "compile" with "implementation"

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/oboe#137]
There are warnings messages about those...

![image](https://user-images.githubusercontent.com/5357526/41974231-0f48673a-7a20-11e8-80f7-af6995862525.png)
![image](https://user-images.githubusercontent.com/5357526/41974243-18194794-7a20-11e8-95a2-2f77ae855dc0.png)
![image](https://user-images.githubusercontent.com/5357526/41974253-21bdc432-7a20-11e8-84b1-3e7784260735.png)
![image](https://user-images.githubusercontent.com/5357526/41974282-3360b3d4-7a20-11e8-848a-caaf45e32783.png)

**Comment by dturner** [comment]
Thanks very much for filing this issue. Fixed: https://github.com/google/oboe/commit/54e10952323522c72d91caa6c933eca8fa7357d7

**Comment by AndroidDeveloperLB** [comment]
Actually you can use 28 for compileSdk and AndroidX for the support libraries.

**Comment by dturner** [comment]
Feel free to submit a pull request :)

**Comment by AndroidDeveloperLB** [comment]
Here:
https://github.com/google/oboe/pull/146
Tested to work fine on all samples.
