### ISSUE TITLE
[Suggestion] Oboe Tester Audio Latency Flags

### ISSUE THREAD

**Issue by abu100** [google/oboe#1395]
Hey! I have a suggestion. I think you should consider adding the Audio Hardware Flags **FEATURE_AUDIO_LOW_LATENCY** and  **FEATURE_AUDIO_PRO** on the first screen of OboeTester. These flags can help estimate actual Playout Latency.

**Comment by dturner** [comment]
Thanks for the suggestion. You can view the flags by tapping DEVICE REPORT, then scrolling to the bottom. 

You are correct in saying that these flags can be useful to estimate latency, however, it's much more accurate to use the frame render timestamps.
