### ISSUE TITLE
[Oboe Tester] RoundTrip Latency Dataset

### ISSUE THREAD

**Issue by abu100** [google/oboe#1396]
Hey! Is there a Roundtrip dataset available based on the reports generated in the Oboetester application? If there is one, can you please let me know where I can get it? I am interested in using the dataset to get a more accurate output latency.

**Comment by dturner** [comment]
Thanks for the question. Unfortunately we don't publish this information. For latencies Superpowered publish a database here: https://superpowered.com/latency
