### ISSUE TITLE
NDK R15 is stated as the requirement to use Oboe. But it won't build with NDK 15....

### ISSUE THREAD

**Issue by HobbyProjects** [google/oboe#141]
The header files in NDK 15r are missing some of the typedefs that are required to build oboe namely:
...
typedef int32_t aaudio_input_preset_t;
typedef int32_t aaudio_content_type_t;
typedef int32_t aaudio_session_id_t;
among other ones.

Does that mean the actual requirement for Oboe is NDK 16 and above?

**Comment by dturner** [comment]
Good spot, thanks! With the new P features which we just introduced NDK r17b is required. You can get this either through Android Studio SDK manager or via direct download: https://developer.android.com/ndk/downloads/ 

I will update the docs accordingly.

**Comment by dturner** [comment]
Fixed in https://github.com/google/oboe/commit/0ec23b42a14b1b8b173ec4f7ccd0eff5db167dcd

**Comment by HobbyProjects** [comment]
Can you point me to where i can see the new features that were added in Android P?
