### ISSUE TITLE
How to open mp3 or wav file from storage?

### ISSUE THREAD

**Issue by abkoradiya** [google/oboe#1421]

**Comment by robertwu1** [comment]
Take a look at the DrumThumper sample app. https://github.com/google/oboe/tree/main/samples/drumthumper.

This app plays some notes from storage

**Comment by abkoradiya** [comment]
@robertwu1 I have already checked, it loads music from assets. And I am talking about file storage uri.

**Comment by LajosNeto** [comment]
@robertwu1 I have been playing around with the code from RhythmGame that loads an mp3 file from the assets folder. I have the same doubt as @abkoradiya : is it possible to load a mp3 file from a given URI? I have the scenario in which the user downloads a mp3 file and I would like to use this file within oboe.

**Comment by robertwu1** [comment]
There has been quite a few permission changes with file storage in the last couple of Android releases. See [this](https://stackoverflow.com/questions/73985513/android-permission-read-media-audio-and-read-external-storage-for-api-level-33).

We don't have any samples in Oboe about this unfortunately.

**Comment by philburk** [comment]
You may be able to use ExoPlayer Media3 Transformer to convert an MP3 file or URI to a WAV or PCM.

https://developer.android.com/guide/topics/media/transformer/getting-started
