### ISSUE TITLE
getExclusiveCores() returns empty array

### ISSUE THREAD

**Issue by balegoff** [google/oboe#1452]
Android version: 12
Android device: Pixel 4a 5G
Oboe version: 1.6.1
 
I'm doing some optimizations for my app and wanted to reproduce what is done in the MegaDrone sample, especially the thread affinity thing. 

My call to `android.os.Process.getExclusiveCores()` returns an empty array, which means I cannot benefit from the CPU core binding feature.

I'm wondering if this is normal ?

**Comment by philburk** [comment]
The get exclusive cores method gives you a result if the manufacturer has set aside a CPU just for audio. That is pretty rare. But you can still use core affinity. Just set it to whatever the current core is when your callback is first called. The advantages that you will not have unexpected core migration which can cause a glitch. The disadvantage is that it can consume more power and also prevents the CPU scheduler from moving you between cores when there's a reason to.

**Comment by balegoff** [comment]
So I understand it might not be an ideal solution to use this feature.
What do you recommend to do ?
How would you retrieve the core id in the first callback call ?

I started to do as many optimization as possible because since I updated to Android 12, I get glitches in my app using my Pixel 4a 5G.

From what I see in Systrace my audio thread gets sent a lot between cores, but it might seem the cause of the issue is that sometimes the thread is taking way too much time to process (like blocking), this very weird as it happens with the exact same code as before.

If you want tot take a look at it here is the trace, maybe you'll see something more interesting than me:
[trace.html.zip](https://github.com/google/oboe/files/7604365/trace.html.zip)

**Comment by philburk** [comment]
> How would you retrieve the core id in the first callback call ?

Here is an example function [setHTreadAffinity()](https://github.com/google/oboe/blob/4fa162bc5f1949f4130e1ee43ae237e8359b8d9c/samples/shared/DefaultDataCallback.h#L101).

Thanks for the systrace. I can't believe how often your thread is bouncing between cores, every few msec.
I assume your process is com.meteaure.polaris

One problem that can occur is that the CPU scheduler statistics can get reset when a thread migrates. That can cause glitches if you have a moderate workload.

At 3,220 msec your callback was running with about 80-95% CPU utilization, taking 1.6-1.9 msec.

I see in the trace that at 3,260 ms that your thread is running constantly without sleep, indicating a CPU overload.
Then the clock jumped up from 576MHz to 1804 MHz and the thread was able to run in about 1.0 msec.
So your task was doing about 1.5X more computation that normal. I do not see signs of it being blocked.

**Comment by meteaurestudios** [comment]
Thanks for all these informations Phil.

I actually compared with a trace from my Pixel 2XL running Android 11 and the audio thread is very focused on one core, although it jumps very rarely to another one. The Pixel 4a 5G is doing an incredible amount of jumps as you say. I don't have a trace from when the 4a 5G was still on Android 11 unfortunately, this would have been a good way to see if it's something due to the OS upgrade or not.

I see in the MegaDrone example that `setThreadAffinityEnabled(true)` is called from the MegaDroneEngine constructor, which is called from MainActivity's onResult(). The thing in my case is that I don't delete my engine when onPause() is called, so I create my C++ audio engine from onCreate(). Is it safe to call only `setThreadAffinityEnabled(true)` from my constructor (hence onCreate()), or should I make it recall the `setThreadAffinity()` method when pausing/resuming the activity ?

**Comment by balegoff** [comment]
Thanks for all these informations Phil.

I actually compared with a trace from my Pixel 2XL running Android 11 and the audio thread is very focused on one core, although it jumps very rarely to another one. The Pixel 4a 5G is doing an incredible amount of jumps as you say. I don't have a trace from when the 4a 5G was still on Android 11 unfortunately, this would have been a good way to see if it's something due to the OS upgrade or not.

I see in the MegaDrone example that `setThreadAffinityEnabled(true)` is called from the MegaDroneEngine constructor, which is called from MainActivity's onResult(). The thing in my case is that I don't delete my engine when onPause() is called, so I create my C++ audio engine from onCreate(). Is it safe to call only `setThreadAffinityEnabled(true)` from my constructor (hence onCreate()), or should I make it recall the `setThreadAffinity()` method when pausing/resuming the activity ?

**Comment by balegoff** [comment]
So I implemented the thread affinity logic with CPU Ids like in the MegaDrone sample, and this seems to fix my glitching issue on the Pixel 4a 5G. The audio thread is now called periodically on the same CPU and doesn't show any long executions times as in the previous systrace file I uploaded above.

I also implemented the latency tuner, so now I should be pretty setup against glitches !
