### ISSUE TITLE
OBOE call causes App to crash

### ISSUE THREAD

**Issue by Ateros4me** [google/oboe#1453]
Android version(s):7.1.1
Android device(s):Galaxy J5
Oboe version:1.6.1
App name used for testing: 
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
When the NativeInterface is call the app crashes saying the "app keeps stopping"

**Steps to reproduce**
Difficult without me downloading all my files

**Expected behavior**
Should Connect the Audio In to Audio Out with not noticable latency

**Device**
Galaxy J5

**Any additional context**
I've added the files that may indicate the problem with the App

[CMakeLists.txt](https://github.com/google/oboe/files/7597796/CMakeLists.txt)

I've copied the build.gradle and AudioActivity.kt but had to add .txt to the end to download it.
[build.gradle.txt](https://github.com/google/oboe/files/7597809/build.gradle.txt)
[AudioActivity.kt.txt](https://github.com/google/oboe/files/7597826/AudioActivity.kt.txt)

**Comment by philburk** [comment]
There are no crash logs and no native code so all I can do is speculate. I noticed that in your app you do not check to see if the streams open okay. Maybe it is failing because of a permission error. I also don't see where you are asking for record permission. Try giving your app record permission using the app info dialog which opens if you long press on the app icon.
Also try putting some native logs during the startup code and at the beginning of your callback to see how far you get before it crashes. Also include a stack trace. Otherwise there is nothing we can do to help.

**Comment by Ateros4me** [comment]
Hi Phil, thanks for the reply. I use the following code to give permission but it still fails. Does the OBOE require a seperate permission from the way I've granted it below?

	// Check if have permission
        if (ActivityCompat.checkSelfPermission(
               this,
               Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
	    // we don't have permission so ask for it
            ActivityCompat.requestPermissions(
                this,
                arrayOf(Manifest.permission.RECORD_AUDIO),
                MY_PERMISSIONS_RECORD_AUDIO)
	}

	// See if given permission
        if( ActivityCompat.checkSelfPermission(
	       this,
               Manifest.permission.RECORD_AUDIO) == PackageManager.PERMISSION_GRANTED) {
           // Start the Audio threads
           NativeInterface.createAudioEngine()
           NativeInterface.enable(true)
	}
    }

**Comment by Ateros4me** [comment]
What I find strange is that when I open the file native-lib.cpp in the Android Studio editor it says "This file is not part of the project" which makes me think that the cpp files are not being compiled and so the NativeInterface.kt pointer which references the Cpp routines with "external fun createAudioEngine", for example, has probably just got garbage or zero assigned to it or it's not linking correctly.

**Comment by philburk** [comment]
It sounds like there are several problems mixed together here.
If the app is crashing then please include a stack dump and errors from the logcat.
Maybe the native code is not getting linked so it crashes when it tries to go from Kotlin to native.

> Does the OBOE require a seperate permission from the way I've granted it below?

No. The app just needs the same permission for Java or native code.

**Comment by Ateros4me** [comment]
Hi Phil, thanks, there were multiple issues, but with your previous help and looking at other examples i’ve managed to get the audio feed through to work.
