### ISSUE TITLE
Can I add audio effect from AudioEffect API to my audio and mix them to a new audio file?

### ISSUE THREAD

**Issue by dauwamaui** [google/oboe#1456]
Hi, I am developing a karaoke app. I want to add audio effect from AudioEffect API same as  
Equalizer
Virtualizer
BassBoost
PresetReverb
EnvironmentalReverb
DynamicsProcessing
HapticGenerator

Add them to my own audio and mix to a new audio file?

Thank you.

**Comment by philburk** [comment]
I would recommend adding your own effects processing.
If you use the internal Android AudioEffects then it will increase the latency significantly.
If you do it yourself then you will already have the final audio and can write it to a file in a separate thread.
