### ISSUE TITLE
In faq you say it's possible to attach AudioEffects to stream. But it's not possible

### ISSUE THREAD

**Issue by s7aycool** [google/oboe#1458]
Quote from https://github.com/google/oboe/blob/main/docs/notes/effects.md:
> Using Android AudioEffects
> Oboe streams on Android 9 (Pie) and above can use the Java/Kotlin. See AudioEffect API
> 
> The basic idea is to use Java or Kotlin to create a Session with Effects. Then associate your Oboe streams with the session by creating them with a SessionID.
> 
> In Java:
> 
> AudioManager audioManager = (AudioManager) context.getSystemService(Context.AUDIO_SERVICE);
> int audioSessionId = audioManager.generateAudioSessionId();
> Pass the audioSessionId to your C++ code using JNI. Then use it when opening your Oboe streams:
> 
> builder->setSessionId(sessionId);
> Note that these streams will probably not have low latency. So you may want to do your own effects processing.
> 

Sorry, but setSessionId(SessionId sessionId) can't be invoked with int.

**Comment by philburk** [comment]
I updated the documentation to include a cast. Thanks for the question.
