### ISSUE TITLE
Capacity of numframes of each callback is set by oboe or HAL?

### ISSUE THREAD

**Issue by jet-yangqs** [google/oboe#1460]
I want to fix the numFrames of each callback. What the capacity of that value? Can 320 (20ms length, 16kHz, mono, int16) match and work in all android device?

**Comment by philburk** [comment]
Yes, I expect this will work for all devices.
Call AudioStreamBuilder [setFramesPerDataCallback()](https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_builder.html#afb8e95e80df7edd1af27af490438785e)

Oboe will handle the extra buffering. Please let us know if you find any problem.
