### ISSUE TITLE
Can I use oboe to monitor device change and handle the stream switch event?

### ISSUE THREAD

**Issue by jet-yangqs** [google/oboe#1461]
how to handle device(Mic Phone and Speaker) change and the stream switch when a recording or playing stream is opened and started? Could I handle it in native layer use oboe?

**Comment by jet-yangqs** [comment]
I learn from #1272   that I can handle stream switch by overriding oboe::AudioStreamCallback::onErrorAfterClose function.

But I also found that oboe::AudioStreamCallback has two error callback functions: oboe::AudioStreamCallback::onErrorAfterClose and oboe::AudioStreamCallback::onErrorBefforClose, so which one is better to override for handling stream switch(caused by device change)?

**Comment by robertwu1** [comment]
Use onErrorAfterClose. #1403 is another example
