### ISSUE TITLE
CPU scales wrongly its processing when not touching screen

### ISSUE THREAD

**Issue by Skwalaliar** [google/oboe#1465]
Android version(s): 11 (KKK31.Q3-19-97)
Android device(s): Motorola edge 20 lite
Oboe version: 1.6.1
App name used for testing: Oboe Tester (57) v2.2.2
 
**Short description**
When using AAudio in low latency mode, CPU goes in energy economy mode that causes under-runs on output. Under-runs disappears as soon as we interact with the screen, and re-appears when we stop touching it

**Steps to reproduce**
Launch the test output on Oboe tester with the following settings : 
API : AAudio
Device : any
SRate : 48000
Channels : 2
Format : Float
Perf : LOW_LATENCY
Usage : Media
Workload = ~10%

**Expected behavior**
The CPU handles correctly the work, and scales its power mode accordingly to the load required.
**Actual behavior**
The CPU goes in energy-saving mode and the load indicator fluctuates between 80% and above 100%, that provokes undesired audio glitches due to under-runs. But when we are interacting with the screen, there are no more glitches, and the load indicator stabilizes itself to a lower value (for example 64% with a 9.71% workload). This behavior also happens inside our app, which uses only AAudio, and causes the same problem : a callback is taking almost 5ms to compute when we are not touching the screen, and 1ms when we are touching the screen. This problem happens on some smartphones only, and the only fix we found so far (from Google High performance audio conference, 2016) is to simulate a touch on the screen, but that seems a bit sketchy...

I also attach a Perfetto trace when using Oboe tester, CPU frequency drops dramatically when the screen is not touched, that may be the root cause of the problems, but I couldn't find by myself a fix. 
On this trace I touch the screen between 14.9s and 17.4s, and between 21.3s and 23.5s.

Thank you very much in advance for helping me !
**Device**

ro.product.brand = motorola
ro.product.manufacturer = motorola
ro.product.model = motorola edge 20 lite
ro.product.device = kyoto
ro.product.cpu.abi = arm64-v8a
ro.build.description = kyoto_retail-user 11 RRK31.Q3-19-97 ff360 release-keys
ro.hardware = mt6853
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

```

**Any additional context**

[trace-k6853v1_64_6360-RRK31.Q3-19-97-2021-12-09-11-48-55.perfetto-trace.zip](https://github.com/google/oboe/files/7684414/trace-k6853v1_64_6360-RRK31.Q3-19-97-2021-12-09-11-48-55.perfetto-trace.zip)

**Comment by philburk** [comment]
The root problem is in the Android CPU scheduler. It is not handling real-time audio tasks well. We are working on that.
The touch boost trick does not always work.
We could boost the CPU whenever we have MIDI input or real-time audio running.
This is being tracked by an internal bug:
b/122678281 | Boost CPU performance on MIDI input or RT audio

< This behavior also happens inside our app, which uses only AAudio, and causes the same problem

@Skwalaliar - We are looking for apps that we can test for performance issues. Is your app in the Play Store?

**Comment by Skwalaliar** [comment]
Okay thanks, I understand a bit better why does this happens !
In my case, the touch boost trick fortunately worked on this particular device, but if it's not the case on every other one, we will be a bit blocked with certain devices.

@philburk unfortunately our app is actually on closed-beta on the play store, and this version is using the openSL-ES framework for now. But if you want, I can add your e-mail address on our closed-beta loop, and i will inform you when our new version (using AAudio) is released on closed-beta. I hope this newer version will be out in a few months, after testing and merging phases !

**Comment by Skwalaliar** [comment]
Well, A small update concerning this problem ; on our app, we have now added inside AndroidManifest.xml: 
`<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>`
and are asking the user to ignore battery optimizations at first launch, and that fixed our problem (at least on the Motorola device that was problematic).

Our app is now on the play Store, is called Supralive, but is not yet using aaudio, which will be coming on the next major update.
