### ISSUE TITLE
Oboe version 1.5.0 and later fails when open stream on ErrorInternal, versions prior works fine.

### ISSUE THREAD

**Issue by renetik** [google/oboe#1475]
Android version(s): 11
Android device(s): Emulators as well as Samsung Galaxy Tab Lite looks like its not device specific
Oboe version: 1.5 and onward, I have no issues with older versions I was on 1.1.1, now I found 1.4.3 still works.
App name used for testing: 
Not released
 
**Short description**
When I open stream I get ErrorInternal

**Steps to reproduce**
I set this.
```
 LOGD("%s: setUpOutputStreamParameters", TAG);
 builder
            ->setDirection(oboe::Direction::Output)
            ->setChannelCount(oboe::ChannelCount::Stereo)
            ->setSampleRate(sampleRate)
            ->setFramesPerCallback(framesPerBuffer)
            ->setFormat(oboe::AudioFormat::I16)
            ->setSharingMode(oboe::SharingMode::Exclusive)
            ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
            ->setUsage(oboe::Usage::Media)
            ->setContentType(oboe::ContentType::Music)
            ->setAudioApi(audioApi)
            ->setCallback(&outputCallback);
    return builder;
```

```
    oboe::Result result = builder.openStream(&outputStream); 
    if (result == oboe::Result::OK && outputStream) {
       ...
    } else {
        LOGE("%s: openOutputStream: %s", TAG, oboe::convertToText(result)); // here I get result: ErrorInternal
    }
```

I am adding this here from comment as it can be relevant:

This are my statements together with others... This is how it looks on 1.5.0 and later:
    AudioEngine: startOutput
    AudioEngine: openOutputStream
    AudioEngine: setUpOutputStreamParameters
E/libOpenSLES: pAudioSnk: numChannels=3019898997
W/libOpenSLES: Leaving Engine::CreateAudioRecorder (SL_RESULT_CONTENT_UNSUPPORTED)
E/AudioEngine: AudioEngine: openOutputStream: ErrorInternal
    AudioEngine: startOutput: 0x0
D/AudioEngine: AudioEngine: closeStream

And this how on 1.4.3 that works:
    AudioEngine: startOutput
    AudioEngine: openOutputStream
    AudioEngine: setUpOutputStreamParameters
I/AAudio: AAudioStreamBuilder_openStream() called ----------------------------------------
I/AudioStreamBuilder: rate   =  44100, channels  = 2, format   = 1, sharing = EX, dir = OUTPUT
    device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 976
    usage  =      1, contentType = 2, inputPreset = 6, allowedCapturePolicy = 0
    privacy sensitive = false
    opPackageName = (null)
    attributionTag = (null)
D/AudioStreamBuilder: build() EXCLUSIVE sharing mode not supported. Use SHARED.

**Comment by philburk** [comment]
@rene-dohan - Oboe normally works fine. So there must be something unique about the parameters you are passing.

What are the values for sampleRate, framesPerBuffer and audioApi? I would like to add those values to our tests.

Can you try not specifying those values?

**Comment by rene-dohan** [comment]
I tried that but with same results but realized in log other error before that  `pAudioSrc: numChannels=3019898997`

**Comment by rene-dohan** [comment]
Basically I can comment everything out and still same error.  I tried no 1.6.1 too same result. I switch back to 1.4.3 and everything fine. _ (Well not everything but that is for other bug report I wanted to solve some buffer under-runs and wanted to try that minimum in latest latency tuner...) _  

Also this are my log statements with some not mine posibly related...

So this is how it looks on 1.5.0 and later:
    AudioEngine: startOutput
    AudioEngine: openOutputStream
    AudioEngine: setUpOutputStreamParameters
E/libOpenSLES: pAudioSnk: numChannels=3019898997
W/libOpenSLES: Leaving Engine::CreateAudioRecorder (SL_RESULT_CONTENT_UNSUPPORTED)
E/AudioEngine: AudioEngine: openOutputStream: ErrorInternal
    AudioEngine: startOutput: 0x0
D/AudioEngine: AudioEngine: closeStream

And this how on 1.4.3 that works:
    AudioEngine: startOutput
    AudioEngine: openOutputStream
    AudioEngine: setUpOutputStreamParameters
I/AAudio: AAudioStreamBuilder_openStream() called ----------------------------------------
I/AudioStreamBuilder: rate   =  44100, channels  = 2, format   = 1, sharing = EX, dir = OUTPUT
    device =      0, sessionId = -1, perfMode = 12, callback: ON with frames = 976
    usage  =      1, contentType = 2, inputPreset = 6, allowedCapturePolicy = 0
    privacy sensitive = false
    opPackageName = (null)
    attributionTag = (null)
D/AudioStreamBuilder: build() EXCLUSIVE sharing mode not supported. Use SHARED.

**Comment by philburk** [comment]
@rene-dohan - Thanks for the additional information.

> E/libOpenSLES: pAudioSnk: numChannels=3019898997

Oh! That is very bad. Why is it using OpenSL ES? OpenSL ES is deprecated but it should still work.

> So this is how it looks on 1.5.0 and later

What is the exact build and device?
Are you using an emulator or the Samsung device?

What happens if you run OboeTester on that device?
Does it use OpenSL ES or AAudio?

**Comment by rene-dohan** [comment]
As I wrote I am getting this on standard android emulators as well as device. I am little puzzled here. What could force oboe to use OpenSL ES ? If that is my code...  Right now I am commenting out all I can think off that is doing something with audio.. don't have any better idea.. but what is so different from 1.5.0 onward how this could happen just here and prior versions don't do it.. I can ignore it and stay on 1.4.3 but I don't feel its right approach at all :)

**Comment by renetik** [comment]
I found a fix not a problem.. 

I moved oboe in my target_link_libraries to upper position and I can now use new oboe versions again.

```
target_link_libraries(
        renetik-instruments-library-audio
        cpufeatures
        android
        log
        oboe   //--> Now is here 
        libc++_shared
        libcharset
        libffi
        libFLAC
        libfluidsynth
        libfluidsynth-assetloader
        libgio-2.0
        libglib-2.0
        libgmodule-2.0
        libgobject-2.0
        libgthread-2.0
        libiconv
        libintl
        liboboe
        libogg
        libsndfile
        libvorbis
        libvorbisenc
        libvorbisfile
        libz
        preloadable_libiconv
        stkeffect
        // oboe   //--> Before was here
        sndfile
)
```

This fixed reported error.. Hope it will be useful for someone someday ...

**Comment by philburk** [comment]
I notice you have both oboe and liboboe in your list.

Have you tried Oboe V1.6.1? Or the latest from GitHub?

Maybe this is related to this namespace issue #930
