### ISSUE TITLE
Drop samples during recording audio

### ISSUE THREAD

**Issue by sunwell1994** [google/oboe#1480]
Hi, just want to double-check the possibility of dropping samples during audio recording. I find that some samples are missing when I work on the A/V synchronization after tens of seconds of recording. How can I prevent Oboe from dropping samples? Thanks.

**Comment by philburk** [comment]
Are you seeing gaps in the audio, sections silence?
Or are you seeing the timestamps drift?

What are you doing?
What did you expect to happen?
What did you actually see?

**Comment by robertwu1** [comment]
Closing as there is no response
