### ISSUE TITLE
Updated Examples / NDK / Just work? 

### ISSUE THREAD

**Issue by danoli3** [google/oboe#1483]
Android version(s): 21-32
Build tools 32.0.0
Gradle 7.0.4 +
Android device(s): 
Oboe version: 1.61
NDK: 23b
App name used for testing: **Android Studio 2021.1+** 

**Short description**
Examples and project do not work out of the box with any android studio version in the last year

**Steps to reproduce**
Open the Project and try and run them...

**Expected behavior**
Examples run, or upgrade behaviour work automatically to enable examples to be functional

**Actual behavior**
Doesn't work

**Comment by philburk** [comment]
@danoli3 - It seems unlikely that all the examples are broken for everyone.
So it is may be something specific to your situation.

> Actual behavior
> Doesn't work

That does not give us enough information.
Why do you think they are not working?
Do apps build?
Do apps install on the device?
Do the apps launch but then immediately crash and close?
Do the apps look but make no sound?
Do they show error messages? What are the messages?

Also what device(s) are you using? Emulator?
What specific Android versions have you tried?
Have you tried building any non-Oboe examples
Have you tried rebooting the Android device to see if the HAL had hung?

**Comment by danoli3** [comment]
Android Studio 2021.1 won't compile the project or examples without significant changes.

Try this yourself: Download the latest Android studio:
Checkout a fresh Oboe project and try and run the examples

**Comment by danoli3** [comment]
I think the cause of the problems stems from this: Initial Checkout: Open build Gradle as per instruction 
<img width="851" alt="Screen Shot 2022-02-04 at 12 33 18 am" src="https://user-images.githubusercontent.com/830748/152355028-3f49caad-d683-4db8-a4be-a96a607fe683.png">

```
NDK not configured. Download it with SDK manager. Preferred NDK version is '21.1.6352462'. 
Install NDK '21.1.6352462' and sync project
```


I do not have NDK 21.1.6352462 installed.
I'm guessing you might have it or another NDK installed and are specifying it in the  un-committed : `local.properties` 
When I do that (which is the wrong way regardless)
<img width="1343" alt="Screen Shot 2022-02-04 at 12 48 29 am" src="https://user-images.githubusercontent.com/830748/152355448-f6b7df7c-4d06-4092-a3fa-9c3914727a83.png">
```safeGet(androidProjectRe…oject::getNdkVersion, "") must not be null```

**Recommended Changes:** 
Oboe Samples change to NDK specifier in the Gradle Build Scripts 
<img width="590" alt="Screen Shot 2022-02-04 at 12 50 38 am" src="https://user-images.githubusercontent.com/830748/152355699-f266ae46-7063-48b8-b318-26d64001eacf.png">

```
android {
    compileSdkVersion 32
    ndkVersion '23.1.7779620'
    
    ```

**Comment by danoli3** [comment]
Thanks @philburk I'll check out latest and confirm

**Comment by philburk** [comment]
Thanks for reporting. Should be fixed now.
