### ISSUE TITLE
2 simultaneous output streams using 2 different high-priority callbacks?

### ISSUE THREAD

**Issue by kpelckmans** [google/oboe#1494]
Android version: Android 9, SDK 28, Pie 
Android device: NVidia Shield TV with Behringer UCA222 USB Audio Interface
Oboe version: main GitHub branch

Code below runs in separate processes A and B. I am using AAudio directly, but presume the same would happen if I use the Oboe C++ wrapper:
```
AAudioStreamBuilder_setDeviceId(builder, deviceId);
AAudioStreamBuilder_setDirection(builder, AAUDIO_DIRECTION_OUTPUT);
AAudioStreamBuilder_setSharingMode(builder, AAUDIO_SHARING_MODE_SHARED);
AAudioStreamBuilder_setSampleRate(builder, rates[0]);
AAudioStreamBuilder_setChannelCount(builder, 2);
AAudioStreamBuilder_setFormat(builder, AAUDIO_FORMAT_PCM_FLOAT);
AAudioStreamBuilder_setDataCallback(builder, aaudio_callback, &callbackCount);
AAudioStreamBuilder_setUsage(builder, AAUDIO_USAGE_MEDIA);
AAudioStreamBuilder_setContentType(builder, AAUDIO_CONTENT_TYPE_MUSIC);
AAudioStreamBuilder_setPerformanceMode(builder, AAUDIO_PERFORMANCE_MODE_POWER_SAVING);
        
result = AAudioStreamBuilder_openStream(builder, &aAudioStream);

if(result == AAUDIO_OK) {
     LOG_INFO("requested device %d, opened device %d", deviceId, AAudioStream_getDeviceId(aAudioStream));
} 
```

LOG_INFO for 
1) process A with callback to output deviceId 16
2) process B with callback to output deviceId 23
```
requested device 16, opened device 16
requested device 23, opened device 16
```

LOG_INFO for 
1) process A with callback to output deviceId 23
2) process B with callback to output deviceId 16
```
requested device 23, opened device 23
requested device 16, opened device 23
```

As expected, the two callbacks work, but only output to 1 device and the 2 output streams are mixed.

Can the high-priority thread only be used once, even from different processes?

Some extra device info:
```
ro.product.manufacturer : NVIDIA
ro.product.model     : SHIELD Android TV
ro.product.name      : mdarcy
ro.product.cpu.abi   : arm64-v8a
```

device 16: build-in hdmi audio out
```
type: TYPE_HDMI
address: 
channel counts: 1, 2, 4, 6, 7, 8
channel index masks: none
channel masks: ENCODING_PCM_FLOAT, ENCODING_AAC_HE_V2, CHANNEL_OUT_QUAD, CHANNEL_OUT_5POINT1, CHANNEL_OUT_SURROUND, null, CHANNEL_OUT_7POINT1_SURROUND
encodings: ENCODING_PCM_16BIT
sample rates: 32000, 44100, 48000, 88200, 96000, 176400, 192000
```

device 23: Behringer UCA222 USB Audio Interface
```
type: TYPE_USB_HEADSET
address: card=0;device=0;
channel counts: 1, 2
channel index masks: 1, 3
channel masks: ENCODING_PCM_FLOAT, ENCODING_AAC_HE_V2
encodings: ENCODING_PCM_16BIT
sample rates: 32000, 44100, 48000
```

**Comment by robertwu1** [comment]
Thanks for the bug report! I will try to repro this on my end. From a [previous bug report](https://github.com/google/oboe/issues/1051) and [AAudio docs](https://github.com/google/oboe/issues/1051), it seems like multiple streams is an expected scenario.

What happens if you set the performance mode as LOW_LATENCY instead?AAudioStreamBuilder_setPerformanceMode(builder, AAUDIO_PERFORMANCE_MODE_LOW_LATENCY);

**Comment by philburk** [comment]
> requested device 16, opened device 23

That seems like a bug. The contract for AAudio is that if you request a specific device then you either get that device or the open should fail.

@robertwu1 - You can use the write_sine_callback example in libaaudio to try and repro this. Open two terminal windows so you have two processes. OboeTester will show you a Device Report with the device IDs.

**Comment by robertwu1** [comment]
I reproed this locally with write_sine_callback. I used the speaker and a 3.5mm headset

When first starting on speaker, playing on both plays both on the speaker.
When first starting on the headset, the speaker continues to glitch when trying to play on the speaker.

Thanks again for the bug report!

**Comment by robertwu1** [comment]
This seems only to happen when both streams are shared POWER_SAVING. @kpelckmans, if you change the streams to low latency, your problem should be solved.

I will investigate further

**Comment by robertwu1** [comment]
@kpelckmans Seems like there is no guarantee from that multiple shared streams would work. Please change the streams to low latency and it will work. Closing this bug because we have an internal bug tracking this b/219763493

**Comment by philburk** [comment]
> This seems only to happen when both streams are shared POWER_SAVING.

What happens if you use AAUDIO_PERFORMANCE_MODE_NONE?

**Comment by robertwu1** [comment]
NONE acts the same as POWER_SAVING

**Comment by kpelckmans** [comment]
Tried both AAUDIO_PERFORMANCE_MODE_LOW_LATENCY and AAUDIO_PERFORMANCE_MODE_NONE, but it does not seem to have any effect.

**Comment by kpelckmans** [comment]
I reimplemented with blocking audio write instead of the high priority thread callback, but still get the same error.

What is the solution? Should I try to use OpenSL ES? Is there a way to directly address TinyALSA? Should I directly write to the USB audio interface?

**Comment by kpelckmans** [comment]
Hi, is there a way to read https://issuetracker.google.com/issues/219763493?

**Comment by philburk** [comment]
@kpelckmans wrote:
> is there a way to read https://issuetracker.google.com/issues/219763493?

No. It is internal. We just put a link here so we can find it quickly. The fix will probably involve people who are not on GitHub so we track the fix inside Android.

@robertwu1 wrote:
> if you change the streams to low latency, your problem should be solved.

Does that work the same for Legacy streams? Try low latency streams and use -m1 to turn off MMAP mode.

**Comment by kpelckmans** [comment]
>  we have an internal bug tracking this b/221114221
What was the conclusion of the Android team? I would like to use Android TV for playing multi-room audio.
