### ISSUE TITLE
improve sleeptime between stop() and close()

### ISSUE THREAD

**Issue by philburk** [google/oboe#1500]
There are ongoing problems with callbacks running after the stop.

In AudioStreamAAudio::close() we stop the stream and then sleep before closing the stream.
    
            usleep(kDelayBeforeCloseMillis * 1000);

We should a call that allows the developer to change that sleep time.

Also the default should be based on the framesPerBurst, which may be 20 msec on some devices.

**Comment by philburk** [comment]
API could maybe scale sleep time to (appScaler * burstTime)

**Comment by robertwu1** [comment]
We should be careful if they aren't using Low Latency. Burst sizes are quite large for Power Savings
