### ISSUE TITLE
CodeQl gives overflow warning for flowgraph/resampler

### ISSUE THREAD

**Issue by ann0see** [google/oboe#1506]
**Short description**
CodeQl flags the following lines as high severity issues (probably they are not severe at all, therefore posting it publically): "Multiplication result converted to larger type
High
Multiplication result may overflow 'int' before it is converted to 'size_type'."
See i.e:
https://github.com/github/codeql/blob/17fbbdba34d755fa318d588732f75708aa110be5/cpp/ql/src/Likely%20Bugs/Arithmetic/IntMultToLong.ql
https://github.com/google/oboe/blob/1a7dce497ded081ed127059ae46455aa105612b6/src/flowgraph/resampler/MultiChannelResampler.cpp#L133
https://github.com/google/oboe/blob/1a7dce497ded081ed127059ae46455aa105612b6/src/flowgraph/resampler/MultiChannelResampler.cpp#L32

![image](https://user-images.githubusercontent.com/20726856/157329051-65cd3d0a-10b5-4198-b7c8-bd36b01fc127.png)
![image](https://user-images.githubusercontent.com/20726856/157329132-b80b31b4-2abb-4c39-aff5-f416b25a8fc0.png)
![image](https://user-images.githubusercontent.com/20726856/157329224-83f4caaa-9b0a-4692-8305-00084845bacf.png)
![image](https://user-images.githubusercontent.com/20726856/157329289-e315dce5-a4b1-4eb7-a30a-de42b5680842.png)

**Steps to reproduce**
Clone an app using oboe
Set up CodeQl
Compile and observe warnings from CodeQl as mentioned above
**Expected behavior**
No warnings of CodeQl. Should be fixed by smaller code-refactorings probably.
**Actual behavior**
The error log in CodeQl is warning about issues concerning overflow.
**Device**

/

**Any additional context**

/

**Comment by robertwu1** [comment]
@ann0see Did you change any parameters to get CodeQl to run correctly? When I tried to create codeql.yml, the cpp checker doesn't seem to build to to mismatch in compiler flags

**Comment by ann0see** [comment]
No. I think it worked quite out of the box? That’s our workflow file: https://github.com/jamulussoftware/jamulus/blob/master/.github/workflows/autobuild.yml

**Comment by ann0see** [comment]
The CI https://github.com/google/oboe/runs/5504278249 shows similar issues.

**Comment by ann0see** [comment]
How often do you release? I.e when can we assume these patches out live?

**Comment by robertwu1** [comment]
Here is our release page: https://github.com/google/oboe/releases

**Comment by ann0see** [comment]
Ok. So basically there's no schedule. We'll probably fix the latest commit if possible on our repo. Is the code on master stable?

**Comment by robertwu1** [comment]
Code on master is stable atm. Nothing risky has gone in recently.

**Comment by ann0see** [comment]
Ok. Great. So I'll talk to our dev team. Maybe we can pin your repo to the current master in our submodule.
