### ISSUE TITLE
Unable to merge audio effects to the output audio recordings

### ISSUE THREAD

**Issue by YogarajRamesh** [google/oboe#1512]
Android version(s): 11
Android device(s): Realme 3 pro
Oboe version: 1.6.1

Short description
I had recorded(using callback) with echo effects using fxlab in my app but the output recording doesn't have any echo effect. It has only default stream. Is there anyway to add effects to the output audio.

Device

Realme 3 pro

**Comment by philburk** [comment]
This sounds like the same bug as #1513 
Let's close this one and keep that one.
