### ISSUE TITLE
Unable to add effects to audio recording using FXlab

### ISSUE THREAD

**Issue by MaHi0717** [google/oboe#1513]
Android version(s): 11
Android device(s): Realme 3 pro
Oboe version: 1.6.1

Description
 I am using FXlab to create a karaoke app with echo effect for voice, while recording i am able hear the effects in live stream, however after recording is done using callback function the **output doesn't have any effects('echo')** instead getting Raw audio recording.  

Device
Realme 3 pro

@atneya @philburk @dturner

**Comment by philburk** [comment]
@MaHi0717 - this is not very clear.

By "recording" are you referring to the live voice recording in memory,
OR voice that was recorded to a file,
OR previously recorded material (song) that you are playing?

It seem like the order of effects may be wrong. Maybe your echo is before the place where the song is mixed into the output.

The echo effect is not an Oboe or AAudio function. It is an app function. So I suspect this is an app bug.

**Comment by philburk** [comment]
This sounds like an application issue.
We cannot help developers with application features.
This forum is for Oboe bugs.
Please use the Discussion forum. Someone else may offer advice.

#1508
