### ISSUE TITLE
Up and down microphone can't auto switch in VoiceCommunication mode with setSpeakerphoneOn(true)

### ISSUE THREAD

**Issue by myj420** [google/oboe#1515]
Android version(s): 10
Android device(s): oneplus 6t and other devices
Oboe version: 1.5.0

Short description
this my code 
input:
  ->setFramesPerCallback(mFullDuplexStream.sampleRate*20/1000)
        ->setDeviceId(oboe::kUnspecified)
        ->setDirection(oboe::Direction::Input)
        ->setSampleRate(mFullDuplexStream.sampleRate)
        ->setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Fastest)
        ->setChannelCount(1)
        ->setInputPreset(oboe::InputPreset::Generic);

output:
    builder->setSessionId((oboe::SessionId)sessionID);
    builder->setCallback(this)
    ->setDeviceId(oboe::kUnspecified)
    ->setDirection(oboe::Direction::Output)
    ->setChannelCount(mFullDuplexStream.channelNum)
    ->setSampleRate(mFullDuplexStream.sampleRate)
    ->setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Fastest)
    ->setUsage(oboe::Usage::VoiceCommunication)
    ->setFramesPerCallback(mFullDuplexStream.sampleRate*20/1000);

setMode(audioManager.VoiceCommunication);
setSpeakerphoneOn(true);

openStream(mRecordingStream);
openStream(mPlayStream);

when i start the above steps,  just one mic Effective。 but when i call setSpeakerphoneOn(false),
Up and down  microphone  Effective。

**Comment by philburk** [comment]
@myj420 - Are you calling setSpeakerphoneOn(false) while the streams are running or before they are opened? Does that make a difference?

Is the problem that you have only one mic when true?
Is is the problem that you have two mics when false?

The routing from microphones is determined by the manufacturer. It is not guaranteed by the API.
This may be working as intended.

**Comment by myj420** [comment]
> @myj420 - Are you calling setSpeakerphoneOn(false) while the streams are running or before they are opened? Does that make a difference?
> 
> Is the problem that you have only one mic when true? Or is the problem that you have two mics when false?
> 
> The routing from microphones is determined by the manufacturer. It is not guaranteed by the API. This may be working as intended.

I calling setSpeakerphoneOn(false) before open;  this is my code
            closeStream(mPlayStream);
            closeStream(mRecordingStream);
            setMode(3);

                switchOutputType(usespeaker);
                usleep(500 * 1000);
            ret = openStreams();

i just want tow mics can auto switch in VoiceCommunication mode;
another problem is when i call set SpeakerphoneOn(true) in VoiceCommunication mode; my phone(oneplus 6t) record audio is very low but in SpeakerphoneOn(false) is louder

**Comment by philburk** [comment]
> another problem is when i call set SpeakerphoneOn(true) in VoiceCommunication mode;
> my phone(oneplus 6t) record audio is very low but in SpeakerphoneOn(false) is louder

Please report this as a separate bug.

**Comment by philburk** [comment]
This mic behavior is device specific and is probably work as intended by the manufacturer.
