### ISSUE TITLE
Is Oboe for iPhone devices?

### ISSUE THREAD

**Issue by nmartin-sens** [google/oboe#1529]
I'm currently developping a high performace audio app in Android Studio with Oboe, and I wonder if Oboe works in multiplatform environment, i.e. also for iPhone devices?

**Comment by robertwu1** [comment]
Oboe only works for Android. It uses the AAudio and OpenSL ES, which are only supported in Android.

For multiplatform development, consider using Oboe for Android and Core Audio for iOS. [Here](https://docs.flutter.dev/development/platform-integration/c-interop)'s a way to bind to native code with Flutter.
