### ISSUE TITLE
With minSdk = 30, Oboe causes compilation error as 'slCreateEngine' is deprecated

### ISSUE THREAD

**Issue by atsushieno** [google/oboe#1530]
Android version(s): 11
Android device(s): emulator
Oboe version: 917f8c7
App name used for testing: OboeTester
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**

Since Android 30, OpenSLES is deprecated, and it will cause build errors when any of our app sources use it (actually build warnings, but the default `-Werror` C++ compilation settings turns the warnings as errors). Currently Oboe uses OpenSLES without any platform tweaks, so if we specify `minSdk 30` in our app `build.gradle`, where I submodule Oboe and use `add_subdirectory()` in my `CMakeLists.txt` the build fails.

My app depends on NdkBinder and thus sets minSdk = 29, but since it has [a blocking issue with minSdk 29 with NDK r23 or later](https://issuetracker.google.com/issues/219987524), setting minSdk to 30 could be a temporary workaround. But now it is incompatible option with Oboe because of this problem.

**Steps to reproduce**

- Open OboeTester.
- change `minSdk 23` to `minSdk 30` in its `app/build.gradle`
- build

**Expected behavior**

- It still builds (maybe by dropping OpenSLES parts? Some decision agreement among the dev. team would be needed)

**Actual behavior**

- /path/to/oboe/src/opensles/EngineOpenSLES.cpp:35:18: error: 'slCreateEngine' is deprecated: first deprecated in Android 30 [-Werror,-Wdeprecated-declarations]

**Device**

- emulator, x86, API Level 31 (should not matter)

**Any additional context**

It is most likely non-issue with binary distribution (prefab) but that's not a compatible solution with other non-prefab native libraries so far.

**Comment by philburk** [comment]
Thanks for pointing this out.

As you mentioned, we could drop OpenSL ES support when minSDK>=30. But It is helpful to be able to switch between OpenSL ES and AAudio when debugging. A better approach might be to implement stubs for the OpenSL ES headers similar to the way we do for AAudio. We can then use dlsym() to link with slCreateEngine().

**Comment by atsushieno** [comment]
Ah, yes, that makes perfect sense.
