### ISSUE TITLE
OboeTester: automated latency test fails on second run

### ISSUE THREAD

**Issue by philburk** [google/oboe#1533]
Android version(s): T
Android device(s): P6
Oboe version: 2.2.2 and 2.2.3
OboeTester version: 1.6.1 and 1.6.2
App name used for testing: OboeTester

**Short description**
Second automation test fails.

**Steps to reproduce**
adb shell am start -n com.mobileer.oboetester/.MainActivity     --es test latency     \
       --es file /sdcard/Download/latency20190903.txt     --ei buffer_bursts 2     --ei out_channels 1 

Should work. Repeat:
adb shell am start -n com.mobileer.oboetester/.MainActivity     --es test latency     \
       --es file /sdcard/Download/latency20190903.txt     --ei buffer_bursts 2     --ei out_channels 1 

**Expected behavior**
Test should make noise and report latency.

**Actual behavior**
No Noise. Get logcat message:
   OboeTester: onStop() called so stop the test =========================

**Comment by philburk** [comment]
The second test runs on Samsung Exynos Note 10 running R.
So this may be specific to T or P6.

**Comment by philburk** [comment]
It fails on Pixel 4 running TM.

**Comment by philburk** [comment]
On SP2A I get these logs:

First Intent:
05-13 11:55:14.576  3664  3664 I OboeTester: onStart() called ========================= ZZZZ
05-13 11:55:15.202  3664  3664 I OboeTester: startAudio() called ========================= ZZZZ

Second Intent:
05-13 11:55:28.707  3664  3664 I OboeTester: onStart() called ========================= ZZZZ
05-13 11:55:29.226  3664  3664 I OboeTester: onStop() called ========================= ZZZZ
05-13 11:55:29.226  3664  3664 I OboeTester: onStop() called so stop the test ========================= ZZZZ
05-13 11:55:29.226  3664  3664 I OboeTester: stopTest() called ========================= ZZZZ
05-13 11:55:29.321  3664  3664 I OboeTester: startAudio() called ========================= ZZZZ

On TM I get this log ------------------------------- TM
First Intent:
05-13 11:52:31.259 18164 18164 I OboeTester: onStart() called ========================= ZZZZ
05-13 11:52:31.940 18164 18164 I OboeTester: startAudio() called ========================= ZZZZ

Second Intent:
05-13 11:52:49.110 18164 18164 I OboeTester: onStart() called ========================= ZZZZ
05-13 11:52:49.785 18164 18164 I OboeTester: startAudio() called ========================= ZZZZ
05-13 11:52:49.893 18164 18164 I OboeTester: onStop() called ========================= ZZZZ
05-13 11:52:49.893 18164 18164 I OboeTester: onStop() called so stop the test ========================= ZZZZ
05-13 11:52:49.893 18164 18164 I OboeTester: stopTest() called ========================= ZZZZ

Note that the order has changed in the second intent:

S => onStart(), onStop(), stopTest(), startAudio()
T => onStart(), startAudio(), onStop(), stopTest()

**Comment by philburk** [comment]
The problem was caused by a change in the timing of calls to onStop() and onResume().

onResume() was posting a delayed run of the test on the UI thread after 500 msec.
On **S** the onStop() method was called just **before** the test started.
On **T** the onStop() method was called just **after** the test started.

By delaying the test for 1000 msec we are able to run twice.

**Comment by robertwu1** [comment]
Is this from a change in OboeTester behavior or a change in the order of the operations between S and T?

**Comment by philburk** [comment]
There was a race condition in OboeTester due to an unexpected call to onStop().
The timing changed between S and T. In T, the onStop() method got called later, after the test had started.
