### ISSUE TITLE
DrumThumper build.gradle commit on master, not main branch

### ISSUE THREAD

**Issue by philburk** [google/oboe#1534]
This commit needs to be cherry-picked to main.

https://github.com/google/oboe/commit/e54d1305a8462f3746ab1fe44abc68a9597b94b6

**Comment by philburk** [comment]
I copied the OboeTester docs change from https://github.com/google/oboe/commit/6d6d92ead58db1d8c6cfb0f2339a8db5d93493bb
by hand.

Paul can either make the changes from https://github.com/google/oboe/commit/e54d1305a8462f3746ab1fe44abc68a9597b94b6
by hand in main or cherry-pick the commit.

**Comment by robertwu1** [comment]
Phil cherrypicked this.
