### ISSUE TITLE
Add method isTimestampSupported

### ISSUE THREAD

**Issue by dturner** [google/oboe#156]
Timestamps are only supported on some streams: 

- Streams which use AAudio as the API
- In future, OpenSL ES output streams which can use AcquireJavaProxy to call getTimestamp on the AudioTrack object

Adding `isTimestampSupported` provides a way for clients to know whether the following methods will return meaningful values: 

`getTimestamp`
`calculateLatencyInMillis`

**Comment by niklasdahlheimer** [comment]
What about adding the OpenSL ES `getPosition()` method? 
I know that there is a bug reported in the android implementation of OpenSL ES regarding buffer-underruns, but if no underruns occur, this method would deliver timestamps for OpenSL ES without the need to query Java-objects.

**Comment by dturner** [comment]
> if no underruns occur

That's really the problem though. The AAudio method of returning timestamps doesn't have that bug and I'm loathed to introduce a flaky way of obtaining timestamps, even if it would be available from API 16.

**Comment by dturner** [comment]
Links: https://groups.google.com/forum/#!topic/android-ndk/Ez5_nvAmhE8
Internal bug: b/22628197

**Comment by dturner** [comment]
Clients can call `getTimestamp` and if it returns `Result::OK` timestamps on that stream are supported
