### ISSUE TITLE
Huawei P30 Lite - Output latency derived from timestamps unreliable when connected to bluetooth

### ISSUE THREAD

**Issue by chrismanchester** [google/oboe#1563]
Android version(s): 9
Android device(s): Huawei P30 Lite (HWMAR/MAR-LX2)
Oboe version: 1.6.2
App name used for testing:  OboeTester
 
**Short description**
Timestamps for the output stream produce unreliable values (implausibly low) when bluetooth output is used

**Steps to reproduce**
Enable bluetooth, connect headset (tested with AirPods and Samsung Galaxy Buds)
Navigate to OboeTester "TEST OUTPUT"
Tap "OPEN" followed by "START"

**Expected behavior**
timestamp.latency values reflect output latency

**Actual behavior**
timestamp.latency value will be unrealistically low, approximately 50ms, while the connection is observed to have an actual latency of about 300ms

**Device**

```
$ for p in \
>     ro.product.brand ro.product.manufacturer ro.product.model \
>     ro.product.device ro.product.cpu.abi ro.build.description \
>     ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
>     do echo "$p = $(adb shell getprop $p)"; done
ro.product.brand = HUAWEI
ro.product.manufacturer = HUAWEI
ro.product.model = MAR-LX2
ro.product.device = HWMAR
ro.product.cpu.abi = arm64-v8a
ro.build.description = MAR-LX2-user 9.1.0 HUAWEIMAR-LX2 264-OVS-LGRP2 release-keys
ro.hardware = kirin710
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]
```

**Any additional context**

Disconnecting the output device, playing some audio over the air, and reconnecting it seems to have an impact on the bug. Some of the time, after reconnecting the estimate will become more accurate (closer to 300ms), and some of the time the new stream will appear to continue to report the latency of the speaker path (about 10ms). The estimate of around 50ms will reliably be present on the first attempt after turning on bluetooth in settings and connecting the output device.

**Comment by chrismanchester** [comment]
Tahnks @robertwu1, I will send these by email to Phil today.

**Comment by philburk** [comment]
Thanks for reporting this!

Note that we are no longer actively working with Huawei. So it will be difficult to resolve this issue for this device.

But we may incorporate the timestamp.latency.msec measurement into a future CTS Verifier and improve the requirements in the Android CDD. Then we could enforce timestamp accuracy.

Closing because there is nothing to do in Oboe or AAudio. We will pursue this internally.
