### ISSUE TITLE
Add __riscv as a CPU architecture option

### ISSUE THREAD

**Issue by philburk** [google/oboe#1585]
Oboe StabilizedCallback.h should have a RICSV check.
This was proposed in AOSP.
https://android-review.googlesource.com/c/platform/external/oboe/+/2170113

Are there other places where it is needed?

**Comment by robertwu1** [comment]
Do you have a phone that we can test with? In [build_all_android.sh](https://github.com/google/oboe/blob/main/build_all_android.sh), we don't build ricsv. There are quite a few places we would need to add this. See [this](https://github.com/google/oboe/search?q=armeabi-v7a) search.

We intentionally don't build certain abis like armeabi and mips.

We should get an emulator or a real phone to test this.

**Comment by robertwu1** [comment]
Update: seems like we don't need to update abis yet. See https://developer.android.com/ndk/guides/abis.
