### ISSUE TITLE
QuirksManager doesn't respect OboeGlobals::areWorkaroundsEnabled()

### ISSUE THREAD

**Issue by robertwu1** [google/oboe#1589]
Several places in QuirksManager.cpp do not respect areWorkaroundsEnabled(). This does not cause any changes to the end user.

This means that OboeTester is doing sample rate conversion and I16 to Float conversions even when the areWorkaroundsEnabled() checkbox is not checked.

I'm not completely sure whether this is a bug or WAI.

**Comment by robertwu1** [comment]
This means the data test path may be test different things than intended.

**Comment by philburk** [comment]
Some conversions are workarounds, required to fix a bug, and gated by the flag. Some conversions are requested by the developers, maybe to optimize the data path, and not gated by the flag.
