### ISSUE TITLE
couldn't find "liboboe.so"

### ISSUE THREAD

**Issue by teamclouday** [google/oboe#1609]
Hey, I'm trying to add oboe to my Android app. The build was successful but app failed immediately after launch:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "liboboe.so" not found
```
I followed the ["Getting Started" document](https://github.com/google/oboe/blob/main/docs/GettingStarted.md#option-1-using-pre-built-binaries-and-headers) to add the library.

`build.gradle` file:
```gradle
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 31
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.example.microphone"
        minSdkVersion 23
        targetSdkVersion 31
        versionCode 7
        versionName "1.8"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++14"
                arguments "-DANDROID_STL=c++_shared"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        prefab true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.18.1'
        }
    }
}

dependencies {
    implementation 'com.google.oboe:oboe:1.6.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.1'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.3'
    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.4.1'
    implementation 'com.google.android.material:material:1.6.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    testImplementation 'junit:junit:'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
}
```

`gradle.properties` file:
```
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
```

`CMakeLists.txt` file:
```cmake
cmake_minimum_required(VERSION 3.18.1)
project("microphone")
add_library(microphone
        SHARED
        microphone.cpp)
find_package(oboe REQUIRED CONFIG)
target_link_libraries(microphone
        oboe::oboe
        log)
```

The source code `microphone.cpp` is empty. And in `MainActivity.kt`, it's loaded by:
```kotlin
companion object {
        init {
            System.loadLibrary("microphone")
        }
    }
```

I'm very new to NDK and didn't find a solution in existing issues. What am I missing here?

**Comment by teamclouday** [comment]
Update: I tried [option 2 (build from source)](https://github.com/google/oboe/blob/main/docs/GettingStarted.md#option-2-building-from-source) and it works now. Successful build and no more errors.
Option 1 didn't work for me.

**Comment by robertwu1** [comment]
I created a new [sample native project](https://developer.android.com/studio/projects/add-native-code#new-project) and followed the steps from ["Getting Started" document](https://github.com/google/oboe/blob/main/docs/GettingStarted.md#option-1-using-pre-built-binaries-and-headers). This seemed to work. I don't see anything weird that you are doing.

Can you try following the instructions I linked? Perhaps your project structure is messed up.

**Comment by teamclouday** [comment]
Hey Robert, thanks for response. 

I tried to create a new native project and applied option 1.\
I ended up having the same issue: app build successfully but same "liboboe.so" not found error.
Analyzing the app shows that the `liboboe.so` file is not included in output apk, while all other .so files exist (e.g. `libc++_shared.so`)

My Android Studio and NDK tools are latest version, so not sure what caused this.

**Comment by teamclouday** [comment]
Update, I made it work with remote repository ([option 1](https://github.com/google/oboe/blob/main/docs/GettingStarted.md#option-1-using-pre-built-binaries-and-headers))! I figured it out by downloading [NDK Prefab Sample](https://github.com/android/ndk-samples/tree/main/prefab/curl-ssl), build locally and compare the settings.\
**The issue is with Android Gradle Plugin Version**.

Previously, in Android Studio, File -> Project Structure -> Project, I had following settings:
```
Android Gradle Plugin Version: 7.2.2
Gradle Version: 7.3.3
```
Now change to:
```
Android Gradle Plugin Version: 4.2.2
Gradle Version: 7.3.3
```

And also modify following files:
* `build.gradle`, remove cmake version:
   ```gradle
   externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            // version '3.18.1'
        }
    }
   ```
* `CMakeLists.txt`, set reasonable minimum version:
   ```cmake
   # cmake_minimum_required(VERSION 3.18.1)
   cmake_minimum_required(VERSION 3.6.0)
   ```

Now compile again and `liboboe.so` is included in apk!
![image](https://user-images.githubusercontent.com/22620163/186070613-26aa079e-f65e-4c07-9053-a67015a6042e.png)

So for future reference, if you're in a similar situation, try to downgrade Gradle plugin version 🙂

Closing
