### ISSUE TITLE
Support spatialization behavior in oboe

### ISSUE THREAD

**Issue by flamme** [google/oboe#1612]
Spatialization behavior is added in API 32 in AAudio. Oboe need to support this API so that the apps can sets the behavior affecting whether spatialization will be used.

What's more, the framework will put spatialization output at a higher priority than low latency when it is possible. It may worth to discuss if oboe want to disable spatialization on stereo stream by default.

**Comment by robertwu1** [comment]
This was added for AAudio in T [here](https://cs.android.com/android/_/android/platform/frameworks/av/+/656bfdc71f8d68a5f23872f6c8d8241f22f32a3e). I think we should just use the same parameters as AAudio.

The parameters for AAudio are [setSpatializationBehavior](https://developer.android.com/ndk/reference/group/audio#aaudiostreambuilder_setspatializationbehavior) and [setIsContentSpatialized](https://developer.android.com/ndk/reference/group/audio#aaudiostreambuilder_setiscontentspatialized).

SetSpatializationBehavior sets whether the spatializer can be used when if it is available. The options are AUTO and NEVER. Oboe's default should be NEVER.

SetIsContentSpatialized sets whether the content is already spatialized. This is a boolean. Oboe's default should be false.

**Comment by philburk** [comment]
> Oboe's default should be NEVER.

Or we could default to NEVER for PerfMode==LowLatency and AUTO for None.

**Comment by robertwu1** [comment]
In that case, should we add an extra enum for Oboe?

DEFAULT: PerfMode==LowLatency and AUTO for None
AUTO: Always use AUTO
NEVER: Always use NEVER

This extra enum does seem a bit confusing though.

**Comment by philburk** [comment]
We decided to stick with the default = NEVER.
