### ISSUE TITLE
Resampler has very low output when converting from 11025 to 88200

### ISSUE THREAD

**Issue by philburk** [google/oboe#1625]
Enable the unit test in testResampler.cpp to reproduce this.

There is an initial hump and then the output is shaped correctly but with very low amplitude.

**Comment by robertwu1** [comment]
What about 88200 to 11025?

**Comment by philburk** [comment]
> What about 88200 to 11025?

That seems OK.

These also fail:
11025 => 96000
8000 => 64000
It seems to fail if (outputRate / inputRate >= 4.0)
