### ISSUE TITLE
Noise in AAudio recording

### ISSUE THREAD

**Issue by xianfeng99** [google/oboe#1640]
Android version(s): Android 9
Android device(s): HUAWEI INE-LX1
Oboe version: 1.6.4
App name used for testing: 
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 I'm running tests on OboeTester.

**Short description**
(Please only report one bug per Issue. Do not combine multiple bugs.)
Under the Record And Play option, I set up mono or stereo for recording, there is noise, and the mono sound is not correct.

**Steps to reproduce**
On the OboeTester MainActivity page
-> Click RECORD AND PLAY
-> Set Format to PMC_I16
-> Click RECORD (on the Recorder page)
-> Click PLAY
-> The sound is noisy
-> Save data (write pcm data to file in InputStreamCallbackAnalyzer.cpp) and listen to the same phenomenon in Audacity.
Stereo channel (without clicking on other settings options)

Mono (in the Recorder page)
-> set Channels to 1
-> Set Format to PMC_I16
-> Click RECORD
-> Click PLAY
-> The sound heard is noisy and incorrect
-> Save data (write pcm data to file in InputStreamCallbackAnalyzer.cpp) and listen to the same phenomenon in Audacity.

**Expected behavior**
The recorded data is not noise  and correct.

**Actual behavior**
Mono data is noisy and incorrect (stretched).
Stereo channel data has noise.
（I don't set the Format, the result is the same.）
I tested on other devices and the result is correct.

**Device**
ro.product.brand = HUAWEI
ro.product.manufacturer = HUAWEI
ro.product.model = INE-LX1
ro.product.device = HWINE
ro.product.cpu.abi = arm64-v8a
ro.build.description = INE-LX1-user 9.1.0 HUAWEIINE-LX1 280-OVS-LGRP2 release-keys
ro.hardware = kirin710
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

Please list which devices have this bug.
If device specific, and you are on Linux or a Macintosh, connect the device and please share the result for the following script. This gets properties of the device. 

```
for p in \
    ro.product.brand ro.product.manufacturer ro.product.model \
    ro.product.device ro.product.cpu.abi ro.build.description \
    ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
    do echo "$p = $(adb shell getprop $p)"; done
```

**Any additional context**

If applicable, please attach a few seconds of an uncompressed recording of the sound in a WAV or AIFF file.

**Comment by robertwu1** [comment]
You mentioned how this works for your other phones correctly. Does your Huawei phone support MMAP?

Does your Huawei phone not support Float? There seems to be a bug when we are saving a WAV file in OboeTester. We always save the wav file with 24 bits, expecting it to be FLOAT. Can you test saving this with 16 bits on your phone?
 https://github.com/google/oboe/blob/d0645d6772fb3cb7e2f0587d082093c982f711a7/apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp#L301

**Comment by xianfeng99** [comment]
Thank you very much for your comments.

There will be the same problem whether you use PCM_I16 or PCM_FLOAT.
Save data (write pcm data to file in InputStreamCallbackAnalyzer.cpp) and listen to the same phenomenon in Audacity.

But I set a dual -channel and use the pull mode. The sound of the recording is correct.
And the same problem will be used to use a separate AAUDIO (not in OBOE DEMO).
Is it the problem of adaptation of the device?

**Comment by robertwu1** [comment]
This seems to be an issue with the specific device as other devices do not have this problem.
