### ISSUE TITLE
Multichannel output not working properly on Pixel 6

### ISSUE THREAD

**Issue by triplef** [google/oboe#1643]
Android version(s): 12
Android device(s): Pixel 6
Oboe version: 1.6.1 and from main branch
App name used for testing: Hello Oboe
 
**Short description**
Using multi-channel audio interfaces with the Pixel 6 has various issues depending on the connected audio interface:

- Reloop Beatpad: distorted sound on all 4 channels
- Reloop Ready: clean sound on all 4 channels
- Pioneer DJ DDJ-WeGO4: distorted sound on all 4 channels
- Pioneer DJ DDJ-WeGO3: no sound from all for 4 channels
- Pioneer DJ DDJ-400: no sound from all for 4 channels
- Numark Mixtrack Platinum FX: distorted sound on all 4 channels
- Novation Audio Hub 2x4: clean sound on all 4 channels

This is similar to #943 on Samsung and other devices, but given that this is Google’s own hardware we thought a separate issue would make sense.

**Steps to reproduce**

1. Launch Hello Oboe
2. Connect audio interface
3. Select 4 output channels
4. Tap screen to play sound

**Expected behavior**
Each output of the audio interface should play a sine signal with a different pitch.

**Actual behavior**
See above. The results are the same with both AAudio and OpenSL.

Additionally the buffer size increases significantly from ~20 to ~80-120 ms when selecting 4 channel output.

**Device**
ro.product.brand = google
ro.product.manufacturer = Google
ro.product.model = Pixel 6
ro.product.device = oriole
ro.product.cpu.abi = arm64-v8a
ro.build.description = oriole-user 12 SQ3A.220705.004 8836240 release-keys
ro.hardware = oriole
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]

**Comment by flamme** [comment]
triplef@, thanks for filing the bug!

> Additionally the buffer size increases significantly from ~20 to ~80-120 ms when selecting 4 channel output.

This is expected as for default/stereo output, they can be in low latency path. But for 4 channels output, they will not be in low latency path. I think the 4 channels output will fall in hifi output path, which will the lower layer period size will be at least 4 times of low latency one. That is why you are seeing the buffer size increased. 

Sorry but I don't have the devices you tested on my side. Could you please help do some more test for further analysis?

1. Rerun the test on Oboe Tester, which is available from play store. Please use select `TEST OUTPUT` and take a screen shot of your parameters selection.
2. Rerun the test on other earlier Pixel device, for instance, Pixel 5, Pixel 4 if possible. Please also sue Oboe Tester for test.

I have created internal bug b/258495478 to track the issue.

**Comment by flamme** [comment]
@triplef , the Pixel team has confirmed this is fixed on Android 14. AFAIK, could you reset on latest build to see if this still happens? Otherwise, I will close this issue. Thanks,

**Comment by flamme** [comment]
I'm closing this. @triplef, please feel free to reopen if you still see the issue on latest build.
