### ISSUE TITLE
SampleRateConversionQuality autodocs missing some names

### ISSUE THREAD

**Issue by philburk** [google/oboe#1651]
[SampleRateConversionQuality](https://google.github.io/oboe/namespaceoboe.html#a82f3720eba7654aceb7282be36f9ff1d) only lists None, Fastest, Best.

https://google.github.io/oboe/namespaceoboe.html#a82f3720eba7654aceb7282be36f9ff1d

**Comment by robertwu1** [comment]
See https://github.com/google/oboe/blob/main/include/oboe/Definitions.h. You need to explicitly add comments for autodocs to use them.

DataCallbackResult, Result, and StreamState need to have their comments updated. The comments are after with "//".

**Comment by robertwu1** [comment]
Also channel masks
