### ISSUE TITLE
Oboe builder setup 

### ISSUE THREAD

**Issue by MohamedkhGhonim** [google/oboe#1676]
I set the setup for oboe builder as following but the sample rate conversion not work videos with sample rate rather than 44100 not converted to 44100
builder.setSharingMode(oboe::SharingMode::Exclusive)
            ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
            ->setFormat(oboe::AudioFormat::Float)
            ->setFormatConversionAllowed(true)
            ->setCallback(this)
            ->setChannelCount(oboe::ChannelCount::Stereo)
            ->setSampleRate(44100)
            ->setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Medium)
            ->setFramesPerCallback(num_samples_audio_frame)
            ->openStream(outStream);

**Comment by robertwu1** [comment]
->setSampleRate(44100)
->setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Medium)

What this means is that we will ask for samples as it is 44.1 kHz even if the underlying device does not support 44.1kHz. This conversion is meant for audio use cases where an app wants to play a specific type of audio and have it work for most devices.

If some of your videos are playing at 48 kHz instead, call setSampleRate(48000) instead for those videos and change your code appropriately for the new sizes.

Consider using [ExoPlayer](https://github.com/google/ExoPlayer) if you are playing videos and nothing is latency sensitive.

**Comment by philburk** [comment]
@MohamedkhGhonim - What did you expect to hear?

What did you actually hear?

What is the audio sample rate of your video files?

**Comment by MohamedkhGhonim** [comment]
@philburk I expect to deal with any video with any sample rate, so I need to convert any sample rate to 44100 or 48000

**Comment by philburk** [comment]
Assuming you are only playing one video at a time,
you need to set the sample rate for Oboe to match the video content.
So if your video is recorded at 22050 Hz then you need to call:

    ->setSampleRate(22050)

Then Oboe or AAudio will do the sample rate conversion for you.

**Comment by MohamedkhGhonim** [comment]
Hi thank u, but I detect the problem, I need to set the framespercallback automatic while I know that from the decoder , in fact the decoder called many times to get chunks of sound , oboe setting is define after the decoder even fire, so I put it by hand for now : sample rate 22050 -> 2048 frames per callback while sample rates (44100,48000) -> 1024 frames per callback

**Comment by MohamedkhGhonim** [comment]
I have new issue now, when I add two videos with same sample rate , the oboe stop call back at the end of the first video, is there is any way to handle it, or it was be supposed that oboe handle it ?

**Comment by philburk** [comment]
> I have new issue now,
Please open a new Issue when you have a new Issue.
Otherwise it is difficult to keep them straight.
