### ISSUE TITLE
Can we make multiple resamplers in same AudioPlayer? 

### ISSUE THREAD

**Issue by Slahuddin-Ch** [google/oboe#1678]
I am receiving multiple audio frames with different sample rate.
I am using resampler::MultiChannelResampler::make(...) to make resample all audio data to 44100 so I can play it in 1 stream after resampling. 
how can I create multiple resampleres so I can resample any sample rate I receive?

**Comment by philburk** [comment]
Yes, you can create a unique resampler for each source of data and then resample each one to 44100.
Then mix everything at 44100.
