### ISSUE TITLE
Implement P usage and input presets for OpenSL ES

### ISSUE THREAD

**Issue by philburk** [google/oboe#168]
Use SL_ANDROID_KEY_STREAM_TYPE based on USAGE and CONTENT_TYPE.
Need to figure out the optimal mapping.

Use SL_ANDROID_KEY_RECORDING_PRESET based on INPUT_PRESET.

**Comment by philburk** [comment]
Dup of https://github.com/google/oboe/issues/78

**Comment by philburk** [comment]
Reopening this because this bug is for OpenSL ES issue, which still needs work. The AAudio side is done.

**Comment by dturner** [comment]
Steps to test: 

- Clone https://github.com/pbodilis/oboe
- Open `hello-oboe` project (in Android Studio 3.4 Canary 8)
- In `PlayAudioEngine::setupPlaybackStreamParameters` set the stream usage to each of the following `Media`, `VoiceCommunication`, `Alarm`, `Notification` and `Assistant`
- For each usage run `hello-oboe`, change audio API to OpenSL ES. 
- Open volume settings and verify that changing the volume for that stream type changes the volume of the app's audio output 

Note the mappings from usage to the volume sliders in the settings UI (in Android Pie) are as follows: 

- Media -> Media volume
- VoiceCommunication -> Call volume
- Alarm -> Alarm volume
- Notification -> Ring volume
- Assistant -> Ring volume

It'd be better if the above tests were run from the command line - @philburk any ideas how we could do this? Pretty sure it's not possible at present.

**Comment by philburk** [comment]
Fixed in #283
