### ISSUE TITLE
How to seek audio to a position

### ISSUE THREAD

**Issue by DeepakHeadspire** [google/oboe#1682]
I just want to know how to seek to a position of an audio file?
Suppose I want to play an audio from 15 second (15000 millisecond) not from the starting...

**Comment by philburk** [comment]
This is not a function of Oboe.
When you open the file you will need to figure out the offset of the data in the file.
Then figure out the size of each frame in the file.

    seek_offset = data_offset + (time * sampleRate * bytesPerFrame)

Then read from that offset.
