### ISSUE TITLE
could oboe deal with two video with the same sample rate ?

### ISSUE THREAD

**Issue by MohamedkhGhonim** [google/oboe#1683]
I have new issue now, when I add two videos with same sample rate , the oboe stop call back onAudioReady at the end of the first video, is there is any way to handle it, or it was be supposed that oboe handle it ?
@philburk @robertwu1

**Comment by philburk** [comment]
Oboe should not know when one video stops and the new one begins.

Are you returning DataCallbackResult::Continue or DataCallbackResult::Stop from the callback?

**Comment by MohamedkhGhonim** [comment]
I am returning DataCallbackResult::Continue
