### ISSUE TITLE
LowLatency causes cracksin audio  after some time on one usb c input audio interface I tested 

### ISSUE THREAD

**Issue by renetik** [google/oboe#1687]
Android version(s): 11

Android device(s): Mi 9T 
Oboe version: Main 30.12.2022 
App name used for testing: Renetik FX Rack (to be released)
 
**Short description**
LowLatency causes cracks in audio on one usb c input audio interface I tested on others works fine. 
Looks like just that xiaomi device has this issue, but how should I solve it for users , what if more devices has this low latency issue? Shall I not use low latenci on input stream ? 

**Steps to reproduce**
... Create autput , create input , set oboe::PerformanceMode::LowLatency to input , start engine -> listen to some cracks in sound. Remove oboe::PerformanceMode::LowLatency, restart app -> no issues in sound. 

**Expected behavior**
Should work good with LowLatency on all devices or just be disabled automaticaly or I dont know how can I ship this app wit LowLatency if I know it has problems with some devices, I am not sure what to do actually.

**Actual behavior**
First it sounds good and then after few second or minute starts crackling, when aj restart stream again first good then crackling, you can listen in audio.

**Device**
See Android device and that audo interface is Cubilux.

```
ro.product.brand = Xiaomi
ro.product.manufacturer = Xiaomi
ro.product.model = Mi 9T
ro.product.device = davinci
ro.product.cpu.abi = arm64-v8a
ro.build.description = davinci-user 11 RKQ1.200826.002 V12.1.4.0.RFJMIXM release-keys
ro.hardware = qcom
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [1]
```

Here clearly you can hear audio effect and also some wired pause then it comes back to normal and in few second again crackling pause normal:

[FX Rack Recording (2).wav.zip](https://github.com/google/oboe/files/10326192/FX.Rack.Recording.2.wav.zip)

**Comment by philburk** [comment]
Thanks. We will report this to Xiaomi.

**Comment by philburk** [comment]
It looks like the MMAP buffer is underflowing on that device because the MMAP position for the DSP is incorrect.

Try increasing the buffer size. That will move the CPU writes away from the DSP.

    oboeStream.setBufferSize(oboeStream->getFramesPerBurst() * 4);

Does that reduce the crackling?

I notice that when there is a gap in the recording at 24 seconds then the sound is clear when it resumes.
Did you stop and restart the stream then or did you just turn off some instruments and kept the stream running?

If it only happens with LowLatency then it is probably not a CPU performance problem.

Also please try turning off Touch Sounds  in Settings >> Sounds to see if that makes a difference.

**Comment by renetik** [comment]
Application allready support this buffer size as user setting (default is 3x) so even if this is solution (that involves greater lattency) its already available in apps I released. Som maybe lets close this as I was looking for automatic softwafre solution that I can provide for all users. I will not force them to any lattency setting nor I will set 4* as default just for this one case.

**Comment by renetik** [comment]
When I set _input->setBufferSizeInFrames(_input->getFramesPerBurst() * 4); on that input stream , it fixed crackling on xiomi . Before when I was tring this I thought you mean to set it on output stream. I thought that aslo because you have written in Oboe comment :

    * This should only be used with Output streams. It will
    * be ignored for Input streams because they are generally kept as empty as possible.
    
    What is pretty weird as I fixed bug byt setting it exacly like  that. 
    
    So could be fine for future oboe users to clear this out.
