### ISSUE TITLE
setState cycle when playing from input device and headphone jack connected.

### ISSUE THREAD

**Issue by renetik** [google/oboe#1690]
Android version(s): 11
Android device(s): Mi 9 T
Oboe version: 1.6 and later

When I plug in jack headphones while playing from usb input device oboe get into some kind of cicle. I cannot detect error anywhere it just cicles in console and audio stops. Then I can restart stream and everything works again. 

```
W/AudioRecord: restoreRecord_l(2768): dead IAudioRecord, creating a new one from obtainBuffer()
D/AudioStreamLegacy: onAudioDeviceUpdate() devId 2321 => 2777
D/AudioStreamLegacy: onAudioDeviceUpdate() DISCONNECT the stream now
D/AAudioStream: setState(s#3) from 4 to 13
D/AAudio: AAudioStream_requestStop(s#3) called
D/AAudioStream: setState(s#3) from 13 to 9
E/AAudioStream: setState(3) tried to set to 9 but already DISCONNECTED
D/AudioRecord: stop mSessionID=10121
D/AudioRecord: stop(2776): mActive:1
D/truments.fxrac: PlayerBase::stop() from IPlayer
D/AudioStreamLegacy: onAudioDeviceUpdate() devId 2777 => 2777
D/AAudio: AAudioStream_requestStop(s#3) called
D/AAudioStream: setState(s#3) from 13 to 9
E/AAudioStream: setState(3) tried to set to 9 but already DISCONNECTED
D/AudioRecord: stop mSessionID=10121
D/AudioRecord: stop(2776): mActive:0
D/truments.fxrac: PlayerBase::stop() from IPlayer
D/AudioStreamLegacy: onAudioDeviceUpdate() devId 2777 => 2777
D/AAudio: AAudioStream_requestStop(s#3) called
D/AAudioStream: setState(s#3) from 13 to 9
E/AAudioStream: setState(3) tried to set to 9 but already DISCONNECTED
D/AudioRecord: stop mSessionID=10121
```

**Comment by renetik** [comment]
So my workaround is to listen ACTION_HEADSET_PLUG and restart stream to fix audio. Sad is that now each time jack is inserted there is audio pause even if jack is not used in playback. Looking for proper solution to this please.

**Comment by philburk** [comment]
Is it possible that Live Caption is enabled? Press a volume key and look for the Live Caption icon below the popup fader. 
It should have a diagonal line when disabled.

**Comment by philburk** [comment]
No response.
I think this is the same as: [b/173928197](http://b/173928197) | P3 | AAudio shared MMAP streams do not disconnect properly on RQ1A when headset plugged in

**Comment by renetik** [comment]
> @renetik - Is it possible that Live Caption is enabled? Press a volume key and look for the Live Caption icon below the popup fader. It should have a diagonal line when disabled.

I dont think so. Never heard about such thing in my live :)
