### ISSUE TITLE
CMake config works fine on Android Studio but not in command line.

### ISSUE THREAD

**Issue by hpsaturn** [google/oboe#1705]
Android version(s): not matter
Android device(s): not matter
Oboe version: 1.7.0

**Short description**
I have a complete Oboe implementation, that is working well, that using CMake and the **"prefab true"** build feature in Gradle, like in your documentation. It works fine from Android Studio too, but for my pipe line for CI it doesn't works. I have a normal tool for build any CMake project from command line, and it works without **prefab true** and adding the oboe source code, but how would be the way to build it with "prefab true"?

**Steps to reproduce**

Build any Oboe project with `prefab true` build feature in gradle file, and in the command line use:

```bash
cmake -DCMAKE_TOOLCHAIN_FILE=$(ANDROID_NDK)/build/cmake/android.toolchain.cmake -B app/build/tmp/cmake_test -S app/src/main/cpp ; cd app/build/tmp/cmake_test ; make -j 8
```
We have the next error:
```cmake
CMake Error at app/src/main/cpp/CMakeLists.txt: (find_package):
  Could not find a package configuration file provided by "oboe" with any of
  the following names:

    oboeConfig.cmake
    oboe-config.cmake

  Add the installation prefix of "oboe" to CMAKE_PREFIX_PATH or set
  "oboe_DIR" to a directory containing one of the above files.  If "oboe"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Expected behavior**
Build the libraries like AndroidStudio+Gradle+CMake stuff but from command line. 

**Actual behavior**
Only with CMake from CLI it doesn't works.

**Comment by robertwu1** [comment]
@hpsaturn did this work in the past for Oboe version 1.6.1?

**Comment by DanAlbert** [comment]
> Build the libraries like AndroidStudio+Gradle+CMake stuff but from command line.

Then run `./gradlew build`. CMake alone cannot solve this problem. It is not responsible for fetching dependencies or running prefab.

If for some reason you'd prefer to redo the work that gradle would normally do on your behalf, https://google.github.io/prefab/example-workflow.html. That's the wrong answer for most projects.

**Comment by hpsaturn** [comment]
Thanks for your answer. The `./gradlew build` alternative is not so good because it takes a lot of time ~4min, similar to other variants, `./gradlew assembleDebug` ~2min. With OpenSLES library and building it with CMake only ~15secs because we need only test the C++ layer and our libraries. 

Maybe the option that you mentioned running prefab before is the possible solution. But I think that is more easy works with the Oboe source code in the project, to have a clean CMake solution.

**Comment by DanAlbert** [comment]
If you want a CMake-only solution then you cannot use the AAR. CMake cannot use AARs directly.

**Comment by hpsaturn** [comment]
Thanks. I'm back to try to have this with CMake but building from oboe source code (submodule alternative) like is mentioned in Oboe documentation.

But I have the next issue:

```
CMake Error: install(EXPORT "mynativeaudiolibTargets" ...) includes target "mysystemsoundlib" which requires target "oboe" that is not in any export set.
```
This error sounds that only happen in the Android Studio gradle+CMake side, and the project now is broken. But if I using CMake via command line, it pass the error message, continue and it reaches to have a right build.

```
cmake -DCMAKE_TOOLCHAIN_FILE=$(ANDROID_NDK)/build/cmake/android.toolchain.cmake -B app/build/tmp/cmake_test -S app/src/main/cpp ; cd app/build/tmp/cmake_test ; make -j 8
```

Maybe do you know how to fix this CMake install error message in a project that have many CMake subprojects and using Oboe?

**Comment by philburk** [comment]
> But I have the next issue:

@hpsaturn - Did you solve the first issue? Is this a new problem?
If so then please close this one and open a new Issue.

**Comment by hpsaturn** [comment]
No yet, but I think with the information about the `prefab` we could close it. Not is a easy way, and it not is so clean like was OpenSL/ES library. Maybe you know if Oboe in some moment will be included into Android like was OpenSL/ES ?

**Comment by philburk** [comment]
Oboe will not be included in the Android NDK.
The goal for Android is to provide a compatibility layer that works with new and old versions of Android.
It uses AAudio or falls back to OpenSL ES. It also has a QuirksManager and workarounds for known bugs.
You could call AAudio directly. But you will lose the advantages of the Oboe layer.
