### ISSUE TITLE
Incorporate tricks from Chrome into Oboe, clear buffers on stop

### ISSUE THREAD

**Issue by philburk** [google/oboe#171]
Clear buffers in stop()
https://cs.chromium.org/chromium/src/media/audio/android/opensles_output.cc?l=43

**Comment by dturner** [comment]
https://cs.chromium.org/chromium/src/media/audio/android/opensles_output.cc?l=182

**Comment by philburk** [comment]
Nice!
> What is the "vivo" blacklist?
Moved to separate bug.
https://github.com/google/oboe/issues/201
