### ISSUE TITLE
[LiveEffect] Logcat warns that input stream is not low latency when it is

### ISSUE THREAD

**Issue by dturner** [google/oboe#172]
Steps to repro: 

- Run LiveEffect sample on Nexus 9
- Hit `Start`
- Open logcat

Expected result

- Logcat shows that the input stream is created as a low latency stream and no warnings are shown

Actual result

    com.google.sample.oboe.liveeffect I/AudioRecord: AUDIO_INPUT_FLAG_FAST successful; frameCount 0
    com.google.sample.oboe.liveeffect D/OboeAudio: FifoProcessor: capacityInFrames = 3072, bytesPerFrame = 4
    com.google.sample.oboe.liveeffect W/AUDIO-APP: Stream is NOT low latency.Check your requested format, sample rate and channel count

Note the line: `Stream is NOT low latency.` which should not appear. 

This could indicate that the stream's performance mode is not being set correctly in Oboe

**Comment by ggfan** [comment]
taking a look

**Comment by philburk** [comment]
Ask rago@ about this. It may be because when Effects are turned on you may
not get a fast track. Maybe you have low latency input but not output or
vice versa.

**Comment by ggfan** [comment]
Ok, will do.  I like to see it: Nexus 9 does not support O and later OSes, so this got to be OpenSL ES + Android N, only my guess.  The bug report missed the critical info about OS version, I did not see it on Pixel phone + P...

**Comment by dturner** [comment]
My Nexus 9 is running Android 7.0 NRD91R

**Comment by ggfan** [comment]
OS diff contributes to the different behaviour:
- NRD91R:  nyc_release branch,        dated 2016-12-09, Android 7.0, API 24,  saw the error
- N2G47S: nrc-mr2-release branch, dated 2017-04-03, Android 7.1.2, API 25, NOT seeing the error.

**Comment by philburk** [comment]
There is no guarantee that you will get LowLatency mode when you ask for it. 

I think the problem here is that we were given a FAST track internally but there is no way for Oboe to determine that because it is < N_MR1. So it should just set performanceMode to None, which it does. This is actually WAI.

Note that we should query the final performance mode using GetConfiguration(). But that is not supported for < N_MR1. See https://github.com/google/oboe/issues/179

**Comment by philburk** [comment]
How do you know the input stream is actually Low Latency?

Could this bug be related to #179 ?
