### ISSUE TITLE
Crackling noise on Samsung A51

### ISSUE THREAD

**Issue by MinaAbdElMassih** [google/oboe#1731]
Android version(s): 12
Android device(s): Samsung A51
Oboe version: 1.6.1
App name used for testing: None
 
**Short description**
Crackling noise heard every second when setting performance mode to LowLatency, when changing performance mode to None, the crackling noise hugely decreases but it still exists, this issue only occurs on Samsung A51.
The video that produces this noise has the following properties:
25fps 44100Hz 32 bit sample size.

Any help greatly appreciated.

Thanks

**Comment by robertwu1** [comment]
Can you repro this with OboeTester and record a video?

What about PerformanceMode::PowerSaving? Also, does this repro with 44100 24 bit, 44100 float, or 48000 32 bit?

**Comment by MinaAbdElMassih** [comment]
Thank you for your time and support!

@robertwu1 

> Can you repro this with OboeTester and record a video?

Yes I tried with OboeTester, it appears that noise is due to high work load ±24% causes noise.

> PerformanceMode::PowerSaving

Yes, causes crackling noise as well.

> does this repro with 44100 24 bit, 44100 float, or 48000 32 bit?

We use PTS_Float for all and changing sampling rate from 44100 causes noise always.

@philburk 

> Does it happen on any other device? What devices were tested?

Devices tested: Oppo A16, Samsung galaxy J6, Huawei Y7 Prime, Samsung galaxy A11 and Samsung A51.
Issue occurs on Samsung Galaxy A51.

> Does the crackle occur very regularly, like a clock ticking?
> Or is it random?

With PerformanceMode set to LowLatency it is periodic ... happens almost every second there is crackle noise.
Setting PerformanceMode to None lessens noise greatly but it is no longer periodic and becomes random ... so I am settling with setting the mode to LowLatency.

> Are you using the internal sample rate converter in AudioFlinger or the Oboe sample rate converter?

Using Oboe sample rate converter.

> setSampleRateConversionQuality()

Adding set sample rate conversion quality Best causes more noise, Medium cause noise, None noise still exist and nothing changes ... noise is like before.

> AudioFlinger

I don't use, I will check it out, by any chance do you know if its license allow using it in commercial applications?

Thanks!

**Comment by MinaAbdElMassih** [comment]
Noise was solved with using threads, it was related to work load.
