### ISSUE TITLE
Recording audio from multipe device source simultaneously

### ISSUE THREAD

**Issue by mainuddinm55** [google/oboe#1734]
I want to record audio from multiple devices simultaneously. suppose the phone is connected to a Bluetooth device and a built-in microphone. The Bluetooth device keeps a little bit away from phone now I want to record from both (built-in microphone, Bluetooth) at a time. 

have any way to achieve this?
If not please guide me about the technical limitation.

**Comment by philburk** [comment]
It may not be possible to record from two sources at the same time. We will check on that.

Have you tried any experiments with opening two streams with different device IDs?
What were the results? I suspect the second stream may always fail.

**Comment by philburk** [comment]
Our experts say that it is possible to record from two different devices in some cases. But it is not guaranteed. If the two streams are on the same HAL and are similar then only the highest priority stream will work.

**Comment by mainuddinm55** [comment]
Thank you @philburk I got my answer.

**Comment by mainuddinm55** [comment]
Hey, @philburk thanks for your support. I am try with creating two stream but getting only first stream response. 

Now, I got my answer.
