### ISSUE TITLE
Compilation errors with latest LLVM libc++

### ISSUE THREAD

**Issue by bylaws** [google/oboe#1746]
Oboe version: 1.7.0+

 
**Short description**
PR #1521 was accidentally reverted by #1524, leading to compilation errors on newer libc++ versions due to missing implicit includes.

**Comment by philburk** [comment]
Thanks for reporting this.
We should add them back where needed and comment them so it doesn't happen again.

    #include <algorithm>   // Do NOT delete. Needed for LLVM. See #1746

**Comment by philburk** [comment]
We should check for this in Continuous Integration.

@bylaws - What version of LLVM did Oboe fail on?

**Comment by bylaws** [comment]
Should be around llvm ~14.0.0, the exact commit is mentioned in the original pr

**Comment by philburk** [comment]
Include added back in.
