### ISSUE TITLE
Logging should be off by default

### ISSUE THREAD

**Issue by dturner** [google/oboe#175]
By default Oboe logs a lot of messages to logcat. This is fine for development but may not be desirable in a live environment. 

Oboe should have logging switched off by default. It should be enabled by adding: 

    target_compile_definitions(oboe PRIVATE "$<$<CONFIG:DEBUG>OBOE_ENABLE_LOGGING=1")

to `CMakeLists.txt`

**Comment by ggfan** [comment]
tentatively adding target_compile_options(oboe PUBLIC -DOBOE_ENABLE_LOGGING=1): PUBLIC means that the flag is enabled for the compiling module itself PLUS all depending modules.

**Comment by dturner** [comment]
Fixed in https://github.com/google/oboe/pull/180

**Comment by dturner** [comment]
Fixed in https://github.com/google/oboe/commit/66783b1dd4c6b11e9981fee537e2944bcd7bc825
