### ISSUE TITLE
Low latency mode causes audio unintelligible on WeDo HDX2

### ISSUE THREAD

**Issue by forlayo** [google/oboe#1750]
Android version(s):  Android 9
Android device(s):  WeDo HDX2 Android cam.
Oboe version: 1.7.2
App name used for testing:  OboeTester  2.3.7
 
**Short description**
When recording audio using Oboe and setting the option of performance to low latency, the audio recorded is unintelligible, with a feeling like when watching coded video tv shows on 90s.

**Steps to reproduce**
- Open OboeTester 2.3.7
- Click on "Record and Play" option.
- Leave all option as is, and be sure selecting LOW_LATENCY for performance.
- Click on record, talk few seconds ( you'll see that the bottom bar of audio input is not moving as it should move and "timestamp latency" shows like "?").
- Click on stop.
- Click on play, audio is unintelligible.

Notes:
- Repeating the previous steps but setting "performance" to NONE, makes the audio recorded clear.
- Exaclty same behavior when I use it from my code.

**Expected behavior**
Audio is played clearly.

**Actual behavior**
Audio recorded is unintelligible, with a feeling like when watching coded video tv shows on 90s

**Device**

WeDo HDX2 Android cam.

If device specific, and you are on Linux or a Macintosh, connect the device and please share the result for the following script. This gets properties of the device. 

```
ro.product.brand = WeDo
ro.product.manufacturer = WeDo
ro.product.model = HDX2
ro.product.device = rk3399
ro.product.cpu.abi = arm64-v8a
ro.build.description = rk3399.20220916.205528
ro.hardware = rk30board
ro.hardware.chipname =
ro.arch =
| grep aaudio =
```

**Any additional context**

Audio note taken with my iphone from the speakers of the device when I click on Play on OboeTester app.
[audio_record.zip](https://github.com/google/oboe/files/10971400/audio_record.zip)

**Comment by philburk** [comment]
They may never have tested low latency. But low latency is very important for good quality video conferencing.
I will talk to the manufacturer.

@forlayo - Do you work for WeDo?
Is this the device? https://www.wedoinnov.com/HDX2/

**Comment by forlayo** [comment]
I am not working for WeDo, it’s a device we are using off the shelf with or software.

Yes, it’s exactly the model of your link.

If you need any support from my side, I am happy to help. Thanks to checking it with the manufacturer 😊

**Comment by philburk** [comment]
I sent an email to WeDo. I will update this bug when they respond.

@forlayo - Any luck from your end?

**Comment by philburk** [comment]
We cannot buy the device.
We wrote to the manufacturer and they did not respond.
The bugs was found on Android 9.
There is nothing more we can do on this so I am closing it.
