### ISSUE TITLE
Compiling 1.7.0 fails

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#1761]
I originally filed an issue where 1.7.0 did not compile, but I had to add -D__ANDROID_NDK__ to the CFLAGS in my Android.mk, 
 probably because I'm using an older NDK (r20b).

But now I encounter something that is not NDK-related:

int32_t getMDelayBeforeCloseMillis() const is defined but not implemented
int32_t getDelayBeforeCloseMillis() is implemented in AudioStream.h however and AS says it is never used.

And several warnings like:

/oboe/src\aaudio/AudioStreamAAudio.h:123:44: warning: parameter 'mDelayBeforeCloseMillis' shadows member inherited from type 'AudioStream' [-Wshadow-field]
    void setDelayBeforeCloseMillis(int32_t mDelayBeforeCloseMillis);
                                           ^
oboe/include\oboe/AudioStream.h:597:26: note: declared here
    int32_t              mDelayBeforeCloseMillis = kMinDelayBeforeCloseMillis;

Seems this method should be changed to:
void setDelayBeforeCloseMillis(int32_t delayBeforeCloseMillis) as in its implementation

Actually, these should just be removed from AudioStreamAAudio.h:
    int32_t getDelayBeforeCloseMillis() const;

    void setDelayBeforeCloseMillis(int32_t delayBeforeCloseMillis);

Then it's all fine.

**Comment by philburk** [comment]
@extreamsd - Thanks for catching this.
It did not fail on our builds. Are you using -Werror?

Does the fix in #1762 look OK?

**Comment by extreamsd** [comment]
Yes, looks fine! Please note that the build didn't fail on this, just warnings were thrown. My original problem did fail the build, but that was just me using an older NDK.
