### ISSUE TITLE
FCNT F41B (arrows Be4 Plus F-41B) many crashes (libmedia_omx.so)

### ISSUE THREAD

**Issue by peterdk** [google/oboe#1790]
Android version(s): 12 
Android device(s): FCNT F41B (arrows Be4 Plus F-41B)
Oboe version: 1.7.0
App name used for testing:  Mini Piano Lite (Bugsnag crash reports)
 
**Short description**
I have 50+ users on Android 12 with this device causing my app to crash. I think it's related to the audio path, but not directly to Oboe? Wondering if you can report this to the manufacturer or have anything to say about it. 

**Expected behavior**
No crashes

**Actual behavior**
```
SIGSEGV: Segmentation violation (invalid memory reference)

0  libmedia_omx.so +0x1f2b4              android::hardware::media::omx::V1_0::utils::LWOmxNode::freeNode()
1  libstagefright.so +0x9cdc4            android::ACodec::LoadedState::onShutdown(bool)
2  libstagefright.so +0x9bc44            android::ACodec::LoadedState::onMessageReceived(android::sp<android::AMessage> const&)
3  libstagefright.so +0xc0174            android::AHierarchicalStateMachine::handleMessage(android::sp<android::AMessage> const&)
4  libstagefright_foundation.so +0x18980 android::AHandler::deliverMessage(android::sp<android::AMessage> const&)
5  libstagefright_foundation.so +0x1ea24 android::AMessage::deliver()
6  libstagefright_foundation.so +0x19d6c android::ALooper::loop()
7  libutils.so +0x13518                  android::Thread::_threadLoop(void*)
8  libutils.so +0x12cc0                  thread_data_t::trampoline(thread_data_t const*)
9  libc.so +0xb5088                      __pthread_start(void*)
10 libc.so +0x52f98                      __start_thread
```

**Comment by robertwu1** [comment]
Thanks for the report. I have filed an internal bug report b/279180069

**Comment by robertwu1** [comment]
Can you provide us with a bug report from the device? I don't have a FCNT F41B on hand so I can't repro this myself.

**Comment by peterdk** [comment]
I am just reporting what I get from Bugsnag for my app. I don't have the device myself as well.

**Comment by philburk** [comment]
Thanks, we are contacting the vendor.
Note similar crash:
https://stackoverflow.com/questions/74959448/fcnt-arrows-f-41b-device-appear-native-crash-in-libmedia-omx-so

**Comment by philburk** [comment]
I have found that Acodec/OMX is no longer maintained.
We recommend that partners use CCodec and Codec2.

I don't know if there is any thing you can do in your app to avoid using OMX.
But if so then it might help.

If you are playing videos then I would recommend switching to ExoPlayer. It is actively supported.

There is nothing we can do in Oboe. So I am closing this.
