### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by birdhello** [google/oboe#1794]
CMAKE_ARGS="-H. \
  -DBUILD_SHARED_LIBS=true \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DANDROID_TOOLCHAIN=clang \
  -DANDROID_STL=c++_shared \
  -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
  -DCMAKE_INSTALL_PREFIX=."

-H. 是什么意思？有人可以告诉我吗？谢谢！

**Comment by philburk** [comment]
https://stackoverflow.com/questions/31090821/what-does-the-h-option-means-for-cmake

**Comment by robertwu1** [comment]
-H is deprecated. We should change this to -S
