### ISSUE TITLE
Device menus broken because of AppCompatSpinner change

### ISSUE THREAD

**Issue by philburk** [google/oboe#1795]
OboeTester on main

**Short description**
Device menu in TEST OUTPUT does not pull down.
Voice Communication menu also broken.
It worked before PR #1769 , which used AppCompatSpinner

**Steps to reproduce**
Launch Oboetester
Tap TEST OUTPUT
Select from the Device menu

**Expected behavior**
The menu has a triangle and multiple devices.

**Actual behavior**
No triangle. Menu is unusable.

**Device**
Cheetah.

**Comment by philburk** [comment]
Breaking change was reverted. Need to figure out why it broke.

**Comment by robertwu1** [comment]
Seems like there needs to be an AppCompat theme. We would probably need to change all activities to AppCompatActivity and add a default theme. I don't think this is worth it for a test app like OboeTester.
