### ISSUE TITLE
add workaround for incorrect number of input channels on Galaxy J7

### ISSUE THREAD

**Issue by gkasten** [google/oboe#181]
Details are in https://github.com/googlesamples/android-ndk/issues/499

**Comment by philburk** [comment]
Original bug at https://github.com/googlesamples/android-ndk/issues/499

Need to determine exact manufacturer and model. Then for that model, either fail if app asks for mono. Or convert Stereo to Mono.

**Comment by philburk** [comment]
We need to get Galaxy J7 device to test,
and we should consider whether we should using _LEFT instead of _CENTER for mono.

**Comment by dturner** [comment]
We should add a test to open input streams with CENTER and LEFT and check that we get channelCount==1 on both

**Comment by atneya** [comment]
Should be fixed by #530

**Comment by philburk** [comment]
This is a request for a workaround for a bug that seems to be specific to the Galaxy J7.
The workaround would be to force channel conversion from stereo to mono.

**Comment by philburk** [comment]
The J7 was released with Lollipop in 2015.
Gerry tested it with Marshmallow and mono was working. So it appears Samsung fixed this.
Closing as obsolete.
