### ISSUE TITLE
Usage VoiceComm and Speech mode volume control not work on Android 13

### ISSUE THREAD

**Issue by hpsaturn** [google/oboe#1814]
Android version(s): Android 13 API 34
Android device(s): Pixel6 Oriole, Pixel7 GrapheneOS
Oboe version: 1.7.2
App name used for testing: Oboe tester 2.3.7 and private app.
 
**Short description**

I have issues to set the volume when you use **VoiceComm** `Usage` and **Speech** `mode`. With Oboe tester on Android 13 the volume control that is enabled is a media volume, not a call volume controller, and you can't set the volume. On Android 11 works fine, the volume controller is a call volume controller and it can set the volume.

**Steps to reproduce**

In Oboe tester:
TEST OUTPUT -> Usage set to: VoiceComm -> Content Type set to: Speech -> Open -> Start 

After that, try to change the volume. It choose the wrong controller and it can't set the volume.

![screenshot20230530_114547](https://github.com/google/oboe/assets/423856/2533de42-7dbf-44b8-8f99-d15c4e6649dd)

**Expected behavior**

With the same steps on Android 11 with the same API Audio (AAudio), you able to change the volume and the controller is the call controller. 

![screenshot20230530_115838](https://github.com/google/oboe/assets/423856/b46831fc-0e80-4dc1-9384-e003d3da835e)

**Actual behavior**

In the app that I'm working, I have a similar issue. I set the communication attributes on the initialization of my Java side:

```Java
private static AudioAttributes AUDIO_ATTRIBUTES = new AudioAttributes.Builder()
                .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                .setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)
                .build();
```

but the only way to change the volume, is enter to volume controllers and change the **media volume**. This is wrong. With OpenSL/ES and the same attributes everything works fine.

**Device**

- Pixel 6 with Oriole API 34
- Pixel 7 with GrapheneOS (Android 13)

**Script output on Oriole device:**

```bash
ro.product.brand = Android
ro.product.manufacturer = Google
ro.product.model = AOSP on Oriole
ro.product.device = oriole
ro.product.cpu.abi = arm64-v8a
ro.build.description = aosp_oriole-userdebug UpsideDownCake AOSP.MASTER 9525719 test-keys
ro.hardware = oriole
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]
```

**Comment by philburk** [comment]
Thanks for reporting this. It appears to be a System UI problem.
I created this internal bug:
[b/285185485](http://b/285185485) | P4 | Volume keys do not work when UsageVoice:Communication and ContentType:Speech

**Comment by philburk** [comment]
Note that we do not normally accept bug reports for Android variants like Graphene OS.
But I was able to reproduce it on Pixel 7 Pro running the official UDC-DEV.

**Comment by philburk** [comment]
Jiabin pointed out that if you set MODE_IN_COMMUNICATION on the main screen then the volume keys work.
Maybe Android13 is correct and Android 11 was broken.

**Comment by hpsaturn** [comment]
Yes, I already have it in my development. When I starting the communication for example, I have:

```java
   public void startCommunication() {
        AudioManager am = AudioManagerCompat.getAudioManager(context);
        am.setMode(AudioManager.MODE_IN_COMMUNICATION);
    }
```
but, with that the behavior is different, because the call volume controller is showed but it doesn't nothing, and we have the same issue: The real stream choose for the system, is `media` or `stream_music`, not a `stream_voice_call`. My provisional workaround is intercept with a observer this changes and set the media volume. It is a ugly workaround I think. With Android 11 and OpenSL/ES it doesn't happen.

**Comment by philburk** [comment]
I tried OboeTester on TQ2A on Pixel 7 Pro.
I set MODE_IN_COMMUNICATION
PerfMode:NONE
Usage:VoiceComm
ContentType:Speech

The sound came out the earpiece.
The volume keys brought up the call fader and the keys worked. PASS
Note that there was some zipper noise
The call volume does not go all the way to zero, as intended.

**Comment by hpsaturn** [comment]
Thanks @philburk for the feedback. A little question, whats means "TQ2A"? is your internal QA setup or issues dashboard? Is possible test this fix? which is the branch that you are using? Thanks in advance.

**Comment by philburk** [comment]
> whats means "TQ2A"?

That is the second quarterly release. T QPR2.

Try https://developers.google.com/android/ota
Also https://flash.android.com/

**Comment by philburk** [comment]
I tried adding this call to OboeTester. It helped for Usage::Alarm but not Usage::Notification.
Does it help in your app?

    private void setStreamControlByAttributes(int usage, int contentType) {
        AudioAttributes attributes = new AudioAttributes.Builder().setUsage(usage)
                .setContentType(contentType).build();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            int volumeControlStream = attributes.getVolumeControlStream();
            Log.i(TAG, "setVolumeControlStream(" + volumeControlStream + ")");
            setVolumeControlStream(volumeControlStream);
        }
    }

**Comment by hpsaturn** [comment]
Sorry for late response, I'm returning again to this issue I was in vacations. Well the issue persist in TQ2A.230305.008.E1 on a official Pixel6, also with the last synced sources on Grapheno OS, running the last GooglePlay version of Oboe Tester. 

Also I tried with your code, with the `setVolumeControlStream` and it doesn't fix the issue. The Volume bar type is right (VoiceComm), but it doesn't change the volume

**Comment by hpsaturn** [comment]
Today I can do a test with the official Android 14 update, I guess this version:

```bash
ro.build.fingerprint:
google/oriole/oriole:14/UP1A.231105.003/11010452:user/release-keys
ro.build.display.id:
UP1A.231105.003
```
And I notice that the issue persist. The media bar that is showed and handled for the buttons is the media bar, not the call bar. And also of course, it can't able to change the volume. I'm going to review the android source code, because maybe is a OS issue. Maybe anyone knows where I can start? Thanks

![screenshot20231114_170159](https://github.com/google/oboe/assets/423856/3525daaf-be0b-4914-b3d6-d6acefc301bd)

**Comment by hpsaturn** [comment]
Well, I tested the last version of OboeTester and I notice that we don't have this behavior now. I looked up what was the change, and I founded that OboeTester implements new settings with Oboe 1.8:

https://github.com/google/oboe/blob/main/apps/OboeTester/app/src/main/cpp/NativeAudioContext.cpp#L203-L204

I added to my common setup method. like this:

```cpp
oboe::AudioStreamBuilder *
AndroidAudioDeviceManager::setupCommonStreamParameters(
    oboe::AudioStreamBuilder *builder) {
    builder->setAudioApi(mAudioApi)
      ->setFormat(mFormat)
      ->setFormatConversionAllowed(true)
      ->setSharingMode(oboe::SharingMode::Exclusive)
      ->setUsage(oboe::Usage::VoiceCommunication)
      ->setContentType(oboe::ContentType::Speech)
      ->setPerformanceMode(oboe::PerformanceMode::LowLatency);
  return builder;
}
```
And also added one setting more to my Microphone stream setup:

```cpp
 builder->
 ...
 ->setInputPreset(oboe::InputPreset::VoiceCommunication)
```
and the behavior it is the expected :D  
then I'm going to close this issue.
