### ISSUE TITLE
mmap output silent when using USB-C headset on s23+ (SM-S916U1)

### ISSUE THREAD

**Issue by chrismanchester** [google/oboe#1831]
Android version(s): 13
Android device(s): s23+ (SM-S916U1)
Oboe version: 1.7.3
App name used for testing:  OboeTester

 
**Short description**

mmap output becomes silent after using USB-C headset for a short time

**Steps to reproduce**

Preconditions: USB-C headset plugged in, "Digital Wellbeing" "Volume Monitor" feature enabled

Select "Test Output"

Press "Open"
Press "Start"

**Expected behavior**
test tone plays through headset

**Actual behavior**
no audio played from headset

**Device**

Confirmed on SM-S916U1, user reports from other s23 variants

```
$ for p in \
>     ro.product.brand ro.product.manufacturer ro.product.model \
>     ro.product.device ro.product.cpu.abi ro.build.description \
>     ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
>     do echo "$p = $(adb shell getprop $p)"; done
ro.product.brand = samsung
ro.product.manufacturer = samsung
ro.product.model = SM-S916U1
ro.product.device = dm2q
ro.product.cpu.abi = arm64-v8a
ro.build.description = dm2quew-user 13 TP1A.220624.014 S916U1UES1AWC9 release-keys
ro.hardware = qcom
ro.hardware.chipname = 
ro.arch = 
| grep aaudio = [aaudio.hw_burst_min_usec]: [2000]
[aaudio.mmap_exclusive_policy]: [2]
[aaudio.mmap_policy]: [2]
```

**Any additional context**

It takes some time using the phone with the headset plugged in before the issue begins. Once it gets into this state multiple headsets will have the issue (tested with Samsung USB-C headset and Apple adapter with 3.5mm headset).

Restarting the device will restore output for a short time

edit: See https://github.com/google/oboe/issues/1831#issuecomment-1601888757 for more specific reproduction parameters

Un-checking the "MMap" check box in the OboeTester UI will restore output

This may not be viewable outside my account, but for reference we filed this in the Samsung Dev portal here: https://developer.samsung.com/dashboard/support/46619

**Comment by chrismanchester** [comment]
> @chrismanchester - Thanks for the report.
> 
> > mmap output becomes silent after using USB-C headset for a short time
> 
> How short? A couple seconds? A few minutes?

Hi Phil, this is a weird one. I had to use the phone for unrelated testing in OboeTester and Sing for most of an afternoon before first reproducing it, but now that I have it happens within the first few streams I open after booting the device.

If it starts to seem like it's no longer reproducing I can sometimes get it to happen by toggling the mute state of the device, but this is very inconsistent.

**Comment by flamme** [comment]
I tried on the same Samsung Galaxy S23+ on Android 13 on my side. But haven't been able to reproduced the issue. Will try more to see if I can reproduce it. 

BTW, I don't have access to the report on Samsung Dev portal mentioned above.

**Comment by chrismanchester** [comment]
Hi @flamme, I spent some more time with the device this afternoon and finally found the pre-condition for the bug: under the "Digital Wellbeing" section of the settings the "Volume Monitor" feature must be enabled.

Once this is enabled mmap output through the USB-C headset will only work if the phone is on silent mode and has not been taken off silent mode while the headset is plugged in since boot and no legacy output stream has been used with the headset since boot.

**Comment by flamme** [comment]
Brilliant finding, @chrismanchester!

I can reproduce the issue on my Samsung device with enabling "Volume Monitor". The `Volume Monitor` works as an audio effect. But when it is on MMAP playback, it is not attaching to the MMAP thread. The `volume monitor` effect is something created by Samsung, I think it worth to have Samsung folks to take a look.

**Comment by flamme** [comment]
I created an internal bug with Samsung to follow up this issue.

[b/289284362](http://b/289284362) | P2 | MMAP output silent when using USB-C headset on s23+ (SM-S916U1) when turning on Volume Monitor

**Comment by philburk** [comment]
Thanks for reporting this. Samsung found and fixed the problem. The fix will be in an upcoming OTA.
