### ISSUE TITLE
Can I open two output streams on two differen output devices ?

### ISSUE THREAD

**Issue by renetik** [google/oboe#1844]
Oboe version: 1.7

I was testing in my app to add aditional oudio stream to use as monitor of main oudio stream for mixing an live performance purposes.. But somehow I cannot get it working on Samsung or Xiaomi deices. Is this really supported? What happens is that when I open another stream on other device my main stream swicthes to that device. 
Just some example of how I create streams.. nothing special there:

**So the quastion is if this is tested nad supported to open multiple output strems for multiple output devices.**
    
 ```
    bool start(int deviceId) {
        logDebug("%s: start deviceId:%d", TAG, deviceId);
        if (isStarted) return true;
        this->_deviceId = deviceId;
        _callback = new OutputCallback(this, _settings, _mixer);
        auto openStreamResult = openStream(deviceId);
        if (openStreamResult != oboe::Result::OK) {
            logError("%s: openStreamResult:%s", TAG, oboe::convertToText(openStreamResult));
            close();
            return false;
        }
        if (_settings->sampleRate != _stream->getSampleRate()) {
            _settings->setSampleRate(_stream->getSampleRate());
            _mixer->onSampleRateChanged();
        }
        if (_bufferMultiplier >= 1) {
            auto frames = _stream->getFramesPerBurst() * _bufferMultiplier;
            logDebug("%s: setBufferSizeInFrames:%d", TAG, frames);
            _stream->setBufferSizeInFrames(frames);
        } else _callback->latencyTuner(new oboe::LatencyTuner(*_stream));

        auto startStreamResult = _stream->requestStart();
        if (startStreamResult == oboe::Result::OK) {
            logDebug("%s: isStarted", TAG);
            isStarted = true;
            _mixer->onStartOutput();
            return true;
        } else {
            logError("%s: start: %s", TAG, oboe::convertToText(startStreamResult));
            close();
            return false;
        }
    }
    
        oboe::Result openStream(int deviceId) {
        logDebug("%s: openStream", TAG);
        logDebug("%s: sampleRate %d", TAG, _settings->sampleRate.load());
        oboe::AudioStreamBuilder builder;
        builder.setDeviceId(deviceId == -1 ? oboe::kUnspecified : deviceId);
        builder.setDirection(oboe::Direction::Output);
        builder.setSampleRate(_settings->sampleRate);
        builder.setChannelCount(oboe::ChannelCount::Stereo);
        // EXCLUSIVE for lowest possible latency.
        builder.setSharingMode(oboe::SharingMode::Shared);
//        builder.setInputPreset(oboe::VoicePerformance);
        builder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
//        builder.setUsage(oboe::Usage::Media);
//        builder.setContentType(oboe::ContentType::Music);
//        builder.setAudioApi(oboe::AudioApi::AAudio);
        builder.setFormat(oboe::AudioFormat::Float);
        builder.setFormatConversionAllowed(true);
        builder.setChannelConversionAllowed(true);
        builder.setSampleRateConversionQuality(oboe::SampleRateConversionQuality::Medium);
        //if not set crashes on xiaomi
        builder.setFramesPerDataCallback(_settings->framesPerBuffer);
        builder.setCallback(_callback);
        return builder.openStream(_stream);
    }
```

**Comment by robertwu1** [comment]
Each OEM can define how they handle multiple output streams with two different output devices. This means that for different devices, there may be different behavior.

For a live performance, why not have one input stream and one output stream? You can add an output mixer on your side.

**Comment by philburk** [comment]
Good question. I don't think I have ever opened two exclusive MMAP output streams on two different devices!
I added #1845 for that.

>        //if not set crashes on xiaomi
>       builder.setFramesPerDataCallback(_settings->framesPerBuffer);

Uh oh! Could you please file a separate bug for that.

**Comment by renetik** [comment]
> Each OEM can define how they handle multiple output streams with two different output devices. This means that for different devices, there may be different behavior.
> 
> For a live performance, why not have one input stream and one output stream? You can add an output mixer on your side.

I want to monitor output, as you can see on any dj mix. I have multuple inputs already. What I need is to basicaly open anothe output stream and copy via ring buffer audio data there for mirroring of playback there while still can be audio different if necessary with different effects or whatever. Same you see on any DJ equipment mixer.

**Comment by renetik** [comment]
> Each OEM can define how they handle multiple output streams with two different output devices. This means that for different devices, there may be different behavior.
> 
> For a live performance, why not have one input stream and one output stream? You can add an output mixer on your side.

This sounds really bad who desided on this design ? :) Very bad for android platform if this not get resolved. If thas tha case I am doomed here, I cannt make this feature to Renetik Mix app or other of app I work on... 
It was intended fot this one mainly.. 
https://play.google.com/store/apps/details?id=com.renetik.instruments.mix

**Comment by philburk** [comment]
> I want to monitor output, as you can see on any dj mix. 

Some DJ rigs have 4 channel USB output.
Can you use channels [0,1] for the house and [2,3] for monitoring?

**Comment by renetik** [comment]
> > I want to monitor output, as you can see on any dj mix.
> 
> Some DJ rigs have 4 channel USB output. Can you use channels [0,1] for the house and [2,3] for monitoring?

Sure I understand there are some special expensive devices with multpile output channels.... that I never heard of..  :)  but apps I am making are more about easy to use and accessible features for common people to jump in easily and make some music still providing pro like sound and some advanced capabilities.. So this will not be priority for me have better ideas already for other audio apps I do.

 If output monitoring is not posiible for now I will let it go. 
 I did some refacotring of c++ code becuase of that so it was usefull effort at last...
 Thanks.

**Comment by philburk** [comment]
> I am making are more about easy to use and accessible features for common people

I think providing a low cost way to monitor two individual streams would be a good thing.
I will add that to OboeTester in #1845 and explore ways of testing and requiring that functionality in Android.
Thanks for bringing this to our attention.
