### ISSUE TITLE
MediaCodec/MediaMuxer support with Oboe

### ISSUE THREAD

**Issue by shreks7** [google/oboe#1865]
Is there any example or documentation for using `oboe` with Android `MediaCodec` & `MediaMuxer`? I am trying to see record a video but with `oboe` buffer as the audio source. I know the process in general - Write the audio buffer to the codec and mux it with the `h264` video codec but wanted to know if there is anything out there for reference.  Thank you!

**Comment by philburk** [comment]
I am not aware of any docs that describe using Oboe with MediaCodec/Muxer.
You may be the first.
Let us know how your project turns out.
