### ISSUE TITLE
OboeTester Data path tests don't look at input channel masks correctly

### ISSUE THREAD

**Issue by robertwu1** [google/oboe#1869]
Should reference [AAudioConvert_androidToAAudioChannelLayoutMask](https://cs.android.com/android/platform/superproject/main/+/refs/heads/main:frameworks/av/media/libaaudio/src/utility/AAudioUtilities.cpp;l=367;drc=3d4951806618b5119ec60a12d80c026bf7ae4153)

**Comment by philburk** [comment]
This is related to internal bug:
[b/292294672](http://b/292294672) | P1 | AAudio channel masks for INPUT do not match Java CHANNEL_IN masks
