### ISSUE TITLE
workaround FIFO wraparound bug in 8.1

### ISSUE THREAD

**Issue by philburk** [google/oboe#188]
Reading or writing a non-multiple of the burst size could cause data corruption.

**Comment by philburk** [comment]
This only appears to happen with input streams on OC_MR1 in MMAP mode.

**Comment by philburk** [comment]
Can use block adapter from
https://cs.corp.google.com/android/frameworks/av/media/libaaudio/src/utility/

May not be needed if all Pixel phones now on P. 8.1 is O_MR1.

**Comment by atneya** [comment]
Should we mark this will not fix @philburk ?

**Comment by philburk** [comment]
Only affected MMAP on Pixel 1 phones, which are now running P. So fix not needed.
