### ISSUE TITLE
get_nprocs() not supported on older versions on Android

### ISSUE THREAD

**Issue by robertwu1** [google/oboe#1891]
[get_nprocs()](https://linux.die.net/man/3/get_nprocs) was supported starting in [Android 5.1](https://www.gnu.org/software/gnulib/manual/html_node/get_005fnprocs.html). We should add the appropriate checks in Oboe

**Comment by philburk** [comment]
Build errors in: cl/555314102

Alternatives at:
https://developer.android.com/ndk/guides/cpu-features
