### ISSUE TITLE
OboeTester ROUTING STRESS screen goes dark and the test stops

### ISSUE THREAD

**Issue by xiaotongtzhao** [google/oboe#1906]
Android version(s): VIC 10696667, TM 10664255
Android device(s): Tested on Pixel 6, Pixel 7 Pro and Felix
Oboe version: 1.7.5 OboeTester 2.5.5
App name used for testing: OboeTester
 
**Short description**
Set display lock time as 15 seconds
Start OboeTester and run "Routing Stress" test
In middle of testing, screen goes dark and test stops.

**Expected behavior**
When test is running, screen won't go to dark

**Actual behavior**
Screen goes dark and test stops

**Comment by philburk** [comment]
I could not reproduce this at first. Then I remembered that I had enabled "Stay Awake" mode in Developer Options.
So I unplugged the ADB cable and then I was able to reproduce the problem.

**Comment by xiaotongtzhao** [comment]
Verified the fix with 8/24/2023's OboeTester from github.
