### ISSUE TITLE
I want to know how to play mp3 file in scoped storage using oboe

### ISSUE THREAD

**Issue by antwhale** [google/oboe#1907]
In your sample code, there is only way to play .wav and .mp3 file in assets folder.
I want to know how to play mp3 file in scoped storage using oboe

**Comment by philburk** [comment]
Oboe does not provide any support for storage. Your app needs to load the data into memory and then pass it to Oboe.

I don't know how to use scoped storage. I would start with these docs.
https://developer.android.com/training/data-storage
