### ISSUE TITLE
Cannot open recording stream on Motorola Moto G 2nd Gen

### ISSUE THREAD

**Issue by dturner** [google/oboe#192]
Steps to repro: 

- Run the LiveEffect sample
- Hit Start

Expected outcome: 

- Audio from the microphone is heard through the speaker or headphones

Actual outcome: 

- No audio is heard from the speaker or headphones

The following logcat output shows that the recording stream fails to be created: 

> 07-21 18:51:02.063 16034-16034/com.google.sample.oboe.liveeffect E/libOpenSLES: Cannot create AudioRecorder: data sink must be in PCM format
> 07-21 18:51:02.063 16034-16034/com.google.sample.oboe.liveeffect E/libOpenSLES: Cannot create AudioRecorder: invalid source or sink
> 07-21 18:51:02.063 16034-16034/com.google.sample.oboe.liveeffect W/libOpenSLES: Leaving Engine::CreateAudioRecorder (SL_RESULT_PARAMETER_INVALID)
> 07-21 18:51:02.063 16034-16034/com.google.sample.oboe.liveeffect E/OboeAudio: createAudioRecorder() result:SL_RESULT_PARAMETER_INVALID
> 07-21 18:51:02.063 16034-16034/com.google.sample.oboe.liveeffect E/AUDIO-APP: Failed to create recording stream. Error: ErrorInternal
> 07-21 18:51:02.063 16034-16034/com.google.sample.oboe.liveeffect E/AUDIO-APP: Failed to create recording (0x0) and/or playback (0xb8aef600) stream

**Comment by philburk** [comment]
What version was the Moto G running?

Is this a version issue or vendor implementation issue?
I would think that the FLOAT code in OpenSL ES would all be above the level of the HAL.

**Comment by dturner** [comment]
The Moto G was running API 21 LXB22.99-16.3. 

The only reference I can find to that error message is here: https://android.googlesource.com/platform/frameworks/wilhelm/+/4597a74/libopensles/android_AudioRecorder.cpp#61

So it could be a version issue, although I was sure that API 21 had float support for recording streams. Maybe that was introduced later?

**Comment by dturner** [comment]
I just tested a Samsung Galaxy S4 running API 21 and ran into the same issue. Looks like it *is* a version issue.

**Comment by dturner** [comment]
Once we figure out what is the expected behaviour we should definitely add a test for this.

**Comment by dturner** [comment]
It appears that [float playback capability was added to Lollipop](https://android.googlesource.com/platform/frameworks/wilhelm/+/e57c133%5E!/) but [float record capability was only added in Marshmallow](https://android.googlesource.com/platform/frameworks/wilhelm/+/marshmallow-release/src/android/AudioRecorder_to_android.cpp#167).

Verified by running repro steps on emulators: 

API 21 - error message
API 22 - error message 
API 23 - no error
API 24 - no error

**Comment by vbarthel-fr** [comment]
Here is an attempt at addressing this issue: https://github.com/google/oboe/pull/205

As mentioned in the PR, I don't have the knowledge required to fully understand the consequences of those changes. See the description of the PR for more details :)

**Comment by vbarthel-fr** [comment]
My bad, there is already an opened PR addressing this issue: https://github.com/google/oboe/pull/194

Sorry for all that :/
