### ISSUE TITLE
Keep screen always on for test disconnect in OboeTester

### ISSUE THREAD

**Issue by flamme** [google/oboe#1957]
When running `Test Disconnect` in OboeTester, if the screen is off, `onStop` will be called and cancel the test. It may make the tester misunderstand that the test fails.

**Comment by flamme** [comment]
It was fixed by https://github.com/google/oboe/pull/1905. Phil, please feel free to close as obsolete if the one on play store is updated too.

**Comment by philburk** [comment]
I plan to update the Play Store version after the new Data Paths and glitch test changes are stable.
