### ISSUE TITLE
What are the advantages of using aaudio through oboe?

### ISSUE THREAD

**Issue by lhran99** [google/oboe#1972]
I am about to develop my audio app, for low latency scene。I find that there is not much code about aaudio in oboe, just wrap all libaaudio.so symbols , so i want to know is there some advantages to using aaudio through oboe than without oboe?

BTW，is there some difference between aaudio with legacy mode and opensles ? It seems that they all using Native AudioRecord 。I want to replace opensles with aaudio with legacy mode for my legacy app。

**Comment by robertwu1** [comment]
AAudio is supported only from Android 8 and above. We recommend using AAudio for Android 8.1 and above. If your app needs to support older Android versions, you would need to add an if statement manually for OpenSL ES support. Oboe will handle this fork for you.

Oboe contains several upgrades over using AAudio directly including a sample rate converter, full duplex stream support, and a quirks manager for some known bugs for specific devices.

OpenSL ES is no longer officially supported so there may be bugs that we can longer fix.

If you aren't using MMAP, both AAudio and OpenSL ES are similar to native AudioRecord. Why not use AAudio or Oboe in your app and create MMAP streams if they are supported?

**Comment by lhran99** [comment]
> AAudio is supported only from Android 8 and above. We recommend using AAudio for Android 8.1 and above. If your app needs to support older Android versions, you would need to add an if statement manually for OpenSL ES support. Oboe will handle this fork for you.
> 
> Oboe contains several upgrades over using AAudio directly including a sample rate converter, full duplex stream support, and a quirks manager for some known bugs for specific devices.
> 
> OpenSL ES is no longer officially supported so there may be bugs that we can longer fix.
> 
> If you aren't using MMAP, both AAudio and OpenSL ES are similar to native AudioRecord. Why not use AAudio or Oboe in your app and create MMAP streams if they are supported?

thanks.

AAudio and OpenSL ES are similar to native AudioRecord
------
I run oboetester in my android device, compare the difference between aaudio without mmap and opensles, and found that aaudio has lower latency than opensles. I am not sure whether it means "aaudio without mmap is better than opensles?" or not?

Device: Pixel 4
[ro.bootimage.build.version.sdk]: [34]

aaudio without mmap:
<img width="465" alt="WeChatWorkScreenshot_7b01cf9f-bfad-4e7c-bf6c-1f613a5d2e0d" src="https://github.com/google/oboe/assets/10515793/ccb130ea-d5e1-44d3-b358-c9816ae257f1">
<img width="465" alt="WeChatWorkScreenshot_001b2de8-cc87-4459-ab00-61846ac50673" src="https://github.com/google/oboe/assets/10515793/0029eb1c-7efc-4fa9-997e-aeacb16951cf">

opensles:
<img width="465" alt="WeChatWorkScreenshot_59689305-2c15-4e5e-9d97-539314174299" src="https://github.com/google/oboe/assets/10515793/ef13315d-f14a-420c-95a1-705b70435466">
<img width="465" alt="WeChatWorkScreenshot_fa0dfcae-df0c-4524-a0fe-c7d6c99d371d" src="https://github.com/google/oboe/assets/10515793/42b59974-a7c5-4f3f-8120-4a23c02d8708">

**Comment by robertwu1** [comment]
In your AAudio test, it seems like you disabled MMAP only for the input path. If you disable MMAP for the output path as well, the results should be similar.

**Comment by robertwu1** [comment]
Similarly, you only changed the API to OpenSL ES for the input path.

**Comment by lhran99** [comment]
> In your AAudio test, it seems like you disabled MMAP only for the input path. If you disable MMAP for the output path as well, the results should be similar.

The first is  aaudio without mmap for input and aaudio with mmap for output, the second is opensl for input and aaudio still with mmap for output。

From the oboetester, it seems that aaudio without mmap has larger buffer size than opensles for input path.
For the input path, aaudio without mmap buffer size is 4096, while opensles buffer size is 3072, even through they have same burst.

"If you disable MMAP for the output path as well, the results should be similar.:"
It means output with mmap cause the input without mmap has lower latency than opensles?

**Comment by lhran99** [comment]
> In general the latency for OpenSL will have similar latency to AAudio because they both use AudioTrack and AudioRecord classes internally. But there will be some differences because for OpenSL ES the burst size is determined by
> 
> ```
> oboe::DefaultStreamValues::FramesPerBurst
> ```
> 
> which is set based on the query for AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER. But not that number does not take into account the details of the stream configuration.
> 
> In contrast, AAudio is able to get more optimal buffer sizes based on more complete information.
> 
> So AAudio Legacy may have lower latency than OpenSL ES.
> 
> In general we recommend just using Oboe and letting it decide the best options for the lowest latency.

thanks for this information.
