### ISSUE TITLE
Is it possible to change the number of audio words in a frame in LiveEffect?

### ISSUE THREAD

**Issue by mahaju** [google/oboe#1977]
Android version(s): 14
Android device(s): Galaxy S22
Oboe version: 1.8.1
App name used for testing: LiveEffect
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
I noticed that in LiveEffectEngine.java the function

`native_setDefaultStreamValues(defaultSampleRate, defaultFramesPerBurst);`
allows me to set the sampling frequency and I am assuming the number of PCM words coming in from the microphone in one frame of audio. The default values are 48000 and 192. However, I want to change them to 16000 Hz sampling frequency and 64 words per frame.

I have found that inside the function 
`DataCallbackResult onAudioReady((...)` 
in FullDuplexStream.h, the value of `numFrames` is always 96 whether `defaultFramesPerBurst = 192`  or `defaultFramesPerBurst = 64` 

However, I think the sample rate is being changed from 48kHz to 16kHz because I can notice the change in audio quality when listening. Is there a way fix the size of audio frame to 64 words at 16kHz?

**Comment by philburk** [comment]
The call to native_setDefaultStreamValues() only has an effect when OpenSL ES is used.
This will normally only happen on old Android devices, before Android 8.1.

You can set the sample rate by calling:
    builder.setSampleRate(16000);
and set the callback size using:
    builder.setFramesPerDatacallback(64);

https://google.github.io/oboe/classoboe_1_1_audio_stream_builder.html#aef61b952f2e4cf1e0d77bcfd45dde623

**Comment by mahaju** [comment]
There is a call to setSampleRate() inside LiveEffect/src/main/cpp/LiveEffectEngine.cpp

```
oboe::AudioStreamBuilder *LiveEffectEngine::setupRecordingStreamParameters(
    oboe::AudioStreamBuilder *builder, int32_t sampleRate) {
    // This sample uses blocking read() because we don't specify a callback
    builder->setDeviceId(mRecordingDeviceId)
        ->setDirection(oboe::Direction::Input)
        ->setSampleRate(sampleRate)
        ->setChannelCount(mInputChannelCount);
    return setupCommonStreamParameters(builder);
}
```
Is this where the sample frequency should be changed? I thought this was the function that eventually gets called by native_setDefaultStreamValues() function in LiveEffectEngine.java

Should the call to setFramesPerDatacallback() be here in the LiveEffectEngine.cpp file as well?

**Comment by mahaju** [comment]
I've also noticed that in a Galaxy A32 phone with Android 13, defaultFramesPerBurst in LiveEffectEngine.java is 256, while numFrames in onAudioReady() in FullDuplexStream.h is also 256. This is different from the Galaxy S22 mentioned in the original question, where defaultFramesPerBurst  = 192 and numFrames = 96. What does this indicate?

**Comment by robertwu1** [comment]
See our [documentation](https://google.github.io/oboe/classoboe_1_1_default_stream_values.html) for DefaultStreamValues. Please don't rely on these as OpenSL ES will not be used by default in Oboe after Android 8.1.

**Comment by philburk** [comment]
> Android studio shows me a compiler error and the program does not compile,

What is the error? Please paste in a few lines of your code.

> This is different from the Galaxy S22 mentioned in the original question, where defaultFramesPerBurst = 192

Different manufacturers tune their phones differently.

**Comment by robertwu1** [comment]
LiveEffect uses a [FullDuplexStream](https://google.github.io/oboe/classoboe_1_1_full_duplex_stream.html) as it has both an input and output stream. I recommend starting with a simpler example like [SoundBoard](https://github.com/google/oboe/tree/main/samples/SoundBoard) where only an output stream is used.

If you want to see how the parameters you set affects the resulting stream, try [OboeTester](https://github.com/google/oboe/tree/main/apps/OboeTester). You can set many parameters in Test Input and Test Output.

**Comment by mahaju** [comment]
@philburk on reopening the project after a few hours that particular error doesn't happen anymore. Probably a clean/rebuild would have fixed it for me. I apologize for that

**Comment by mahaju** [comment]
@robertwu1 I need both input and output streams though its the whole reason I'm using LiveEffect as the base code. I also need to get 64 audio samples at 16000 Hz and make an audio passthrough program, so that I can add another audio processing algorithm to it later on. Like I said, I tried calling ->setFramesPerDataCallback(64) inside `oboe::AudioStreamBuilder *LiveEffectEngine::setupRecordingStreamParameters(` as mentioned in my post above but it doesn't work.

**Comment by robertwu1** [comment]
LiveEffectEngine uses a FullDuplexStream so there is both an input and output stream. You need to configure both the input stream and output stream. See LiveEffectEngine::setupPlaybackStreamParameters

**Comment by robertwu1** [comment]
If you call setFramesPerDataCallback in LiveEffectEngine::setupCommonStreamParameters, you should see that number of frames in LiveEffectEngine::onAudioReady
