### ISSUE TITLE
Problem building oboe

### ISSUE THREAD

**Issue by Nimitz14** [google/oboe#199]
Hi,

I just pulled the latest oboe commit from master as my version was several months old, and unfortunately can't build my project anymore. It seems it's expecting the file `aaudio/AAudio.h` to exist (AndroidStudio is spewing tons of errors about missing definitions, and I can see files asking for `aaudio/AAudio.h`)? I don't remember ever having to download the AAudio code separately before though? Probably something silly I've done, but it seems how to add Oboe in the CMakeLists.txt of the external project hasn't changed, so I'm not sure as to what I could have missed?

Also (while I'm here), for my use case I have some quite CPU intense processes being done in `onAudioReady`. I do not require very low latencies, so I would be fine with a lot of samples being buffered (while my stuff in `onAudioReady` is doing its thing) before `onAudioReady` is called again. Am I correct in thinking Oboe will take care of doing this all on its own? So even if occasionally `onAudioReady` may take up to a second to run, Oboe will buffer all audio and then dump it on its next call to `onAudioReady` without any issues? I've had some issues with samples being dropped (it seems actually the entire call to `onAudioReady` was dropped), but I've got some ideas why I might have caused that (I was for example using a fixed size `FramesPerCallback` via `setFramesPerCallback`, which I imagine if set too low for how long onAudioReady runs could cause problems).

**Comment by philburk** [comment]
If you are missing  "aaudio/AAudio.h" then you are probably building with an old NDK.  It was added in NDK r17.
https://github.com/google/oboe#requirements

> Also (while I'm here), 

Please start a new Issue for unrelated questions. Then we can track them separately. Also others can find your 2nd question easier.

> I do not require very low latencies, 

Then request  builder.setPerformanceMode(PerformanceMode:None);
That is the default but it helps to be sure.

> So even if occasionally onAudioReady may take up to a second to run

Wow! That is a really long time. I would not use a callback for that task. For very high latency, you can use a blocking write() in your own thread.
The buffer capacity may be less than one second. Try to create a stream with a large buffer with a capacity and size > one second.

If you cannot make one then create your own FIFO and then use a callback to read from the FIFO.

**Comment by Nimitz14** [comment]
Thank you, the update solved it.

> Wow! That is a really long time. I would not use a callback for that task. For very high latency, you can use a blocking write() in your own thread. The buffer capacity may be less than one second. Try to create a stream with a large buffer with a capacity and size > one second.

So I tried removing the CPU intense parts and still had samples being dropped, so I'll focus on fixing that problem now (I'll try and reproduce it in a simple app that just records the input audio and writes it out to a file). I'm assuming the directive to not use file operations in `onAudioReady` has to do with performance reasons correct (and not something else that could cause problems with writing)?

To be clear the reason I can get away with the occasional high latency is because I'm not outputting any audio (only reading the input), so there's no reason for me to ever call write().

Is there any way to ask questions without creating an issue (since you asked them to be separated but it seems wrong to create issues for questions)? I have more: requestFlush does not work for input audio, which means the number of frames processed will always be a multiple of the FramesperCallback, is that intentional (as that means sometimes samples must be dropped at the end)? Also I played around with the settings a bit and created occasional artificial delays in `onAudioReady`, but `numFrames` never changed  (`setFramesperCall` was never called, happened for different performance settings). So it seems `onAudioReady` is not made for dealing with variable workloads (question is it expected for a stream to use the same number of frames per callback once started)? I'm probably going to then go in the direction of just using `onAudioReady` to populate my own buffer (that I'll take care of controlling).

**Comment by philburk** [comment]
> Thank you, the update solved it.

Great. I will close this issue.

> Is there any way to ask questions without creating an issue (since you asked them to be
> separated but it seems wrong to create issues for questions)?

No. Issues work well for questions. Questions often turn out to reveal bugs. Also issues can be searched by topic. That is one reason to put unrelated questions in multiple Issues. Also we want to be able to close the Issue when the questions is answered.
