### ISSUE TITLE
System screen recorder doesn't capture audio in Oboe sample apps

### ISSUE THREAD

**Issue by meteaurestudios** [google/oboe#1992]
Android version(s): 14
Android device(s): Pixel 8, Pixel 4a 5G
Oboe version: 1.8.1
App name used for testing: hello-oboe
 
**Short description**

Audio is not captured from the Android built-in screen recorder, despite having activated the option

**Steps to reproduce**

- Build and launch hello-oboe
- Tap the screen to ensure sound is produced from the app
- In the Android quick settings, tap the "screen record" tile
- Toggle the "device audio" switch to on
- Start recording, while tapping the screen in hello-oboe to produce sound

**Expected behavior**

- Watch the recorded video --> we should hear sound as it was played realtime

**Actual behavior**

- Watch the recorded video --> no sound captured

**Device**

Reproduced on:
- Pixel 8
- Pixel 4a 5G

**Any additional context**

Other Oboe samples apps feature the same issue.
It's interesting to note that on Pixel 8, audio is captured in Koala Sampler, which uses Oboe.

**Comment by philburk** [comment]
This is being tracked internally at [b/300121986](http://b/300121986) | P2 | AAudio MMAP not captured in Screen Recording

If AAudio is using Legacy then it can be captured.

**Comment by meteaurestudios** [comment]
Thanks for the update Phil. Any chance we can follow it from a ticket or something ?

**Comment by philburk** [comment]
There was a partial fix in Android 15. If Screen Recording is started,
then an Oboe/AAudio stream is opened,
then AAudio will use Legacy mode. So the audio will be recorded.

If the order is reversed, and the Oboe/AAudio stream is opened before the Screen Recording is started,
then the stream is already MMAP and will not be recorded. We are working on fixing that for a future release.

**Comment by meteaurestudios** [comment]
Ok, thanks for the tip on the partial fix. I'll try that when I'll update to Android 15 :)
