### ISSUE TITLE
don't use FLOAT on Vivo devices before M

### ISSUE THREAD

**Issue by philburk** [google/oboe#201]
It was not properly supported. Use PCM16 or reject.

Try  __system_property_get("ro.product.manufacturer", buf);

See https://www.google.com/url?q=https://crbug.com/737188

**Comment by philburk** [comment]
After the flowgraph code is in we can convert float=>int16 on those devices.
Also see related code at:
https://github.com/google/oboe/blob/master/src/opensles/AudioOutputStreamOpenSLES.cpp#L119

**Comment by dturner** [comment]
We need a check in the stream open method: 

If device == Vivo && android version <= M &&  requested format is float then: 
return InvalidFormat

Longer term we can do float->int16 conversion using flowgraph

**Comment by philburk** [comment]
Fix as part of https://github.com/google/oboe/issues/493

**Comment by gkasten** [comment]
Can this be marked Closed? (see Jun 11 above)

**Comment by philburk** [comment]
We can do float to int16 conversion now. But we need to recognize vivo devices.
What can we query to detect a vivo device?

If anyone has a Vivo device running Lollipop, please enter:

    adb shell getprop > vivoprops.txt

and then attach the vivoprops.txt file to this bug. Thanks.

**Comment by robertwu1** [comment]
We can use either ro.product.brand=vivo or ro.product.manufacturer=vivo

**Comment by robertwu1** [comment]
See https://github.com/czy1121/settingscompat/blob/master/roms/vivo.txt
