### ISSUE TITLE
How to import iolib/parselib 

### ISSUE THREAD

**Issue by miteshsondhi** [google/oboe#2022]
Hi, First I want thanks google for creating this awesome project. I followed every step and looking in samples for days but after all the steps I am only able to import oboe/Oboe.h but in samples like drumthumbper they use player/SimpleMultiPlayer.h and stream/MemInputStream.h. How can I use iolib/parselib in my project please help.

**Comment by robertwu1** [comment]
Take a look at the [CMakeLists.txt](https://github.com/google/oboe/blob/main/samples/drumthumper/src/main/cpp/CMakeLists.txt) for DrumThumper.

Below are the critical lines.

~~~
set (PARSELIB_DIR ../../../../oboe/samples/parselib)
set (IOLIB_DIR ../../../../oboe/samples/iolib)

include(${PARSELIB_DIR}/src/main/cpp/CMakeLists.txt)
include(${IOLIB_DIR}/src/main/cpp/CMakeLists.txt)

include_directories(
        ${PARSELIB_DIR}/src/main/cpp
        ${IOLIB_DIR}/src/main/cpp)
~~~

With these lines, you should be able to use player/SimpleMultiPlayer.h and stream/MemInputStream.h

**Comment by robertwu1** [comment]
Closing since question is answered
