### ISSUE TITLE
sample Buzzing and low pitched

### ISSUE THREAD

**Issue by youlisse** [google/oboe#2039]
I just want to pass a wav audio with cpp, but the sound is down pitch with an high frequency that buzz in my ears, I just don't get it sorry ...
my sample is 48khz 16 bit float pcm 

#include <jni.h>
#include <oboe/Oboe.h>
#include <android/log.h>
#include <vector>
#include <memory>
#include <cstring>
#include <iostream>
#include <sstream>

#define LOG_TAG "WavAudioPlayer"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

struct WavHeader {
    char riffHeader[4];  // Should be "RIFF"
    uint32_t fileSize;
    char waveHeader[4];  // Should be "WAVE"
    char fmtHeader[4];   // Should be "fmt "
    uint32_t fmtChunkSize;
    uint16_t audioFormat;
    uint16_t numChannels;
    uint32_t sampleRate;
    uint32_t byteRate;
    uint16_t blockAlign;
    uint16_t bitsPerSample;
    char dataHeader[4];  // Should be "data"
    uint32_t dataSize;
};

class WavAudioPlayer : public oboe::AudioStreamCallback {
public:
    std::shared_ptr<oboe::AudioStream> stream;
    std::vector<int16_t> audioBuffer; // Buffer to hold audio data
    size_t bufferIndex = 0; // Current position in the audio buffer
    WavHeader header;

    WavAudioPlayer(const std::vector<int16_t>& audioData, int sampleRate, int channelCount) {
        loadWavData(audioData, sampleRate, channelCount);
        createAudioStream();
    }

    ~WavAudioPlayer() {
        stopStream();
    }

    void loadWavData(const std::vector<int16_t>& audioData, int sampleRate, int channelCount) {
        header.sampleRate = sampleRate;
        header.numChannels = channelCount;
        header.bitsPerSample = 16; // Assuming 16 bits per sample for this example
        header.byteRate = sampleRate * channelCount * header.bitsPerSample / 8;
        header.blockAlign = channelCount * header.bitsPerSample / 8;
        header.dataSize = audioData.size() * sizeof(int16_t);
        audioBuffer = audioData;
    }

    void createAudioStream() {
        oboe::AudioStreamBuilder builder;
        builder.setFormat(oboe::AudioFormat::I16);
        builder.setChannelCount(header.numChannels);
        builder.setSampleRate(header.sampleRate);
        builder.setCallback(this);
        builder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
        builder.setSharingMode(oboe::SharingMode::Exclusive);

        oboe::Result result = builder.openStream(stream);
        if (result != oboe::Result::OK) {
            LOGE("Failed to open stream. Error: %s", oboe::convertToText(result));
            return;
        }

        stream->requestStart(); // Start the stream
    }

    oboe::DataCallbackResult onAudioReady(oboe::AudioStream* oboeStream, void* audioData, int32_t numFrames) override {
        auto* outputData = static_cast<int16_t*>(audioData);
        for (int i = 0; i < numFrames; ++i, ++bufferIndex) {
            if (bufferIndex < audioBuffer.size()) {
                outputData[i] = audioBuffer[bufferIndex];
            } else {
                outputData[i] = 0; // Fill remaining with silence if buffer ends
            }
        }
        return bufferIndex < audioBuffer.size() ? oboe::DataCallbackResult::Continue : oboe::DataCallbackResult::Stop;
    }

    void stopStream() {
        if (stream) {
            stream->stop();
            stream->close();
            stream.reset();
        }
    }
};

std::unique_ptr<WavAudioPlayer> audioPlayer;

extern "C"
JNIEXPORT void JNICALL
Java_com_example_appircam_MainActivity_createEngine(JNIEnv *env, jobject thiz) {
    // Initialize any engine components here if necessary
}

extern "C"
JNIEXPORT void JNICALL
Java_com_example_appircam_MainActivity_createUriAudioPlayer(JNIEnv *env, jobject thiz, jbyteArray byteArray, jint sampleRate, jint channelCount) {
    jbyte* nativeByteArray = env->GetByteArrayElements(byteArray, nullptr);
    jsize length = env->GetArrayLength(byteArray);

    if (nativeByteArray == nullptr) {
        LOGE("Failed to get byte array elements");
        return;
    }

    std::vector<int16_t> audioData(length / sizeof(int16_t));
    std::memcpy(audioData.data(), nativeByteArray, length);

    audioPlayer = std::make_unique<WavAudioPlayer>(audioData, sampleRate, channelCount);

    env->ReleaseByteArrayElements(byteArray, nativeByteArray, 0);
}

extern "C"
JNIEXPORT void JNICALL
Java_com_example_appircam_MainActivity_stopAudioPlayer(JNIEnv *env, jobject thiz) {
    if (audioPlayer) {
        audioPlayer->stopStream();
        audioPlayer.reset();
    }
}

an here's my kotlin just for a basic usage 

package com.example.appircam

import android.os.Bundle
import android.widget.Button
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    private lateinit var timerTextView: TextView
    private lateinit var startStopButton: Button
    private var isRunning = false

    companion object {
        init {
            System.loadLibrary("native-lib")
        }
    }

    external fun createEngine()
    external fun createUriAudioPlayer(byteArray: ByteArray, sampleRate: Int, channelCount: Int)
    external fun stopAudioPlayer()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        timerTextView = findViewById(R.id.timerTextView)
        startStopButton = findViewById(R.id.startStopButton)

        createEngine()

        startStopButton.setOnClickListener {
            if (isRunning) {
                stopAudioPlayer()
                isRunning = false
                startStopButton.text = "Start"
            } else {
                playSound()
                isRunning = true
                startStopButton.text = "Stop"
            }
        }
    }

    private fun playSound() {
        val resId = R.raw.soundb
        val inputStream = resources.openRawResource(resId)
        val byteArray = inputStream.readBytes()
        inputStream.close()

        val sampleRate = 48000 // Make sure this matches your actual sample rate
        val channels = 2 // Mono or Stereo

        createUriAudioPlayer(byteArray, sampleRate, channels)
    }
}

**Comment by philburk** [comment]
@youlisse - It looks like at the top level code you are saying that there are two channel for stereo. But in the callback function you were treating it as mono. That would account for it being low-pitched and buzzy. For stereo you need to write two samples for every frame.

**Comment by youlisse** [comment]
@philburk you the goat thx, have a nice day I'm a bit new to android and sound engine dev, u helped me a lot !!

It could help to have an essential minimalist example somewhere on the doc, going through drumThumper was not a good time for a rookie :) 

best regards

**Comment by philburk** [comment]
Check out the MinimalOboe example.
