### ISSUE TITLE
Builds with 16 KB page size

### ISSUE THREAD

**Issue by NLLAPPS** [google/oboe#2041]
Hi, as per [https://developer.android.com/guide/practices/page-sizes](https://developer.android.com/guide/practices/page-sizes), are there  any plans to provide builds with 16 KB page size? If so, are you able to provide timeline?
Thank you

**Comment by philburk** [comment]
We will investigate this.

You could build Oboe from source by cloning the GitHub repo.
Then you could set the build options as you with.

**Comment by philburk** [comment]
Thanks for the question. We have reviewed the docs that you linked to.
It seems that if we build Oboe using 16 KB alignment then it will also work for 4 KB.

We are considering adding this line to our Oboe prebuilt script:

    target_link_options(${CMAKE_PROJECT_NAME} PRIVATE "-Wl,-z,max-page-size=16384")
    
@NLLAPPS - Would that help you?

What is the impact if we do not do that? Does it mean that you would not be able to use Oboe on a 16KB aligned device?!

**Comment by philburk** [comment]
Thanks for the info. I appreciate you sharing your knowledge.

I think -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON is the way to go. But we should not make our prebuilt using a Beta NDK.

Maybe we can declare -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON for now and it will just be ignored by older NDK versions. Then when NDK-r27 is released it will take effect and we can spin a new Oboe release.

We can tell any developer that wants 16KB support to make sure they are using an NDK-r27 or later release.

**Comment by MikuAuahDark** [comment]
Hello, sorry for bumping.

Are there plans on new Oboe releases with 16KB pages? We're relying on Oboe AAR for the binaries. All of our dependencies has been compiled with 16KB page size in mind except Oboe. This result in crash in Android 15 AVD with 16KB pages when trying to load Oboe due to it being compiled with 4KB page size.

**Comment by robertwu1** [comment]
@MikuAuahDark can you help me test #2126? I uploaded a test prefab below.[oboe-1.9.2.zip](https://github.com/user-attachments/files/18158804/oboe-1.9.2.zip)

**Comment by MikuAuahDark** [comment]
Quick test with AVD with 16KB page size and the prefab seems to work.

**Comment by robertwu1** [comment]
Great! Thanks for confirming!
