### ISSUE TITLE
Is there any way to detach a faulty oboe program or insufficient memory for it to process?

### ISSUE THREAD

**Issue by nguyenquynh201** [google/oboe#2055]
Hello, I'm currently having a problem. While I was recording, suddenly the oboe program got an error. It seems like there isn't enough memory for the oboe to execute, but I don't receive any error messages from the oboe. Is there any way to fix it? I can detach when the oboe fails, for example there is no sound in the headphones, etc

**Comment by philburk** [comment]
We need more information.

> suddenly the oboe program got an error.

What app were you using?
On what device?
On what version of Android?
What was the error?
Did Oboe return an error code?
Did it crash?
Was there anything interesting in the logcat?
How log did it record before failing?

>  I can detach when the oboe fails, 

What do you mean by detach?

If you are recording to memory then it can use a lot of memory and run out.
You may want to save the audio to SSD storage as you record.

If the device had been running for a long time it may be in a low memory condition. Rebooting may help.

**Comment by nguyenquynh201** [comment]
Thank you for your response. I will provide some necessary information.

Currently, my application is a recording app using Oboe to manage audio and DeepAR to capture images during recording.

The devices I am encountering issues with are Samsung SM-A325F and Redmi 2201117SG, among others.

During the recording process, the console log reports errors as shown in the image I provided. I suspect that it might be due to insufficient memory to adequately support Oboe's execution. However, this is just a guess. I would greatly appreciate your assistance with this issue.
<img width="991" alt="image" src="https://github.com/google/oboe/assets/80728170/c6cf9f6f-af50-4343-8653-40b3e2b61b4e">

**Comment by philburk** [comment]
You only answered a few of my questions.

> console log reports errors as shown in the provided image. 

Messages on the Console are not a problem. May programs print alarming messages even when everything is fine.
If the app runs well and the audio sounds good then maybe there is not a problem.

Maybe express the Issue in terms of "what you expected" and "what actually happened".
See bug template [here](https://github.com/google/oboe/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=).

By the way, Oboe does not do compression. So this probably is  not the place to report bugs with Codecs.  Is Oboe or AAudio failing in some way?

**Comment by philburk** [comment]
Closing because this seems unrelated to Oboe and due to inactivity.
