### ISSUE TITLE
Can't get Low Latency 

### ISSUE THREAD

**Issue by simdax** [google/oboe#2057]
Hello !

I'm trying the last commit on branch main (9f3e628a)

I'm launching minimalOboe on a virtual Device
(pixel 3a API43)

Performance Mode fails to be **LowLatency**

![image](https://github.com/google/oboe/assets/2458806/67fe2b21-a93e-4559-9dfd-b25a1191a63e)

PerfMode goes from 12 to 10 (LOWLATENCY to None)

Same thing on LiveEffect.

Any clue?
Thank You!

**Comment by simdax** [comment]
In OboeTester, I see also that I can't get low latency
![image](https://github.com/google/oboe/assets/2458806/b5564946-132e-4553-b6ff-7f68f3054b91)

**Comment by philburk** [comment]
Sorry. The emulator is a virtual machine and does not support the LOW_LATENCY mode.

For high performance modes you will need to test on physical hardware.

The emulators are mostly for checking API version compatibility and layout issues.
