### ISSUE TITLE
Glitch in background, exclusive mode

### ISSUE THREAD

**Issue by simdax** [google/oboe#2062]
Hello.

I'm working on a plugin that should be open when my application runs in background.

I use a fullduplex stream, as i filter the input from the default microphone. The idea is to keep the app alive while recording the surrounding sound.

For now, all is ok when I run my plugin from the app. But when going in background the stream becomes glitchy.

I'm not sure also to really be able to be able to start a stream with exclusive mode. Do I need to do something special?

Thank you!

**Comment by robertwu1** [comment]
Try the LiveEffect sample. It currently does not run in the background so I created a Pull Request (#2063). It seems to work fine in the background with the minor change with that PR.

**Comment by simdax** [comment]
As I mentionned it here https://github.com/google/oboe/pull/2063#issuecomment-2218522159
It seems that passing in background make some few glitches.

**Comment by philburk** [comment]
If your callback function does a lot of processing then there may be a problem running in the background.
That is because the CPU gives lower priority to background tasks and lowers the CPU frequency.

What device are you on?
OS version?
etcetera

**Comment by robertwu1** [comment]
See https://developer.android.com/develop/background-work/services/foreground-services. Starting for Android U, foreground services are required.

**Comment by simdax** [comment]
It would be nice to have a background example, with the foreground service.
I'm not sure how to keep enough CPU for my plugin processing

**Comment by robertwu1** [comment]
I filed issue #2065
