### ISSUE TITLE
Why doesn't convertPcm16ToFloat do `source[i] / 32768.0f`?

### ISSUE THREAD

**Issue by dturner** [google/oboe#21]
This line of code (from https://github.com/google/oboe/blob/master/src/common/Utilities.cpp#L43)

`destination[i] = source[i] * (1.0f / 32768.0f);`

Why not just use:

`source[i] / 32768.0f`

**Comment by dturner** [comment]
Originally asked by mnaganov

**Comment by philburk** [comment]
A multiply is generally much faster than a divide.
Some compilers will pre-calculate the 1/x at compile time and then compile a multiply for the first line.  But they will compile a divide for the second line.

It might look better to define a const float kScaleI16ToFloat = (1.0f/32768.0f)
and then dest = source * kScaleI16ToFloat;
