### ISSUE TITLE
Tracing underruns on API 24

### ISSUE THREAD

**Issue by jbloit** [google/oboe#216]
Hi, 
I'm trying to trace underruns on a device running API 24. From looking into the oboe's source, I seem to understand that getXRunCount() is not supported for that API level. Am I understanding right? Is there an alternative technique to detect underruns on lower level APIs? 
Thank you

**Comment by dturner** [comment]
Yes you're understanding right. 

For API 24 the alternative method would be to use `acquireJavaProxy` to get the `AudioTrack` object for the OpenSL ES stream, then call `getUnderrunCount`.

SimpleSynth has an example of this: 

C++ side: https://github.com/googlesamples/android-audio-high-performance/blob/master/SimpleSynth/app/src/main/cpp/audio_player.cc#L306
Java side: https://github.com/googlesamples/android-audio-high-performance/blob/master/SimpleSynth/app/src/main/java/com/example/simplesynth/MainActivity.java#L278
