### ISSUE TITLE
Runtime exception caused by getExclusiveCores()

### ISSUE THREAD

**Issue by jbloit** [google/oboe#221]
Hi,

I'm trying to fix glitches in my own oboe-powered apps, and trying to set thread affinity in the audio callback. I've been trying to run the simple synth and megaDrone examples on an API-24 device (Samsung SM-G920F). Each time I run the apps,  they crash when trying to run getExclusiveCores():

Caused by: java.lang.RuntimeException: Unknown error
        at android.os.Process.getExclusiveCores(Native Method)
        at com.example.oboe.megadrone.MainActivity.getExclusiveCores(MainActivity.java:77)
        at com.example.oboe.megadrone.MainActivity.onStart(MainActivity.java:42)

Are you able to reproduce? Any hint to help? (This is probably not a strictly oboe issue though, right?)

Thank you.

**Comment by jbloit** [comment]
Hmm, that's puzzling. I just reseted the device to make sure, and I do have
Nougat. I asked Samsung support, they say Nougat is the latest available
version. Samsung support refers to this website to check the version:

https://www.gsmarena.com/samsung_galaxy_s6-6849.php#g920f which also says
Nougat is available too... Not sure where the difference lies.

**Comment by dturner** [comment]
My device suddenly found the Nougat update :) I'll get it updated and see if I can repro. My guess is that it's a Samsung specific bug. 

Possibly related: https://stackoverflow.com/questions/48827532/process-getexclusivecores-throws-exception-on-certain-devices

**Comment by philburk** [comment]
There should be a CTS test for this.

**Comment by dturner** [comment]
I am able to reproduce this issue. I have filed a bug (b/116704040) requesting a CTS test. 

In the mean time developer guidance should be to always wrap calls to `getExclusiveCores` in try/catch checking for a RuntimeException. I will update the sample accordingly. 

Thanks for spotting this @jbloit
