### ISSUE TITLE
[LiveEffect] No output on Android P using wired headset

### ISSUE THREAD

**Issue by antonkovalyov351** [google/oboe#222]
Hi, 
I am developing Android app that uses OpenSL ES lib. I used samples from `googlesamples/android-ndk`. There I found out about `oboe` project.  

I faced an issue with audio recording on Google Pixel running Android P. Looks like it doesn't work for `android-ndk/native-audio` and `oboe` samples when recording using **wired headset**.

Here are results of my tests:

_Google Pixel XL / Android P._

**OpenSL ES:**
 - IN: headset  + OUT: headset = NO OUTPUT [[Logs](https://pastecode.xyz/view/67d62958)]
 - IN: phone mic  + OUT: headset = NO OUTPUT 
 - IN: phone mic  + OUT: phone speaker = ALL GOOD

**AAudio:**
 - IN: headset  + OUT: headset = NO OUTPUT [[Logs]](https://pastecode.xyz/view/67c883a8)
 - IN: phone mic  + OUT: headset = ALL GOOD
 - IN: phone mic  + OUT: phone speaker = ALL GOOD

_Samsung S8+ / Android 8.0.0._
All works as expected.

Any help will be appreciated.

**Comment by philburk** [comment]
Thanks for the report. We'll try to help.

Does your wired headset work if you try to do voice recognition in the search bar? Press the microphone icon.

What brand of wired headset are you using?

Are you selecting the devices manually or using the default routing?

Does it work better after a reboot?

**Comment by dturner** [comment]
Just tested on a Pixel XL running Android Pie PPR2.180905.006 using Google branded wired headset. All tests were successful. Is it a proprietary Samsung headset? Maybe there's an intermittent connection on the 3.5mm jack?

**Comment by antonkovalyov351** [comment]
@philburk @dturner Thanks for quick response!

---

> What brand of wired headset are you using?

AKG headset from Samsung S9+ box.

> Does your wired headset work if you try to do voice recognition in the search bar?

Headset doesn't work with voice recognition both on Google search and Youtube. Playback works on Youtube.

> Are you selecting the devices manually or using the default routing?

In my tests `IN` and `OUT` means selected devices(phone's or headset). Also default selection doesn't work with this headset.

> Does it work better after a reboot?

Nothing changes after reboot.

> Is it a proprietary Samsung headset? Maybe there's an intermittent connection on the 3.5mm jack?

Yes, this headset is from Samsung S9 box.

I tested on: 
Samsung S8+ / Android 8.0.0
Samsung S9+ / Android 8.0.0
Xiaomi Mi A1 / Android 8.1.0
AKG headset works for these devices.

I faced this issue only with Google Pixel and Google Pixel XL running Android P (PPR2.180905.006)

Today I tested with different headset (Steelseries) and it worked for all cases.

---
**Questions:**
Is it known issue?
Does it Android P issue or Google Pixel issue?
Any workarounds for this?
Can I detect if headset is compatible using Android SDK/NDK?

---

Thanks in advance!

**Comment by dturner** [comment]
> Is it a known issue?

Pretty sure it's not. 

> Today I tested with different headset (Steelseries) and it worked for all cases.

So on Pixel devices you were able to record and play audio through the Steelseries headset using the AudioEffect oboe sample - is that correct? 

If so, it implies there's something specific about the AKG headset and/or the way Pixel devices handle it. Would it be possible to get the logcat output from when you connect the AKG headset?

**Comment by dturner** [comment]
Thanks. I can't see anything obviously wrong but maybe @philburk will be able to. 

Please could you post the Steelseries logcat output as well and we can do a diff on them.

**Comment by antonkovalyov351** [comment]
Logs using Steelseries: https://pastecode.xyz/view/741931ba

**Comment by dturner** [comment]
After the line 

> 09-20 11:38:43.752 629-9018/? E/audio_hw_primary: offload_thread_loop: Compress handle is NULL

Steelseries has the following lines: 

> 09-20 11:38:43.762 903-903/? I/Telecom: WiredHeadsetManager: ACTION_HEADSET_PLUG event, plugged in: true, : WHC.oADA@AKE
09-20 11:38:43.762 903-1537/? I/Telecom: CallAudioRouteStateMachine: Message received: CONNECT_WIRED_HEADSET=1, arg1=0: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET@AKE
    QuiescentEarpieceRoute: Processing message CONNECT_WIRED_HEADSET: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET@AKE
09-20 11:38:43.763 903-1537/? I/Telecom: Logging.Events: Non-call EVENT: AUDIO_ROUTE, Wired headset connected: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET@AKE
09-20 11:38:43.765 629-3079/? W/DeviceHAL: Error from HAL Device in function open_input_stream: Invalid argument
09-20 11:38:43.766 903-1537/? I/Telecom: CallAudioRouteStateMachine: Message received: SWITCH_HEADSET=1003, arg1=0: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AKE
    QuiescentEarpieceRoute: Processing message SWITCH_HEADSET: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AKE
09-20 11:38:43.767 903-1537/? I/Telecom: Logging.Events: Non-call EVENT: AUDIO_ROUTE, Leaving state QuiescentEarpieceRoute: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AKE
    Logging.Events: Non-call EVENT: AUDIO_ROUTE, Entering state QuiescentHeadsetRoute: WHC.oADA->CARSM.pM_CONNECT_WIRED_HEADSET->CARSM.pM_SWITCH_HEADSET@AKE

Looks like with the AKG headset the `WiredHeadsetManager` isn't picking up the headset "plug in" event. I'll show this to some folks to see if there's an obvious answer/solution.

**Comment by dturner** [comment]
Any chance of a photo of the AKG headset, including the 3.5mm jack, also a side-by-side photo of the 3.5mm jack on the Steelseries? 

My suspicion is that this is hardware related and could be caused by slight differences in the TRRS plug dimensions.

**Comment by antonkovalyov351** [comment]
![img_20180920_134226](https://user-images.githubusercontent.com/11294259/45813504-7913ca80-bcdb-11e8-90c4-e061bf7afbca.jpg)
![img_20180920_134255](https://user-images.githubusercontent.com/11294259/45813505-7913ca80-bcdb-11e8-9e3e-421cf4742c4a.jpg)
![img_20180920_134311](https://user-images.githubusercontent.com/11294259/45813507-79ac6100-bcdb-11e8-8e36-79e6543acbcc.jpg)

**Comment by antonkovalyov351** [comment]
Today I flashed Android 8.1.0 on Google Pixel and got same result - No output. 
So I believe this is purely hardware issue and AKG headset and Google phones are not compatible.
So I only have one question left: **can I check headset compatibility using Android SDK?**
In any case this issue can be close. 
Thanks for your help!

**Comment by dturner** [comment]
This sounds like an Android bug. Will file internally. 

> can I check headset compatibility using Android SDK?

No. Headsets should just work.

**Comment by stereomatch** [comment]
antonkovalyov351,

>Samsung S8+ / Android 8.0.0
>Samsung S9+ / Android 8.0.0
>Xiaomi Mi A1 / Android 8.1.0
>AKG headset works for these devices.

There is a known issue for headsets between different manufacturers - I forget what the specifics are, but for the longest time one had to be careful in using headsets for one android device with another manufacturer's android device - some did not work.  Basically the microphone on the headset would not work.  So to be sure you would first test it on the device.

You would have to test this headset on your Pixel when running Oreo, and then running Pie - this would confirm if the issue is with Pie, or just a hardware issue with Pixel (which is possible) - either for device faulty issue, or because the issue with one manufacturer's headset not working in another.

In any case, if a second headset does work with the Pixel, it is unlikely to be a Pixel or Pie issue.

**Comment by antonkovalyov351** [comment]
@stereomatch Thanks for your response.

My mistake was that I didn't tested all cases before creating issue. 
After some time I figured out to test different headset with **Pixel** on **Pie** and AKG headset with **Pixel** on **Oreo**.
The result was that AKG headset is not compatible with **Pixel** phones and it does not depend on **Android version**.

Thanks for your time anyway.

**Comment by stereomatch** [comment]
Here is a good webpage which documents all the differences - between TRRS and TRS and between android and iPhone variations:

https://www.wildmountainechoes.com/equipment/audio-recording-with-a-smartphone/

The relevant section which may explain your particular issue - how two plugs each with same pin shape/number of pins can be incompatible depending on android device.


>However, there are also differences in the TRRS jacks, in the location of the ground and mic connections:
>
>Diagram of OMTP and CTIA plugs
>
>Differences in wiring between the OMTP (Sony, older Android) and CTIA (Apple, newer Android) plugs.  CTIA is also called AJH.  Note that there is only one mic input, so all input will be mono.  Right and Left refer to headphone output.
>
>This difference is something you need to be aware of, and make sure that any microphone, headset, or adapter is compatible with your phone.  Unfortunately, there is no way to tell from the outside which is the proper jack for your device.  However, the CTIA (Apple) version is becoming the norm, so Apple-compatible devices now work on many recent android phones.  Be sure to check the descriptions to make sure your device is compatible.  For more information on the wiring of various plugs, see here.

For the OMTP and CTIA at least, the difference is that the microphone and ground pins are swapped.

If the headset came from the Samsung S9+, then perhaps that conforms to the newer CTIA standard for android devices.  While your Google Pixel maybe expecting OMTP - if the Pixel is older than the Samsung S9+.

You could try making a converter cable by buying a TRRS extender cable and swapping the mic and ground wires.  Or you can just buy one of these OMTP to CTIA converter cables:

https://www.amazon.com/IDS-Home-Universal-Earphone-Converter/dp/B06WP89QRQ
IDS Home Universal 3.5mm OMTP to CTIA Earphone Adapter Gold Plated Stereo Jack Converter, Black 

https://www.amazon.com/Universal-3-5mm-Earphone-Adapter-Converter/dp/B06W58F7HG
IDS Home Universal 3.5mm OMTP to CTIA Earphone Adapter Converter Cable

https://www.amazon.com/kenable-Adapter-Cable-Convert-Headsets/dp/B01M34NYE3
kenable PRO 4 Pole 3.5 Adapter Cable Convert Headsets from OMTP to CTIA/AHJ

**Comment by dturner** [comment]
Closing because this isn't related to Oboe. Thanks for all your work investigating and documenting the issue though - likely to be useful to others who run into the same issue.
