### ISSUE TITLE
Flaky tests, possibly related to the screen being off

### ISSUE THREAD

**Issue by dturner** [google/oboe#224]
When I'm running tests I regularly get one or two failed tests, which will then pass the next time round. 

For example: 

[ RUN      ] StreamStates.InputStreamLeftRunningShouldNotInterfereWithNextOpen
Failure
Expected equality of these values:
 r
Which is: 4-byte object <81-FC FF-FF>
Result::OK
Which is: 4-byte object <00-00 00-00>
requestStart returned: ErrorInvalidState

**Comment by dturner** [comment]
May be related to internal bug concerning volume issues/mutexes

**Comment by philburk** [comment]
I get many error like this if I run the Oboe unit tests with the screen turned off.
I think it is failing to open the INPUT streams for security reasons.

**Comment by robertwu1** [comment]
I've tested this multiple times on a Pixel 6 with Android T and a Pixel 3 with Android Q. Works as expected. Closing bug
