### ISSUE TITLE
build of tests fails, SDK location not found

### ISSUE THREAD

**Issue by philburk** [google/oboe#225]
I cannot build the tests based on "oboe/tests/README.md"

I entered:
    export ANDROID_NDK=/Users/philburk/Library/Android/sdk/ndk-bundle
    export PATH=$PATH:/Users/philburk/Library/Android/sdk/cmake/3.6.4111459/bin
    ./run_tests.sh 

And got a lot of gradle messages followed by:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':app'.
> > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

**Comment by dturner** [comment]
I will update the docs

**Comment by philburk** [comment]
I defined ANDROID_HOME and was able to run the tests.

    export ANDROID_HOME=$HOME/Library/Android/sdk

**Comment by philburk** [comment]
I added some notes in a README.md here:
https://github.com/google/oboe/blob/master/tests/README.md
