### ISSUE TITLE
Provide Oboe binary distribution

### ISSUE THREAD

**Issue by felipecsl** [google/oboe#230]
Discussion started on https://github.com/felipecsl/ktnes/issues/4

Instead of having users clone Oboe in order to use it, It would be desirable to have Oboe distributed as an `aar` package for Android app consumption, since that supports including the precompiled `libOboe.so` files for each supported native platform along with header files.

**Comment by dturner** [comment]
This has also been requested by the JUCE team. Raising priority.

**Comment by philburk** [comment]
1. Do we want to provide statically linked or dynamically linked libraries?
2. What are some of the potential problems?
3. Are there issues with statically allocating Oboe objects and then dynamically linking with an Oboe library that may have differently sized objects?
4. Are there any internal APIs that need to be exposed?
5. Can we release a Universal binary or do we need to release multiple libraries?

**Comment by alanwang4523** [comment]
> This has also been requested by the JUCE team. Raising priority.
I create a project [OboeLib](OboeLib) to build liboboe.so and liboboe.a

https://github.com/alanwang4523/OboeLib

**Comment by alanwang4523** [comment]
@dturner @philburk 

I create a project [OboeLib](https://github.com/alanwang4523/OboeLib) to build liboboe.so and liboboe.a for Oboe

https://github.com/alanwang4523/OboeLib

**Comment by dturner** [comment]
Investigate using https://github.com/google/prefab

Related issue on NDK site: https://github.com/android/ndk/issues/916#issuecomment-566271340

**Comment by DanAlbert** [comment]
Oboe was actually the first package to be requested by a user :) https://github.com/google/prefab/issues/27

@dturner feel free to put a meeting on my calendar if that'll help.

**Comment by dturner** [comment]
Many thanks @DanAlbert. I will be in MTV next week and have scheduled a meeting for Monday to discuss.
