### ISSUE TITLE
Publish a list of Android device latency

### ISSUE THREAD

**Issue by dturner** [google/oboe#235]
List should include those that conform to the Pro audio spec (<20ms round-trip) and those that are "close but no cigar" :)

**Comment by JonChristensen** [comment]
Do you happen to have a non-official but share with me via a back channel version of this list already?

**Comment by dturner** [comment]
Unfortunately getting the devices for testing is proving problematic. The two popular devices which I have tested so far are: 

Samsung Galaxy Note 9 (Exynos): 19.33ms
Samsung Galaxy S9 (Exynos): 20.95ms

**Comment by calexHG** [comment]
@JonChristensen 

...also, if you haven't seen it yet, AOSP maintains an evolutionary list documenting the latencies achievable by the Google-released smartphones under various configurations, across the existing history of Android API / OS releases.

https://source.android.com/devices/audio/latency/measurements#examples

**Comment by suyashjoshi** [comment]
I have Samsung Galaxy S8, let me know how to test and happy to share the result.

**Comment by philburk** [comment]
We are gathering latency information from third party devices. But the information belongs to the manufacturers. So we cannot publish it.

Someone else is welcome to create a list based on measurements using OboeTester.
