### ISSUE TITLE
Convert methods could return a std::string and numeric value

### ISSUE THREAD

**Issue by dturner** [google/oboe#24]
See discussion here https://github.com/google/oboe/pull/18#discussion_r153951257

**Comment by philburk** [comment]
This would require returning a std::string, which would have to be deleted.

**Comment by philburk** [comment]
If a user wants to print the number then they can do this:
LOG("foo() returned %s(d)", convertToText(result), result);

**Comment by dturner** [comment]
C++17 is better at declaring compile time values but only C++14 is supported in AS.
