### ISSUE TITLE
Input timestamp error

### ISSUE THREAD

**Issue by antonkovalyov351** [google/oboe#240]
I use **LiveEffect** sample.

**Device:** Samsung S8+ and S9+ / Android 8.0.0
**Input and output sources:** Auto select.
**API:** AAudio

When I try to use method `getTimestamp()` on `recordingStream` inside `onAudioReady` callback I receive `ErrorInvalidState` while it works OK for `playbackStream`. Record stream state: `starting`, play stream state: `starting` and never changes to `started`.

On **Xiaomi Mi A1** running **Android 8.1.0** states are: Record stream state: `started`, play stream state: `started`. Input timestamp doesn't work.

When I switch to **Google Pixel XL** running **Android 9.0** both (recording and playback) timestamps are present. Record stream state: `started`, play stream state: `started`.

Are there any limitations for `getTimestamp()` method? 

Thanks in advance!

**Comment by dturner** [comment]
AFAIK `getTimestamp` should work on both recording and playback streams, however, I don't believe there's a CTS tests which verifies this.  

Related: The Android CDD Audio Latency section: https://source.android.com/compatibility/9/android-9-cdd.html#5_6_audio_latency

Specifies that the accuracy of `getTimestamp` is strongly recommended to be +/-1ms (although again there's no CTS test). 

Phil and I to discuss.

**Comment by dturner** [comment]
I will test on S9. Strange that AAudio is being used on Android 8.0 since it's only recommended from 8.1 onwards.

**Comment by stefansjs** [comment]
I'm seeing a similar error here on my OnePlus 6 on Android 10. Has there been any progress internally on this? Is there any workaround?

I've been printing to the console to see the state, and I get log lines like this one for every callback
```cpp
__android_log_print(ANDROID_LOG_WARN, TAG,
    "Couldn't get timestamp from %s: %s. state: %s",
    convertToText(mAudioStream->getDirection()),
    convertToText(result.error()),
    convertToText(mAudioStream->getState())
    );
```

```
Couldn't get timestamp from Input: ErrorInvalidState. state: Started
```

Naturally when I try to debug into the function callbacks are called too quickly to produce anything useful, but it does look like the input stream is trying to return OK.

**Comment by stefansjs** [comment]
It looks like in my case it comes from the underlying AAudio implementation. I can't understand why AAudio can report that the stream is in a `started` state, but getTimestamp complains about the state.

![Screen Shot 2021-01-28 at 3 14 16 PM](https://user-images.githubusercontent.com/5892043/106210762-4cf69700-617c-11eb-802d-563683c057c4.png)

**Comment by andrew-k-21-12** [comment]
@stefansjs do you encounter this error after initial `requestStart()` of your stream or there are some stop/start calls for the stream before you are trying to get the timestamp?

**Comment by stefansjs** [comment]
I'm calling getTimestamp from callbacks. Initially I thought it was some sort of startup racing behavior, but if I log (every 1000 occurrences) it happens every callback. I haven't been able to get the timestamp at all, but just for input callbacks

**Comment by philburk** [comment]
The getTimestamp() call is not implemented for low latency streams on the Legacy data path. b/30557134
But it is implemented for MMAP.

Also some devices may not support it properly. We are adding tests to improve support.

This is not an Oboe bug. If the underlying AAudio supports it then Oboe will pass it through. If not then there is no workaround that we can provide. Luckily input latency tends to be low.

**Comment by stefansjs** [comment]
Perhaps it would be more clear to return `ErrorUnimplemented` rather than a state error.
