### ISSUE TITLE
oboe musical game codelab points to dead links on github

### ISSUE THREAD

**Issue by johnwpoliver** [google/oboe#241]
https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html#0

I found at least 3 links which took me to a 404 Not found, including 

https://github.com/google/oboe/blob/master/FullGuide.md#audio-streams
https://github.com/google/oboe/blob/master/FullGuide.md#setting-performance-mode

**Comment by dturner** [comment]
Many thanks for filing this issue. All affected links have now been updated to point to the correct documentation.
