### ISSUE TITLE
Oboe will not solve mainstream poor audio latency on Androids 

### ISSUE THREAD

**Issue by LifeIsStrange** [google/oboe#244]
Thank you for this project, the issue is that it's opt-in, most application will never be updated to use it and therefore benefit from it.

That is a step in the right direction but you should solve audio latency by default thanks to a modern actively developped audio software pile that would be porting the Linux alsa sound server/Jack + pulseaudio and making it the DEFAULT instead of audioflinger.

Facts: Samsung use the Jack sound server for their Tyzen OS.
Collabora already ported alsa some years ago for you...

Here are empirical data and additional rational reasons such as synergies from merging drivers:  https://arunraghavan.net/2012/01/pulseaudio-vs-audioflinger-fight/

Here are empirical data that show How uncompetitive Android is against Apple on the audio side
https://juce.com/maq

Here is the android issue that need to be prioritarised:
https://issuetracker.google.com/issues/37073168

Music is maybe the main hapiness factor coming from smartphones/tablets, doesn't people merit to have quality music ? And thus Low audio latency ? I'm not aware of a lot of android current roadmap features than can achieve such meaning in the human's lifes.

Also from a marketing/funding point of view, I think that this can increase sales if well marketed, and that you could have sponsorship from Spotify/deezer/etc as they would compete for being able to say  « How we helped making android music quality great (again™).

**Comment by dturner** [comment]
Thanks for bringing pulseaudio to our attention. I have added the relevant engineers onto the Android issue for review.
