### ISSUE TITLE
Crash on app start (java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader)

### ISSUE THREAD

**Issue by Ashkan-Sarlak** [google/oboe#245]
Hi,

I'm trying to create the rhythm game as it is explained in the codelab. When I'm launching the app (without adding any code, just launching it for the first time), it crashes at `System.loadLibrary("native-lib");` in the `MainActivity`.

The error log:
`10-15 12:57:49.148 16745-16745/com.google.oboe.sample.rhythmgame E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.oboe.sample.rhythmgame, PID: 16745
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.oboe.sample.rhythmgame-2/base.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.oboe.sample.rhythmgame-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.oboe.sample.rhythmgame-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libnative-lib.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.google.oboe.sample.rhythmgame.MainActivity.<clinit>(MainActivity.java:28)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2365)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:234)
        at android.app.ActivityThread.main(ActivityThread.java:5526)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Also I had [this issue](https://github.com/google/filament/issues/15) when trying to build the app which I solved it(?) by trying [this comment](https://github.com/google/filament/issues/15#issuecomment-426259512): creating an empty directory.

Any ideas on this?

**Comment by philburk** [comment]
Thanks for reporting this.
What version of Android are you using?
What device are you running on?

**Comment by Ashkan-Sarlak** [comment]
Thanks Phil.
It's a Sony D6502 (Xperia Z2) with Android 6.0.1(API 23)

**Comment by dturner** [comment]
Sounds like the native build is failing. Are there any errors in the logs during the build? Could you try doing a full clean/build please. 

My suspicion is that the build is attempting to build for the MIPS architecture and failing, once failed the .so isn't built for your target architecture and hence the error at runtime.

**Comment by dturner** [comment]
I just pushed https://github.com/google/oboe/commit/59b75d30f3588c8c69768d2f4d99676bfa1cf77f which might fix it - please could you retest?

**Comment by Ashkan-Sarlak** [comment]
Thank you Don
I pulled the master and now this error occurs during the build phase:
`Unsupported method: NativeArtifact.getSourceFolders().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.`

So I upgraded gradle plugin to latest version `3.3.0-alpha13`. But the error persists.

However I changed the apiFilter like you did on `io18codelab` branch and now the app launches. But the screen (gray area) flashes like hell. I don't know if this is the intended behavior or not. At least now I can continue the codelab.

By the way can you a propose a better way to handle [mips64el-linux-android issue](https://github.com/google/filament/issues/15) I wrote above? The quirky "solution" of making an empty directory is just suppressing the error I think and may cause a problem later on.

**Comment by philburk** [comment]
The flashing bug is now in #247.
Can this UnsatisfiedLinkError bug be closed?
