### ISSUE TITLE
RhythmGame - Codelab branch: Screen flashes after launching the template app

### ISSUE THREAD

**Issue by Ashkan-Sarlak** [google/oboe#247]
Hi
I'm following [this codelab](https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html#1) and after [fixing some issues](https://github.com/google/oboe/issues/245), without adding any extra code, I launched the template app which is quite like the one you can see on the codelab site, except that the gray area flashes incessantly. You can see it in this gif:
 
![ezgif com-optimize](https://user-images.githubusercontent.com/5101469/47034383-13a0e580-d184-11e8-8e3c-b4d9e1b34c74.gif)

The device spec I'm running the app is:
Sony Xperia Z2 (D6502)
Android 6.0.1
Build number 23.5.A.1.291

Android Studio 3.1.4
Build #AI-173.4907809, built on July 24, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.6

**Comment by robertwu1** [comment]
I can't repo this. Closing this.
