### ISSUE TITLE
convert methods should return a std::string rather than const char *

### ISSUE THREAD

**Issue by dturner** [google/oboe#25]
const char * is old school C

**Comment by philburk** [comment]
Who deletes the std::string?

**Comment by philburk** [comment]
const char * may be old school but it has advantages.
The caller does not have to delete the string.
So it can easily be used in logs.
Also std::string may cause a memory allocation, which should be avoided in real-time audio.

**Comment by philburk** [comment]
It seems like we are taking something very simple and converting it to something more complex.
If we want to add the result code to the string, we could could add a convenience function that called the simple (const char *) function then added the result code and returned a std::string.
Or the app could do that very easily.

**Comment by dturner** [comment]
The motivation isn't primarily because we want to return a result code (although it does help with that), it's that users of the Oboe library may prefer to receive a std::string over a C-style string. 

Some benefits of std::string over C strings: https://embeddedartistry.com/blog/2017/7/24/stdstring-vs-c-strings

As for your point about memory allocation - this is true and we should be very clear in the comments and documentation that the `convertToText` method shouldn't be called in the data callback under normal conditions. 

I've asked some partners for their opinions on what they'd prefer - maybe C-style strings are still en vogue for audio programmers.

**Comment by dturner** [comment]
Things are better in C++17 but Android Studio only supports up to C++14 so closing for now.
