### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by teotigraphix** [google/oboe#253]
Hi,

I am trying to build the samples from the code lab. (well actually using the code lab)

https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html#2

I cannot get pass Run, obviously the project is not building so I have no Run Configurations.

Any idea? I searched found things about this but was wondering why it's not working out of the box.

Windows 10 64
Android Studio 3.2.1
NDK - 18.1.5063045

**Comment by teotigraphix** [comment]
Note that on the dev PC I am using I did not have older versions of the NDK installed, only on my older dev computer.

From what I read on stackoverflow, this has to do with a missing directory in the tool-chains folder. Yes, it is missing.

Is this a case of oversight that something got removed that old time users still have? 'mips64el-linux-android'

**Comment by teotigraphix** [comment]
Ok, excuse my newbness with the NDK here but adding empty directories as such;

**.../android\sdk\ndk-bundle\toolchains\mips64el-linux-android\prebuilt**

Worked, but I always like to know why in a code lab, this would mess up.

Mike

**Comment by dturner** [comment]
Thanks for posting this Mike. I've also run into this in the past, it's a real pain and it shouldn't happen when you're just trying to get up and running with a codelab. I'll try to figure out a code workaround.

**Comment by dturner** [comment]
I'm pretty sure that the issue can be resolved by changing the gradle plugin to 3.2.1 as per https://stackoverflow.com/questions/49892430/android-studio-error-while-building-apk/52945794#52945794

**Comment by teotigraphix** [comment]
Yeah I did this backwards.

But now on to another problem. Once I got the above fixed which it compiles, trying to Run gives me this;

![warning-1](https://user-images.githubusercontent.com/226417/47731388-64134b00-dc3a-11e8-9592-1fbc8c26b42a.PNG)

![fail-1](https://user-images.githubusercontent.com/226417/47731393-6675a500-dc3a-11e8-99b0-8e50d267154c.PNG)

**Comment by teotigraphix** [comment]
Ok, I guess I am having problems because I don't have enough familiarity with NDK gradle.

After searching I added ''armeabi-v7a'' to the abiFilters (I need to research this more).

The app installed on the Nexus but the screen was flashing. Is this project using anything that a Nexus 7 can run? (OpenGL version or something?)

**Comment by dturner** [comment]
Forget that, issue already filed: https://github.com/google/oboe/issues/247

**Comment by dturner** [comment]
It appears I never fixed the `io18codelab` branch. Error is: 

ERROR: No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
This version of the NDK may be incompatible with the Android Gradle plugin version 3.0 or older.
Please use plugin version 3.1 or newer.
Upgrade plugin to version 3.4.0 and sync project

**Comment by dturner** [comment]
Fixed in https://github.com/google/oboe/commit/1823a5293b75a3bbee95327ed1d9837f8e47d0bd
