### ISSUE TITLE
Obtaining optimal value for framesPerBurst from AudioManager

### ISSUE THREAD

**Issue by lukaszkozakiewicz-roli** [google/oboe#254]
Hi,

Following the suggestion from Oboe documentation, we get the default frames per burst value from `AudioManager` by calling `AudioManager::getProperty(AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER)` function. In commit 7dcf25d you removed `AudioStreamBuilder::setDefaultFramesPerBurst()` and you introduced `DefaultStreamValues::FramesPerBurst`. The new API suggests that the value returned by `AudioManager` can be assumed to be constant for a given Android device, so for instance the value will not change when headphones are plugged in or unplugged. Is it therefore safe to cache the value of frames per burst returned? Or should one check the value whenever creating a new stream and should one update `DefaultStreamValues::FramesPerBurst` accordingly?

Lukasz

**Comment by lukaszkozakiewicz-roli** [comment]
Ok, thanks for clarification.

**Comment by philburk** [comment]
Note that if a device supports FAST tracks then the PROPERTY_OUTPUT_FRAMES_PER_BUFFER will give you the optimal size for a FAST track.  But you will not get a FAST track if the sample rate is off or the FAST mixer is full or possibly other reasons.  In that case the buffer size will be too small and you will probably get lots of glitches. This is only a problem with OpenSL ES.
