### ISSUE TITLE
Make Java companion library which encapsulates the native code

### ISSUE THREAD

**Issue by Kisty** [google/oboe#257]
Is it possible to make a library so it's easy to add this to any Java/Kotlin project without knowing about C++ development in Android? Or would that defeat the point of the library due to JNI ovrrhead? Related #230

**Comment by dturner** [comment]
> Or would that defeat the point of the library due to JNI ovrrhead?

Pretty much. If you're using Java to generate your audio then you're best off using `AudioTrack`.
