### ISSUE TITLE
Add document for Android version specific issues.

### ISSUE THREAD

**Issue by philburk** [google/oboe#258]
Add documentation that describes the limitations, bugs and workarounds for each version of Android.

For example:

- AAudio supported after 8.0
- AAudio recommended after 8.1
- When is FLOAT supported in OpenSL ES?

**Comment by dturner** [comment]
Create document which lists Android versions. E.g. 

Oreo 26:
- AAudio introduced

Bugs: 
- PlayerRefBase bug

Marshmallow 23:
Key features
- Float input introduced
Bugs/Workarounds: 


Lollipop 21: 
- Float output introduced

**Comment by dturner** [comment]
Add AndroidVersionHistory.md

**Comment by philburk** [comment]
@dturner - note that M_MR1 and N are both labelled API 24

Where do we link to https://github.com/google/oboe/blob/master/docs/AndroidAudioHistory.md ??

**Comment by dturner** [comment]
Linked from README on homepage
