### ISSUE TITLE
Is there a method to get the audio stream played by apps like YouTube and Google Play Music on phone?

### ISSUE THREAD

**Issue by huHHhhuhu** [google/oboe#259]
Is there a method to get the audio stream playbacked by apps like YouTube or Google Play Music ?

Thanks!

Cheers,
David

**Comment by philburk** [comment]
No. Sorry. Oboe does not add any special privileges. It just uses existing public APIs. So it is not possible to capture the output of other apps.

**Comment by huHHhhuhu** [comment]
Hi @philburk ,
OK, thanks for your help!

David
