### ISSUE TITLE
Crash on muliple devices (signal 11 (SIGSEGV), code 1 (SEGV_MAPERR))

### ISSUE THREAD

**Issue by WrobelKrakow** [google/oboe#263]
I have added oboe to Our app: [Best Piano](https://play.google.com/store/apps/details?id=com.netigen.piano)

I have modified RythmGame sample and I have a lot of errors like this:

This crash reports are from on Android 6.0, 7.0, 7.1, 8.0, 8.1, most from device Galaxy S7 (herolte) 
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.netigen.piano <<<

backtrace:
 
  #00  pc 0000000000037f44  /data/app/com.netigen.piano-1/lib/arm/libnative-lib.so (_ZN4Game11startStreamEv+79)
 
  #01  pc 0000000000de7807  /data/app/com.netigen.piano-1/oat/arm/base.odex
```
This is that modified method:
```
void Game::startStream() {// Create a builder
    AudioStreamBuilder builder;
    builder.setFormat(AudioFormat::I16);
    builder.setChannelCount(Mono);
    builder.setSampleRate(kSampleRateHz);
    builder.setCallback(this);
    builder.setPerformanceMode(PerformanceMode::LowLatency);
    builder.setSharingMode(SharingMode::Shared);
    audioStream = nullptr;
    builder.openStream(&audioStream);
    auto result = audioStream->requestStart();
    if (result != Result::OK) {
        LOGE("Failed to start stream. Error: %s", convertToText(result));
    }
}
```
I know this reports aren't too much helpful, but I can't reproduce this error on our test devices or emulators.

**Comment by philburk** [comment]
I also recommend passing a return code up to the application. If it fails then ask the user to close other audio apps, in case they have left streams open.

**Comment by dturner** [comment]
RhythmGame checks the status of openStream(): 

https://github.com/google/oboe/blob/master/samples/RhythmGame/src/main/cpp/Game.cpp#L61

Please reopen if still an issue.

**Comment by WrobelKrakow** [comment]
Ok, thanks I've missed checking start

**Comment by philburk** [comment]
Reopening.

Another possibility is that your callback method is causing some corruption on the stack. That could cause startStream to have a segfault. The requestStart() method calls your callback method and then queues the first buffer in order to start the stream running. Is your callback ready to be called?

(Also, just out of curiosity, why are you forcing the app to 44100 Hz. That will prevent you from getting a LowLatency stream on most devices.)

**Comment by philburk** [comment]
@dturner - Can you test RhythmGame on a Galaxy S7?

**Comment by WrobelKrakow** [comment]
Hi, I have published my current native code here: [OboeIssue
](https://github.com/WrobelKrakow/OboeIssue). 
I think it will be easier for You to find what I have made wrong. 
The worst thing with this crashes it's I can't reproduce them at my test devices or emulator.

**Comment by WrobelKrakow** [comment]
> 
> 
> Reopening.
> 
> Another possibility is that your callback method is causing some corruption on the stack. That could cause startStream to have a segfault. The requestStart() method calls your callback method and then queues the first buffer in order to start the stream running. Is your callback ready to be called?
> 
> (Also, just out of curiosity, why are you forcing the app to 44100 Hz. That will prevent you from getting a LowLatency stream on most devices.)

I use 44100 because at 48000 piano sounds bad at lower android versions (version <= 5.0).
In next releases I will implement resampling or prepare multiple apk.

**Comment by WrobelKrakow** [comment]
> Another possibility is that your callback method is causing some corruption on the stack. That could cause startStream to have a segfault. The requestStart() method calls your callback method and then queues the first buffer in order to start the stream running. Is your callback ready to be called?

Thanks for this suggestion, it was happening in callback. This crashes are probably not related to Oboe. I have been loading sound in splash activity, and sometimes app was killed and when recreating it will not go to splash activity. I turn on in developer options:
don't keep activities and set background processes limit to zero, and app start crashes on some devices (f.e) samsung J3, but on others don't (Moto XPLAY, Lenovo Idea Tab)
Original RythmGame sample isn't crashing.
I will publish new version today and tomorrow I will inform if this crashes disappears, if yes this issue can be closed.

**Comment by WrobelKrakow** [comment]
Thanks guys for help, it's resolved;)
