### ISSUE TITLE
Usage example using mediacodec

### ISSUE THREAD

**Issue by Wolfvx** [google/oboe#264]
Hello there.
I have been trying to use this library with mediacodec that is provided with NDK but so far has been unsuccessful in extracting correct PCM data using that codec and then supplying it to the oboe Stream. Extracted data seems to be PCM8 but oboe needs PCM16 as far as I can see and I am sure I am missing calculations for bitrate.
Could you please prove an example of code that uses oboe stream to play .aac or other format file except RAW pointed by URI? It would help me tremendously.

**Comment by dturner** [comment]
> Extracted data seems to be PCM8 but oboe needs PCM16 as far as I can see

Oboe needs whatever the audio stream is configured for, which can either be 16-bit samples (`int16_t`) or single precision floats (`float`). If the extracted data isn't in that format that sounds like  either your source audio format is incorrect, or that your decoder is incorrectly configured. 

> and I am sure I am missing calculations for bitrate.

Again, this sounds like the decoder needs to be configured for a specific bitrate, which should match that of the audio stream, and can be obtained using `audioStream->getSampleRate`. 

Calculating the bit rate from the stream's sample rate is relatively easy. For example if you have a 16-bit, stereo audio stream consuming 48,000 frames per second then you have: 

   48,000 * 2 (bytes per sample) * 2 (channel count) = 192,000 bytes per second = 1,536 kilobits per second

Did you see this sample: https://github.com/googlesamples/android-ndk/tree/master/native-codec

If you post your full source maybe I can help further.

**Comment by endre-borcsok** [comment]
Hi there. 

I tried something similar last night with the MediaCodec in Java. My input is a 48k stereo mp3 file that the decoder turns into 16bit stereo PCM. I think the decoded stream is correct, when I pass this data to an AudioTrack it plays fine. I'm having problems with passing that java byte array to Oboe, or more precisely to JNI. What's the correct way to merge two java bytes into a int16_t or float in C++? Here is what I tried (as far as I know char is the equivalent of a java byte):

int16_t = (((int)char_1) << 8) | (int)char_2;

I probably had other problems too, just wonder if this is correct or is there any better way to do this?

**Comment by dturner** [comment]
I have updated the RhythmGame sample to use the NDK media extractor: https://github.com/google/oboe/blob/master/samples/RhythmGame/src/main/cpp/audio/NDKExtractor.cpp

**Comment by philburk** [comment]
> int16_t = (((int)char_1) << 8) | (int)char_2;

When you cast char_2 to an int you will probably get sign extension. The high bits will clobber the data from char_1. You need something like:

 int16_t = (((int)char_1) << 8) | (((int)char_2) & 0x00FF);
