### ISSUE TITLE
[Question] Using Sound Effects and Oscillators at the same time.

### ISSUE THREAD

**Issue by NilayKulkarni** [google/oboe#266]
I'm working on a project that requires the use of Oscillators as well as sound effects from files. I tried learning from observing how the RhythmGame and the MegaDrone use the Sound Effects and the Oscillators respectively, but couldn't figure it out.

I know almost nothing about sound production and have had very little exposure of cpp. This may be a trivial question but I couldn't make it work by myself.

Here's my onAudioRead function.
`oboe::DataCallbackResult
UkappiEngine::onAudioReady(oboe::AudioStream *audioStream, void *audioData, int32_t numFrames) {

    int32_t bufferSize = audioStream->getBufferSizeInFrames();

    if (mBufferSizeSelection == kBufferSizeAutomatic2) {

    } else if (bufferSize != (mBufferSizeSelection * mFramesPerBurst)) {
        audioStream->setBufferSizeInFrames(mBufferSizeSelection * mFramesPerBurst);
        bufferSize = audioStream->getBufferSizeInFrames();
    }

    /**
     * The following output can be seen by running a systrace. Tracing is preferable to logging
     * inside the callback since tracing does not block.
     *
     * See https://developer.android.com/studio/profile/systrace-commandline.html
     */
    int32_t underrunCount = audioStream->getChannelCount();

    Trace::beginSection("numFrames %d, Underruns %d, buffer size %d", numFrames, underrunCount,
                        bufferSize);

    int32_t channelCount = audioStream->getChannelCount();

    if (audioStream->getFormat() == oboe::AudioFormat::Float) {

        /*if (mIsToneOn) {
            for (int i = 0; i < channelCount; ++i) {
                mOscillators[i].renderAudio(static_cast<float *>(audioData) + i,
                                       numFrames);
            }
        } else {
            memset(static_cast<uint8_t *>(audioData), 0,
                   sizeof(float) * channelCount * numFrames);
        }*/

        for (int i = 0; i < numFrames; ++i) {
            mMixer.renderAudio(static_cast<float_t *>(audioData)+(2*i), 1);
        }

    } else {

        for (int i = 0; i < numFrames; ++i) {
            mMixer.renderAudio(static_cast<int16_t *>(audioData)+(2*i), 1);
        }

        /*if (mIsToneOn) {
            for (int i = 0; i < channelCount; ++i) {
                mOscillators[i].renderAudio(static_cast<int16_t *>(audioData) + i,
                                       numFrames);
            }
        } else {
            memset(static_cast<uint8_t *>(audioData), 0,
                   sizeof(int16_t) * channelCount * numFrames);
        }

        if (mIsKickOn) {
            for (int i = 0; i < channelCount; ++i) {
                mKick->renderAudio(static_cast<int16_t *>(audioData) + i, numFrames);
            }
        } else {
            memset(static_cast<uint8_t *>(audioData), 0,
                   sizeof(int16_t) * channelCount * numFrames);
        }*/

    }

    Trace::endSection();

    return DataCallbackResult::Continue;
}`

Here's the renderAudio function of the Oscillator.

    void Oscillator::renderAudio(float *buffer, int32_t numFrames) {
        if (mIsWaveOn) {
            for (int i = 0, sampleIndex = 0; i < numFrames; i++) {
                buffer[sampleIndex] = (float) (sinf(mPhase) * mAmplitude);
                sampleIndex += 2;
                advancePhase();
            }
        }
    }

The Mixer, RenderableAudio, and SoundRecording files are taken from the RhythmGame code.

**Comment by dturner** [comment]
It's difficult to debug your code without seeing all of it - any chance you could post it on github so we can take a look? 

At first glance it looks like `renderAudio` isn't handling the channel count correctly. Assuming you're using a stereo (2 channel) stream, `buffer` should be populated with samples in the following format: 

L1, R1, L2, R2, etc

You might be better off starting with the MegaDrone sample which has 100 oscillators and a mixer, then adding the `SoundRecording` class from RhythmGame to it. 

Worth watching this if you haven't seen it already: https://www.youtube.com/watch?v=FgHX23KdlLA

**Comment by dturner** [comment]
Please reopen if you have more questions.

**Comment by zubyf09** [comment]
@dturner  Can you explain how we can achieve "rever effecs to an audio stream"/AudioFilters  using OBOE ""
https://audiokit.io/examples/FilterEffects/
