### ISSUE TITLE
Background audio

### ISSUE THREAD

**Issue by sinosoidal** [google/oboe#268]
Hi,

How is background audio currently supported on Android? How can one let an app use Oboe while the app is in background? 

I have just integrated Oboe into our synth and if I tap the home button with the synth playing hold notes, the audio is updated from one in one second resulting in a non efective application.

How do other apps keep playing audio in background? Can Oboe helps easily sort/manage this problem?

**Comment by dturner** [comment]
Hey Nuno :) Apps which need to play audio when the app is minimised should use a [Foreground Service](https://developer.android.com/guide/components/services) and display a notification to the user so that they can pause/stop the audio. 

Feel free to email me directly with questions.
