### ISSUE TITLE
Failed test on Pixel XL running Pie

### ISSUE THREAD

**Issue by dturner** [google/oboe#269]
I ran the unit tests today on a Pixel XL running Pie and got the following failed test: 

11-14 15:08:52.566 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity: [ RUN      ] StreamStates.InputStreamLeftRunningShouldNotInterfereWithNextOpen
11-14 15:08:52.704 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity: /Users/donturner/Code/workspace-android/oboe/tests/testStreamStates.cpp:120: Failure
11-14 15:08:52.705 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity: Expected equality of these values:
11-14 15:08:52.705 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity:   r
11-14 15:08:52.707 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity:     Which is: 4-byte object <81-FC FF-FF>
11-14 15:08:52.707 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity:   Result::OK
11-14 15:08:52.707 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity:     Which is: 4-byte object <00-00 00-00>
11-14 15:08:52.707 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity: requestStart returned: ErrorInvalidState
11-14 15:08:52.707 10729 10785 D com.google.oboe.tests.unittestrunner.MainActivity: [  FAILED  ] StreamStates.InputStreamLeftRunningShouldNotInterfereWithNextOpen (138 ms)

Then the tests hung. 

Steps to run: 

- Connect Pixel XL running Pie
- Open terminal and execute `tests/run_tests.sh`

On the next run that test passed but the test binary hung again.

**Comment by dturner** [comment]
Should be fixed with Phil's recent unit test changes.

**Comment by dturner** [comment]
Needs retesting.

**Comment by robertwu1** [comment]
No repro anymore. Closing
