### ISSUE TITLE
Error -38 during AudioTrack native read

### ISSUE THREAD

**Issue by eastari** [google/oboe#270]
Hi, 
How to debug this error - E/AudioTrack-JNI: Error -38 during AudioTrack native read?  
What does it means?  

Thanks a lot.

**Comment by philburk** [comment]
The AudioTrack-JNI indicates that this is part of the Java AudioTrack API and not part of Oboe or AAudio.

If you suspect a bug in the Android Audio framework then you can report it here:
    https://source.android.com/setup/contribute/report-bugs

BTW, the -38 means ENOSYS
    http://www.virtsync.com/c-error-codes-include-errno
