### ISSUE TITLE
Requesting mono, exclusive output stream on Pixel XL results in shared stream

### ISSUE THREAD

**Issue by dturner** [google/oboe#271]
It'd be good if Oboe could honour a request for an exclusive mono stream. Currently if you create an audio stream using the following code: 

    AudioStreamBuilder b;

    b.setPerformanceMode(PerformanceMode::LowLatency);
    b.setSharingMode(SharingMode::Exclusive);

    b.setCallback(this);
    b.setFormat(AudioFormat::Float);
    b.setChannelCount(1);

    Result r = b.openStream(&stream);

You will receive a `SharingMode::Shared` stream with the following logcat message: 

    2018-11-15 11:29:04.704 22567-22567/? E/AAudio: BpAAudioService::client OPEN_STREAM passed stream -889
    2018-11-15 11:29:04.704 22567-22567/? D/AudioStreamInternal_Client: open - openStream() returned -889, try switching from MONO to STEREO

@philburk - would it be acceptable to do automatic mono to stereo conversion in this case? Or is it likely that an audio device might provide an exclusive mono endpoint?

**Comment by philburk** [comment]
This only happens on OC_MR1. On Pie, AAudio opens a stereo stream and downmixes to mono if the caller requests a mono stream. We could add conversion code in Oboe to do this.

**Comment by atneya** [comment]
This should be fixed by #493

**Comment by philburk** [comment]
Oboe now supports setChannelConversionEnabled().
Also AAudio now also does channel conversion.
