### ISSUE TITLE
LatencyTuner - some ideas

### ISSUE THREAD

**Issue by dturner** [google/oboe#272]
The idea behind `LatencyTuner` is to make it easy for apps to tune their buffer size to avoid underruns. The current implementation is a bit simplistic though - it just raises the buffer size until underruns stop occurring or the max buffer size is reached. 

Here's what I'm thinking...

1) It makes sense to specify a maximum buffer size in the `LatencyTuner` constructor. For example, an app may never want their buffer to be >20ms because the user experience would be degraded too much.

2) The `tune` method should make it easier to know when the buffer size has been increased. At the moment it just returns a `Result::OK` if there were no problems, but that doesn't tell you whether any underruns occurred or whether the buffer size was increased. 

Knowing whether underruns are occurring, or more useful, if the max buffer size has been reached would allow an app to use other ways of reducing their load (reduce voices, remove/simply dsp algorithms). 

Of course, the buffer size should be increased to max *before* scaling back load because otherwise you're into the CPU frequency scaling negative feedback loop. 

Proposal: 

- Change `LatencyTuner` constructor to take a maxBufferSize
- Add a method `isAtMaxBufferSize()` which returns true when the current buffer size is at the maximum

Both these could be implemented without breaking the API. 

@philburk WDYT?

**Comment by dturner** [comment]
See https://github.com/google/oboe/pull/273

**Comment by philburk** [comment]
Fixed by #273
