### ISSUE TITLE
convert Int16 to Float so we can get FAST path on older devices

### ISSUE THREAD

**Issue by philburk** [google/oboe#276]
Legacy AudioTrack will not support a FAST path for Input stream in Float format.
This affects OpenSL ES and AAudio Legacy path before P.
AAudio on P will convert Int16 to Float.
This does not affect the AAudio MMAP path.

For affected devices, we should request Int16 from the framework for low latency streams.
If the caller selects Float then we should convert the data in Oboe.

**Comment by atneya** [comment]
Fixed by #493
