### ISSUE TITLE
 recorded data from the low latency inputstream sounds bad, mangled

### ISSUE THREAD

**Issue by SchmadenSchmuki** [google/oboe#278]
Hello
Had a problem when recording with low latency inputstreams.
I can't get good recording data when working with  low latency inputstreams. Everything works fine when using the automatic setup stream, but when I select oboe::AudioFormat::I16 for the stream, to get a low latency inputstream, the recorded data is bad. It's partly recognizeable but there is also much random noise.
It could easily be due through an error in my code but to be honest I would guess the data provided under void* audioData is not what it should be.

My onAudioReady-method looks essentially like this:

    if(oboeStream->getFormat() == oboe::AudioFormat::Float)
    {    
        float* sourceAddress(reinterpret_cast<float*>(audioData));
        float* targetAddress(vectorAudioData.data());

        for(uint64_t i(0); i < samplesToRecord;)
        {
            targetAddress[numberOfRecordedSamples++] = static_cast<float>(sourceAddress[i++]);
        }
    }
    else
    {
        int16_t* sourceAddress(reinterpret_cast<int16_t*>(audioData));
        float* targetAddress(vectorAudioData.data());

        for(uint64_t i(0); i < samplesToRecord;)
        {
            targetAddress[numberOfRecordedSamples++] = static_cast<float>(sourceAddress[i++]);
        }
    }

Samplerate and channelcount are the same in both cases, the difference of the provided audiodata should be addressed and I also can't find another mistake.
As mentioned before, it works fine when I don't care about the selected audioformat and then get a non low latency inputstream with AudioFormat::Float.
When I select AudioFormat::I16 I have problems with the data I get/produce with the low latency inputstream.

vectorAudioData is of type std::vector\<float\>,
numberOfRecordedSamples is an uint64_t outside the callback that counts the recorded samples of all callbackcalls and
samplesToRecord just checks if there is enough space in the vector to write all the samples provided, so it's usually numFrames * channelcount.

It would also be interesting if there is working low latency recording code with oboe available?

Also, when setting up the callbackclass and streams I get the following error logs:
E/OboeAudio: AAudioLoader could not find AAudioStream_getUsage
E/OboeAudio: AAudioLoader could not find AAudioStream_getContentType
E/OboeAudio: AAudioLoader could not find AAudioStream_getInputPreset
E/OboeAudio: AAudioLoader could not find AAudioStream_getSessionId
but I didn't look into that, also they appear in both cases, good and bad.

**Comment by philburk** [comment]
> targetAddress[numberOfRecordedSamples++] = static_cast<float>(sourceAddress[i++]);

That won't work. That just changes the data type, not the value.  Float PCM samples are in the range -1.0 to +1.0. Int16 PCM samples are in the range -32768 and +32767. You need to scale the Int16 by (1.0f/32768). This utility function may be helpful.

https://github.com/google/oboe/blob/9e827e356988cc30086b53346867a8576617db1e/src/common/Utilities.cpp#L48

If you are still having problems then please let me know what OS and Device?
What is your numFrames for the read?
Are you using a callback or a blocking read?

If this is on OC_Mr1 using MMAP, and your callback size, or your read size, is not equal to the burst size, then you may be hitting this bug. https://github.com/google/oboe/issues/188 
The workaround is to only read in sizes equal to the burst size.

**Comment by SchmadenSchmuki** [comment]
Works perfectly now. 
Thanks a lot.
(sorry for the stupid mistake, just didn't think of that anymore)
