### ISSUE TITLE
Add a sample which demonstrates how to use non-blocking read/writes for full duplex

### ISSUE THREAD

**Issue by dturner** [google/oboe#28]
Maybe in Java

**Comment by philburk** [comment]
An oboe echo program should use this technique.

**Comment by dturner** [comment]
Waiting on `stream->read` for this.

**Comment by ggfan** [comment]
Linking bugs: https://github.com/googlesamples/android-audio-high-performance/issues/116
with the 2 callback streams, adding queue in between might be possible.

**Comment by ggfan** [comment]
On the way of the porting loopback to oboe, experiencing a problem: 
 once in a while I would get a noisy playback ( not consistent, but I am bound to hit the noisy playback if I keeps on start/stop the app ). It mostly likely to be my app side, wondering if there is something inside oboe I could check.  The channel/frequency are the ones that matching what I needed. 

Code is here:  https://github.com/ggfan/oboe/tree/loopback

It blends the recorded audio with a raw PCM file ( 48K, signed 16 bit integer, dual channel ).

**Comment by ggfan** [comment]
thanks!  when start/stop app, all streams are closed and re-opened.
I will update the OS first and go from there.

**Comment by dturner** [comment]
Fixed in #103
