### ISSUE TITLE
[Feature Request] Load stabiliser abstraction

### ISSUE THREAD

**Issue by JamesFrink** [google/oboe#280]
Wouldn't it be great if Oboe came with a load stabiliser abstraction that functioned something like [this one](https://github.com/googlesamples/android-audio-high-performance/blob/master/SimpleSynth/app/src/main/cpp/load_stabilizer.cc) that @dturner wrote for AAudio a while back, right out of the box? There are still cases where heavy, unbalanced DSP can cause unforeseen glitches. Being able to "drop in" or enable a solution for that, at least for testing or prototyping, would be very desirable in my opinion. 

Also, in my own experience, people are relatively weary of the whole load stabilisation story and would rather avoid thinking about it, let alone implementing it until they absolutely have to. Having an abstraction for that  be part of Oboe as a feature until a solution comes along would open up more room for creative development in the DSP/FX app world.

**Comment by dturner** [comment]
See https://github.com/google/oboe/pull/290. Would welcome your feedback on this new class. Is it easy to use? Does it do what it's supposed to do on your test device?

**Comment by dturner** [comment]
Fixed in #290. The MegaDrone sample has a usage example.
