### ISSUE TITLE
Sample files audio format?

### ISSUE THREAD

**Issue by NilayKulkarni** [google/oboe#281]
I have been playing around with sound effects for a while. And I've tried .raw files exported in signed8 to signed64 formats. The base code is from the RhythmGame repo. I was wondering if anyone knows the export configuration of the sample files (CLAP.raw, FUNKY_HOUSE.raw). Because those are the only two that play perfectly without noise. signed64 came the closest but still had a lot of white noise.

[Note: I have almost no experience in audio technology]

**Comment by Matt237** [comment]
Your export configuration should be "48000hz 16bit signed" convert your audio with Audacity.

**Comment by philburk** [comment]
The int16 data should also be LittleEndian.
