### ISSUE TITLE
Use SessionID with android audiofx

### ISSUE THREAD

**Issue by elivity** [google/oboe#296]
Hey,
iam using a modified version of the LiveEffect-Sample.
I want to attach an effect to the AudioSessionId created in in Oboe
I wrote a JNI-function to get the SessionID, which returns an int.

When i do "newEQ = new Equalizer(0,theSessId);" in Java 
->i get:
Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3

What am i doing wrong :/ Thanks in advance!

Best regards, Oskar
(pixel2 / android P)

**Comment by philburk** [comment]
Did you call builder.setSessionId(SessionId::Allocate) ?
If not then getSessionId should return SessionId::None.
https://github.com/google/oboe/blob/master/include/oboe/AudioStreamBuilder.h#L236

Or you can allocate a SessionId in Java and then pass that to Oboe.

Note that if you use the Effects from the operating system then you will **not** get a low latency stream. I think it is better to simply do effects processing in your application. An EQ is just a filter bank. There are lots of open source implementations. You also have more control over the effect.

**Comment by elivity** [comment]
Yes, i did call setSessionId(SessionId::Allocate) and thought i could use the id to just pass it into the Eq(i get int values lile 2345 for the sessionId), but that didn't work. If you could recommend a good library for doing simple effects like reverb and equalizer, i would really appreciate it(in c++ i guess would be best) . It seems iam missing the best practices.

**Comment by elivity** [comment]
I guess iam doing something wrong. I get a SessionID in Java now through generateAudioSessionId, pass it like the following, but still the same error:
```
oboe::AudioStreamBuilder *LiveEffectEngine::setupPlaybackStreamParameters(
    oboe::AudioStreamBuilder *builder) {
    builder->setCallback(this)
        ->setDeviceId(mPlaybackDeviceId)
        ->setDirection(oboe::Direction::Output)
        ->setChannelCount(mOutputChannelCount)
            **->setSessionId(static_cast<oboe::SessionId>(passedSessid));**

    return setupCommonStreamParameters(builder);
}
```
I validated, that the AudioManager and the AudioStream in oboe have the same SessionId.

Still the same error:  
E/AudioEffect: set(): AudioFlinger could not create effect 0bed4300-ddd6-11db-8f34-0002a5d5c51b / ec7178ec-e5e1-4432-a3f4-4657e6795210, status: -22
E/AudioEffects-JNI: AudioEffect initCheck failed -3
E/AudioEffect-JAVA: Error code -3 when initializing AudioEffect.

And just before that:
checkEffectCompatibility_l(): effect Equalizer on playback thread in raw mode

If its not the way to do it, you can close this issue. Now i will try integrating Csound. 
Thanks for your help

**Comment by Ornolfr** [comment]
@elivity I'm struggling with the same issue. Could you point out where I could find the synthesizer toolkit equalizer library please?

**Comment by elivity** [comment]
Here you go, https://ccrma.stanford.edu/software/stk/index.html

Have a nice day✌🏼

**Comment by Ornolfr** [comment]
@elivity Can you elaborate a bit more on this please? I can see the class reference, but I couldn't find the one with equalizer functionality: https://ccrma.stanford.edu/software/stk/classes.html

**Comment by elivity** [comment]
I think you can setup biquads, and apply them to your pcm. 

More general : https://www.w3.org/2011/audio/audio-eq-cookbook.html

**Comment by muhlenbrock** [comment]
Hello @elivity I need your help, I have to make an equalizer of 10 bands, but I still can not get the Android audio with Oboe.
Regards

**Comment by elivity** [comment]
@muhlenbrock do you have a git of that project i can comment on? anyway, as soon as i get to it, i'll post a simple example that works for me here.

**Comment by dturner** [comment]
@elivity Glad you got this working.

**Comment by philburk** [comment]
See https://github.com/google/oboe/blob/master/docs/notes/effects.md
