### ISSUE TITLE
`stopStream` actually starts the stream, is this a typo ?

### ISSUE THREAD

**Issue by taemincho** [google/oboe#298]
https://github.com/google/oboe/blob/0213e70bd17db5fca2defa98e4c5a7ffbce6a7ef/samples/LiveEffect/src/main/cpp/LiveEffectEngine.cpp#L236

Should `oboe::Result result = stream->start(0L);` be `oboe::Result result = stream->stop(0L);` ?

**Comment by dturner** [comment]
Thanks very much for spotting and reporting this Taemin
