### ISSUE TITLE
Dependency on NDK r16 is probably too strict

### ISSUE THREAD

**Issue by dturner** [google/oboe#30]
Run some tests to verify the earliest version of the NDK which can be supported.

**Comment by mnaganov** [comment]
You definitely need AAudio header files which appeared in r15. I used r15c for the Loopback app with AAudio support.

**Comment by dturner** [comment]
There are also some other dependencies on macros and methods which only appeared in r15. I will update the docs to say Oboe will work with NDK r15 but not r14 and below.

**Comment by dturner** [comment]
Docs updated in commit 7621b5d558675b71707de10f4e05e28f031ea44c
