### ISSUE TITLE
Does oboe support playing of compressed music formats such as acc, mp3? 

### ISSUE THREAD

**Issue by mvedenee** [google/oboe#302]
How to play acc music format using oboe?

**Comment by dturner** [comment]
This is a common question and the simple answer is: No. That said, many developers have had success using both NdkMediaCodec from the Android NDK and ffmpeg. I hope to publish an article on this in future and will link back to it here when it's done.

**Comment by philburk** [comment]
On Thu, Dec 6, 2018, 9:06 AM Don Turner <notifications@github.com wrote:

> This is a common question and the simple answer is: No
>

This might be a good question and answer for the FAQ. You should also
recommend the appropriate Java APIs.

>

**Comment by mvedenee** [comment]
Hi Don, thank you for the quick response and looking forward to your new article.

My goal is to play a queue of acc chunks which are located in memory.
Is my understanding correct, that you recommend the following way:

1) to decode acc buffer with  ffmpeg library or NdkMediaCodec
2) to play decoded PCM buffer using oboe or OpenSl or something else?

Do we have some other alternatives in native android without manual decoding?

**Comment by dturner** [comment]
Yes, that's right. I've added your question to the [FAQ here](https://github.com/google/oboe/blob/master/docs/FAQ.md#can-i-use-oboe-to-play-compressed-audio-files-such-as-mp3-or-aac). 

I'm afraid I don't have a simple answer at this point in time. I am actually working on a sample which uses ffmpeg for easy decoding of aac and mp3 files which I hope to have published shortly.
