### ISSUE TITLE
raw file in RhythmGame

### ISSUE THREAD

**Issue by f0831027** [google/oboe#307]
hi ,
I use Audacity audio editor to play FUNKY_HOUSE.raw and CLAP.raw. 
Why sound like different to I heard in RhythmGame? 
Does the sound track speed up in RhythmGame? If I want to just play a raw file without any change, how should I do?

 I have almost no experience in audio

**Comment by dturner** [comment]
When you import the raw files into audacity you'll need to specify the sample rate, data type and channel count. These are 48000, 16-bit ints and 2 respectively.

**Comment by dturner** [comment]
Out of interest which Android device are you testing on?

**Comment by f0831027** [comment]
I am using htc u11 and m10.
