### ISSUE TITLE
AudioStreamCallback should use references rather than pointers

### ISSUE THREAD

**Issue by dturner** [google/oboe#31]

**Comment by dturner** [comment]
Phil - Why were we doing this again?

**Comment by philburk** [comment]
I believe they are preferred when a parameter should never be null. Mikhail?

**Comment by mnaganov** [comment]
This what Google C++ style guide suggests: https://google.github.io/styleguide/cppguide.html#Reference_Arguments

References should be used for input parameters (and thus references need to be labelled "const"), unless a null pointer is a valid input parameter value.

Pointers are mostly used for output parameters.

**Comment by philburk** [comment]
We decided that because the stream must be modified then we cannot do a const reference. So closing this as Will Not Fix.
