### ISSUE TITLE
2 streams recording from 2 recording devices NOT possible?

### ISSUE THREAD

**Issue by PindongaFlores** [google/oboe#311]
with OpenSL-ES API: I cannot open the second recordingStream, stream->requestStart() returns "ErrorInternal"

with AAudio API: I cannot start the second recordingStream, builder.openStream() returns "ErrorInvalidState"

In both cases I call builder->setCallback(nullptr) so I thought using separate threads might help, but this didn't solve the problem.

Apparently, 2 output streams that stream to 2 different playbackDevices works.

Any ideas?

**Comment by NielsHygum** [comment]
I have been struggling with the same problem...

**Comment by PindongaFlores** [comment]
I forgot to mention that I get the warning "Stream is NOT low latency." for all 4 streams.
But that seems not to be a problem when using the first 2 input and output streams.
Checking the oboe source code I found in AudioStreamBuilder::openStream() and in AudioStreamAAudio::requestStart() several hints that there are known issues related to this problem.
I will next try to set a callback for the recording stream, but I am not really expecting this could help. And even if it did, I would still like to use my first approach calling mRecordingStream->read() instead.

**Comment by dturner** [comment]
[Same question on stackoverflow](https://stackoverflow.com/questions/53796802/android-oboe-library-2-streams-recording-from-2-recording-devices-possible). Please post relevant info there. If this turns out to be a bug in the oboe library please re-open.
