### ISSUE TITLE
Enabling -Wunused-parameter results in lots of "error: unused parameter" messages

### ISSUE THREAD

**Issue by dturner** [google/oboe#312]
I'm attempting to tidy up the Oboe core codebase and (taking a lead from the JUCE developers) am trying to get the compiler to do a bit more work for us. 

Specifically I'm attempting to use the `-Wunused-parameter` flag to provide errors when a parameter is declared but not used.

This happens a lot in the Oboe codebase because we declare empty method bodies in abstract classes, for example here: https://github.com/google/oboe/blob/master/include/oboe/AudioStreamCallback.h#L100

Just wondering, what is best practice here? Should we remove the empty function bodies, use an UNUSED macro, not worry about it? 

Relevant link: https://sites.google.com/site/opensourceconstriubtions/ettl-martin-1/articles/suppress-unused-parameter-compiler-warning

**Comment by dturner** [comment]
Talk to Kevin, Andy or Mikhail

**Comment by philburk** [comment]
(void)x;

**Comment by FredGithub** [comment]
I use `-Wextra` in my project which enables `-Wunused-parameter` and thus get a compile error because Oboe enables `-Werror`. I can disable warnings for Oboe as a workaround but it would be great to have it fixed.
