### ISSUE TITLE
hello-oboe samples clicks at the start / end of a sound

### ISSUE THREAD

**Issue by NikolaA95** [google/oboe#326]
[Problem] occurs when sound is interrupted(or started) regardless of wave position(not being zero I suppose) and clicking sound is heard .
This problem is brought here https://stackoverflow.com/questions/53803958/android-oboe-library-clicks-at-the-start-end-of-a-soundand was suggested it could be reported as bug. I have same problem and nether do I have experience in generating audio waves so I am posting it here.

**Comment by YousefJayrwandi** [comment]
Hi, I am not sure this is where I should be writing but was wondering if the issue #326 been resolved? I am experiencing a similar problem with clicks upon note release when using sine wave generated synth. 
I tried making my own release envelope, but it still clicks when a note has been released. I am quite new to this so would appreciate if you can help me out. Thank you!

**Comment by philburk** [comment]
This item has been closed. If your note clicks when released then it is a problem in your synth. Make sure you leave the stream running and mix multiple notes into one stream.

**Comment by dturner** [comment]
You could probably do this pretty simply using https://github.com/google/oboe/blob/master/src/flowgraph/RampLinear.h
