### ISSUE TITLE
Clarification on format

### ISSUE THREAD

**Issue by svenoaks** [google/oboe#33]
If we make an output stream specifying the format `builder.setFormat(oboe::AudioFormat::I16);` do we have to check the actual type or is it guaranteed that we will be working with shorts and not floats?

**Comment by dturner** [comment]
Always check the format after creating the stream. There is no guarantee that what you request is what you will receive. 

That said, at time of writing if you request `AudioFormat::I16` you should always receive it since it's supported on all current Android versions. That might change in future.
