### ISSUE TITLE
Consider changing Oboe to use only floats

### ISSUE THREAD

**Issue by dturner** [google/oboe#334]
Based on recent discussions let's consider updating Oboe to only use floats (maybe for version 2). This would make the API simpler to use because it would remove the need for clients to go through the "check what stream format we received, cast to that format inside `onAudioReady`, ensure our audio rendering classes support both `float` and `int16_t` types" rigmarole.

This would involve removing `AudioStream::setFormat` and changing the method signature of the callback from: 

    onAudioReady(AudioStream *audioStream, void *audioData, int32_t numFrames)  

to: 

    onAudioReady(AudioStream *audioStream, float *audioData, int32_t numFrames)

It would also require Oboe to provide float->int16_t conversion for native audio streams which don't support floats. Possibly relevant issues: #276 #145 #201

**Comment by philburk** [comment]
I would prefer that users just request float if they prefer float. And then we handle any necessary conversions. We could even make that the default if they do not specify a format.

There are so many systems that use int16 that it would be hard to not support it.

**Comment by dturner** [comment]
Fair enough. Let's leave as is then, the change to floats only really makes sense if we can change `void *audioData` to `float *audioData` to avoid a cast. 

Side note: I'm working on updating the sample apps to use floats in their signal path and only change to int16 if required.
