### ISSUE TITLE
[Question] Need a list of USB Sound Cards with stereo Line-In

### ISSUE THREAD

**Issue by PindongaFlores** [google/oboe#338]
Many use cases can be supported by Oboe when using an external sound card.
My search up to now for a device with "stereo-line-in" **supported by Android** resulted in devices which only mention Windows, Mac or iOS, e.g. this one for 19 EUR:
http://downloads.music-group.com/software/behringer/UCA222/UCA222_P0A31_M_Web_DE.pdf

When using the following sound card Android doesn't find any inputs (only the output is found):
https://www.conrad.de/de/71-soundkarte-extern-renkforce-digitalausgang-externe-kopfhoereranschluesse-externe-lautstaerkenregelung-1601924.html

Please include a link. Thanks!

**Comment by dturner** [comment]
Any class compliant USB audio device should work with Android so the key phrase to search for is "class compliant". This means that no special drivers are required.

Closing as this isn't an Oboe specific issue (thanks for highlighting it though).
