### ISSUE TITLE
If PerformanceMode::LowLatency is requested set the buffer size to 2*bursts by default

### ISSUE THREAD

**Issue by dturner** [google/oboe#340]
At the moment the client has to manually call `setBufferSizeInFrames` after the stream has been opened. If they've already specified that they want a low latency stream it'd might be convenient for us to manually set the buffer size to 2 * bursts since this is our recommendation (barring any more intelligent buffer sizing algorithm e.g. LatencyTuner)

**Comment by philburk** [comment]
This seems reasonable.

**Comment by philburk** [comment]
@dturner I think this was fixed.
