### ISSUE TITLE
Is there a pre-requirement about compileSdkVersion?

### ISSUE THREAD

**Issue by akinesia** [google/oboe#345]
Hello.

I am trying to use "oboe" on my android app. And I have something to ask.

App's compileSdkVersion is 26. And if I import oboe on my app, I couldn't build this.
However if I do this on 27 version, it is okay.
As you know, it is hard to change compileSdkVersion.

So..!
There is no way to use "oboe" on 26 version?
Or do I have to upgrade this version?

**Comment by dturner** [comment]
What error message are you getting when you use `compileSdkVersion 26`? 

Also, is there a reason why you're not using `compileSdkVersion 28`? It's always best to use the latest version of the Android SDK to compile against. 

Note that this is different to `minSdkVersion` which is what affects the number of Android devices your app will run on (Oboe will work on API 16+).

More: https://stackoverflow.com/questions/24510219/what-is-the-difference-between-min-sdk-version-target-sdk-version-vs-compile-sd

**Comment by dturner** [comment]
Please reopen if you have further problems.
