### ISSUE TITLE
OboeTester needs an easier way to test disconnecting headphones

### ISSUE THREAD

**Issue by philburk** [google/oboe#350]
We currently show the state as a number. We should show the state name.

We could also add an option to automatically reopen the stream when disconnected.
We then need a way to detect the reopening in the Java code so that the device ID and other information gets updated. Maybe we could reopen from Java when we see the DISCONNECTED state.

**Comment by atneya** [comment]
#541 attempts to address this in the samples, would we still want to restart from Oboe itself?

**Comment by philburk** [comment]
This is specific to OboeTester. Generally, test code does not make good example code. We just need a clean UI in OboeTester so OEMs can easily test the disconnect features.

**Comment by philburk** [comment]
"TEST DISCONNECT" was added to OboeTester.
