### ISSUE TITLE
Running Oboe simultaneously with other applications.

### ISSUE THREAD

**Issue by ttveldhuis** [google/oboe#354]
This is mainly a question so I don't know if creating an issue is the right approach but:

I have written an application that is supposed to do some audio processing using Oboe. It is running as a foreground service to be able to continue recording in the 'background'. 

The problem I am running in to is that when my application is running, other applications do not appear to be able to start recording and vice versa.

I have tried using `AudioManager#requestAudioFocus` to see if other applications need access to the microphone, but this means that even Youtube and Spotify stop my app from recording and the application doesn't get a notification for when it can continue recording. 

I know with OpenSLES it is not possible to prefer shared audio, but I thought AAudio (which both of my devices can use) having set the sharing mode to `SharingMode::Shared` would maybe help this. Although I am not sure I am interpreting `SharingMode` correctly.

Any suggestions for an approach on how to either get multiple application to be able to record simultaneously or to detect when another application starts and stop recording so that my application can stop and continue appropriately? 

(I have tried running on a Samsung S8 and Nexus P6).

**Comment by ttveldhuis** [comment]
Thanks for you reply, I was suspecting that the shared mode was mainly for output. 

Would be great if you or @dturner could help to look in to the ability to detect when another application starts and stop recording so that I can stop and continue recording on my side appropriately.

**Comment by sonicdebris** [comment]
We are experiencing the same issue. Moreover, we noticed that different things happen when we use either `AAudio` or `OpenSL` (through `Oboe`) and we try to open the input stream while an app that doesn't honor audio focus is using it:
- **With AAudio:** we get an error when trying to open the input stream
- **With OpenSL:** we the input stream opening returns success, but no input callback is ever called

Of course, if the other app honors the audio focus and stops the input when losing it, everything works fine. Our app and I'd say most of the ones out there do, but we found at least one case where this wasn't true.

As an experiment, we tried ignoring the audio focus ourselves and opening other audio apps while ours was using the input, and the other apps were not able to use the input, as expected.

I believe it would be appropriate to let an application that has correctly requested (and obtained!) the audio focus to just be able to "steal" the input from another, misbehaving app. If this is not possible or desirable, it would still be useful to actually get an explicit (and maybe specific) error in the case of `OpenSL` when trying to start the input stream.

**Comment by atneya** [comment]
This is duplicated in #539

**Comment by lucaszanella** [comment]
I'm having a very similar issue: it happens exactly as described in this post but even if I close my app and call `NativeInterface.destroyAudioEngine()` on the activity's close, when I go to other app I can't record audio.

I have to force close the app in settings for it to work.

**Comment by philburk** [comment]
> With OpenSL: the input stream opening returns success, but no input callback is ever called

That is a bug in OpenSL ES #539.
This is not an Oboe bug. Audio policy prevents sharing of the microphone.
