### ISSUE TITLE
High latency when used with Bluetooth headset

### ISSUE THREAD

**Issue by Ornolfr** [google/oboe#357]
I'm experiencing a problem with all output sound having a noticeable constant delay (around 0.5 seconds) when I'm testing the Oboe sample projects with my Bluetooth headset. When I disconnect it and use the device speaker as the output, everything works great.

I don't think this is something specific to the headset, since it works fine without any delays in Youtube or music player on Android. And since I'm trying to make something similar on Android, I also tested it with the recent iOS "Hearing" accessibility feature, and it worked fine too.

Is this something that can be fixed? Thanks in advance!

Device: Lenovo K920, Android 7.1.2 (LineageOS). Also tested on Moto G4, Android 7.0
Headset: Zeus Storm

**Comment by Ornolfr** [comment]
Today I had an opportunity to test this on Google Pixel with AAudio API. In hello-oboe sample it showed me a latency of ~275 ms when Bluetooth headset is connected, whereas device speakers have latency of just 5 ms.

**Comment by dturner** [comment]
Bluetooth headsets have, on average, much higher latency than built-in speakers, 3.5mm jack output or USB audio devices. This is because Bluetooth is a bursty, wireless protocol and requires larger audio buffer sizes to avoid underruns/glitches. 

You mentioned that "it works fine without any delays in Youtube or music player on Android" - are you measuring the delay? Oboe is designed for *interactive* audio (i.e. triggered by some other event) whereas Youtube and other apps will simply play/stream pre-recorded audio data where the latency is not important. 

That said, one possible cause of extra latency would be that the Oboe samples are not creating low latency streams to the bluetooth headset because the requested sample rate doesn't match the native sample rate of the headset. Please could you paste the output of logcat into this bug so we can take a look.

**Comment by Ornolfr** [comment]
I understand that there must be at least some additional latency when using Bluetooth, but I do not feel any latency when I'm for instance, play a sound effect using the MediaPlayer, if that can be a valid example. And like I stated earlier, iOS's hearing accessibility feature, which encompasses both microphone recording and sound playback, works without any tangible delay.

Here is the logcat:
Hello-oboe: https://drive.google.com/open?id=1Uzi8Ts0VdtiHwfd5Ub1oLSasVkk0DPvy
LiveEffect: https://drive.google.com/open?id=1xJBPMRslxasVRQHjwIbVvNLTr90lKLyf

I can see a warning log "Stream is NOT low latency." in the LiveEffect sample. It is not logged when I'm not using the Bluetooth headset. Do you have any idea what might be the problem? Thanks!

**Comment by dberlin** [comment]
You @'d the wrong person :)

**Comment by dturner** [comment]
> AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 48000 Hz, output 44100 Hz

There's the problem. Your bluetooth headset has a native sample rate of 44100 frames/second, however, the output stream is configured to output at 48000 frames/second. This means that your output stream needs to resample its data before sending it to the BT headset - this incurs significant (probably 50-100ms) extra latency. 

You *should* be able to obtain the native sample rate of a BT headset using the `AudioDeviceInfo` class in Java. 

You can edit the `hello-oboe` sample to check whether the sample rate is reported by adding `Log.d(TAG, info)` after the following line:

https://github.com/google/oboe/blob/master/samples/audio-device/src/main/java/com/google/sample/audio_device/AudioDeviceListEntry.java#L83

**Comment by Ornolfr** [comment]
@dturner Yep, `AudioDeviceInfo` appeared to return an empty array for my Bluetooth headset too. Your workaround seems alright, so I think I'll stick to it if there isn't any other way to get the native sample rate.

**Comment by Ornolfr** [comment]
@dturner It appears the results are inconsistent. So here goes data I was able to collect while testing LiveEffect sample (I added stream type to the warning log about stream being in non low-latency mode):

Lenovo K920 (Lineage OS, Android 7.1.2):
48000 Hz - [LogCat](https://i.imgur.com/KekyRnE.png) - High actual latency
44100 Hz - [LogCat](https://i.imgur.com/seMDv9e.png) - Low actual latency

Google Pixel (Android 9):
48000 Hz - AAudio - [LogCat](https://i.imgur.com/Bd0RVlK.png) - High actual latency
44100 Hz - AAudio - [LogCat](https://i.imgur.com/atXYuR8.png) - High actual latency
48000 Hz - OpenSL ES - [LogCat](https://i.imgur.com/quh6UGC.png) - High actual latency
44100 Hz - OpenSL ES - [LogCat](https://i.imgur.com/EjyZ0Jx.png) - High actual latency

Xiaomi Mi5 (Android 8.0):
48000 Hz - AAudio - [LogCat](https://i.imgur.com/t2YJYJr.png) - High actual latency
44100 Hz - AAudio - [LogCat](https://i.imgur.com/BnIkn7o.png) - High actual latency
48000 Hz - OpenSL ES - [LogCat](https://i.imgur.com/dYsVKsl.png) - High actual latency
44100 Hz - OpenSL ES - [LogCat](https://i.imgur.com/UQOlzgD.png) - Medium-low actual latency

HTC One M8 (Android 6.0):
48000 Hz - [LogCat](https://i.imgur.com/MHzA4n2.png) - High actual latency with audio glitches (probably over/underruns?)
44100 Hz - [LogCat](https://i.imgur.com/3OSG8h8.png) - High actual latency with audio glitches (probably over/underruns?)

So while adjusting the sample rate to the native rate of the Bluetooth headset seems like a step in the right direction, there's still more to it, especially on Pixel device. Can you please take a look and share your thoughts about what else might be going on here? Thank you.

**Comment by dturner** [comment]
Thanks for all this info. This is certainly an area which we need to understand better. 

One other cause for getting sub-optimal latency is that the LiveEffect sample requests a stereo (channel count = 2) recording stream - maybe your headset has only a single microphone so only supports low latency for mono recording stream. 

You could modify the LiveEffect sample to request mono, then do a mono->stereo conversion for the playback stream. There's code to do this in `shared/MonoToStereo.h`.

**Comment by Ornolfr** [comment]
@dturner Thanks for the suggestion. Clarification - I'm only using the device's built-in microphone. Looks like some devices have one microphone and others have 2, but I didn't experience any impact on latency whether I used mono or stereo modes for the streams.

**Comment by Ornolfr** [comment]
@dturner interesting finding. I added changes from this pull request here https://github.com/google/oboe/pull/348 and it greatly decreased the latency on the Google Pixel device. Which is interesting to me because I was under impression that increasing buffer size increases the latency. It doesn't work for OpenSL ES though, is it not possible to change buffer size for OpenSL ES streams?

**Comment by philburk** [comment]
> Which is interesting to me because I was under impression that increasing buffer size increases the latency.

It will. Before #348 set the size to two bursts, it was probably set to the bufferCapacity by default. That might be 8, 16 or more bursts.

> is it not possible to change buffer size for OpenSL ES streams?

You cannot change buffer size on OpenSL ES streams that use a callback. You can change it on OpenSL ES output streams that use blocking write() calls.

>  I added changes from this pull request here #348 and it greatly decreased the latency on the Google Pixel device.

Good. Closing this because the problem seems to have been mostly solved a while ago.
