### ISSUE TITLE
There's some easy way to convert mp3 or wave files to the raw data expected by Oboe?

### ISSUE THREAD

**Issue by rafagan** [google/oboe#360]
I'm trying to find the exact raw conversion expected by Oboe, using the existing examples as the project base. There's some Android SDK/NDK code to help me convert any mp3 or wave sound to raw and plays it in the available examples?

**Comment by dturner** [comment]
There sure is. The RhythmGame example now includes MP3s, and I wrote an article on how to speed up the decoding process using FFmpeg: https://medium.com/@donturner/using-ffmpeg-for-faster-audio-decoding-967894e94e71
