### ISSUE TITLE
Ensure the recording stream uses the built in microphone

### ISSUE THREAD

**Issue by Ornolfr** [google/oboe#363]
How can we ensure that the recording stream created in Oboe library uses the device built in microphone? I see there is a builder method to set device id, but it states that:
```
     * Note that when using OpenSL ES, this will be ignored and the created
     * stream will have deviceId kUnspecified.
```

From what I was able to find out, when a wireless headset with a mic is connected, Oboe still uses the device built in microphone. But when a wired headset is used, it uses the headset's microphone.

Is there any workaround to this? AAudio stream type requires Android 8.1+ which is just a small part of the APIs that I'm aiming to support.

**Comment by antonkovalyov351** [comment]
Any updates?

**Comment by dturner** [comment]
OpenSLES doesn't support deviceIds but it may still be possible by using the Java APIs (setPreferredDeviceId)

**Comment by Ornolfr** [comment]
@dturner Thanks for your answer. Such method indeed exists, from the documentation:
```
public boolean setPreferredDevice (AudioDeviceInfo deviceInfo)
Specifies an audio device (via an AudioDeviceInfo object) to route the input to this AudioRecord.
```

The question is, how do we tie together Java's AudioRecord object (and how should we instatiate it?) to the Oboe recording stream? Or can we just create an arbitrary AudioRecord object, set the preferred device id and this will affect the Oboe streams too?

**Comment by dturner** [comment]
Closing as stale. Please re-open if you have further questions.
