### ISSUE TITLE
Cannot play audio with AudioStream::write without dataCallback 

### ISSUE THREAD

**Issue by vietanhto** [google/oboe#370]
I cannot use AudioStream::write to play audio without data callback.

It seems to be related to this change: https://github.com/google/oboe/commit/b878e2f389007e66f21bec7a7aefbd916289d1d1
This change requests AudioStream to stop if callback is not set. After commenting the check, I am able to play audio because it falls back again to the default callback.

**Comment by philburk** [comment]
What device are you using?
What Android version are you using?
Are you using OpenSL ES or AAudio?

> After commenting the check, I am able to play audio

What check? Where? What file?

**Comment by vietanhto** [comment]
This check:
https://github.com/google/oboe/blob/master/src/common/AudioStream.cpp#L46

As I understand, with this check, we will never play with default callback thus prevent us from using write without data callback.

I used Amazon Kindle Fire HD8 while testing it. However, I think the issue is device independent because AudioStream is shared code. The device is API 22 so it uses OpenSL ES.

**Comment by philburk** [comment]
OK, thanks for the details. I can reproduce the problem using OboeTester:

Build and launch OboeTester
Uncheck box for "Use Callback".
Click "TEST OUTPUT".
Select "OpenSL ES" audio API.
Click "OPEN"
Click "START"

Expect to hear sound.

Actually hear NO sound. Counters do not advance.

**Comment by philburk** [comment]
@vietanhto Please let me know if this fixes the problem for you.

Thanks for reporting this.
