### ISSUE TITLE
generateSineWave

### ISSUE THREAD

**Issue by fgenolini** [google/oboe#371]
The doc GettingStarted.md mentions generateSineWave
This is not defined and should not be present in such a basic document, where anything that can go wrong will distract and potentially deter new comers from using the API

**Comment by fgenolini** [comment]
Thanks for your time: when getting started the simplest example is the best indeed.

I was actually looking to output concert A (440 Hz) as a pure sine wave, so I really wished that generateSineWave would be somehow a primitive or class member ;-)
Found how to do it manually ;-)

**Comment by dturner** [comment]
Many thanks for your feedback. I have updated the documentation in this pull request: #382. Please take a look.

**Comment by dturner** [comment]
#382 was merged.
