### ISSUE TITLE
AAudio: Global volume control is broken on S9 Exynos

### ISSUE THREAD

**Issue by Themaister** [google/oboe#380]
I've been using straight AAudio and now Oboe to write some Android audio applications. However, with AAudio I noticed a very strange bug with Android 9.0 on a Galaxy S9 Exynos model (no idea if this is device-specific).

When I start a regular playback stream in LowLatency mode, the global volume control in Android does not apply, blasting audio at full volume even if the volume control is at mute. I have to physically press the volume control on my device, and then, and only then does the volume become correct. It works with PerformanceMode::None. I did not have this issue on Android 8.0, albeit AAudio on Android 8.0 was broken in shutdown.

The same code works just fine in OpenSL ES, even in LowLatency mode where I set the appropriate frame size / sample rates.

Here is the Oboe implementation for reference, I don't think it's doing anything special which would explain this issue.
https://github.com/Themaister/Granite/blob/master/audio/audio_oboe.cpp

**Comment by philburk** [comment]
Thanks! I have reported this to Samsung.
Do you have a specific build number?
Are you running the latest version from Samsung?

**Comment by Themaister** [comment]
- One UI version 1.0
- Android 9.0
- Build number is PPR1.180610.011.G965FXXU2CSA2.

This is the latest OTA I'm getting in Norway at least.

**Comment by philburk** [comment]
Thanks. I passed that to Samsung.
They say the bug has been fixed but not in that G965FXXU2CSA2 build.
The fix will appear in a future build. We cannot predict when.

**Comment by Themaister** [comment]
Thanks, that's great news!

**Comment by svenoaks** [comment]
This seems to be fixed in latest patch but #400 and #381 remain.
