### ISSUE TITLE
More than one Audio stream with Audio FX for one stream

### ISSUE THREAD

**Issue by s-bhat99** [google/oboe#384]
Hello, 
I am working on a karaoke app and have been trying to go over the Oboe examples to find something that suits my needs. 
I need to be able to play 2 audio files (music and vocal) simultaneously and I see that I could create 
two AudioStream objects in shared mode. My understanding after going over Oboe documentation is that when more than one AudioStream objects  are used in shared mode, Oboe applies a mixer before playing the sounds. 
However, I would like to add some Audio FX like reverb, echo to the vocals at the time of playing these 2 in real time. In the sense the user records his voice and then in the preview mode adds audio fx to vocals and once done the music and the vocals (with audio fx) is mixed to one file. 
Here are my questions:
1. Is it possible to apply audio fx just to one of the Audio Stream data ?
2. Is there build in methods for adding audio fx like the AudioEffect class (MediaPlayer and AudioTrack) ?

Thanks

**Comment by philburk** [comment]
For Karaoke, you want low latency for the vocal playback.
So I recommend doing your own mixing and effects processing and then just use one low latency Oboe output. Effects and mixing is just math. You don't need the OS for that.

The advantages of doing your own effects and mixing are:

1. You can get much lower latency than when you use the built-in effects.
2. The effects will work on all versions of Android.
3. You have more control.
4. You can use EXCLUSIVE mode if you only have one stream.
5. There will be less CPU overhead.

The disadvantages are that you may have to do more work. 

But writing audio effects is great fun or you can find many effects libraries and examples online.

**Comment by s-bhat99** [comment]
Thank you for the quick response. Yes I can do the mixing and effects myself.
The confusion I have is that the user should be able to apply the effects in real time and for the vocals only. So if I use one Oboe output to play the vocals and allow the user to apply effects in real time, should I use either AudioTrack or MediaPlayer to play music in sync with the vocals? Is that possible ?

**Comment by dturner** [comment]
No, don't use any Java APIs. Just apply the audio effects to your vocal data *before* mixing it with the music. Signal path:

Vocals -> Effects -> Mixer -> onAudioReady
Music ----------------^

Take a look at the RhythmGame sample for mixing and syncing events.
