### ISSUE TITLE
Is there a way to fill the audio data passed to onAudioReady() in Java? 

### ISSUE THREAD

**Issue by stephanedupont** [google/oboe#389]
I'm experimenting with replacing AudioTrack with Oboe in a project.

I have a set a classes in Java that are handling all the "audio generation" part and really basic C code to have an Oboe stream running.

Oboe calls onAudioReady() as it's supposed, but I can't find how to have the audiodata float (or short) buffer passed to Java as there is no JNIenv or jobject available.

Is there a way to do that or am I stuck with Audiotrack?

Or maybe a way to register a JAVA method as a callback for the stream?

**Comment by philburk** [comment]
If you are generating audio in Java then there is no advantage to using the
Oboe call back. You could use the oboe blocking write() from java. Just
pass your float array through JNI and then call the stream write() method.
Or just use a Java audio track with the low latency attribute set. That
will be very similar.

**Comment by stephanedupont** [comment]
Thank you @philburk, was not aware of the write method.

So I don't understand what is the advantage of using Oboe if using an Audiotrack gives the same result? Is it because using the blocking Oboe write call gives a higher latency than the callback? Isn't Oboe supposed to give lower latency than Audiotrack?

Using an Audiotrack (might not using the low latency attribute though, I have to check this) gives me up to 250ms latency, even on quite high end phones like the OnePlus 5T. I'm trying to reduce this.

**Comment by stephanedupont** [comment]
Also, as low latency attribute on AudioTrack is only for API > 26, on API < 26 would the AudioTrack has the same latency than Oboe using OpenSL ES?

**Comment by philburk** [comment]
The main advantage of using Oboe is when you're using native code, for
example C++, to generate the audio. Then you can output the audio directly
without going through Java. Also the native callback is at a very high
priority so you can have better CPU scheduling.

If you are using Java then there is still some benefit to using Oboe but
not as much. On older versions of Android that do not have the Java
LOW_LATENCY attribute you can sometimes get a FAST track through
Oboe/OpenSL ES. And Oboe gives you adjustable latency.

**Comment by stephanedupont** [comment]
Thank you very much for you answer @philburk

You mention that Oboe have an adjustable latency? Can you please point me towards how to use this? (I didn't find anything on it in the documentation)

More than low latency, I'm really interested in constant latency, so I can measure the delta between a touch input on the screen and the audio played and use it to determine the precision of it (like in a rhythm game). The way I did things, constant latency is more important to me than low latency. What road would you go for this? Oboe or AudioTrack?

**Comment by dturner** [comment]
You should definitely check out the RhythmGame sample (https://github.com/google/oboe/tree/master/samples/RhythmGame) as it shows how to synchronise touch and audio events. 

Adjustable latency works by calling `setBufferSizeInFrames` whilst the stream is running. This will change the buffer size, increasing or decreasing latency accordingly. This is usually used to tune the buffer size so that it's just large enough to avoid underruns. 

In your case you may want to tune the buffer size when your app starts (say for 1s) then keep it constant for the duration of the game so the user has a consistent tap to sound experience.

**Comment by stephanedupont** [comment]
Thank you!

**Comment by stephanedupont** [comment]
Thank you @dturner, but I checked the sample, it doesn't show how to synchronise touch and audio events: the sample doesn't take audio latency and touch screen latency into account. It kinda work, sure, but is really not precise...
