### ISSUE TITLE
Feature Request: support of multiple devices "simultaneously"

### ISSUE THREAD

**Issue by PindongaFlores** [google/oboe#393]
In many desktop operating systems it is possible to open several audio devices "simultaneously".
In Android this is not possible.
Please:
- add support for opening and streaming to multiple audio devices "at the same time"
- if not possible, pass this request to AAudio
- if not possible, please provide a Link to make this request outside Oboe scope
Apparently, some use-cases can be covered with a single Audio Device supporting many input and/or output channels. Nevertheless, this implies that the users shall spend money on additional devices.
I made this request in the past but it was rejected. In between I have serious evidence that this is a very "hot feature" that Android shall provide in future in order not to be behind competitors! Please trust me, this is a very important and real use-case!
Thx in advance!

**Comment by dturner** [comment]
Interested to hear about this use case. For Android feature requests please head to: https://source.android.com/setup/contribute/report-bugs

**Comment by PindongaFlores** [comment]
thank you Don...I referred to this Issue..hope you agree, here the link:
https://issuetracker.google.com/hotlists/1470752/edit#basic
Hope we can get in touch ...still dont know how..could not find you yet...no way to get in touch with users of GitHub....pretty difficult for "starters" like me..
