### ISSUE TITLE
returned oboe::DataCallbackResult::Stop, but the stream state remains in Stopping forever.

### ISSUE THREAD

**Issue by taemincho** [google/oboe#396]
Hi Phil,

This is related to issue #277 
With the latest codes in the master branch. 
When I returned `oboe::DataCallbackResult::Stop` in the input stream callback, the callback stopped being called as expected, but the stream state remained in `Stopping` and never changed to `Stopped`.

This happens on Pixel 2XL, Android 9 for both AAudio and OpenSLES.

I've also tested the 1.1-stable branch.
In this case, the callback stopped, but the stream state remained in `Started` with Errors `W/AudioStreamLegacy: processCallbackCommon() callback requested stop, fake an error` and `E/AudioRecord: EVENT_MORE_DATA requested 384 bytes but callback returned -1 bytes` 

And when I tried to restart the stream by calling `requestStart()`, it didn't work.

**Comment by philburk** [comment]
Thanks for the report.

> when I tried to restart the stream by calling requestStart(), it didn't work.

That is due to a bug in the AAudio Legacy path for Android P (9). This and other bugs related to  DataCallbackResult::Stop have been fixed for a future Android release.

>  the stream state remained in Stopping and never changed to Stopped.

We may be able to workaround that in Oboe.

**Comment by philburk** [comment]
This has been fixed. We spawn a thread to stop the stream.
