### ISSUE TITLE
setBufferSizeInFrames() on S9+ Exynos with Android 9 fails

### ISSUE THREAD

**Issue by svenoaks** [google/oboe#400]
This is probably another Samsung bug to go along with #380 and #381. Looks like AAudio is a  mess here. If you `setBufferSizeInFrames()` when the stream is being created on the main thread, `getBufferSizeInFrames()` returns framesPerBurst (minimum size) in the callback when it starts. Also, the` LatencyTuner.tune()` seems to not be able to set it all the time as there are often many audible statics before it finally increases. 

Note. I haven't checked return value of setBufferInFrames() return value yet. I'm not having this problem on other devices with Pie.

**Comment by PindongaFlores** [comment]
It also doesn't work with Huawei P Smart on Android 8.0.0.
`Neither mLatencyTuner->tune()` nor `oboeStream->setBufferSizeInFrames()` is working in my code.
BufferSize is always 1920, no matther what I do.
Have glitches even when `oboeStream->getXRunCount()` returns zero.

**Comment by philburk** [comment]
> If you setBufferSizeInFrames() when the stream is being created on the main thread,
> getBufferSizeInFrames() returns framesPerBurst (minimum size) in the callback when it starts. 

What did you set setBufferSizeInFrames(?) to?

Did setBufferSizeInFrames() return an error or just not the requested value?

What is the Capacity of the stream?  The "BufferCapacity" is the allocated size. The "BufferSize" is how much of the capacity is being used and determines the current latency.

The Capacity must be set using the builder. Size can sometimes be varied after the stream is created. Size cannot exceed the Capacity.

The Capacity should be about 8X the Burst size for AAudio. With OpenSL ES it will probably 2X.

**Comment by svenoaks** [comment]
Hi, here is my code and the output Samsung S9+ Android 9.0, Oxynos, patch level February 1, 2019

```
void ElastiquePlayer::createPlaybackStream() {
        oboe::AudioStreamBuilder builder;
        if (sdk >= 27 && builder.isAAudioSupported()) {
                builder.setDirection(oboe::Direction::Output);
                builder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
                builder.setSharingMode(oboe::SharingMode::Exclusive);
                builder.setSampleRate(samplerate);
                builder.setChannelCount(2);
                builder.setFormat(oboe::AudioFormat::I16);
                builder.setCallback(this);

                oboe::Result result = builder.openStream(&audioStream);

                mFramesPerBurst = audioStream->getFramesPerBurst();

                LOGI("framesPerBurst: %d, capacity: %d", mFramesPerBurst, audioStream->getBufferCapacityInFrames());

                //if (buffersize > mFramesPerBurst * 8) buffersize = mFramesPerBurst * 8;
                //if (buffersize < mFramesPerBurst * 4) buffersize = mFramesPerBurst * 4;

                result = audioStream->setBufferSizeInFrames(mFramesPerBurst * 2);

                LOGI("Result of setBufferSizeInFrames. %s", oboe::convertToText(result));

                LOGI("in createPlaybackStream - bufferSizeinFrames: %d", audioStream->getBufferSizeInFrames());

                mLatencyTuner = std::unique_ptr<oboe::LatencyTuner>(new oboe::LatencyTuner(*audioStream));

                result = audioStream->requestStart();
}
```

```
oboe::DataCallbackResult
ElastiquePlayer::onAudioReady(oboe::AudioStream *audioStream, void *audioData, int32_t numFrames) {
        LOGI("in callback - buffersizeinFrames: %d", audioStream->getBufferSizeInFrames());
}
```

> 2019-03-09 19:55:27.189 7067-7067/com.smp.musicspeed I/SOUNDPROCESS: framesPerBurst: 96, capacity: 3072
> 2019-03-09 19:55:27.189 7067-7067/com.smp.musicspeed I/SOUNDPROCESS: Result of setBufferSizeInFrames. OK
> 2019-03-09 19:55:27.189 7067-7067/com.smp.musicspeed I/SOUNDPROCESS: in createPlaybackStream - bufferSizeinFrames: 192
> 2019-03-09 19:55:29.433 7067-7545/com.smp.musicspeed I/SOUNDPROCESS: in callback - buffersizeinFrames: 96

`setCapacityInFrames()` call on builder has no effect. This happens with `PerformanceMode::LowLatency` or `PerformanceMode::None`, haven't checked the third.

**Comment by svenoaks** [comment]
Also, there is tons of static for many seconds with the tune() being called repeatedly and nothing happening. After some time getBufferSizeInFrames() doubles, and there is still static. Even after after a minute, there still may be static as buffer size hasn't increased enough.

One workaround I have found is to call `setBufferSizeInFrames()` in every callback. But with #381 I still can't use it on this device.

**Comment by PindongaFlores** [comment]
> What did you set setBufferSizeInFrames(?) to?

* different values, none worked.

> Did setBufferSizeInFrames() return an error or just not the requested value?

* no error, as Sven mentions it just has no effect.

> What is the Capacity of the stream? The "BufferCapacity" is the allocated size. The "BufferSize" is how much of the capacity is being used and determines the current latency.

* the capacity was the default = 1920.
   I didn't set it explicitly. I focused only on setting the Buffer Size in Frames instead ("after stream creation", without success). 
   Now that I set it using the builder it kind of works.
   Nevertheless, the gliches persist. 
   I am quite convinced that the USB-sound-card may be responsible for this.

> The Capacity must be set using the builder. Size can sometimes be varied after the stream is created. Size cannot exceed the Capacity.

* done. This actually helped as I mention above, though changing the buffer size "after" stream creation still doesn't work. 

> The Capacity should be about 8X the Burst size for AAudio. With OpenSL ES it will probably 2X.

* I tried different combinations but none helped. Here an example:

```
play-stream getBufferSizeInFrames = 240
play-stream getFramesPerBurst = 240
play-stream getBufferCapacityInFrames = 61440
play-stream setBufferSizeInFrames(7680) *** 
play-stream getBufferSizeInFrames = 7680
play-stream getFramesPerBurst = 240
rec-stream getBufferSizeInFrames = 61440
rec-stream getFramesPerBurst = 240
rec-stream getBufferCapacityInFrames = 61440
rec-stream setBufferSizeInFrames(7680) *** 
rec-stream getBufferSizeInFrames = 61440
rec-stream getFramesPerBurst = 240
```

As I commented, with "headset" I have no problems, so external HW may case the glitches (?).

**Comment by svenoaks** [comment]
After further examination, it seems this is happening on all tested devices, Pixel with 9, Nexus 5X with 8.1.

What I have found is I can call setBufferSizeInFrames() in the first callback once instead of during creation on main thread. 

Is it some kind of synchronization issue between the creating thread and the callback thread?

**Comment by philburk** [comment]
@svenoaks - it looks like setBufferSizeInframes() worked in your example. burst=96. You setBufferSize to 2*burst and got 192 frames.

Then you added the latency tuner and started the stream. The latencyTuner will set the BufferSize initially to 1 burst. I do not see LatencyTuner being called but that is probably why the BufferSize is 96.
https://github.com/google/oboe/blob/master/src/common/LatencyTuner.cpp

**Comment by philburk** [comment]
> One workaround I have found is to call setBufferSizeInFrames() in every callback with
> some size (burst size * 6 or so) that prevents static.

OK, so the issue is related to buffer underruns.  You should not need to call it on every callback. Just call it once and it should stay. if you are calling setBufferSizeInFrames() then do not use the LatencyTuner or they will conflict.

**Comment by svenoaks** [comment]
> Then you added the latency tuner and started the stream. The latencyTuner will set the BufferSize initially to 1 burst.

Ok, the constructor of LatencyTuner resets it to *1 burst size. 

> if you are calling setBufferSizeInFrames() then do not use the LatencyTuner or they will conflict.

Ok, now I just setBufferSizeInFrames after constructing LatencyTuner and all is well.

**Comment by philburk** [comment]
@PindongaFlores - let's work on this in #402.
I think your issues are a bit different than Steve's.

> rec-stream setBufferSizeInFrames(7680) *** 
> rec-stream getBufferSizeInFrames = 61440

setBufferSizeInFrames() is not useful for input streams because we always try to run them close to empty. It may even be disabled on some devices. #403
