### ISSUE TITLE
Possible outdated Oboe tutorial documentation?

### ISSUE THREAD

**Issue by strommj** [google/oboe#401]
I'm new to the Android NDK scene, and encountered oboe.  Thus I went and started the code labs tutorial for this project.

When on this part:
https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html#2

It asks you to check out branch `io18codelab`.  On this branch I noticed I had the warning: `WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`

I also noticed that this has already been fixed in this issue:
https://github.com/google/oboe/issues/137

I also noticed this issue, which has been fixed: https://github.com/google/oboe/issues/245

Does this mean the code labs documentation should be pointing to a branch that will stay current, instead of a branch that might become outdated due to some sdk-related updates/deprecations?

Cheers,
Matthew Strom

**Comment by dturner** [comment]
This issue has been fixed on the `io18codelab` branch (which is the one which the codelab refers to). At some point I intend to update the codelab to use a recent stable release. Issue filed https://github.com/google/oboe/issues/501
