### ISSUE TITLE
FFT for spectrum view

### ISSUE THREAD

**Issue by westside** [google/oboe#405]
Thank you for great library. 

I want to visualize my voice by using spectrum data (FFT)
Now I'm considering FFTW(http://www.fftw.org/) but need to install something in android. 
Is there any suggestion like built in library set for it?

**Comment by philburk** [comment]
There are no FFT libraries built into Android. The FFT is pure math so it is better to do that outside the OS.  I believe that FFTW is available in source code form so you could just copy the code into your app. 

FFTW is under GPL. So make sure you are aware of how the GPL license works.

FFTs usually use a power-of-2 block size so you may be affected by this bug: https://github.com/google/oboe/issues/188

**Comment by westside** [comment]
Thank you for commenting possible issue. 

The reason I asked example is to make sure the way to get audio data before FFT. 
For example, when getting mic data, I can get audio data by doing below. 
And I cannot control numFrame when using callback. 
Is that right? 

```
oboe::DataCallbackResult LiveEffectEngine::onAudioReady(
oboe::DataCallbackResult LiveEffectEngine::onAudioReady(
    oboe::AudioStream *oboeStream, void *audioData, int32_t numFrames) {

    if(oboeStream->getFormat() == oboe::AudioFormat::Float)
    {
        float* dataFloat = (static_cast<float*>(audioData));

        LOGE("input stream read else %f %f", dataFloat[0], dataFloat[1]);
    } else  if(oboeStream->getFormat() == oboe::AudioFormat::I16) {
        uint16_t *dataInt = static_cast<int16_t *>(audioData);
        LOGE("test %d %d %d", dataInt[0], dataInt[1], dataInt[numFrames - 1]);
    }

}
```

**Comment by dturner** [comment]
You can specify a fixed `numFrames` in the callback by calling `AudioStreamBuilder::setDataCallbackSize`, although you may run into the bug that Phil mentioned above (due to be fixed this week). You could also gather data inside `onAudioReady` until you have enough to perform your FFT.

**Comment by dturner** [comment]
Please reopen if you still have issues.
