### ISSUE TITLE
release 1.2 with some new bug fixes

### ISSUE THREAD

**Issue by philburk** [google/oboe#407]
Fix crash caused caused by error callback running on a blocking read/write stream that does not use a data callback. https://github.com/google/oboe/pull/364

Fix locks in flush(). https://github.com/google/oboe/pull/378

Stop stream when callback returns a Stop code. Workaround for some AAudio bugs. https://github.com/google/oboe/pull/323

Plus many improvements in the samples and OboeTester.

**Comment by dturner** [comment]
Attempt to release by 22nd March
