### ISSUE TITLE
unit tests fail with "libandroidicu.so" not found

### ISSUE THREAD

**Issue by philburk** [google/oboe#421]
After fixing #318,

export PATH=$PATH:/Users/philburk/Library/Android/sdk/cmake/3.6.4111459/bin 
export ANDROID_NDK=/Users/philburk/Library/Android/sdk/ndk-bundle 
export ANDROID_HOME=/Users/philburk/Library/Android/sdk

and running ./run_tests.sh
I get this error:

03-26 16:33:10.608  6959  6986 E com.google.oboe.tests.unittestrunner.MainActivity: ERROR: CANNOT LINK EXECUTABLE "/data/user/0/com.google.oboe.tests.unittestrunner/files/testOboe": library "libandroidicu.so" not found

**Comment by dturner** [comment]
The resulting test binary should be the same whether compiled on MacOS or Linux. The only difference I can see is that I'm using a different Cmake version: /Users/donturner/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake

My NDK version is r20.0.5344622 rc1. Are you using the same one? 

Also, I just created a pull request #423 which removes the android include paths from `CMakeLists.txt` (they were causing the build to fail on my machine). Could you try that one out and see if it fixes it. 

Lastly you might want to try a different emulator. I'm successfully running on Pixel 2 API 28 emu.

**Comment by philburk** [comment]
I tried the pull request #423 on a Marlin running the current master.
Same as before.  I still get the error:
     library "libandroidicu.so" not found

> My NDK version is r20.0.5344622 rc1. Are you using the same one?

How do I check that?

**Comment by dturner** [comment]
You can check in Android Studio under Tools->SDK manager->SDK tools: 

![image](https://user-images.githubusercontent.com/873212/55319404-b3210e80-546c-11e9-9bbd-854f47f2af6a.png)

**Comment by philburk** [comment]
I updated the NDK through the interface that Don described.
Now the tests build and run.
I did see an error saying it could not install the UnitTestRunner because the signatures did not match.
So I uninstalled the old test app and then it ran.

I did see two failures:
04-02 17:03:43.168 11746 11794 D com.google.oboe.tests.unittestrunner.MainActivity: [  FAILED  ] StreamStates.OutputStreamStateIsStartedAfterStarting
04-02 17:03:43.168 11746 11794 D com.google.oboe.tests.unittestrunner.MainActivity: [  FAILED  ] StreamStates.InputStreamStateIsStartedAfterStarting

But I think those are actual test failures. The test framework is working OK.
