### ISSUE TITLE
Request for more information or examples on using Raw audio input

### ISSUE THREAD

**Issue by strommj** [google/oboe#422]
Just a little background in case you want to look: https://stackoverflow.com/questions/55319981/raw-files-arent-playing-or-are-playing-incorrectly-oboe-android-ndk

Even though I seem to be doing everything I need to configuration-wise, and converting in between floats and int16_t for buffer queuing, etc, I still can't get my app to play a raw sound.

It would be helpful if there was a starter/introduction example that simply plays a raw audio sound.  I am using some of the classes from the Rhythm Game example (before the recent commit) to render my audio, but it's tough to gauge what I'm doing wrong.

P.S.  Is it my raw file?  I exported a audio sample from audacity into a "Other Uncompressed" -> Raw (headerless) -> Signed 16-bit PCM.

**Comment by dturner** [comment]
Answered on SO. Please reopen if you're still having issues.
