### ISSUE TITLE
Flaky test: StreamStates.InputStreamLeftRunningShouldNotInterfereWithNextOpen 

### ISSUE THREAD

**Issue by dturner** [google/oboe#425]
This test often fails when running on the emulator. Let's discuss during next meeting.

**Comment by philburk** [comment]
There is a known race condition in AudioPolicyManager that can cause an open to fail if called immediately after a close.

A workaround would be to add a usleep(200*1000) between the calls to closeStream() and openInputStream().

I tried to run on the emulator. But I only have Nexus 5 installed. It complains about an "incompatible target".
darwin-x86_64 vs arm64-v8a
