### ISSUE TITLE
Stream state is not updating correctly in AAudio input stream

### ISSUE THREAD

**Issue by taemincho** [google/oboe#432]
Hi Phil and Don,

Device name: HUAWEI nova 2i
Android version 8.0.0
Oboe from the latest `master` branch.

I opened an AAudio input stream with a data callback, and called `requestStart()`, but the stream remained in `Starting` state and never proceeded to `Started` state.
However, the data callback was regularly called while the state was in `Starting`. 
I mean the state was actually `Started` but the state was not updated correctly to `Started`

Thank you for your hard work.
Taemin

**Comment by philburk** [comment]
There were state transition bugs in early AAudio. We can maybe work around that by changing the Oboe state to STARTED after the first successful callback or write().

**Comment by philburk** [comment]
We cannot fix the old version. So I added a workaround to Oboe that forces state Starting to Started.

**Comment by atneya** [comment]
Is this fixed?

**Comment by philburk** [comment]
We have a workaround in Oboe.
