### ISSUE TITLE
Using oboe to record incoming and outgoing voice/telephony calls

### ISSUE THREAD

**Issue by sheraz-nadeem** [google/oboe#447]
Hello Everyone,

First of all, thanks for such a great effort to provide us with low-latency Android API that we, as developers, can use it in our apps. 

Currently, I am a bit stuck with Oboe and trying to figure out a way to record incoming/outgoing voice/audio streams using oboe in a telephony audio call. I am able to successfully record my voice in a telephony call but I cannot hear other side's voice in the recorded audio. 

Following is the device log printed when I request opening a recording stream with deviceId = MediaRecorder.AudioSource.VOICE_CALL(4) or VOICE_UPLINK(2) or VOICE_DOWNLINK(3)

> I/AAudioStream: AudioStream::open() rate = 48000, channels = 2, format = 1, sharing = SH, dir = INPUT
> I/AAudioStream: AudioStream::open() device = 2, perfMode = 12, callback: ON with frames = 0
> 
> D/OboeAudio: AudioStreamAAudio.open: AAudioStream_Open() returned AAUDIO_OK, mAAudioStream = 0x8eb7ce00
> 
> D/AAudio: AAudioStream_requestStart(0x8eb7ce00) called --------------
> **D/AudioStreamLegacy: onAudioDeviceUpdate() deviceId 6**
> D/AAudio: AAudioStream_requestStart(0x8eb7ce00) returned 0 ---------

As you guys can see that onAudioDeviceUpdate method is called and now DeviceId is changed to VOICE_RECOGNITION(6). Is there something I am doing wrong or is the Android system not allowing me to record VOICE_CALL feature? I have tested on Android Samsung J4 device (API Level 27) & Samsung Note 3 Neo (Api Level 18). 

On API Level 27, when I set recording device as VOICE_COMMUNICATION(7) then I get following error in the logcat.

> D/OboeAudio: openStream() INPUT -------- Oboe version 1.1.1 --------
> D/OboeAudio: AAudioLoader():  dlopen(libaaudio.so) returned 0x96181087
> W/OboeAudio: AAudioLoader could not find AAudioStreamBuilder_setUsage
> W/OboeAudio: AAudioLoader could not find AAudioStreamBuilder_setContentType
> W/OboeAudio: AAudioLoader could not find AAudioStreamBuilder_setInputPreset
> W/OboeAudio: AAudioLoader could not find AAudioStreamBuilder_setSessionId
> W/OboeAudio: AAudioLoader could not find AAudioStream_getUsage
> W/OboeAudio: AAudioLoader could not find AAudioStream_getContentType
> W/OboeAudio: AAudioLoader could not find AAudioStream_getInputPreset
> W/OboeAudio: AAudioLoader could not find AAudioStream_getSessionId
> D/OboeAudio: AudioStreamAAudio() call isSupported()
> D/AAudio: AAudioStreamBuilder_openStream() called ----------------------------------------
> D/AAudio: AudioStreamBuilder(): mmapPolicy = 1, mapExclusivePolicy = 1
> W/AAudio: AudioStreamBuilder(): EXCLUSIVE sharing mode not supported. Use SHARED.
> I/AAudioStream: AudioStream::open() rate = 0, channels = 2, format = 1, sharing = SH, dir = INPUT
> I/AAudioStream: AudioStream::open() device = 7, perfMode = 12, callback: ON with frames = 0
> D/AudioStreamRecord: AudioStreamRecord::open(), request notificationFrames = 0, frameCount = 0
> E/AudioRecord: Could not get audio input for session 4297, record source 6, sample rate 0, format 0x1, channel mask 0xc, flags 0x5
> W/AudioRecord: removeAudioDeviceCallback removing different callback!
> E/AudioStreamRecord: AudioStreamRecord::open(), initCheck() returned -19
> D/AAudioStream: destroying 0x8e750500, state = AAUDIO_STREAM_STATE_CLOSED
> D/AAudio: AAudioStreamBuilder_openStream() returns -896 = AAUDIO_ERROR_INTERNAL for (0x0) ----------------
> D/OboeAudio: AudioStreamAAudio.open: AAudioStream_Open() returned AAUDIO_ERROR_INTERNAL, mAAudioStream = 0x0

When I print the Oboe::Result when opening the recording stream, I get following error statement printed in logcat.

`oboe::convertToText(result) => ErrorInternal`
which isn't helpful.

Waiting anxiously for your help on this, as I have been struggling with this for more than a week now and I can't seem to figure our the mistake that I am doing.

Thanks

**Comment by philburk** [comment]
Those recording sources may only be used by system apps. This is designed to prevent apps from eavesdropping on telephone conversations.

See here for more information. https://developer.android.com/reference/android/media/MediaRecorder.AudioSource.html#VOICE_CALL

**Comment by louiewh** [comment]
Thanks  I have same problem?
I want  recording voice_uplink and voice_downlink at same time,   voice_uplink voice_downlink  are recorded by two AudioRecord.  but, Android don't allow two AudioRecord working at the same time.
so I have two problem
1. oboe can record two audio devices at same time ？
2. oboe can record voice_uplink and voice_downlink  capacity 

My app is system app. have [Manifest.permission.CAPTURE_AUDIO_OUTPUT] permission.
