### ISSUE TITLE
Generate sound file in computing time

### ISSUE THREAD

**Issue by luizmello** [google/oboe#449]
Hi, 

I would like to generate and save a sound file, for example a .wav file.
I need to make this sound file in computing time, like generate a file with 1 minute sound file from 100Hz sine wave oscillator, but without waiting 1 min playing and recording. 

Does someone know if this is possible ? Or has any suggestion ?

Thanks !

**Comment by philburk** [comment]
Oboe is designed for real-time audio I/O. It cannot do non-real-time I/O.

But there are lots of other options. Audacity has a signal generator function that lets you create WAV files using various formulae. If you want to get fancy, CSound can create very complex sound files is non-real-time.

You can also create files using the non-real-time option in JSyn. Here is an example.
https://github.com/philburk/jsyn/blob/master/tests/com/jsyn/examples/RecordSineSweep.java

Please use Google to get more information on these tools.

**Comment by luizmello** [comment]
Hi Phil, thanks for the info and directions. 
Best
