### ISSUE TITLE
RhythmGame codelab missing SoundRecording class

### ISSUE THREAD

**Issue by GreySage** [google/oboe#459]
It seems like the SoundRecording class was removed from the project entirely. The RhythmGame [codelab](https://codelabs.developers.google.com/codelabs/musicalgame-using-oboe/index.html#0) associated with it does not reflect this change, and in fact the first coding instruction is to use this non-existing class.

Can the codelab be updated to have useful instructions, or at least an example of a workaround be posted in the readme?

**Comment by dturner** [comment]
It's certainly not ideal that the latest version of RhythmGame has had many more updates than the original codelab version, however, you can still get to the original version by doing: 

`git checkout io18codelab` (which is in the original instructions although easy to miss)

I just tried it and it compiles, however, I ran into this issue: #247
