### ISSUE TITLE
ambix audio file

### ISSUE THREAD

**Issue by f0831027** [google/oboe#462]
hi ,
I am working in oboe on android.
If I need to use ambix audio file ,is this possible in oboe library?
Ambix audio file is  4 channel count. Do oboe support channel count more than 2?

**Comment by philburk** [comment]
Oboe supports uncompressed PCM with multiple channels.
If you can convert the Ambix file to PCM,
and you have a 4 channel USB device, for example a Scarlett 2i4,
then you can play that file.
Use builder.setChannelCount(4).
