### ISSUE TITLE
Publish a test app which uses the current version of oboe

### ISSUE THREAD

**Issue by dturner** [google/oboe#465]
Idea is to take a snapshot of the current release on a separate repo.

**Comment by philburk** [comment]
Purpose is to test the marmot scripts that search for symbol names in an app on the Play Store.
It does not matter if people download this app.

**Comment by atneya** [comment]
https://github.com/philburk/android-fxlab

**Comment by dturner** [comment]
> Purpose is to test the marmot scripts that search for symbol names in an app on the Play Store.

We can already do this. Closing.
