### ISSUE TITLE
Need lots of unit tests

### ISSUE THREAD

**Issue by philburk** [google/oboe#47]
If someone could figure out how to build one simple test then I could leverage a bunch of AAudio tests from CTS.

**Comment by philburk** [comment]
A good first test would be one that just tested oboe::convertFormatToSizeInBytes().

BTW, AAudio CTS tests at:
https://android.googlesource.com/platform/cts/+/master/tests/tests/nativemedia/aaudio/src/test_aaudio.cpp

**Comment by dturner** [comment]
Would you prefer to test on the host, device or both? Here's the pros and cons of each: 

** Host **
Pros: Fast
Cons: Source under test cannot depend on any Android APIs, not supported by the Android Studio/gradle/Cmake build system

** Device **
Pros: Somewhat supported by Android Studio, source under test can depend on Android APIs
Cons: Slow(er) as tests must be deployed to device each time

**Comment by dturner** [comment]
Unit testing structure now in place. For now we'll just test on device.

**Comment by dalecurtis** [comment]
I think this was closed prematurely. This was about adding tests to cover the capabilities of the library, not just adding a unit test harness. There are only 2 tests at present. In order for Chrome to consider adopting the library, the security team has required stronger test coverage.

**Comment by philburk** [comment]
Now that we have a basic test harness, we need to add lots of tests.

**Comment by philburk** [comment]
This is needed for internal bug b/71872740

**Comment by dalecurtis** [comment]
Great! Thanks for the tests. What's your assessment of the coverage / remaining gaps?

**Comment by philburk** [comment]
We could also take some of the AAudio CTS tests and port them to Oboe.

**Comment by dturner** [comment]
> What's your assessment of the coverage / remaining gaps?

Good question. I haven't done any kind of test coverage analysis yet. Are there any tools you'd recommend? 
 
> We could also take some of the AAudio CTS tests and port them to Oboe.

Excellent idea, let's discuss tomorrow.

**Comment by dalecurtis** [comment]
Clang has some nice coverage tooling built in, here are some docs on how we use it in Chromium:
https://chromium.googlesource.com/chromium/src/+/master/docs/code_coverage.md

**Comment by dturner** [comment]
Started tracking device testing in this trix: https://docs.google.com/spreadsheets/d/167MMwO_zqq8K6x-6GinE7QV3P7_ePFQZOfY8EuAT2rQ/edit?usp=sharing

**Comment by dturner** [comment]
We have sufficient coverage for confidence in v1.0 so removing the milestone requirement. We still have a lot of work to do but we can launch without 100% coverage.
