### ISSUE TITLE
Buffer size changes dramatically when not using native sample rate

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#474]
Ok, so let's say a user loads a project (talking Audio Evolution Mobile here) that is made at 44100Hz. When playing back, CPU usage fluctuates dramatically:

Output stream is NOT low latency!
Play format = 4, usesAAudio = 1, frames per burst = 590
SetSampleBufferSize 590
Started Oboe OK!
Process 590 frames
Process 590 frames
Process 2 frames
Process 2 frames
Process 276 frames
Process 276 frames
Process 312 frames
Process 312 frames
Process 294 frames
Process 294 frames
Process 296 frames
Process 296 frames
Process 586 frames
Process 586 frames
Process 4 frames
Process 4 frames
Process 556 frames
Process 556 frames
Process 34 frames
Process 34 frames
Process 288 frames
Process 288 frames
Process 302 frames
Process 302 frames
Process 580 frames
Process 580 frames
Process 10 frames
Process 10 frames

(Pixel 2 running Android Q beta 2). On iOS, the buffer size fluctuates much less. I'm sure there must be a better way to make this less jumpy? The whole processing chain is called for rendering 2 or 4 frames, which of course causes high CPU load.

**Comment by philburk** [comment]
>  (talking Audio Evolution Mobile here) that is made at 44100Hz

The native sample rate for most devices is 48000 Hz. if you open at 44100 Hz then you cannot get a MMAP track, or a FAST track. AudioFlinger will force you through the "Normal" mixer, which adds latency. This is on the older Legacy path. Also the resampler algorithm on the Legacy path is very jumpy and causes these odd frame counts.

The only way to get a low latency path currently is to let AAudio choose the sample rate and then use that rate or do your own resampling.

**Comment by extreamsd** [comment]
I understand about the low latency path, but there are just situations that do not allow for this and not every use case requires low latency (if people only play and record audio without software monitoring or using soft synths). I am only saying that the jumps in frame counts are troublesome for these situations and the resampler could be optimized to reduce this problem as it is done on other platforms.

**Comment by philburk** [comment]
>  I am only saying that the jumps in frame counts are troublesome

I agree. I will pass this information to the engineer who works on that.

You can call builder.setFramesPerCallback(). In AAudio, that will cause the callbacks to be aggregated into one burst of that size. It can add a tiny amount of latency but not much. Less than a burst.

**Comment by extreamsd** [comment]
Cool, thanks!

**Comment by philburk** [comment]
The irregular callbacks are tracked internally with b/131601263

builder.setFramesPerCallback() can prevent it. So closing the bug.
