### ISSUE TITLE
One of the two getTimestamp()methods is not in the documentation

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#478]
virtual Result getTimestamp(clockid_t clockId,
                                int64_t *framePosition,
                                int64_t *timeNanoseconds)

is in the doxygen docs, but I stumbled upon 

virtual ResultWithValue<FrameTimestamp> getTimestamp(clockid_t clockId)

in a code example and couldn't find it in the docs.

**Comment by philburk** [comment]
Thanks for spotting that.  The second one is now the one to use. See https://github.com/google/oboe/issues/209

We should deprecate the first one and make sure the sample code calls the second one, getTimestamp(clockid_t clockId).
