### ISSUE TITLE
problem with calling oboe::AudioStream-functions

### ISSUE THREAD

**Issue by SchmadenSchmuki** [google/oboe#48]
Experienced the following problem and I think (hope) it's not a fault in my code:
I have "static oboe::AudioStream* pOboeAudioStream(nullptr);" after my #include-lines in the native-lib.cpp.
When I call "oboe::AudioStreamBuilder.open(&pOboeAudioStream);" directly in a native function, it works as expected, stream is opened and I can call the stream functions also outside this specific function.

But when I go one step further nested I'm getting troubles.
So when I try something like:
JNIEXPORT jint JNICALL
Java_schmaden_programme_android_test_MainActivity_makeOboeAudioStream()
{
     callFunctionThatDoesAllTheBuilderSetUpAndOpensStream(pOboeAudioStream);
     return 0;
}
I get a crash with the first call that uses pOboeAudioStream outside of callFunctionThatD... . So I can call requestStart() or any other function related to pOboeAudioStream only inside this function. 
The only way to get some sound  is to call requestStart() inside of callFunctionThatD... .

If I call requestStop() outside callFunctionThatD... in the following way:
if(pOboeAudioStream != nullptr) pOboeAudioStream->requestStop();
nothing happens, no stopping, no crash.

As said before it works with the first method, so it's not a problem when you know it, otherwise it's pretty unexpected.

I set up a callback in the builder (if that matter), the code was executed on Android emulator API 27.

**Comment by dturner** [comment]
What is the crash? Presumably a null pointer dereference? Please could you post the stack trace.

**Comment by SchmadenSchmuki** [comment]
The last line in android studio logcat is:
01-12 11:29:12.894 29799-29799/jogi.programme.android.testrequeststartproblem A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 29799 (eststartproblem), pid 29799 (eststartproblem)
Everything before is normal.
Looks like it could be what you said.
For a stack trace, can I get that easily, do I have to use systrace. If so, then that would take some time, I'm not into that yet (though I'm planning to get to know it at some point).

**Comment by dturner** [comment]
Please post everything that comes after the SIGSEGV line, that should give more of a clue as to where the crash is coming from.

**Comment by philburk** [comment]
I suspect the problem is in not passing a pointer to the stream pointer:

This code:
  int16_t OpenOboeStreamFunctions::openStreamRequestStart(oboe::AudioStream* stream,
  oboe::AudioStreamBuilder* builder) {
     oboe::Result result(builder->openStream(&stream));

should  use "**stream" not "*stream":
  int16_t OpenOboeStreamFunctions::openStreamRequestStart(oboe::AudioStream** stream,
  oboe::AudioStreamBuilder* builder) {
     oboe::Result result(builder->openStream(stream));         // <== NO & !!!!!

Then call with an &:
openOboeStreamFunctions.openStreamRequestStart(&pOboeAudioStream, &localBuilder);

Let me know if that helps.

**Comment by SchmadenSchmuki** [comment]
Thanks for the help.
Tried
oboe::Result result(builder->openStream(stream)); // <== NO & !!!!!
but it doesn't compile, I get the following error:
Error:(57, 45) error: cannot initialize a parameter of type 'oboe::AudioStream **' with an lvalue of type 'oboe::AudioStream *'
Strange thing is, when press ctrl and hover over openStream,  the preview I get says declared in "AudioStreamBuilder.h" and "oboe::AudioStream *" is needed.
When I follow the link, android studio shows me "AudioStreamBuilder.cpp" and "oboe::AudioStream **"
for calling the function.

**Comment by philburk** [comment]
I just notice that GitHub removed the double star from my message! The code that I see now in my email is wrong! I will try to fix the message above.

openStreamRequestStart() must be declared with a double star, a pointer to a pointer. But I can't seem to type that without it getting removed.

The builder->openStream() call passes back a pointer to an AudioStream. So you must pass it a pointer to a pointer.

If Preview looks out of sync with the real code, try adding a comment to your CMakeLists.txt file and doing a gradle sync. That can sometime kick it back into sync.

**Comment by SchmadenSchmuki** [comment]
@philburk 
Thanks you, that worked, will make my life a lot easier.

Really have to learn the basics better, never would have thought of that.
(To be honest, I still don't get it, because in the working case I also used openStream(&pOboeAudioStream);.
The only difference I see is one time the function was called over the instance (the working version localBuilder.openStream(&pOboeAudioStream);), the other time with pointer dereference of builderpointer (the problemversion builder->openStream(&stream);), with pOboeAudioStream and stream both being an oboe::AudioStream*.
But I have to read about, think on and play with that tomorrow.)

Thanks a lot.

**Comment by philburk** [comment]
You were passing Oboe a pointer to a pointer. That's good.

But you were passing a pointer to the variable declared in your function.
It received the pointer to the new stream. But it was immediately discarded.

After the fix, you passed a pointer to the variable declared in your object.
That is the one that needed to be set.
