### ISSUE TITLE
Documentation: Full guide - Known issues needs an update

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#482]
There are 5 methods mentioned in "The following methods are defined, but will return Result::ErrorUnimplemented:"

But at least some if not all are implemented, perhaps depending on Android or Oboe version.

**Comment by dturner** [comment]
Thanks for the feedback, we'll get it updated.

**Comment by atneya** [comment]
All 5 function in AAudio, last two don't in OpenSLES.
