### ISSUE TITLE
Questions on power consumption

### ISSUE THREAD

**Issue by ishitatsuyuki** [google/oboe#484]
This post contains several assumptions based on personal investigation; please correct me if any of them are wrong.

I did a thorough inspection of AAudio codebase and I believe that AAudio use a fixed burst size (which is commonly known as period size) targeted for low latency.

Having a small burst size means that the system mixer loop is ran at a high frequency, waking up the CPU very often (and hinder low power states) and decreasing battery life.

Based on this, does it mean that **AAudio/Oboe only targets low latency (and highly interactive) workloads**? To put it the way around, is AAudio to avoid if one's writing a music player, or whatever that runs in background?

**Comment by philburk** [comment]
You don't need low latency for streaming. High latency is actually better.
If you are writing a streaming music player then we recommend using

    builder.setPerformanceMode(PerformanceMode::PowerSaving);

or PerformanceMode::None

BTW, we have found that the low latency mode uses very little extra power.
So don't be afraid to use it if you need it.

Phil Burk

**Comment by ishitatsuyuki** [comment]
I think you missed the point. As I read the AAudio system service source it seems that it doesn't try to use high latency (a big period size) at all.

And currently `PerformanceMode::PowerSaving` just seems to be a noop.

> BTW, we have found that the low latency mode uses very little extra power.

It's not that LL mode is efficient, it's that AAudio doesn't care about power consumption at all, even in normal mode.

**Comment by philburk** [comment]
You can use AAudio for either low latency normal or high latency
applications. Just set the performance mode to tell the system what you are
trying to do.

A lot of the code you were seeing may have been the low-latency code that
uses the MMAP data path in AAudio. That is a new data path designed for low
latency. But if you request normal or high latency then you will go through
the old AudioFlinger, which is the path that has been in Android for years.

So yes you can use AAudio for streaming. but AAudio was not designed
primarily for streaming. It does not support compressed audio modes like
MP3 or AAC. It only supports PCM.

AAudio was designed for two main reasons one was to provide a
high-performance low latency path using MMAP. The other was to provide an
API that is easier to use than OpenSL ES for native code.

Phil Burk

**Comment by ishitatsuyuki** [comment]
Oh, my mistake. I missed that legacy code path. Your explanation was very helpful.

I think the question is resolved now, closing.
