### ISSUE TITLE
OboeTester: round trip latency test loops using OpenSL ES

### ISSUE THREAD

**Issue by philburk** [google/oboe#485]
On Pixel 3aXL

REPRODUCE
Launch OboeTester
Press ROUND TRIP LATENCY
Press green bars to open settings.
Select Open SL ES API for input and output.
Press OPEN
Press START

EXPECT
Some Latency measurement

ACTUAL
Endless spew of 
05-08 11:38:25.122 18681 19629 D OboeAudio: numInputFrames (   0) < numOutputFrames (  96) so reset analyzer
05-08 11:38:25.122 18681 19629 D OboeAudio: state reset to STATE_INITIAL_SILENCE
05-08 11:38:25.124 18681 19629 D OboeAudio: numInputFrames (   0) < numOutputFrames (  96) so reset analyzer
05-08 11:38:25.124 18681 19629 D OboeAudio: state reset to STATE_INITIAL_SILENCE

I think this is a bug in the test or in Oboe. Not Android.

**Comment by atneya-nair** [comment]
The issue also occurs when using AAudio API (same logcat), the latency measurements zero out instead of no response.

**Comment by philburk** [comment]
This may be related to asking for Float input, which causes a loss of FAST record path. So the buffer sizes do match up.

**Comment by philburk** [comment]
There is also a problem with the buffer sizes. When OpenSL gets a PerformanceMode::None stream it still uses the small buffers (96) which does not work with the 960 frame buffers used in the underlying data path.
