### ISSUE TITLE
LiveEffect: Performance issue on Android P

### ISSUE THREAD

**Issue by miqouser** [google/oboe#489]
First of all. How does the app work if device is blocked (is in sleep mode) or the app is in background, if there is no background/foreground services working ? 
And the main question is in touch with above. I am doing some real time audio processing, everything seems good when device is awake, both with AAudio and OpenSL ES. But when the device goes to sleep mode (ex. after 1 minute when the screen turns off), it seems the performance falls and I listen some glitches. 

So:
When device **is awake**, everything suits my needs. 
When device **goes to sleep mode** there are some glitches.
When device **is unlocked** everything is ok again.

Here is the Logcat of my processing, there is time difference between processing starts and after it ends in milliseconds. For me that difference must be <20ms, otherwise I will face glitches.

**When device is awake we see it's ok:**

V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 2 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 1 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 1 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 2 
V/AUDIO-APP: total_time______ 1 
V/AUDIO-APP: total_time______ 1 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 10 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 10 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 10 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 13 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 13 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 10 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 3 
V/AUDIO-APP: total_time______ 10 

**When device is in sleep mode:**

V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 13 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 14 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 14 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 14 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 14 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 11 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 15 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 17 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 11 
V/AUDIO-APP: total_time______ 5 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 17 
V/AUDIO-APP: total_time______ 11 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 11 
V/AUDIO-APP: total_time______ 4 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 15 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 16 
V/AUDIO-APP: total_time______ 52 
V/AUDIO-APP: total_time______ 10 
V/AUDIO-APP: total_time______ 19 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 18 
V/AUDIO-APP: total_time______ 10 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 16 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 14 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 16 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 14 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 15 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 10 
V/AUDIO-APP: total_time______ 28 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 13 
V/AUDIO-APP: total_time______ 18 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 14 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 37 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 11 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 15 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 12 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 13 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 15 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 8 
V/AUDIO-APP: total_time______ 15 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 6 
V/AUDIO-APP: total_time______ 17 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 59 
V/AUDIO-APP: total_time______ 17 
V/AUDIO-APP: total_time______ 7 
V/AUDIO-APP: total_time______ 9 
V/AUDIO-APP: total_time______ 18 

We see a few packets processed in 59, 52, 28, 37 ms, and globally on average, the time of processing has doubled.

**Comment by atneya** [comment]
When the device goes to sleep, the device attempts to lower CPU usage to conserve battery. If your app does not want this to happen (in order to preserve low latency audio), there are existing APIs in place to prevent this reduction in performance. See https://developer.android.com/training/scheduling/wakelock

**Comment by atneya** [comment]
Additionally, avoid using LOGCAT in real-time threads, as it incurs a performance penalty. Using a systrace is usually a better alternative.

**Comment by miqouser** [comment]
Fixed this by launching liveEffect in foreground service and moving my processing outside "onAudioReady" callback to another thread, and yes, by removing logs, closing.
