### ISSUE TITLE
Support format, sample rate and channel count conversion on LowLatency streams

### ISSUE THREAD

**Issue by dturner** [google/oboe#493]

**Comment by philburk** [comment]
Scenarios where conversion is required to get low latency:

- OpenSL ES, Input, format=float
- OpenSL ES, Input, stereo on M(?), because of heap size issue
- All, Rate != 48000
- MMAP, mono, V8.1

**Comment by philburk** [comment]
Some links on resampling:
https://en.wikipedia.org/wiki/Lanczos_resampling
https://en.wikipedia.org/wiki/Sample-rate_conversion
https://en.wikipedia.org/wiki/Sinc_function
https://ccrma.stanford.edu/~jos/resample/
https://ccrma.stanford.edu/~jos/pasp/Windowed_Sinc_Interpolation.html
MultiRate Processing https://www.eetimes.com/document.asp?doc_id=1204860
https://www.earlevel.com/main/2010/11/23/towards-a-practical-oversampling-filter/
http://users.isy.liu.se/en/rt/fredrik/spcourse/splines.pdf

**Comment by philburk** [comment]
Fixes #276 
Fixes #271

**Comment by atneya** [comment]
Can we confirm if this fixing this issue addresses #181 #201 and #212 ? If so, can we add them all to the PR so it closes all these issue, as well as the two you referenced  @philburk

**Comment by philburk** [comment]
Yes, #181 #201 and #212 are related.

**Comment by philburk** [comment]
I will leave #181 and #201 open. They still need specific support in the QuirksManager
