### ISSUE TITLE
relocate oboe CMakeLists.txt closer to oboe lib source

### ISSUE THREAD

**Issue by ggfan** [google/oboe#496]
The [CMake script](https://github.com/google/oboe/blob/master/CMakeLists.txt) file for oboe lib could stay closer to the source file ( under src directory ), so we have

- src for the oboe lib
- samples for the apps

Android studio sometimes has some trouble with relative path above project root directory, this might be able to avoid that.

**Comment by atneya-nair** [comment]
The oboe lib depends on the /include directory, and since the CMake file for the lib should live above its dependencies, it should remain at the project root. An alternative would be making a subfolder for just the include and src directories, however this would break standard convention.
