### ISSUE TITLE
Clean up unused branches

### ISSUE THREAD

**Issue by dturner** [google/oboe#508]

**Comment by atneya** [comment]
Candidates are:
cdep - One line change in documentation which is no longer applicable
multichannel - I think these changes were merged into hello-oboe
addjavaenv - Unsure, appears to be some extra tests
devicelist - Has measurements for latency, should we merge this in?
instrumentedcallback - Unsure
testbadformat - A single test to make sure OpenSLES checks formats

**Comment by dturner** [comment]
As a backup I have forked Oboe to https://github.com/dturner/oboe. I then deleted a whole load of stale branches.
