### ISSUE TITLE
How can I add compression to mixer track/audio stream -newbie question-

### ISSUE THREAD

**Issue by erincdemir** [google/oboe#514]
Greetings Oboe Team,
Huge thanks for developing this library. Right now I am having so much fun while re-making my WebAudio synth from scratch without all the latency.

I added multi-touch support for polyphony and things went a little bit clipping so I guess I need a limiter. The issue is I really don't have any idea on how can I add audio effects. 

Thanks for your time again
Erinc

**Comment by erincdemir** [comment]
```

//Mixer.h stuff
 for (int i = 0; i < mNextFreeTrackIndex; ++i) {
            mTracks[i]->renderAudio(mixingBuffer, numFrames);

            for (int j = 0; j < numFrames * mChannelCount; ++j) {
                audioData[j] += mixingBuffer[j];
            }
        }

        //normalize
        float max=0.0f;
        for(int i = 0;i<numFrames*mChannelCount;i++){
            float value = fabsf(audioData[i]);
            if( max < value){
                max = value;
            }
        }
        if(max>=0.5f){
            for(int i = 0;i<numFrames*mChannelCount;i++){
                audioData[i] /=  max;
            }

        }
```
I tried adding this inside of Mixer.h. Now It limits the sound while I am single touching. But I am hearing crackles when I multitouch. Sorry for all of the rambling and stuff but can you please help me. I am not a wizard at DSP as you can see. Well, thanks for your time and efforts again.

**Comment by philburk** [comment]
This question is outside the scope of Oboe. Oboe just does I/O. Synthesis and DSP is too big a topic. 

But I can't help offering some advice:
For a polyphonic synth, you might have 1 voice or 64. So the range can really vary.
I often use an AGC with a 128 frame pre-delay. Check out:

https://en.wikipedia.org/wiki/Automatic_gain_control

Also search for Dynamic Range Control.

**Comment by erincdemir** [comment]
Humm, so I just went with dividing synth gains by touch pointer count. By the way thanks for answer and information.

I am closing this one.

Have a nice day/night
