### ISSUE TITLE
Conditional code for OpenSL ES float format on API 21+ won't work

### ISSUE THREAD

**Issue by dturner** [google/oboe#52]
This code (which I wrote) is intended to determine whether floating point format is available on this device based on the runtime API level:

https://github.com/google/oboe/blob/master/src/opensles/AudioOutputStreamOpenSLES.cpp#L112

However, `__ANDROID_API__` is a preprocessor define so will give the compile time API level (usually API 16) so floating point won't be available on *any* device. 

mnaganov@ has a solution in his pull request here: https://github.com/google/oboe/pull/51/commits/d35c572c56e312c8cef0e0eb31779ef8dcbb1ded#diff-d0e527b6330d249f712b4e30bf3dde92R96

**Comment by philburk** [comment]
This Issue could benefit from this Feature:  https://github.com/google/oboe/issues/56

**Comment by philburk** [comment]
We can use the new query added in https://github.com/google/oboe/pull/64
to decide whether to do float conversion in Oboe.
