### ISSUE TITLE
Delete Audio Streams in Samples

### ISSUE THREAD

**Issue by atneya** [google/oboe#524]
Currently, all of the samples use raw pointers for audio streams. Although the streams are eventually closed, they are never deleted. Best practice is to delete, especially if many streams are opened and closed subsequently for high perf. applications. We should update the samples to reflect mem. management best practice.

**Comment by philburk** [comment]
Note that after a stream is closed that it cannot be reopened. So deleting it after close would be a good idea.

**Comment by milos-pesic-sc** [comment]
@philburk This is a question that I wanted to raise with regards to error handling.
On an error - let's say in time point t1 - `oboe_aaudio_error_callback_proc` in `AudioStreamAAudio` gets invoked, a new thread is created that should execute `oboe_aaudio_error_thread_proc`. Before that thread gets a chance to execute error callback on the stream object - API consumer decides to close and delete the stream (i.e stream for a new track should be created). This happens let say at time point t2. But now the thread for handling the error gets the context and wants to invoke the error callback on a stream which just got deleted. I am able to reproduce the issue by artificially sleeping in the error handling thread before invoking the error callback on a stream - that gives me a chance to close the old stream and create a new one in between. Is there any way to prevent this from happening?

**Comment by philburk** [comment]
If you stop and close the stream before deleting it then there should be no
call backs that are active. The close calls should be protected by a lock.

**Comment by philburk** [comment]
Is this fixed?

**Comment by atneya** [comment]
On this PR.
