### ISSUE TITLE
Consider moving oboe samples into this repo

### ISSUE THREAD

**Issue by dturner** [google/oboe#53]
Why? 

It's easier to keep the samples and the library in sync with one another when they're in the same repo. There have been a few instances recently where the sample and the library are incompatible  because Oboe has been updated but the sample hasn't. 

When making changes on a topic branch we could make sure that tests, samples and code were all updated together. 

It would also make the samples' CMake configuration slightly less complex because there'd be no need to clone oboe inside of CMake.

**Comment by philburk** [comment]
I like the idea of having everything in sync.

Will this make it any more complicated for developers to clone just the Oboe library in their projects?

**Comment by dturner** [comment]
It shouldn't - it'll just be an extra "samples" folder which contains an Android Studio project.

The only downside is that there'll be some duplication of utility functions and UI code from the high performance audio repo. Not too much of a concern.

**Comment by dturner** [comment]
Fixed in https://github.com/google/oboe/commit/e3e55e6fa2977bd77cc488302a98af8ee8015319
