### ISSUE TITLE
Audio capture fails but no error result when mic in use by another app

### ISSUE THREAD

**Issue by Jim-Foo** [google/oboe#539]
I have a situation where an app (not mine) fails to release audio capture when home or back button pressed. Oboe returns no error but there seems to be no callbacks. How to get an error so I know what's happening and deal with it? Java code will throw an excetion when trying to set input as MIC.

**Comment by Jim-Foo** [comment]
It looks like the way to do this is in java code unless the way that a stream is opened is refactored. The following function is from AudioStream.cpp

Result AudioStream::open() {
    // Parameters are validated by the underlying API.
    return Result::OK;
}

**Comment by Jim-Foo** [comment]
Ignore that about the empty function. It's a virtual method overriden elsewhere.

**Comment by philburk** [comment]
You should get an error return code when the stream open fails:

oboe::Result result = builder.openStream(&stream);

Are you getting an error code?

**Comment by Jim-Foo** [comment]
openStream returns OK. Checking with getSampleRate() etc looks ok. The hardware I'm using is api 24 so it's SL ES.

**Comment by Jim-Foo** [comment]
requestStart() returns OK

logcat

I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x1, using default mask 0x10 based on channel count of 1)
I/AudioFlinger: AudioFlinger's thread 0xaae83d40 ready to run
I/AudioRecord: AUDIO_INPUT_FLAG_FAST successful; frameCount 0
D/OboeAudio: AudioInputStreamOpenSLES(): requestStart() called
D/OboeAudio: AudioInputStreamOpenSLES::setRecordState_l(3)
E/APM_AudioPolicyManager: startInput(32102) failed: other input 31862 already started
E/AudioRecord: start() status -38

**Comment by philburk** [comment]
> openStream returns OK.

Oh. Right. I forgot the microphone access is checked in the start method.  I found a way to reproduce the problem.

Launch a Voice Recorder app,
start recording,
click Home key to put recorder in background.
Launch OboeTester,
click TEST INPUT
Select AAudio API
click OPEN, succeeds
click START, fails with error Toast
click STOP and CLOSE
Select OpenSL ES API
click OPEN, succeeds
click START

I expect to see an error.
But I do not see an error.

The OpenSl ES SetRecordState returns 0.  And the Enqueue returns 0.
So I think this is a bug in OpenSL ES.
I will file an internal bug against OpenSL ES and try to find a workaround.

**Comment by Jim-Foo** [comment]
I did a test using OpenSL ES directly. It seems to confirm that it's an OpenSL ES bug. The logcat message "E/AudioRecord: start() status -38" coincides with SetRecordState(RECORDING) which returns SL_RESULT_SUCCESS.

**Comment by philburk** [comment]
Internal reference:  b/136590252

**Comment by philburk** [comment]
This cannot be fixed in Oboe. So closing it here. We will continue this internally.

**Comment by ryondev** [comment]
Meet a same bug, is the problem in OpenSL ES fixed ?

**Comment by lucaszanella** [comment]
Also having this bug. Is there a fix already?
