### ISSUE TITLE
setDeviceId does not change anything

### ISSUE THREAD

**Issue by nocola** [google/oboe#54]
Hello! Thanks a lot for this project. I tried it for streaming input and output, and it works great. But I wanted to change mic source for input stream by setDeviceId(int sourceFromAudioManager) and it did not work, no effect for different values. Ids were given   from AudioManager.java (api 23). For my app this behavior is very clitical. Are there any suggestions ?
P.S. Sory for my english :)

**Comment by nick-petrovsky** [comment]
@nocola this is not possible without AAudio when OpenSLES is used. Late I can refer the source line. Unfortunately manage source and sink not possible using public API.

**Comment by dturner** [comment]
Thanks for filing this issue. nick-petrovsky is correct, on API < 27 OpenSLES is used and OpenSLES does not support setting the device id. There's no way around this that I'm aware of.

The recommended approach when using `set*` methods is to call the corresponding `get` method on the stream after opening it to determine whether you got what you asked for. Example: 

    builder.setDeviceId(123);
    builder.openStream(&stream);
    if (stream->getDeviceId() == 123) print("Stream is using device Id 123");

In this case I would expect `stream->getDeviceId()` to return `oboe::kUnspecified`, however, from looking at the code it looks like it will return the value set using `setDeviceId` even though this is not supported.

@philburk - Is this correct?  If so, this is a bug which needs fixing.
