### ISSUE TITLE
.wav to Audio Stream

### ISSUE THREAD

**Issue by mekeo** [google/oboe#548]
I think we need more examples. I'm having difficulties in loading just a .wav  into a stream.
Would be nice to have a simple sample code for just a mixer with two bus streams, like Apple had with MixerHost.

**Comment by atneya** [comment]
Thanks for the suggestion.

What difficulties are you encountering in loading a .wav into a stream? The `RhythmGame` sample has examples in loading a mp3 to a stream if that could be of assistance.

A mixer sample sounds like a good idea, what exactly do you mean by two bus streams? For an example on mixing square waves, see `MegaDrone`.

**Comment by mekeo** [comment]
Thanks for the answer, atneya. Ok, I'm testing with RhythmGame, gonna try.

Two streams, I mean just two instruments audio files looped. Drum loop and a guitar riff, for example. And a mixer. Just to see how to stream and mix more than one audio file, like a very simple mixer.

It would be very helpful

**Comment by atneya** [comment]
Thanks for the suggestion, we are always looking for examples that are helpful to start out from.

**Comment by mekeo** [comment]
Well... trying to replicate a simple audio bus from RhythmGame... 

I think these samples are more complicated than should be, cause the main AudioStreamCallback class ( Game ) is very dependent on other classes ( AAsetDataSource, NDKExtractor, OpenGLFunctions, UtilityFunctions, and all linking with others ... ) complicating, specially for newbies in Android C++.

I think best sample code examples are the simplest and direct ones.

**Comment by mekeo** [comment]
The RhythmGame uses compressed .mp3 files, extrated with `AAssetDataSource::newFromCompressedAsset`, with  FFMpegExtractor, NDKExtractor ...

To get better sound quality need to use .wav or .aiff files, any library to get these instead of mp3 ?

Need an example to get data from .wav / .aiff files to the Player in a direct clear way.

**Comment by mekeo** [comment]
The RhythmGame uses compressed .mp3 files, extrated with `AAssetDataSource::newFromCompressedAsset`, with  FFMpegExtractor, NDKExtractor ...

To get better sound quality need to use .wav or .aiff files, any library to get these instead of mp3 ?

Need an example to get data from .wav / .aiff files to the Player in a direct clear way.

**Comment by philburk** [comment]
Oboe does not support sound file I/O. You could use libsndfile.
http://www.mega-nerd.com/libsndfile/

Or you could adapt something like the JSyn WAV and AIFF file parsers.
https://github.com/philburk/jsyn/tree/master/src/com/jsyn/util/soundfile

**Comment by mekeo** [comment]
> Oboe does not support sound file I/O. You could use libsndfile.
> http://www.mega-nerd.com/libsndfile/
> 
> Or you could adapt something like the JSyn WAV and AIFF file parsers.
> https://github.com/philburk/jsyn/tree/master/src/com/jsyn/util/soundfile

Thanks philburk! In c ? ups .. it's gonna be harder than i thought ... Just read a .wav file to the stream.
Any example code ?

**Comment by atneya** [comment]
Most sound file I/O libraries will have example code for decoding and encoding lossless. Decoding files are generally a very finicky task that should be left to libraries.

Libsndfile, which is used in PortAudio is a good general purpose I/O library. An example of reading and writing a WAV file can be found here: https://github.com/erikd/libsndfile/blob/master/examples/sfprocess.c

Using the library in a C++ should be as simple as using an `extern C`. I also believe libsndfile now has CMake support, we should make it easy to import into an existing NDK project.

**Comment by mekeo** [comment]
> Most sound file I/O libraries will have example code for decoding and encoding lossless. Decoding files are generally a very finicky task that should be left to libraries.
> 
> Libsndfile, which is used in PortAudio is a good general purpose I/O library. An example of reading and writing a WAV file can be found here: https://github.com/erikd/libsndfile/blob/master/examples/sfprocess.c
> 
> Using the library in a C++ should be as simple as using an `extern C`. I also believe libsndfile now has CMake support, we should make it easy to import into an existing NDK project.

How nice would be a sample example of it ... Many barriers to entry for developers not used to work with C++ on android

**Comment by mekeo** [comment]
> Oboe does not support sound file I/O. You could use libsndfile.
> http://www.mega-nerd.com/libsndfile/
> 
> Or you could adapt something like the JSyn WAV and AIFF file parsers.
> https://github.com/philburk/jsyn/tree/master/src/com/jsyn/util/soundfile

@dturner explains FFmpeg audio decoding here https://medium.com/@donturner/using-ffmpeg-for-faster-audio-decoding-967894e94e71

What is convenient to use in Oboe, libsndfile or FFmpeg ?

**Comment by philburk** [comment]
FFmpeg is for reading MP3 files.
libsndfile is for WAV and AIFF

If you just have a few files then you could export the WAV file from Audacity as raw int16. Then you can just load that directly from the raw file into your app. Make sure the endianness matches.

**Comment by mgood7123** [comment]
you could try using https://github.com/jniemann66/ReSampler, I just got it working successfully on android a few hours ago https://github.com/jniemann66/ReSampler/issues/8#issuecomment-509023082

**Comment by android-usb** [comment]
Completed with DrumThumper app
