### ISSUE TITLE
First recording values are often zeros

### ISSUE THREAD

**Issue by SchmadenSchmuki** [google/oboe#549]
Hi, when recording sounds I often see that the first values I get from the callback are blank.
I use a Nexus 5X on 8.1, the stream uses the standardsettings, so 48kHz, 2 Channel, and usually roughly the first 80 samples / 40 frames are blank.
That's not consistent though, somethimes it's only the first 20 samples and sometimes it's not there at all.
I think that's really the data oboe delivers and not something from my code because when checking this the only thing I really do is to query the values and make some logs.
So I was wondering if anyone else can see that kind of behaviour.

**Comment by atneya** [comment]
This is the data Oboe is delivering, not your code.

When starting an input stream, the first burst is unpredictable as the stream finishes setting up. In general, after a burst (96 samples), the input data should be valid.

**Comment by SchmadenSchmuki** [comment]
Thanks for the info.
Then I'll just cut the first burst.
