### ISSUE TITLE
Add documentation for InputPreset

### ISSUE THREAD

**Issue by loics2** [google/oboe#552]
There are no mention of `InputPreset` and `setInputPreset` in the documentation. Since the default is `VoiceRecognition` and it can change the raw data, it should be mentioned somewhere.

**Comment by philburk** [comment]
There is some documentation here:
https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_builder.html#a144a3d095fd668210282f1a91f23e1f0

But we should add discussion the user guides.

**Comment by loics2** [comment]
> But we should add something to the user guides.

Yeah, that's what I meant, sorry.

Concerning 53ca4a1, should it mention that the InputPreset changes the raw data? I'm relatively new to AAudio and Oboe, so maybe it's an expected side effect, but I think it's not really explicit. My app works with raw `float` data, and it took me a while to find out why the values were not what I expected.

**Comment by atneya** [comment]
Added guidance in `FullGuide.md`:

> The InputPreset may be used by the device to process the input stream (such as gain control).
