### ISSUE TITLE
add more general purpose query for runtime version

### ISSUE THREAD

**Issue by philburk** [google/oboe#56]
The technique in this Pull Request: https://github.com/google/oboe/pull/51
can be generalized to return an SDK version number at runtime.
Then we can adjust our OpenSL ES support for specific older versions.

When was the "ro.build.version.sdk" property introduced?

**Comment by mnaganov** [comment]
> When was the "ro.build.version.sdk" property introduced?

I can see it in sources for Cupcake.

**Comment by philburk** [comment]
Fixed by https://github.com/google/oboe/pull/64
