### ISSUE TITLE
callbacks stop working if rapidly paused then unpaused in quick sucession

### ISSUE THREAD

**Issue by mgood7123** [google/oboe#569]
W/AudioStreamLegacy: processCallbackCommon() stopping because callback disabled
E/AudioTrack: EVENT_MORE_DATA requested 512 bytes but callback returned -1 bytes

**Comment by philburk** [comment]
@mgood7123 - What program are you using?
What device was this on?
What version of Android are you running?
Were you doing input or output?
What performance Mode?
EXCLUSIVE or SHARED? etcetera....

I tried to reproduce this using OboeTester on a 3a running Q. I could not get it to fail.
But at one point I accidentally checked the "callback returns STOP" which stopped the callbacks.

**Comment by mgood7123** [comment]
> @mgood7123 - What program are you using?
> What device was this on?
> What version of Android are you running?
> Were you doing input or output?
> What performance Mode?
> EXCLUSIVE or SHARED? etcetera....
> I tried to reproduce this using OboeTester on a 3a running Q. I could not get it to fail.
> But at one point I accidentally checked the "callback returns STOP" which stopped the callbacks.

my own program
S8
pie
LowLatency
SHARED
```
    streamBuilder.setCallback(&AudioEngine);
    GlobalTime.setCallback(env, type, &CALLBACK);
    oboe::DefaultStreamValues::SampleRate = (int32_t) sampleRate;
    oboe::DefaultStreamValues::FramesPerBurst = (int32_t) framesPerBurst;
    streamBuilder.setDirection(oboe::Direction::Output);
    // PerformanceMode MUST not be set to LowLatency in order to interact with external processors such as ViPER4Android
    // however Oboe currently crashes if it is not set to LowLatency
    streamBuilder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
    streamBuilder.setSharingMode(oboe::SharingMode::Shared);
    streamBuilder.setFormat(oboe::AudioFormat::I16);
    streamBuilder.setChannelCount(oboe::ChannelCount::Stereo);
    streamBuilder.setSampleRate(sampleRate);
```

**Comment by mgood7123** [comment]
it is possible that this may be related to device lag and https://github.com/google/oboe/issues/396 or https://github.com/google/oboe/issues/65

**Comment by mgood7123** [comment]
this appears to be reproducable in `OboeTester` > `Test Output` but not reproducable in `Test Input`
API: AAUDIO
SRate: 48000 (could by any however it sometimes crashes if set to a non native sample rate)
Channels: 2 (could be any, have not tested)
Format: PCM_I16 ( can be any value)
Perf: NONE (can be any value, confirmed stop in Low Latency)
Device: Auto select


tick `callback returns stop`
any attempts to `START`, or `PAUSE` even if stopped will fail until `CLOSE` then `OPEN` again

even if `OPEN` tick `callback returns stop`, untick `callback returns stop`, `START` will fail and not play anything

also appears to randomly fail simply by `CLOSE` `OPEN` `START`

Format and Samplerate does not appear to matter

however it is 100% reproducable with `callback returns stop` ticked and Perf NONE while itterating over `START` then `PAUSE` (however it also stops if `START` is tapped repeatadly while `callback returns stop` is ticked)

the speed of itteration does not appear to make any difference here

**Comment by mgood7123** [comment]
ALSO reproduced it `WITHOUT` ticking `callback returns stop` by itterating between `START` and `PAUSE` (takes a long time)

**Comment by philburk** [comment]
Thanks for the info.

Checking "callback returns stop" will cause the callback to return the STOP value so you will get no audio. That is expected.

When you said it "failed" do you mean it crashed with a stack trace or just failed to play?

> this appears to be reproducable in OboeTester > Test Output but not reproducable in Test Input

I suppose Viper4Android may not be processing Input. It only processes Output.

> it is possible that this may be related to device lag and #396 or #65

Those were minor bugs that should not cause a crash.

I think this crash is related to Viper4Android, which hacks into the OS. So I would expect it to be very fragile. So I think we will have to close this one.

If you see the crash on a device that is not rooted and does not have Viper4Android then please start a new Issue.

**Comment by mgood7123** [comment]
> Thanks for the info.
> Checking "callback returns stop" will cause the callback to return the STOP value so you will get no audio. That is expected.
> When you said it "failed" do you mean it crashed with a stack trace or just failed to play?
> 
> this appears to be reproducable in OboeTester > Test Output but not reproducable in Test Input
> 
> I suppose Viper4Android may not be processing Input. It only processes Output.
> 
> it is possible that this may be related to device lag and #396 or #65
> 
> Those were minor bugs that should not cause a crash.
> I think this crash is related to Viper4Android, which hacks into the OS. So I would expect it to be very fragile. So I think we will have to close this one.
> If you see the crash on a device that is not rooted and does not have Viper4Android then please start a new Issue.

it fails to play

**Comment by mgood7123** [comment]
> Thanks for the info.
> Checking "callback returns stop" will cause the callback to return the STOP value so you will get no audio. That is expected.
> When you said it "failed" do you mean it crashed with a stack trace or just failed to play?
> 
> this appears to be reproducable in OboeTester > Test Output but not reproducable in Test Input
> 
> I suppose Viper4Android may not be processing Input. It only processes Output.
> 
> it is possible that this may be related to device lag and #396 or #65
> 
> Those were minor bugs that should not cause a crash.
> I think this crash is related to Viper4Android, which hacks into the OS. So I would expect it to be very fragile. So I think we will have to close this one.
> If you see the crash on a device that is not rooted and does not have Viper4Android then please start a new Issue.

as in a device that DOES NOT have a custom recovery? or just a device that does not posses the `su` binary and does not have `ViPER4Android` installed?

**Comment by philburk** [comment]
This Issue is closed. We cannot support a device that has been rooted and is running Viper4Android.
