### ISSUE TITLE
Automatic Gain Control not working in LowLatency mode.

### ISSUE THREAD

**Issue by Artaches** [google/oboe#572]
**Short Description**
AGC seems to be off when starting streams in LL `oboe::PerformanceMode::LowLatency` mode, no matter the `oboe::InputPreset` that is used for input mic. Is there any way to enable AGC while in Low-Latency mode?

**Steps To Reproduce**
In LiveEffect app, setting `->setPerformanceMode(oboe::PerformanceMode::None) ` for input stream enables AGC. Otherwise it's off. `oboe::PerformanceMode::PowerSaving` also enables AGC.

**Expected behavior**
Setting `->setPerformanceMode(oboe::PerformanceMode::LowLatency)` should also have AGC enabled for the oboe::InputPreset that have it.
**Actual behavior**
No AGC for `oboe::PerformanceMode::LowLatency` mode.

Android Version(s): 9.0
Android Device(s): Samsung Galaxy Note 9
Oboe Version: Master (7/11/2019)

**Comment by atneya** [comment]
I am seeing AGC on a PixelXL running Q. Might be device/version specific.

**Comment by Artaches** [comment]
Is that's with running in `oboe::PerformanceMode::LowLatency` mode for the input stream; with ~20ms round-trip latency?

**Comment by atneya** [comment]
Yes.

How are you evaluating if AGC is on or off? Have you reproduced on any other test devices?

**Comment by philburk** [comment]
Please reopen if you have answers.
