### ISSUE TITLE
OboeTester crashes if Opened while stream running

### ISSUE THREAD

**Issue by philburk** [google/oboe#574]
**Short Description**
Crash in audio callback on second open.

**Steps To Reproduce**
Launch OboeTester
TEST INPUT
OPEN
START
OPEN

**Expected behavior**
Not crash.

**Actual behavior**
Crashes in onAudioReady()

**Additional context**

Android Version(s): QT
Android Device(s): Pixel 3a

**Comment by atneya** [comment]
`07-12 14:59:11.509  4198  4198 D OboeAudio: AudioStreamAAudio.open() app    format = 2
07-12 14:59:11.509  4198  4198 D OboeAudio: AudioStreamAAudio.open() sample rate   = 48000
07-12 14:59:11.509  4198  4198 D OboeAudio: AudioStreamAAudio.open() capacity      = 1536
07-12 14:59:11.509  4198  4198 D OboeAudio: AudioStreamAAudio.open: AAudioStream_Open() returned AAUDIO_OK, mAAudioStream = 0x73c0124800
07-12 14:59:11.509  4198  4198 D OboeAudio: ActivityContext::open() builder.openStream() returned 0
07-12 14:59:11.509  4198  4198 D OboeTester: OboeAudioStream_getNativeApi got 2
07-12 14:59:11.524  4198  4204 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x90 in tid 4204 (Jit thread pool), pid 4198 (oboe.manualtest)
07-12 14:59:11.563  4258  4258 E DEBUG   : failed to readlink /proc/4204/fd/76: No such file or directory
07-12 14:59:11.580  4258  4258 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
07-12 14:59:11.580   831   831 I /system/bin/tombstoned: received crash request for pid 4204
07-12 14:59:11.581  4258  4258 I crash_dump64: performing dump of process 4198 (target tid = 4204)
07-12 14:59:11.594  4258  4258 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-12 14:59:11.594  4258  4258 F DEBUG   : Build fingerprint: 'google/marlin/marlin:10/QPP5.190530.010/5680179:userdebug/dev-keys'
07-12 14:59:11.594  4258  4258 F DEBUG   : Revision: '0'
07-12 14:59:11.594  4258  4258 F DEBUG   : ABI: 'arm64'
07-12 14:59:11.595  4258  4258 F DEBUG   : Timestamp: 2019-07-12 14:59:11-0700
07-12 14:59:11.595  4258  4258 F DEBUG   : pid: 4198, tid: 4204, name: Jit thread pool  >>> com.google.sample.oboe.manualtest <<<
07-12 14:59:11.595  4258  4258 F DEBUG   : uid: 10208
07-12 14:59:11.595  4258  4258 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x90
07-12 14:59:11.595  4258  4258 F DEBUG   : Cause: null pointer dereference
07-12 14:59:11.595  4258  4258 F DEBUG   :     x0  000000732f29a398  x1  000000732f2100b8  x2  00000073307cd4e8  x3  0000000000000001
07-12 14:59:11.595  4258  4258 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0001001200000001  x7  000000009ce372c0
07-12 14:59:11.595  4258  4258 F DEBUG   :     x8  000000732a963598  x9  0000000000000000  x10 000000732f2100b0  x11 000000732f2100b8
07-12 14:59:11.595  4258  4258 F DEBUG   :     x12 000000009ce372c0  x13 00000000000001e8  x14 0000000000000000  x15 6060606060606061
07-12 14:59:11.595  4258  4258 F DEBUG   :     x16 00000073beac28e8  x17 00000073beab4ee8  x18 000000732bdac000  x19 000000732f29a398
07-12 14:59:11.595  4258  4258 F DEBUG   :     x20 00000073c0317020  x21 000000732f299c00  x22 0000000000000001  x23 00000073c0317020
07-12 14:59:11.595  4258  4258 F DEBUG   :     x24 0000007330ee5060  x25 0000000000000001  x26 00000073c0317020  x27 00000000ffffffff
07-12 14:59:11.595  4258  4258 F DEBUG   :     x28 00000073307cd8f0  x29 00000073307cd460
07-12 14:59:11.595  4258  4258 F DEBUG   :     sp  00000073307cd430  lr  0000007330dee764  pc  0000007330df2d54
07-12 14:59:11.611  4258  4258 F DEBUG   : 
07-12 14:59:11.611  4258  4258 F DEBUG   : backtrace:
07-12 14:59:11.611  4258  4258 F DEBUG   :       #00 pc 000000000021fd54  /apex/com.android.runtime/lib64/libart-compiler.so (art::ElfBuilder<art::ElfTypes64>::Section::AddSection()+120) (BuildId: 17fc37c7a3668af0862cc9f8f3360ff5)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #01 pc 000000000021b760  /apex/com.android.runtime/lib64/libart-compiler.so (art::ElfBuilder<art::ElfTypes64>::Section::Start()+64) (BuildId: 17fc37c7a3668af0862cc9f8f3360ff5)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #02 pc 000000000021b60c  /apex/com.android.runtime/lib64/libart-compiler.so (_ZN3art5debug15WriteCFISectionINS_10ElfTypes64EEEvPNS_10ElfBuilderIT_EERKNS_8ArrayRefIKNS0_15MethodDebugInfoEEE+332) (BuildId: 17fc37c7a3668af0862cc9f8f3360ff5)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #03 pc 000000000021e1e4  /apex/com.android.runtime/lib64/libart-compiler.so (art::debug::MakeElfFileForJIT(art::InstructionSet, art::InstructionSetFeatures const*, bool, art::debug::MethodDebugInfo const&)+592) (BuildId: 17fc37c7a3668af0862cc9f8f3360ff5)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #04 pc 000000000027f6c0  /apex/com.android.runtime/lib64/libart-compiler.so (art::OptimizingCompiler::GenerateJitDebugInfo(art::ArtMethod*, art::debug::MethodDebugInfo const&)+120) (BuildId: 17fc37c7a3668af0862cc9f8f3360ff5)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #05 pc 000000000027f470  /apex/com.android.runtime/lib64/libart-compiler.so (art::OptimizingCompiler::JitCompile(art::Thread*, art::jit::JitCodeCache*, art::ArtMethod*, bool, bool, art::jit::JitLogger*)+3108) (BuildId: 17fc37c7a3668af0862cc9f8f3360ff5)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #06 pc 0000000000242780  /apex/com.android.runtime/lib64/libart-compiler.so (art::jit::JitCompiler::CompileMethod(art::Thread*, art::ArtMethod*, bool, bool)+208) (BuildId: 17fc37c7a3668af0862cc9f8f3360ff5)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #07 pc 0000000000336350  /apex/com.android.runtime/lib64/libart.so (art::jit::Jit::CompileMethod(art::ArtMethod*, art::Thread*, bool, bool)+624) (BuildId: 7875b0fc0af1d1f6d8050cfaf9201719)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #08 pc 0000000000339534  /apex/com.android.runtime/lib64/libart.so (art::jit::JitCompileTask::Run(art::Thread*)+612) (BuildId: 7875b0fc0af1d1f6d8050cfaf9201719)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #09 pc 0000000000513e98  /apex/com.android.runtime/lib64/libart.so (art::ThreadPoolWorker::Run()+108) (BuildId: 7875b0fc0af1d1f6d8050cfaf9201719)
07-12 14:59:11.611  4258  4258 F DEBUG   :       #10 pc 0000000000513980  /apex/com.android.runtime/lib64/libart.so (art::ThreadPoolWorker::Callback(void*)+148) (BuildId: 7875b0fc0af1d1f6d8050cfaf9201719)
07-12 14:59:11.612  4258  4258 F DEBUG   :       #11 pc 00000000000e372c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 77997b7202606ab2ce8b20d257c89e38)
07-12 14:59:11.612  4258  4258 F DEBUG   :       #12 pc 0000000000084004  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 77997b7202606ab2ce8b20d257c89e38)
07-12 14:59:11.794   685  4248 W AAudioServiceStreamBase: writeUpMessageQueue(): Queue full. Did client stop? Suspending stream. what = 3, Shared
07-12 14:59:12.220   831   831 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_20
`

Looks like the stream opened successfully. But the stack trace is not pointing to a method within the app itself.

Reproed on QT/ PixelX.
