### ISSUE TITLE
OboeTester: DataCallbackResult::Stop not stopping the INPUT stream

### ISSUE THREAD

**Issue by philburk** [google/oboe#576]
Android Version(s): QT
Android Device(s): Pixel 3a
Oboe Version: 1.2.0

**Steps To Reproduce**
Launch OboeTester
TEST IINPUT
OPEN
START
Check "callback returns STOP"

**Expected behavior**
Stream stops.

**Actual behavior**
Stream continues in Started mode but does not deliver any input data.

**Additional context**

If applicable, please attach a recording of the sound.

**Comment by atneya** [comment]
OboeTester (older version from a few weeks ago) on PixelXL, Android Q, does not reproduce.

**Comment by philburk** [comment]
OboeTester V1.4.06 on Sargo on recent QT - PASS

**Comment by philburk** [comment]
Fixed in resampler branch. This bug was never in release code.
