### ISSUE TITLE
Compilation error when compiling oboe using ndk-build, AudioProcessorBase.cpp

### ISSUE THREAD

**Issue by peurpdapeurp** [google/oboe#579]
Android Version(s): android-23
Android Device(s): None, it is a compilation error.
Oboe Version: 1.2.0

**Short Description**
I am trying to build the oboe library using ndk-build, and run into this compilation error:

C:\Users\ezl\Desktop\Edward Lu NIST Summer 2019\NRT-PTT v2.0 Related\Android Projects\NRTPTTv2>ndk-build
[armeabi-v7a] Compile++ thumb: oboe <= AAudioLoader.cpp
[armeabi-v7a] Compile++ thumb: oboe <= AudioStreamAAudio.cpp
[armeabi-v7a] Compile++ thumb: oboe <= AudioStream.cpp
[armeabi-v7a] Compile++ thumb: oboe <= AudioStreamBuilder.cpp
[armeabi-v7a] Compile++ thumb: oboe <= LatencyTuner.cpp
[armeabi-v7a] Compile++ thumb: oboe <= StabilizedCallback.cpp
[armeabi-v7a] Compile++ thumb: oboe <= Trace.cpp
[armeabi-v7a] Compile++ thumb: oboe <= Utilities.cpp
[armeabi-v7a] Compile++ thumb: oboe <= Version.cpp
[armeabi-v7a] Compile++ thumb: oboe <= FifoBuffer.cpp
[armeabi-v7a] Compile++ thumb: oboe <= FifoController.cpp
[armeabi-v7a] Compile++ thumb: oboe <= FifoControllerBase.cpp
[armeabi-v7a] Compile++ thumb: oboe <= FifoControllerIndirect.cpp
make: *** No rule to make target `jni/oboe/src/flowgraph/AudioProcessorBase.cpp', needed by `obj/local/armeabi-v7a/objs/oboe/src/flowgraph/AudioProcessorBase.o'.  Stop.

**Steps To Reproduce** 
**_(The following steps assume that you are working on a Windows machine, with the ndk-build tool already set up to use with Android Studio)_**

1) Create an Android Studio project with C/C++ support.
2) Create a jni folder under the project root directory.
3) Clone release 1.2.0 of Oboe, and place the oboe folder into the jni folder of your Android Studio project.
3) Create an Application.mk file in the jni folder with the following contents:

APP_ABI := armeabi-v7a arm64-v8a x86 x86_64

APP_STL := c++_shared
APP_CPPFLAGS += -fexceptions -frtti -std=c++14
\# -Wno-deprecated-declarations

NDK_TOOLCHAIN_VERSION := clang
APP_PLATFORM := android-23

4) Create an Android.mk file in the jni folder with the following contents:

JNI_FOLDER_PATH := $(call my-dir)

\# Build the oboe library
include $(CLEAR_VARS)
LOCAL_MODULE := oboe
LOCAL_PATH := $(JNI_FOLDER_PATH)/oboe
LOCAL_C_INCLUDES := \
    $(LOCAL_PATH)/include \
    $(LOCAL_PATH)/src
LOCAL_SRC_FILES := \
    src/aaudio/AAudioLoader.cpp \
    src/aaudio/AudioStreamAAudio.cpp \
    src/common/AudioStream.cpp \
    src/common/AudioStreamBuilder.cpp \
    src/common/LatencyTuner.cpp \
    src/common/StabilizedCallback.cpp \
    src/common/Trace.cpp \
    src/common/Utilities.cpp \
    src/common/Version.cpp \
    src/fifo/FifoBuffer.cpp \
    src/fifo/FifoController.cpp \
    src/fifo/FifoControllerBase.cpp \
    src/fifo/FifoControllerIndirect.cpp \
    src/flowgraph/AudioProcessorBase.cpp \
    src/flowgraph/ClipToRange.cpp \
    src/flowgraph/ManyToMultiConverter.cpp \
    src/flowgraph/MonoToMultiConverter.cpp \
    src/flowgraph/RampLinear.cpp \
    src/flowgraph/SinkFloat.cpp \
    src/flowgraph/SinkI16.cpp \
    src/flowgraph/SinkI24.cpp \
    src/flowgraph/SourceFloat.cpp \
    src/flowgraph/SourceI16.cpp \
    src/flowgraph/SourceI24.cpp \
    src/opensles/AudioInputStreamOpenSLES.cpp \
    src/opensles/AudioOutputStreamOpenSLES.cpp \
    src/opensles/AudioStreamBuffered.cpp \
    src/opensles/AudioStreamOpenSLES.cpp \
    src/opensles/EngineOpenSLES.cpp \
    src/opensles/OpenSLESUtilities.cpp \
    src/opensles/OutputMixerOpenSLES.cpp
include $(BUILD_SHARED_LIBRARY)

5) Run Command Prompt as an Administrator, navigate to the directory of your Android Studio project within the Command Prompt, and then execute the command "ndk-build".

**Expected behavior**
Oboe compiles successfully.

**Actual behavior**
Compilation of Oboe fails with the following error:
`make: *** No rule to make target `jni/oboe/src/flowgraph/AudioProcessorBase.cpp', needed by `obj/local/armeabi-v7a/objs/oboe/src/flowgraph/AudioProcessorBase.o'.  Stop.`

**Additional context**

None.

Thank you for any help on this issue.

**Comment by philburk** [comment]
Thanks! I also see that Travis is saying all checks passed for pull requests. 
https://travis-ci.org/google/oboe/builds/560726570

But in the details I can see a link error!

oboe.dir/src/main/cpp/PlayAudioEngine.cpp.o CMakeFiles/hello-oboe.dir/src/main/cpp/SoundGenerator.cpp.o  -landroid -llog oboe-bin/liboboe.a -llog -lOpenSLES -latomic -lm && :
  /home/travis/build/google/oboe/src/opensles/AudioStreamOpenSLES.cpp:83: error: undefined reference to 'oboe::AudioStream::open()'
  /home/travis/build/google/oboe/src/aaudio/AudioStreamAAudio.cpp:123: error: undefined reference to 'oboe::AudioStream::open()'

**Comment by philburk** [comment]
First Travis failure at:
https://github.com/google/oboe/pull/577

**Comment by ggfan** [comment]
do you have to use the ndk-build? if you do not care about the build system,  CMake Plugin is ready to use for Oboe, refer to ["Getting Start guide"](https://github.com/google/oboe/blob/master/docs/GettingStarted.md).

**Comment by ggfan** [comment]
additional notes, there is some re-structuring about files ( the files in master may not be inside 1.2-stable branch, like flowchart directory ).  If you have to use ndk-build, you could translate the files/compile-flags of CMakeLists.txt of your branch into your Application.mk/Android.mk pair, that should be a little smooth, the following works:
```
JNI_FOLDER_PATH := $(call my-dir)

# Build the oboe library
include $(CLEAR_VARS)
LOCAL_MODULE := oboe
LOCAL_PATH := $(JNI_FOLDER_PATH)/oboe
LOCAL_C_INCLUDES := $(LOCAL_PATH)/include $(LOCAL_PATH)/src
LOCAL_SRC_FILES := \
        src/aaudio/AAudioLoader.cpp \
        src/aaudio/AudioStreamAAudio.cpp \
        src/common/LatencyTuner.cpp \
        src/common/AudioStream.cpp \
        src/common/AudioStreamBuilder.cpp \
        src/common/Utilities.cpp \
        src/fifo/FifoBuffer.cpp \
        src/fifo/FifoController.cpp \
        src/fifo/FifoControllerBase.cpp \
        src/fifo/FifoControllerIndirect.cpp \
        src/opensles/AudioInputStreamOpenSLES.cpp \
        src/opensles/AudioOutputStreamOpenSLES.cpp  \
        src/opensles/AudioStreamBuffered.cpp \
        src/opensles/AudioStreamOpenSLES.cpp \
        src/opensles/EngineOpenSLES.cpp \
        src/opensles/OpenSLESUtilities.cpp \
        src/opensles/OutputMixerOpenSLES.cpp \
        src/common/StabilizedCallback.cpp \
		src/common/Trace.cpp \
		src/common/Version.cpp 
LOCAL_LDLIBS    := -llog -landroid -lOpenSLES

include $(BUILD_SHARED_LIBRARY)
```
your Applicaiton.mk is ok
