### ISSUE TITLE
Travis not catching linker errors

### ISSUE THREAD

**Issue by philburk** [google/oboe#584]
Travis should catch linker errors.
But Travis passed even with this compilation error: https://github.com/google/oboe/issues/582

**Comment by philburk** [comment]
Also this Travis test "passed" but has builder errors!
https://travis-ci.org/google/oboe/builds/561237535

From the push test in https://github.com/google/oboe/pull/583

**Comment by ggfan** [comment]
which sample you were building?  The result checking is on the final apk,  ignoring the command line: probably should enable error catching on all terminal commands ( like set -e ).

**Comment by philburk** [comment]
Look for merge in https://github.com/google/oboe/pull/577

Crash in this Travis dump that "Passed".
https://travis-ci.org/google/oboe/builds/560193521

**Comment by ggfan** [comment]
file .ci_tools/build_samples.sh, array bundles[] is checked while apks[] is declared, could you check it out?

**Comment by philburk** [comment]
Thanks for the fix Gerry.
