### ISSUE TITLE
Remove cpu_relax from stabilized callback

### ISSUE THREAD

**Issue by atneya** [google/oboe#587]
cpu_relax may have unintended side effects leading to increased preemptions

**Comment by philburk** [comment]
What are the unintended side effects?
What do you suggest as an alternative?

**Comment by philburk** [comment]
no-inline can be used to make a function that will always get called.
Maybe do shifts and XOR on an input parameter that will get passed as zero. That might minimize gate flipping and reduce power.

**Comment by zubyf09** [comment]
@philburk  this is not relevant to this thread but Can you tell how we can add Audio effects
Equalizer
Virtualizer
BassBoost
PresetReverb
EnvironmentalReverb
DynamicsProcessing

**Comment by philburk** [comment]
> this is not relevant to this thread

Please start a new Issue if you have a new question.

**Comment by dturner** [comment]
A guy from Ableton (Ryan Brown?) gave a talk about how CPU frequency scaling was affecting iOS devices at ADC'19. He referenced the `wfe` instruction as a way of generating artificial load. [Code here.](https://github.com/Ableton/AudioPerfLab/blob/master/Base/Thread.hpp#L50)

**Comment by philburk** [comment]
We are going to deprecate stabilized callback.
