### ISSUE TITLE
Misc security comments

### ISSUE THREAD

**Issue by tguilbert-google** [google/oboe#590]
Aggregating some smaller changes from #352 into one issue.

I know this issue is a non-cohesive collection of smaller issues, but I don't think that any of these sub-issues warranted their own entry.

1) `FifoControllerBase::getFullFramesAvailable()`
Loss of capacity when casting from uint64_t to int32_t

2) `AudioOutputStreamOpenSLES::requestPause()` and  `AudioOutputStreamOpenSLES::requestStop()`
Handle/ignore negative values returned by `getFramesWritten()`

3) `AudioStreamBuffered::write(const void *buffer, ...)`
Why use a `const void*` if it's casted into `void*`

4) `AudioStreamBuffered::transfer` and `AudioStreamBuffered::read`
Handle/ignore the return value from `updateServiceFrameCounter()`

5) `AudioStreamOpenSLES::open()`
Check for overflows in `mFramesPerBurst * kBufferQueueLength`

**Comment by tguilbert-google** [comment]
Any updates?

**Comment by philburk** [comment]
> FifoControllerBase::getFullFramesAvailable()
> Loss of capacity when casting from uint64_t to int32_t

This was addressed by clipping the result between 0 and mTotalFrames, which is guaranteed in range.
We need uint64_t internally because the counters can exceed 32-bit range after 12 hours.

**Comment by philburk** [comment]
> 2. AudioOutputStreamOpenSLES::requestPause() and AudioOutputStreamOpenSLES::requestStop()
> Handle/ignore negative values returned by getFramesWritten()

DONE

**Comment by philburk** [comment]
> 3. AudioStreamBuffered::write(const void *buffer, ...)
> Why use a const void* if it's casted into void*

Both the read() and write() methods share a transfer() function, which is non-const for its read() path.

**Comment by philburk** [comment]
> 4. AudioStreamBuffered::transfer and AudioStreamBuffered::read
> Handle/ignore the return value from updateServiceFrameCounter()

DONE

**Comment by philburk** [comment]
> 5. AudioStreamOpenSLES::open()
> Check for overflows in mFramesPerBurst * kBufferQueueLength

Added check for overflow.
