### ISSUE TITLE
Create a composite class for synchronised, full duplex I/O

### ISSUE THREAD

**Issue by dturner** [google/oboe#60]
Synchronous I/O is hard. We should make it easy for developers to do the following: 

- Read from an input device (e.g. built-in microphone)
- Do some processing (e.g. a vocal effect)
- Pass the resulting audio to an output device (e.g. built-in speaker, USB audio device) 

This could be achieved with an object containing an input stream and output stream. Audio data would be written to the output stream using the callback mechanism. In each callback a non-blocking read would be performed on the input stream, then passed to an EffectsProcessor (written by the developer), then finally to the output.

Please feel free to add to this issue if you have suggestions on how this should be implemented.

**Comment by dturner** [comment]
+1 from Image-Line. Receive single callback with constant number of frames for input and output buffers.

**Comment by philburk** [comment]
I can extract the code from aaudio_loopback that moves through three states:
drain input, synchronize, run

**Comment by philburk** [comment]
There is now a class in OboeTester that we could move into a shared sample library, use in LiveEffects and/or add to an Oboe tools folder.

https://github.com/google/oboe/blob/master/apps/OboeTester/app/src/main/cpp/FullDuplexStream.h
