### ISSUE TITLE
Open multiple streams to play multiple sounds

### ISSUE THREAD

**Issue by f0831027** [google/oboe#602]
Hi ,
If I need to play multiple sounds in my app, do we need to open multiple streams ?
One sound for one stream is it work?

And I checked the Mixer class here: https://github.com/google/oboe/blob/master/samples/MegaDrone/src/main/cpp/Mixer.h

What the different between "use the mixer class to mixed sound" and "open multiple streams " ?
Not sure which way is better, if I open too much stream , is there any risk in it?
Thanks!

**Comment by Diljeet** [comment]
A quick suggestion, you can mix all the sounds you are playing and output them in a single stream.

The megadrone app targets low latency. And in case of multiple streams, all streams opened may not have same latency.
And even if you open many streams and output sound on them simultaneously then the system will mix all of them before outputting to speakers.
So in my opinion, you can mix them yourself and then output them using a single stream. This way you will have better control over the mixing.
However: key problems you may face could be - 1) resampling - if your sounds are of different sample rate 2) sample format conversion - if you have the sounds from different files using different sample format. But once you work with audio and develop understanding this mixing and sample format conversion gets very easy.

**Comment by philburk** [comment]
+1 to what Diljeet said.

Do NOT open multiple streams if you can avoid it.
If you have multiple sounds at the same sample rate then mixing them just involves a multiple an add per sounds. Multiply to adjust to adjust the level. Then add to combine the sounds.

Here are some reasons NOT to open multiple streams.
1. The overhead for each stream is hundreds of times higher than just doing your own mixing.
2. There can only be one EXCLUSIVE low latency stream.
3. There is a limit to the number of low latency streams. If you exceed the limit you can get higher latency and sometimes glitching.

**Comment by dturner** [comment]
Think Diljeet and Phil have you covered here. Please reopen if you have more questions.

**Comment by renetik** [comment]
What if I want to play multiple streams on multiple devices ?
