### ISSUE TITLE
Huge buffer size in multi-channel audio application

### ISSUE THREAD

**Issue by apleton** [google/oboe#604]
In a 2 channels application, the method AudioStream::getFramesPerBurst() returns expected results ( around 240 frames). However when I set 4 output channels, the value returned by getFramesPerBurst() is around 960 (!). Is that normal ? Is that a limitation of the hardware ? A limitation of Oboe ? 
I tested on MotoG5, MotoG7, samsung galaxy A5, and nexus 5. Always the same result.

**Comment by dturner** [comment]
You'll only get a low latency audio stream (with a small buffer size) when requesting a stream with 1 or 2 channels. More than that and you'll get a much large buffer size. 

Feel free to reopen if you have more questions on this.

**Comment by apleton** [comment]
I'm surprised because low-latency multi-channels applications is a common use case for pro audio apps. Is that a limitation of Android or Oboe ? Is there a workaround ? (including using direclty AAudio or OpenSLES) ?  Thanks

**Comment by dturner** [comment]
Right. You didn't say you were connecting to a 4 channel DJ controller - which controller are you using? It should definitely be possible to obtain a low latency stream using 4 channels if the USB audio device has 4 channels.

**Comment by dturner** [comment]
I just tested this use case on a Pixel XL connected to an ION DJ Live controller (4 channel USB audio interface) running Android QPP5.190530.006. Here's how I tested it: 

- Connect DJ controller to phone using USB-C OTG connector
- Run `hello-oboe` sample app. This plays a different pitch sine wave through each channel when you tap on the screen. Lowest pitch = channel 1, highest pitch = channel N where N is the channel count. This way you can audibly verify that the correct audio data is being played through the correct channel.
- Change playback device to your USB audio device (in my case it is listed as `USB-Audio - ION DJ Live USB Device`)
- Latency should be ~20ms, this indicates that a low latency stream is being used
- Change channel count to 4
- Latency stays the same at ~20ms. I confirmed this by tapping on the screen to hear that the sine waves were being played within ~20ms. 

Note that I'm testing this on an Android Q device. I'm unsure whether it's possible to obtain a low latency stream for >2 channels on pre-Q devices. 

I did some testing on a Samsung Galaxy S6 running Android 6.0 (Marshmallow API 23) and whilst I couldn't monitor the latency (this is only supported in API 26+) I could hear that the stream had high latency, probably in the 100-200ms range. My guess is that this is not supported when the underlying API is OpenSLES, but probably is supported in AAudio. 

I'll ask around to see if I can get more info on this. 

BTW, I agree that this is a really important use case for DJing apps so please let me know if you have an insights or test results from other devices - the more info we have the more we can try to solve in Oboe. I'll leave the issue open in case you have more questions.

**Comment by apleton** [comment]
Thanks for the tests. The buffer size with an external interface is fine on my side. The problem appears when I use the phone speakers/headphones with the same configuration (4 channels).
I guess the solution is to use the AudioManager to get the number of channels of the different connected audioDevices and reopen an audioStream with 2 channels or 4 channels accordingly.

**Comment by dturner** [comment]
> The problem appears when I use the phone speakers/headphones with the same configuration (4 channels).

Yes, that makes perfect sense because the 4 channels from your app then needs to be mixed into 2 channels. The mixer adds a load of latency so you won't get a low latency stream. 

> I guess the solution is to use the AudioManager to get the number of channels of the different connected audioDevices and reopen an audioStream with 2 channels or 4 channels accordingly.

Yes, that's exactly what I'd recommend. 

Just following up on a previous comment of mine: 
> My guess is that this is not supported when the underlying API is OpenSLES, but probably is supported in AAudio.

Actually I found that if I switch the underlying audio API to OpenSL ES on the Pixel XL (running Q) I still get a low latency stream which indicates that it *is* possible to get a low latency stream for 4 channels using OpenSL ES. But that it may not be possible on some devices, like the S6 which I tested before.

**Comment by apleton** [comment]
Ok that's good to know. Thanks!
