### ISSUE TITLE
[hello-oboe] Rename to SimpleSound

### ISSUE THREAD

**Issue by dturner** [google/oboe#607]
Move complex functionality into OboeTester, or just ensure that the use cases which it was testing for (e.g. multichannel output) are covered by OboeTester. 

Is there a way we can avoid duplicating the android-ndk oboe sample?

**Comment by dturner** [comment]
rename to SimpleSound and also link to hello-oboe sample now in the NDK repo

**Comment by dturner** [comment]
To discuss: I'm concerned that with hello-oboe being moved out of our repo we might accidentally release a breaking API change without updating it. Isn't there some way we could auto-merge/import the hello-oboe sample into the NDK repo?

**Comment by philburk** [comment]
Maybe we can get Travis to check out and build the HelloOboe app from the Google sample repository when it checks the oboe pull requests.

**Comment by dturner** [comment]
That could work. Another idea would be to move the hello-oboe sample back inside our repo and have a read-only copy in the NDK repo which is updated by Travis.

**Comment by philburk** [comment]
We don't want to change names.
We now have a minimal-oboe sample.
