### ISSUE TITLE
How to set playbackrate of music

### ISSUE THREAD

**Issue by minhtu14** [google/oboe#623]
Hello, 
I'm making  a music game. I find the lib with many features but I want to set speed rate when the game play music. I read your docs but I can't find any keys word relate to setplaybackrate. Any body already did it could help me?

**Comment by philburk** [comment]
When you open a stream set the sample rate to match the sample rate of the music. This can be a high latency stream.  

    builder1.setSampleRate(musicSampleRate);
    builder1.setPerformanceMode(PerformanceMode::None);

You may also want a low latency stream as well.

    builder2.setPerformanceMode(PerformanceMode::LowLatency);

**Comment by minhtu14** [comment]
Maybe, you have misunderstood about my question. it's mean that I want to play a music with x2 or x3 speed. If your answer is correct, i will set double musicSampleRate of music that can x2 speed when playing.
