### ISSUE TITLE
24bit USB audio?

### ISSUE THREAD

**Issue by hendrep** [google/oboe#634]
Is it possible to force Oboe to play audio at 24bit using and external USB DAC?
On some phones it works by default, but not on all. 

I know that 24bit playback is possible on the phones not currently working since I manage to get 24bit playback on these phones when I use Poweramp.

Any suggestions?

**Comment by dturner** [comment]
> Is it possible to force Oboe to play audio at 24bit using and external USB DAC?

No. Oboe has no control over the configuration of the USB audio device. Android chooses a sample rate and bit depth configuration and you're stuck with it. There is an internal feature request (id: 141550628) which requests for an Android API to control this. 

The only way to configure a USB audio device (to say a different bit depth or sample rate) is to package your own USB driver. Presumably this is what Poweramp is doing (I haven't checked).

**Comment by dturner** [comment]
Closing but feel free to add comments

**Comment by philburk** [comment]
There is another internal issue to add 32/24 bit native PCM support to AAudio. b/65067568
