### ISSUE TITLE
Record Voice Call using Oboe

### ISSUE THREAD

**Issue by muzeasd** [google/oboe#643]
Hello there. First, thanks for the great work.

I need to record voice calls using Oboe. But I can not seem to find a sample which can record both incoming voice as well as outgoing voice at the same time. 

If it is not possible, can I record both incoming an outgoing voices in different files and then merge them using Oboe?

Thanks a lot :)

**Comment by dturner** [comment]
I'm 99% sure that the recording of voice calls isn't possible any more, at least on recent versions. Is your experience different?

**Comment by dturner** [comment]
Closing this since it's not a bug but feel free to add comments

**Comment by muzeasd** [comment]
Then how some of the voice call recorders are working? They are available on PlayStore. Can I record incoming voice and outgoing voice in 2 different files and then merge them using Oboe?
