### ISSUE TITLE
Question about final output to audiostream.

### ISSUE THREAD

**Issue by stevenhaggerty** [google/oboe#646]
Hi there.

I'm writing our low level audio engine for our game and I'm a little confused as to what we should be rendering into the final output stream and what kind of post-processing (if any) occurs after filling this stream in our callback. This is particularly important when we're trying to play (for example) up to 32 'channels' at the same time.

Is there any post processing going on to the audiostream buffer after we've written to it (by Oboe)?

Do I have to write a filtering/clipping/normalising routine for after all my channels have been 'summed' into the final audiostream buffer, or is this done afterwards by Oboe?

The reason I ask is, if I simple sum my audio channel samples into the (float) output buffer, then I get distortion. For example, playing the same sample simultaneously 4 times, produces distorted (but recognisable) sound.

Thanks,

Steve.

**Comment by philburk** [comment]
Hello Steve,

Oboe and AAudio will not do any normalization or automatic gain control of the output. It is possible that the DSP might do some but I have not seen that.

For FLOAT streams, your app should ideally output a signal between -1.0 and +1.0.
If you are mixing multiple sources of audio, like voices in a synthesizer, or sounds in a game, then you will need to adjust the levels of your mix to keep the output between -1.0 and +1.0. You can do this any way you choose. Oboe only cares about the final output, not how it was created.

> playing the same sample simultaneously 4 times, produces distorted ...

If the level of each sample is 1.0 then the output will be 4.0 and it will clip. You will need to scale the output. The techniques for generating and mixing the sound is up to you.

> Is there any post processing going on to the audiostream buffer after we've written to it (by Oboe)?

Yes. It will be clipped  and then  the volume adjustment is applied. This prevents a very loud signal from bypassing a low volume request.

It will also be converted to an integer format that is suitable for the hardware. Sample rate conversion will be applied if the application and hardware are running at different rates.
