### ISSUE TITLE
live-microphone 

### ISSUE THREAD

**Issue by azizi436** [google/oboe#647]
i was wondering if you tell me how to use it for a **live-microphone** with low **latency** in a **java** project

**Comment by philburk** [comment]
You can use native methods (JNI) to setup the stream just like in the Oboe examples.
But do not specify a callback for the stream.
Instead, pass a float[] or short[] array to a native method that calls stream->read().

Use env->GetFloatArrayElements() to create a 'C' array from the Java array.
https://www.google.com/search?q=jni+GetFloatArrayElements

You may not get a low latency stream if you use float[]. Use short[] to get low latency.
or, to get low latency with a float array you can enable format conversion in Oboe.
https://github.com/google/oboe/blob/c8de6151eb655d9678c8fbefa0e4ec16d0d267a2/include/oboe/AudioStreamBuilder.h#L351

If you need to record with a specific sample rate and with low latency  then you should use the new sample rate converter built into Oboe.
https://github.com/google/oboe/blob/c8de6151eb655d9678c8fbefa0e4ec16d0d267a2/include/oboe/AudioStreamBuilder.h#L367

If you get an error code returned from the read() then it may be from a DISCONNECT. In that case you should stop(), close() and reopen the stream.
