### ISSUE TITLE
Feature request: Kotlin/Native API + sample with Kotlin/JVM interop through JNI

### ISSUE THREAD

**Issue by LouisCAD** [google/oboe#648]
I believe this would get more Android developers trying Oboe and maybe finding cool new use cases from these people. C++ is too manual to me, and I'm not familiar with it and all its gotchas.

I'm quite familiar with Kotlin/JVM and Kotlin/Native though, and I'd love to use Oboe with a Kotlin API. That would allow me to mix these with coroutines and structured concurrency, which have proven very great tools to implement otherwise complex use cases for me.

**Comment by dturner** [comment]
Great suggestion. We did talk about this recently and there was some reason why we thought it might not work. 

@atneya Wasn't it something to do with Kotlin/Native and C++ interoperability?

**Comment by LouisCAD** [comment]
Indeed, Kotlin/Native can't interop with C++, but can interoperate with C, which can interoperate with C++.

A C API surface would be needed for a Kotlin/Native API to be doable (can be backed by a C++ implementation).

**Comment by dturner** [comment]
Right. It's not on our immediate roadmap but feel free to propose something more concrete. Maybe start with a simple use case: opening a playback stream.

**Comment by philburk** [comment]
Aaudio has a C interface. So we could connect kotlin directly to AAudio. But then we would not have the openSL ES support that we have in oboe. Or the workarounds that oboe contains. So for that example we could put a C wrapper over Oboe which is a c++ wrapper over the AAudio API.

**Comment by philburk** [comment]
The DrumThumper app (in progress) is a Kotln app that calls Oboe through JNI.

**Comment by android-usb** [comment]
Completed w/ DrumThumper sample app.

**Comment by LouisCAD** [comment]
There's no Kotlin/Native API though. Half complete regarding the title.

Should I open a new issue to specifically ask for a Kotlin/Native API?

**Comment by android-usb** [comment]
Have a look at DrumPlayer.kt, especially those functions marked "external". These Kotlin functions call though JNI to native implementations in DrumPlayerJNI.cpp.
