### ISSUE TITLE
Problem with oboe::AudioStream in API24

### ISSUE THREAD

**Issue by niklasdahlheimer** [google/oboe#66]
Hey guys,

I'm working myself through the oboe-Library to use it as an AudioEngine for an LTC-Timecode-player (later the timecode-playback will be synced between many Android-Devices to get a wireless timecode-distribution).

So I tried to rebuilt the Synth from ADC'17-LiveCoding (https://www.youtube.com/watch?v=Pjgfje52Yv0).
Beside the fact that the names of the classes distinguish from the classes of the oboe-library (i.e. Don's "OboeStream" seems to be oboe::AudioStream in the library) I'm hanging on this problem:

When I run the Synth on a  Oreo/API26-AVD, it works fine. When I run it on a Nougat/API24-AVD,

it crashes while it tries to open the stream. So, it looks like opening the stream works fine with AAudio, but if I use a device which only supports OpenSLES, that app crashes.

Anybody has a suggestion on this? Audio-Frameworks seem to be a tough territory to start getting into Android/NDK-coding, but I will get through this somehow :)

Greetings from cologne/germany
Niklas

```#include "AudioEngine.h"

void AudioEngine::start() {


    oboe::AudioStreamBuilder builder;
    builder.setFormat(oboe::AudioFormat::Float);
    builder.setChannelCount(2);

    builder.setCallback(this);
    oboe::AudioStream *stream = nullptr;
    oboe::Result result = builder.openStream(&stream);
    /*if (result != Result::OK){
        LOGE("Failed to create stream. Error: %s", oboe::convertToText(result));
    }*/
    oboe::AudioFormat format = stream->getFormat();
    //LOGI("AudioStream format is %s", oboe::convertToText(format));

    mOsc.setSampleRate(stream->getSampleRate());
    mOsc.setWaveOn(true);

    stream->requestStart();
}

oboe::DataCallbackResult
AudioEngine::onAudioReady(oboe::AudioStream *oboeStream, void *audioData, int32_t numFrames) {
    mOsc.render(static_cast<float *>(audioData), numFrames);
    return oboe::DataCallbackResult::Continue;
}
```

```

#ifndef OBOEAPITEST_AUDIOENGINE_H
#define OBOEAPITEST_AUDIOENGINE_H

#include <oboe/Oboe.h>
#include "Oscillator.h"

 class AudioEngine : public oboe::AudioStreamCallback {

 public:
     oboe::DataCallbackResult
     onAudioReady(oboe::AudioStream *oboeStream, void *audioData, int32_t numFrames) override;

     void start();

 private:
    Oscillator mOsc;
    oboe::AudioStream *stream;
};


#endif //OBOEAPITEST_AUDIOENGINE_H
```

**Comment by philburk** [comment]
Hello Niklas,

Thanks for reporting this.

I ran my test program that uses a callback on a N6 running Nougat 7.0 (API24). It ran fine. But I believe you when you say it crashed. It is probably an Oboe issue.

But I notice that you have an uninitialized "oboe::AudioStream *stream;" in class AudioEngine. That does not seem to be used because you also have a *stream declared in your start() method. That could be a source of bugs now or in the future.

I recommend using the one declared in the class, not in the method. Then you will have the stream pointer that you need to stop() and close() the stream.  I also recommend calling it mStream to make it clear that it is an instance variable.

Try fixing that. If you still have a crash then please attach a file containing the crash stack trace and some of the log before it.

As a test, you might also try forcing Oboe to use OpenSL ES on your Oreo device.

   builder.setAudioApi(AudioApi::OpenSLES);

@dturner Do you have a downloadable project for the Synth from the talk? I can test that on Nougat.

Thanks,
Phil

**Comment by dturner** [comment]
The Hello-Oboe sample is pretty close to the one from our talk at ADC. It includes some added features for setting the buffer size and explicitly specifying an audio device: https://github.com/googlesamples/android-audio-high-performance/tree/master/oboe/hello-oboe

I tried it on an AVD Nexus 5X Nougat API 24 and it ran without crashing. 

If you post your stack trace we can try to identify the cause.

**Comment by niklasdahlheimer** [comment]
hey guys,
After comparing the "Hello-Oboe" sample against my version, which is based on the "ADC'17"-Video, I found the bug at the creation of the AudioEngine-instance:

In the video it is done by creating a static instance of the AudioEngine and starting it by calling engine.start() in the borrowed JNI-method "stringfromJNI".

In hello-oboe it is done by creating a new instance of the AudioEngine IN the JNI-method and calling the createPlaybackStream()-method, which corresponds to the start()-method, from within the constructor:
`PlayAudioEngine *engine = new(std::nothrow) PlayAudioEngine();`

To me, both look like legal ways of creating an instance, but obviously it makes a difference in the memory allocation of the instance-variables.

Probably it's a stupid android-developer-newbie-mistake, but maybe this thread will help some other newbies out there :)

**Comment by dturner** [comment]
Right, yes, in hello-oboe the pointer to the AudioEngine instance is returned to Java - we call this the "handle", it's really just the address in memory of the AudioEngine object. Each subsequent call from Java includes this handle so the AudioEngine object can be accessed. 

It sounds like you had an object going out of scope which was causing a crash. Could you post your erroneous JNI code? I'd be interested to see exactly what you were doing wrong so we can make our docs clearer.

**Comment by niklasdahlheimer** [comment]
sorry for misleading, in fact the bug was somewhere else:
As you see in my code-example in ym first post, I've tried to set the format after initializing the builder:
`builder.setFormat(oboe::AudioFormat::Float);`

Actually THIS was the stumbling block for openSLES. If I would have done my debugging more precisely, I would have come to this block in AudioStreamOpenSLES.cpp:
```
if (__ANDROID_API__ < __ANDROID_API_L__ && mFormat == AudioFormat::Float){
        // TODO: Allow floating point format on API <21 using float->int16 converter
        return Result::ErrorInvalidFormat;
    }
```

That was, what broke the neck of my app :). But the code-comment looks like, its allready on your ToDo-List.

Again, sorry for misleading!

**Comment by stevenhaggerty** [comment]
So we need to check the API level and set the format to I16 if it's < 21?

Is this documented anywhere, as I just got hit by this?

**Comment by dturner** [comment]
You shouldn't need to set the format to I16 explicitly, however, you should check what format you actually got after opening the stream. You'll *always* get I16 on API <21 because it wasn't supported until 21. You *may* get float on API 21+ but there's no guarantees.
