### ISSUE TITLE
Unable to play on Java side

### ISSUE THREAD

**Issue by faiziakbr** [google/oboe#663]
Hi,
I am recording using oboe by following this link
https://www.youtube.com/watch?v=cyMD4TJxIPA
in a thread using C++

and also i have successfully played using the same recordedbuffer from the recorder but when i convert the int32_t array to jintArray and try to play this, it turns into a siren.

      jintArray j = jnv->NewIntArray(requestedFrame);
      jnv->SetIntArrayRegion(j,(jsize)0,(jsize)requestedFrame,(jint*)myBuffer);
      outputStream->write(&j, requestedFrame, kTimeoutValue);

Also if we send the recordedBuffer data to Java side and try to play it from their by converting it into the byteArray using ByteBuffer, still the data that is played by AudioTrack sounds horrible.

Please guide me on this issue.

**Comment by philburk** [comment]
I don't understand what that code is doing.
I don't think passing jintArray to write() will work.
You need to access the raw data first using GetIntArrayElements().

https://www.math.uni-hamburg.de/doc/java/tutorial/native1.1/implementing/array.html
https://nachtimwald.com/2017/07/09/jni-is-not-your-friend/

Can you just pass myBuffer?

Where is the PCM data coming from? Java?

**Comment by faiziakbr** [comment]
We first tried to record audio with Oboe recorder and failed to play that audio with java audio track.
Any solution for that?
Our recorder has sample rate of 48K and all the default properties recommended. Buffer is storing data in int32_t format array. We are sending these buffer values to java and converting them to byte array using ByteBuffer with order of little endian.
And trying to play the sound with java audio track but

**Comment by philburk** [comment]
> If we send this int array data back to C++ and play with oboe player it plays perfect.

Then it seems Oboe is working correctly. Maybe you are not using the proper format in Java AudioTrack. Maybe your endian-ness conversion is wrong. But that is not an Oboe problem.

Try passing a specific number like 0x12348765 from C++ to Java then print it out to see if you are passing it correctly. Remember that Java bytes are signed so you have to mask them with 0x00FF.

> Any solution for calculating exact incoming frequencies on java side with recorder being
> oboe or we have to implement the FFT in C++ code to determine the frequency?

Doing pitch detection, synthesis, or audio signal processing is outside the scope of Oboe. We cannot offer advice on how to do that. Please refer to other online resources.
