### ISSUE TITLE
getFramesPerCallback vs getFramesPerBurst()

### ISSUE THREAD

**Issue by stevenhaggerty** [google/oboe#665]
Hi,

I've written a small sound engine that plays WAV's of varying bitdepths/sample rates. It does a real-time linear re-sample to the native stream-speed then applies pitch/pan/volume multipliers. 

I thought it was working fine until I tried on the LG M200 phone, which caused it to crash.

I allocate some internal workbuffers before starting the stream, large enough to handle a callbacks worth of data. I was using :

size = managedStream->getFramesPerCallback() * (sizeof(float) * 2); // Stereo.

However, on the LG M200, getFramesPerCallback() returns 0. My 6 other test phones return something reasonable (like 192).

Should I be using getFramesPerBurst() instead? If so, what's getFramesPerCallback() for?

Thanks,

Steve.

**Comment by philburk** [comment]
The framesPerBurst is the size of a typical data transfer used inside AAudio. If you do not specify a framesPerCallback then the callback will generally use the burst size, but not always. If there is resampling inside AAudio then the callback size can vary.

If your application needs a very specific callback size then use:

    builder->setFramesPerCallback(desiredSize);

If desiredSize is zero then AAudio will callback using whatever size it wants. That m ay be what you are seeing.

If you need a max size then you can allocate your max size and then just loop in the callback to fill the buffer in pieces if it is too big.

Allocating your buffers as framesPerBurst will be most efficient, but you may need to loop if the callback size is different.
