### ISSUE TITLE
Need new drum pad sample app

### ISSUE THREAD

**Issue by philburk** [google/oboe#677]
This app would show 6 pads on screen. When the user hits a pad, a drum sound will play.
The drum sounds will be loaded from WAVE files.

The app should include a WaveFileReader similar to the [WaveFileWriter](https://github.com/google/oboe/blob/e9e4378c237157405518aca07e354d2395e41a0e/apps/OboeTester/app/src/main/cpp/util/WaveFileWriter.h) in OboeTester. The WaveFileWriter might eventually get moved to a shared sample code folder and then possibly into Oboe.
This will help solve Issue #548 

App should demonstrate the following:

1. Opening a single low latency Oboe Stream.
2. Loading sounds from WAV files and storing in memory.
3. Triggering playback of those sounds based on user input.
4. Mix simultaneous sounds and avoid clipping by careful volume scaling.

Design criteria:

1. Java and C++ code should illustrate best practices.
2. App should be as **simple** as possible. Let the external developer add their own bells and whistles. Just "hello drums".
3. App will not include any sound control settings, pitch shifting, fancy synthesis or DSP, drum patterns sequencers, etc.
4. Drum sounds should not infringe any copyrights. Phil has an old drum sample collection that was recorded from scratch.

**Comment by android-usb** [comment]
Completed w/ DrumThumper sample app.
