### ISSUE TITLE
Question for contribution

### ISSUE THREAD

**Issue by dtree0520** [google/oboe#681]
i'm korean university student.
Recently, i used application which is using 'oboe' library like 'best piano'. i think, it is quite useful and it has good sound. So i want our korean to know oboe library using opensource. But because text file like readme is written in English, people might have trouble in interpreting English.
So can i Translate text file like readme or contributing guidelines into Korean?

**Comment by dturner** [comment]
I'm guessing this is related to another similar issue #682 so I'll close this and answer there.
