### ISSUE TITLE
Korean users need to understand Oboe better

### ISSUE THREAD

**Issue by tjalsrb97** [google/oboe#682]
We are Kwangwoon University students in South Korea and our major is computer engineering. We are very interested in listening to music, so I'm studying about the music software Oboe project.
 But It's not easy to understand because we are just normal students and don't know how to use. So we felt that many people wanting to study music software needs to read easy document(README). 
Because of this reason, we propose the questions. 
- How do you think we propose documents that are easy to understand oboe protect?
- To make it easier for us to understand the Oboe project, why don't we give more details about the Oboe project?
- Can I submit README document in Korean for Koreans using the Oboe Project?

Please read the issue carefully and think positively. Thank you for reading the long article. ^_^

**Comment by dturner** [comment]
Hello. Thanks very much for your interest in Oboe - we're very keen to make it as easy to understand as possible. 

We are happy to take pull requests for any updated documentation including a translated README (@ggfan might be able to help with this as well). Perhaps the naming convention `README.md.locale` would work e.g. `README.md.ko_KR` 

Are there other areas which require better explanation for your users?

**Comment by dturner** [comment]
I'm going to close this due to inactivity. Please feel free to submit PRs with translated text.
