### ISSUE TITLE
get oboe audio sound in app

### ISSUE THREAD

**Issue by Jeela13** [google/oboe#689]
hi sir,
it not a bug but I want to found the solution for this. My issue is I want to get sound which this library is making. I want to get it in the android app and adjust it as well. Like this app (https://play.google.com/store/apps/details?id=org.greh.leftrightearnsoundtest&hl=en) adjust sound left to right.

**Comment by dturner** [comment]
I believe this is possible using `Equalizer` and using a session id of 0 to indicate that this is a global session. https://developer.android.com/reference/android/media/audiofx/Equalizer.html. 

This isn't something which is related to Oboe though so I'm closing.

**Comment by dturner** [comment]
Actually, it looks like Equalizer doesn't support processing of individual audio channels - the processing is applied equally across all channels so this approach won't work. I don't think what you're suggesting is possible I'm afraid.
