### ISSUE TITLE
Recording Always Gives Data With Value of Zero at the Start of Recording

### ISSUE THREAD

**Issue by t6r7** [google/oboe#690]
Android Version(s): 9
Android Device(s): Samsung Tab A 10.1
Oboe Version: Most Recent One (1.2?)

**Short Description**
Hello! I've been trying to use Oboe to record and play audio. The goal is simply to play a song and record the song (and write the recording to a file), which involves recording and playback at the same time. I have successfully implemented the playback--I can load a song and play it back using Oboe without any apparent problems. I have also implemented the recording, and it works, but with a catch. The catch is that the recording always records a bunch of zeros at the beginning. And, after some experimenting, it seems that the amount of zeros is always around the 9600-9792 mark. I have tried both recording with a callback and recording inside of the playback callback (using the read() method), but I get the same behavior for both approaches. 

**Steps to Reproduce**
I've attached the relevant files for my code at the bottom, but here is what I think is relevant code for the issue:

The onAudioRead function:
```
oboe::DataCallbackResult AudioEngine::onAudioReady(oboe::AudioStream *audioStream, void *audioData, int32_t numFrames) {
    float* myBuffer = new float[numFrames];
    int framesRead = 0;
    if(frames>=songLength){
        closeFromPlayback(audioStream);
        inStream->stop();
        return oboe::DataCallbackResult::Stop;
    }
    else{
        if(first) {//drains input but only once
            do { 
                oboe::ResultWithValue<int32_t> result = inStream->read((void *) myBuffer, numFrames, 0);
                if (result != oboe::Result::OK) {
                    break;
                }
                framesRead = result.value();
            } while (framesRead > 0);
            first = false;
        }
        oboe::ResultWithValue<int32_t> result = inStream->read((void*) myBuffer,numFrames, (signed long) (3*numFrames*10e9/48000));


        fileOut.write((char *) myBuffer, numFrames * sizeof(float));

        memcpy(audioData, (const void*) audioBuffer, numFrames*sizeof(float));
        audioBuffer+=numFrames;
    }


    return oboe::DataCallbackResult::Continue;
}
```
I know I am not supposed to write to files inside the callback method, but I decided to try it out and see if I got any problems. It doesn't seem to be producing any problems, and I sure don't see how it could be causing the current problem.

Initialization of playback and recording streams:
```
oboe::Result AudioEngine::createPlaybackStream(oboe::AudioStreamBuilder builder) {
    return builder.setDirection(oboe::Direction::Output)
            ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
            ->setSharingMode(oboe::SharingMode::Shared)
            ->setCallback(this)
            ->setFormat(oboe::AudioFormat::Float)
            ->setChannelCount(oboe::ChannelCount::Mono)
            ->setSampleRate(48000)
            ->openStream(&mStream);
}

oboe::Result AudioEngine::createRecordingStream(oboe::AudioStreamBuilder builder) {
    return builder.setDirection(oboe::Direction::Input)
            ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
            ->setSharingMode(oboe::SharingMode::Shared)
            ->setInputPreset(oboe::InputPreset::Unprocessed)
            ->setFormat(oboe::AudioFormat::Float)
            ->setChannelCount(oboe::ChannelCount::Mono)
            ->setSampleRate(48000)
            ->openStream(&inStream);
}
```
Starting the streams
```
void AudioEngine::start() {
    fileOut.open("/sdcard/recording.bin", std::ios::out | std::ios::binary|std::ofstream::trunc);

    auto result = createPlaybackStream(oboe::AudioStreamBuilder());
    auto resultRec = createRecordingStream(oboe::AudioStreamBuilder());

    if ((result == oboe::Result::OK)&(resultRec == oboe::Result::OK)){
        inStream->requestStart();
        mStream->requestStart();

    } else {
        LOGE("Error creating streams. Error: %s", oboe::convertToText(result));
    }

}
```
**Expected behavior**
I expect the recording file to contain audio data at the beginning of the file. 

**Actual behavior**
The recording file contains about 9600 zeros at the beginning of the file. Below are MATLAB plots of the start of the sound file I am using (AEC Reference) and of the start of the recording (Mic Reference). ![image](https://user-images.githubusercontent.com/37992316/68079021-75d48480-fd9f-11e9-8347-62bfe1bde066.png)

As you can see, the beginning of the recording is zero. I have attached the sound file I am using. It is a binary file with single precision float data. The sound file is pink noise that was generated using MATLAB.

**Additional Discussion**
I initially thought that maybe there was something wrong with writing to file and not with the audio recording, but I tried two things to convince myself otherwise. The first thing I did was when I was still using the callback method for recording: I used another ofstream to write only the data from the first callback into another file. I checked the file with a hex viewer, and I got all zeros. The second I did using the current version of the code (which uses the read() method inside of the audio callback function): Here I would read the values into a buffer I declared inside of the onAudioReady function. Then, I would sum all the values in the buffer and check if the sum was zero or non-zero. I used LOGD() to print out when the sum of the buffer was non-zero, which generally happened after 9600-9792 frames. Thus, I believe that the writing to file is not the problem here.

I also made sure to check that the state of recording stream was "Started" in the first callback and before I started writing to file. I found that the state was "Started", so I assume that is not the problem.

Otherwise, I really don't know what could be the problem. I don't know if this is relevant, but I am using JNA to interface with the C++ code instead of using JNI. 

**Files**
[OboeIssueFiles.zip](https://github.com/google/oboe/files/3801142/OboeIssueFiles.zip)

**Comment by dturner** [comment]
I just want to make sure I have your use case clear before delving in further.

You have a sound file which you load into memory. You open a playback (output) stream and play the sound file through the phone's built-in speaker. You also want to record what is playing through the built-in speaker using the built-in microphone so you start a recording (input) stream at the same time. 

Is that correct? Why is it necessary to record the audio data which you already have? Presumably you're overdubbing the audio with something else (vocals?). 

Please give as much detail about your intended use case as there might be an easier way to achieve your goal.

**Comment by t6r7** [comment]
> You have a sound file which you load into memory. You open a playback (output) stream and play the sound file through the phone's built-in speaker. You also want to record what is playing through the built-in speaker using the built-in microphone so you start a recording (input) stream at the same time.

Correct. The use case will be karaoke, so vocals will be recorded in addition to the audio data.

Although I did not find the cause of the problem, I did found a workaround. The workaround is that I first start the input stream and I read values from the input stream in blocks of 64 frames until the sum of those values is non-zero. Then I start the playback stream and in the first callback of the playback stream I drain the input stream buffer. After that I just read numFrames of samples from the input stream for each callback. This workaround adds a bit of a delay before playback/recording starts (which is unimportant in my use case), but it guarantees that I skip the non-zero values.

Thanks for taking the time to read my post!

**Comment by philburk** [comment]
Devices can take a while for the audio input to become stable. Sometimes the hardware can produce low frequency spikes or noise when they first start. So it is common for devices to zero out the initial data. It is only 200 msec on your device.  I think your workaround is reasonable.
