### ISSUE TITLE
Massive glitches on Galaxy Tab S2 since commit 6359dca

### ISSUE THREAD

**Issue by balegoff** [google/oboe#694]
Android Version(s): 7.0
Android Device(s): Samsung Galaxy Tab S2 8" (SM-T710)
Oboe Version: 6359dca

I get massive glitches on my app when I position oboe on the commit mentioned above, prior commits (try 1478301 for ex.) don't produce these glitches at all.

The glitches are periodical and continuous in debug mode and don't depend on user interaction.
In release it happens when finger doesn't touch the screen.

With commit 6359dca getFramesPerBurst reports a value of 960 frames.
With commit 1478301 getFramesPerBurst reports a value of 240 frames.
I don't know if it is related by wanted to mention it.

Here is the systrace for the debug version of the app.
Let me know if you need anything else.

[trace.html.zip](https://github.com/google/oboe/files/3815137/trace.html.zip)

**Comment by philburk** [comment]
@balegoff - thanks for the report. We were getting glitches on Pixel before the commit and the commit fixed them. But I think it still needs work.

You are running 7.0. But OpenSL ES did not support Performance Mode queries until 7.1. So I think I need to make that patch conditional on version.
