### ISSUE TITLE
Travis not showing tests in progress for Pull Requests

### ISSUE THREAD

**Issue by philburk** [google/oboe#697]
I pushed https://github.com/google/oboe/pull/695
I expected to see the Travis tests in progress.
They did not appear to be running!

So I merged the code and deleted the branch.
Then later the test failed because it could not check out the branch.

**Comment by ggfan** [comment]
it seems to be ok with my test.  I need to refresh the github page to see that CI is in progress.

**Comment by ggfan** [comment]
close it for now, if it happens again, we could have a look then!
