### ISSUE TITLE
Samsung Galaxy Note10 Unable to record in low latency mode(openSL Mode) 

### ISSUE THREAD

**Issue by WangShuo1143368701** [google/oboe#698]
Android Version(s):9.0
Android Device(s):Samsung Galaxy Note10

Samsung Galaxy Note10 Unable to record in low latency mode(openSL Mode)

**Comment by philburk** [comment]
What does "unable to record" mean? Did it crash? Was it silent? Did the stream not Open? Did it open but make noise? Did you not get a little latency stream?

**Comment by philburk** [comment]
Closing due to lack of information.
