### ISSUE TITLE
Interaction with TelecomManager API

### ISSUE THREAD

**Issue by dmalukov** [google/oboe#700]
Hello!
I work on voip app and I've faced the problem - Oboe doesn't play sound when a self-managed ConnectionService is active until the AudioStream is recreated. It happens only if AAudio is used. 

I slightly modified the hello-oboe sample to show the problem. 
https://github.com/dmalukov/oboe/tree/tcom_test
To reproduce the issue: just click "Outgoing" (it calls TelecomManager::placeCall) and then try to make a sound. 
The stream is still active, but you will hear nothing.

Google Pixel 3, Android 10, Build QP1A.191105.003.
Oboe - the latest master branch revision.

**Comment by android-usb** [comment]
I'm unclear on the testing protocol. Are you trying to play Oboe audio as a telecom stream? What do you mean by "try to make a sound."?

**Comment by dmalukov** [comment]
There is a sample - hello-oboe. If you tap on the screen the app plays sound.

The scenario was the following:
- Create a Connection using self-managed ConnectionService.
- Open oboe stream and start writing a data to play sound - instead of a sound there was nothing.
- If you didn't do the first step, oboe plays a sound.

But it seems that the problem was solved with one of android updates. Now (android build QQ2A.200405.005) everything works as expected.
