### ISSUE TITLE
outputstream not opening when set to a very low or high samplerate

### ISSUE THREAD

**Issue by SchmadenSchmuki** [google/oboe#701]
When I want to create an output stream with a samplerate higher than 1 600 000 or lower than 8 000 my app crashes with: 

     E/open stream: Failed to create stream. Error: ErrorInvalidRate

Everything tested between and including those limits worked just fine.

The AudioDeviceInfos for the outputdevices on my phone return an empty array from getSampleRates(), indicating that the devices support arbitrary samplerate.
(I work on a Nexus 5X with Android 8.1, latest version of oboe.)

I could avoid the problem by not creating such streams but my problem is that I don't know where to get the information for maximum and minimum samplerates. 
Are the observed numbers valid for all phones and will they stay valid in the future? I couldn't find anything to query them.

If oboe would only create streams to the possible limits and I could check the values afterwards that would also work fine.

Thanks for any help or further information 
best regards
SchmadenSchmuki

PS: If this doesn't belong here feel free to close or delete the issue (in this case pointing me in the right direction would be appreciated).

**Comment by philburk** [comment]
> my app crashes...

It is always possible that an audio stream may not open. The device may be busy or get unplugged just as you open it. So your app should be able to handle that without crashing. It would be good to check to see if the stream opened and just alert the user that the audio failed.

The 8000 to 1600000 Hz limits are imposed in this file:
frameworks/av/media/libaaudio/src/core/AAudioStreamParameters.cpp

Humans generally cannot hear anything above 20KHz so a 48000 Hz sample rate is generally enough. But some applications, such as ultrasonic data transfer, may require higher rates. Also recording at a higher rate, doing non-linear processing, and then downsampling is sometimes useful.  But generally anything above 192000 Hz is not very useful. And anything below 8000 Hz will sound pretty muffled. If you need a lower rate you could open at a higher rate and then downsample to the lower rate.

I'm curious, what sort of application requires the extreme sample rates?

**Comment by SchmadenSchmuki** [comment]
Thank you very much for the informations.

Yes, the crash is sloppy programming on my side so I changed the title.

I'm just working/playing around with resampling. 8000 Hz is the lowest samplerate I can record and with downsampling such data the problem occurred. Then I was just curious how far I could go up and was quite surprised that it went that far.
Still, I didn't want to limit myself yet so the question arised where the limits are in general.

So I'm wondering, do the limits also apply to OPEN SL ES?
To be honest I don't really know what to do with:
> frameworks/av/media/libaaudio/src/core/AAudioStreamParameters.cpp

(I'd also be interested, you mentioned downsampling, is there a easy, simple or built in way to do this? 
At the moment, to me it looks rather complex and costly. I was already wondering how the devices can manage/handle arbitrary samplerates that quickly but guessed the hardware somehow does the magic/work.)

**Comment by philburk** [comment]
There is a sample rate converter in the oboe flowgraph/resampler folder. You can use it but it is not documented.

**Comment by philburk** [comment]
The 1.3 release includes a resampler in Oboe. Some docs here:
https://github.com/google/oboe/releases/tag/1.3
