### ISSUE TITLE
Cannot start Input stream in low latency mode (OpenSL Mode)

### ISSUE THREAD

**Issue by Norfiwafi** [google/oboe#710]
Android Version(s): 9.0
Android Device(s): Samsung S9, Samsung S9 plus, Android studio Emulator
Oboe Version:1.3

Hi,
It seems related to #698 but since the author did not give any further description, I thought I needed to create mine. 
I saw this behaviour in our app, and in the liveEffect sample 
When starting an input Stream in openSL Mode (performanceMode::lowlatency), the SetConfiguration does pass SL_ANDROID_PERFORMANCE_LATENCY, but when retrieving the GetConfiguration after that, the result value is SL_ANDROID_PERFORMANCE_NONE leading to no low latency stream and bigger buffer size.
For instance, on the samsung S9, we will have an output stream of 192 samples, but an input stream of 960 samples. 

Does the SL_ANDROID_PERFORMANCE only works on Output direction ? What can we do to get a better buffer size in Input mode ? (I don't want to use AAudio for the moment because of the related Headphone/speaker connection callback not triggered on several samsung phones)

Thanks in advance

**Comment by philburk** [comment]
Are you opening the stream with Format::Float?
That can sometimes prevent getting a low latency input stream.
Try the new builder.setFormatConversionAllowed(true) in Oboe release 1.3.
Then Oboe will convert from Format::Int16 to Float and allow low latency.

**Comment by Norfiwafi** [comment]
Hi,
thank you !
 I was not calling the formatConversionAllowed, indeed, because the comment says : 

>     /**
     * If true then  Oboe might convert data formats to achieve optimal results.
     * On some versions of Android, for example, a float stream could not get a
     * low latency data path. So an I16 stream might be opened and converted to float.
     *
     * Default is true.
     */

However, this is false by default (as for the channelConversion).

Everything is working as expected now.
