### ISSUE TITLE
Focusrite Scarlett 2i2 not showing as input device

### ISSUE THREAD

**Issue by xglax** [google/oboe#721]
Android Version(s): 7.1.1
Android Device(s): Nexus 9
Oboe Version: Master branch

**Short Description**

When listing all audio devices through AudioManager.getDevices method, built in mic is listed as input, but Focusrite Scarlett 2i2 which is detected as USB Device, has only outputs.

Is there any reason for this to be happening? Should it be working?

**Comment by dturner** [comment]
This is probably a device specific USB issue. There's not much we can do about that in Oboe I'm afraid. Nexus 9 is too old of a device for us to consider fixing since it only runs Nougat: https://developers.google.com/android/images?hl=en#volantisg

**Comment by jcusters** [comment]
I found that in their effort to make it simpler, they made it worse. An USB audio device needs only to have a USB descriptor stating it's capabilities ( nr of inputs, nr outputs, sample frequencies and nr of bits ) , but android needs to guess if its a : TYPE_USB_DEVICE, TYPE_USB_ACCESSORY or TYPE_USB_HEADSET. And then comes the Manufacturer who assumes that a TYPE_USB_DEVICE only has outputs and TYPE_USB_HEADSET only has a mono input. With all this guessing and assuming you'll be lucky if a certain combination of Audio device and Android works as expected.

Please correct me if I'm wrong.

**Comment by philburk** [comment]
@android-usb - Paul, can you comment on this?

**Comment by philburk** [comment]
Android 7 and Nexus 9 are too old to change.
There have many improvement in USB audio since then.
Closing as obsolete.
