### ISSUE TITLE
Samsung Galaxy J3 mic input levels are low

### ISSUE THREAD

**Issue by dvallieresMH** [google/oboe#722]
Android 9
Samsung Galaxy J3
Oboe Version: 1.2.0

When testing the Samsung Galaxy J3 we are finding that the microphone dBs are quite low.
When testing the levels from the bottom mic we get recorded RMS output(dB) of -45.9 and 
from the top mic we get RMS output(dB) of -50.7.

Install oboe Live Effect and record.  (Was recording with Oboe Tester to save files) EDIT*
The phone should record at a perceptible level.
It seems that the phone is recording at a much lower than it should be.

We've seen similar behavior in other Samsung phones, the J3 is a good example of the behavior. Phones from other manufacturers seem to get higher initial mic levels than Samsung phones.

**Comment by dturner** [comment]
This sounds like a Samsung specific issue. We'll refer it over to them. Possibly something in the Mixer profile gain settings.

**Comment by tetelestia** [comment]
This issue does seem to be persistent across a few Samsung devices. Is there anywhere we can follow up with them about it?

**Comment by philburk** [comment]
DUPing this to https://github.com/google/oboe/issues/728
Samsung has been notified.
