### ISSUE TITLE
Synchronisation between input and output

### ISSUE THREAD

**Issue by romanbsd** [google/oboe#730]
Android Version(s): 24
Android Device(s): Samsung
Oboe Version: 1.3.0

I'm trying to implement an acoustic echo cancellation, therefore it's important to have input and output frames in sync (minding latency, of course).
However, when I open an input stream and output stream it may be hundreds of ms between the first frame of first stream and the second. Also, after the first frame on the second stream arrives, the first stream might miss one or few callbacks. I'm completely puzzled by this behaviour.
The problem is exacerbated by the fact, that my algorithm uses a specific frame size (which works nicely on devices with a buffer size of 192, where I can pass the buffer directly, but requires a FIFO for other devices such as Samsung - buffer of 240).

So the question is - what would be the recommended way to have the input and output frames in sync?

**Comment by philburk** [comment]
Depending on the device, stream startup can be a bit unpredictable. It takes a while for the callback behavior to settle down. But there are techniques you can use to improve the synchronization between input and output.

The LiveEffect sample code has a class called FullDuplexStream.
It synchronizes the input and output streams and tries to minimize latency.

https://github.com/google/oboe/blob/eae3fa1d9de4036b62a78317c20c21b88237fad0/samples/LiveEffect/src/main/cpp/FullDuplexStream.cpp

Here is the basic idea:
Use callbacks for the output stream.
From the output callback, do a non-blocking read from the input stream by using a timeout of zero.
You want to get into a state where the input buffer is empty and the output is full.
Then when you get preempted, the input will fill up and the output will drain.
So, for the first few callbacks we drain the input stream completely.

Then we give it a rest for one callback so it is not completely empty. If an MMAP stream is completely empty then it might glitch when the DSP and CPU pointers cross in the buffer.

Then we are in a synchronized state.

> but requires a FIFO for other devices such as Samsung - buffer of 240).

You can use the input stream FIFO to read arbitrary amounts of data. You should not need an additional FIFO. Just make sure the input has enough bufferCapacity.

Here is a video that describes this technique in more detail.
https://youtu.be/hY9BrS2uX-c

**Comment by romanbsd** [comment]
Thanks! I'll try that approach.
