### ISSUE TITLE
Is it possible to get dynamic bundle modules based on fast path sample rate?

### ISSUE THREAD

**Issue by peterdk** [google/oboe#738]
I don't know where to ask this question, so I ask it here.

My piano app uses 44100Hz source samples. 80% of the devices nowadays require 48000Hz for the  fastpath, so I resample the output stream myself to it. 

I was wondering if it's possible to use 2 bundle modules with the samples for the different required sample rates. I can't find a Packagemanager feature flag for it unfortunately, which seems to be required when wanting it to install directly during app install.

Or am I mistaken that the fastpath does only work when the correct sample rate is used?

**Comment by philburk** [comment]
> Or am I mistaken that the fastpath does only work when the correct sample rate is used?

It is true that you can only get a low latency path in AAudio or OpenSL ES if you match a native sample rate.

So we added a sample rate converter to Oboe in [v1.3](https://github.com/google/oboe/releases/tag/1.3).

This allows you to get a low latency path with sample rate conversion:

    builder.setSampleRateConversionQuality(SampleRateConversionQuality::Medium);

> possible to use 2 bundle modules with the samples for the different required sample rates.

@dturner  - do you know the answer?

**Comment by dturner** [comment]
There isn't a package manager flag for obtaining the native sample rate of the built-in audio devices so you wouldn't be able to install a 48kHz sample pack for 48kHz devices. It's a nice idea though, except for the fact that users can connect USB audio devices which can have different sample rates so you'd still have to do resampling in many cases. 

My advice would be to supply samples in 48kHz, then switch on Oboe's resampler for cases where it's not 48kHz.  

Does that answer your question?

**Comment by peterdk** [comment]
Thanks! I am indeed now testing the use of 48000 samples since that is the default on 80% of devices. It's too bad there is no flag, but indeed, I need to handle sample rate changes anyway.
