### ISSUE TITLE
Exclusive mode troubleshooting

### ISSUE THREAD

**Issue by gavv** [google/oboe#748]
Hi, thanks for this great library!

I have two questions:

* How can I determine why exclusive mode is not granted? Is the only possible reason that HAL does not support it, or there is something I can do with this?

  I'm not forcing format/rate/channels and not forbidding conversions in Oboe, but always get shared mode for any device. isMMapUsed() is also always false for opened streams.

* Can a Bluetooth device support AAudio MMAP mode or is it only available for ALSA devices? If the latter case, does this also mean that Bluetooth devices can never use exclusive mode?

**Comment by philburk** [comment]
This questions is similar to the questions of [why you do not get a LowLatency stream](https://docs.google.com/document/d/1PKLky2Gw3Ps3sbfD04OHspA6mXGFcyogkBik3aH7fcw/edit?folder=1IBC0y7AAIm3fj8MiU1ewZRmRJ0zDLCU7#).

> How can I determine why exclusive mode is not granted?

Sometimes the logcat will have a clue. But it may be hard to tell.

> Is the only possible reason that HAL does not support it

There are several reasons:
1. The device/HAL may not support it. Only Pixel and a few Samsung and Huawei phones support it. A Vivo phone might also but I have not confirmed it. What device are you using?
2. Another app may have the EXCLUSIVE resource already open. Enter:

    adb shell dumpsys media.aaudio

> Can a Bluetooth device support AAudio MMAP mode?

No. Also the latency for Bluetooth is so high that MMAP would not help you much.

**Comment by gavv** [comment]
Thanks for explanations!

> What device are you using?

Xiaomi Redmi Note 7. So I guess it's not supported. Found this in logcat:

```
01-04 18:24:55.950 10080 10080 D AudioStreamBuilder: build() EXCLUSIVE sharing mode not supported. Use SHARED.
```
