### ISSUE TITLE
when I change the sampling rate with setSampleRate(), the numFrames parameter of onAudioReady() will not be reflected at the same rate.

### ISSUE THREAD

**Issue by erlee-hdtel** [google/oboe#751]
Android Version(s): 8.0.0
Android Device(s): Samsung galaxy s7
Oboe Version: 1.3

**Short Description**
when I change the sampling rate with setSampleRate(), the numFrames parameter of onAudioReady() will not be reflected at the same rate.

**Steps To Reproduce**
When open oboe input stream, set the builder like followings.
```cpp
oboe::AudioStreamBuilder builder;
builder.setDirection(oboe::Direction::Input);
builder.setPerformanceMode(oboe::PerformanceMode::LowLatency);
builder.setSampleRate(8000);
builder.setFramesPerCallback(160);
```

**Expected behavior**
when I set sample rate as 8000, I want onAudioReady() 's numFrames to be 160.

**Actual behavior**
numFrames is always 960.

**Additional context**
when I modify configureBufferSizes() function in AudioStreamOpenSLES.cpp like following, It works.

```cpp
    // For high latency streams, use a larger buffer size.
    // Performance Mode support was added in N_MR1 (7.1)

    int32_t framesPerHighLatencyBurstWithResamplingRate = kFramesPerHighLatencyBurst;
    if (mSampleRate > 0 && mSampleRate < DefaultStreamValues::SampleRate) {
        framesPerHighLatencyBurstWithResamplingRate = kFramesPerHighLatencyBurst * mSampleRate / DefaultStreamValues::SampleRate;
    }

    if (getSdkVersion() >= __ANDROID_API_N_MR1__
        && mPerformanceMode != PerformanceMode::LowLatency
        && mFramesPerBurst < framesPerHighLatencyBurstWithResamplingRate) {
        // Find a multiple of framesPerBurst >= resampleFramesPerHighLatencyBurst.
        int32_t numBursts = (framesPerHighLatencyBurstWithResamplingRate + mFramesPerBurst - 1) / mFramesPerBurst;
        mFramesPerBurst *= numBursts;
        LOGD("AudioStreamOpenSLES:%s() NOT low latency, set mFramesPerBurst = %d",
             __func__, mFramesPerBurst);
    }
    mFramesPerCallback = mFramesPerBurst;
```
As you can see, I set the performance mode to PerformanceMode::LowLatency, but when check mPerformanceMode value, it isn't PerformanceMode::LowLatency.
so, I add upper code.

when I see the AudioStreamOpenSLES::updateStreamParameters(), It calls GetConfiguration() like following.
```cpp
result = (*configItf)->GetConfiguration(configItf, SL_ANDROID_KEY_PERFORMANCE_MODE,
                                                &performanceModeSize, &performanceMode);
```
but, returned performanceMode value is 0.
```cpp
mPerformanceMode = convertPerformanceMode(performanceMode);
```
so, mPerformanceMode will be PerformanceMode::None.
 
If applicable, please attach a recording of the sound.

**Comment by philburk** [comment]
> numFrames is always 960.

Hmm. Maybe related to:  https://github.com/google/oboe/pull/695

**Comment by erlee-hdtel** [comment]
we make voip app. when we make RTP audio packet, we use captured frames in 20ms. if capture size is over 20ms, it makes some jitter because RTP packet will be on the internet line simultaneously.
peer side voip app. can re-order the RTP packet, but it causes to make latency over 120ms.
