### ISSUE TITLE
Essimating CPU load on C++ side ?

### ISSUE THREAD

**Issue by sletz** [google/oboe#754]
I would like to estimate the averaged C++ load of the audio callback.  I see some code on Java side here: https://github.com/google/oboe/blob/ec8de0feef6df0af28d8de1d85437e2b7620c92e/apps/OboeTester/app/src/main/java/com/mobileer/miditools/synth/SimpleAudioOutput.java
but nothing in C++ code. We already have code that assume the audio callback is always called with the same buffer size, which is not always the case anyomre with OBOE.
Any plan to have code for that in OBOE C++ code ?

**Comment by dturner** [comment]
The way to measure load inside the callback is to measure the entry and exit times, then average those over a set number of callbacks. 

You can use Oboe's `getNanosecond` method to get accurate timestamps: https://github.com/google/oboe/blob/master/src/common/AudioClock.h

You can also use tracing functions to see individual callback times using systrace: https://github.com/google/oboe/blob/master/samples/hello-oboe/src/main/cpp/LatencyTuningCallback.cpp#L33

One thing to note is that the time inside the callback is dependent on the CPU frequency. The higher the frequency the quicker you'll be able to perform your calculations so what you're currently measuring is really % utilization of the current CPU bandwidth. If you have a CPU intensive audio synthesis algorithm it's usually a good idea to keep this above 80% to avoid the CPU frequency scaler from dropping the frequency down and causing you to take too long inside the callback. 

I spoke about this here: https://youtu.be/C0BPXZIvG-Q?t=967

**Comment by dturner** [comment]
Please let me know if you have more questions.

**Comment by philburk** [comment]
If you have variable callback size then you may want to normalize the CPU
load as a percentage of real time.

To get stable measurements you may want to lock the CPU frequency. There is
a script called pokecpu.sh in the SynthMark repository on GitHub.

Phil Burk

**Comment by sletz** [comment]
At the beginning I saw variable callback sizes, now (after setting `oboe::PerformanceMode::LowLatency` I guess) I see fixed values (like 256 frames). So I can use code I already had, that basically does the same as AudioClock.h). The timing measures are kept in a ring buffer and averaged in the `oboeaudio::getCPULoad` method. The implementation is there https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/audio/oboe-dsp.h.

BTW it means we now have a OBOE implementation for Faust, that is available in the export section of Faust Web IDE <img width="1440" alt="Capture d’écran 2020-01-12 à 09 48 38" src="https://user-images.githubusercontent.com/1430487/72216406-c9dab280-3520-11ea-8c93-886bf01b3946.png">
ans could be added here then: https://github.com/google/oboe/blob/master/docs/AppsUsingOboe.md

**Comment by philburk** [comment]
Thanks Stephane! I'm really glad to hear Faust is using Oboe. I added it to the Apps list.
BTW, I looked at the Oboe implementation and noticed a possible problem. See:
https://github.com/grame-cncm/faust/issues/382
