### ISSUE TITLE
log error if value accessed in ErrorOrValue when error != OK

### ISSUE THREAD

**Issue by philburk** [google/oboe#76]
Suggested by Mikhail so that we can tell if a caller is ignoring the error return value.

**Comment by dturner** [comment]
I'm not sure this is such a good idea, we'd be adding a check to every call to `ResultWithValue::value()` which might introduce unnecessary overhead in a real-time system. Isn't it the caller's responsibility to check the result before checking the value?

**Comment by mnaganov** [comment]
How much overhead an integer comparison adds? Also, I'm not aware of any methods in Oboe that need to be called in a tight loop.

I agree it's caller's responsibility to check for the return code, but when they forget to do that and something is not working, checking the log and seeing that there was an error is a great help for them.

**Comment by dturner** [comment]
Phil and I have some concerns about the extra overhead which would be introduced by branching, especially when some get methods (e.g. getXRunCount) might be called on every callback.

**Comment by philburk** [comment]
I am more concerned about suddenly flooding the logcat with error messages. For example, if getXRunCount() returns zero value because it is not supported, then no big deal.
