### ISSUE TITLE
Proper way of handling errors in onErrorAfterClose

### ISSUE THREAD

**Issue by cerupcat** [google/oboe#764]
Android Version(s): Various
Android Device(s): Pixel 2
Oboe Version: 1.3

**Short Description**

After my app is running her a long time (hours potentially), it will eventually get a `onErrorAfterClose` callback with `ErrorTimeout` result. I've seen most examples restart the stream on 'ErrorDisconnected', but I don't see any examples of what to do on other errors like 'ErrorTimeout'. Once this happens, the app stops audio input/output. Should we generally restart the stream on any error?

**Comment by philburk** [comment]
This might be because of a crash or hang in audioserver.
If so then a delayed reopen might work.

Try to reproduce using:   adb shell killall audioserver

**Comment by android-usb** [comment]
The "DrumThumper" sample shows both the "correct" way to handle OnErrorAfterClose, and the "work-around" method for the audioserver issue Phil references above.

**Comment by rpattabi** [comment]
DrumThumper attempts to open the stream again in `onErrorAfterClose` irrespective of the error. We're currently doing it only if the error is `ErrorDisconnected`. Does it mean the recommendation is to re-open the stream also for `ErrorTimeout` (and also for other errors)?

@philburk mentioned if audioserver crashed or hung, delayed reopen might work. However, we don't see any delay in DrumThumper code. The code we referred to is:

https://github.com/google/oboe/blob/8a0601f78014104a9e2f2cf8f16b7463c6fff4ab/samples/iolib/src/main/cpp/player/SimpleMultiPlayer.cpp#L63-L94

Please note that we've seen `ErrorTimeout` when we tried to stop the audio stream. So we're not sure if always re-opening the stream is the right approach. Also the fact that onErrorAfterClose() is called from different thread complicates things for us.

It would be great if you could provide the reasons behind each error code. We understand `ErrorDisconnected` happens on headset or bluetooth connectivity change and `ErrorTimeout` happens on audio server crash or hang (@philburk seems to mean there are other reasons).

On the other hand, in case of audio server problem, we would rather prefer oboe to bring the stream to original state than we having to handle it.
