### ISSUE TITLE
Samsung no stereo signal from phone's built-in microphones when selecting a specific internal mic by ID.

### ISSUE THREAD

**Issue by Artaches** [google/oboe#765]
Android Version(s): 9
Android Device(s): Galaxy Note 9, Galaxy S8, s10
Oboe Version: 1.3.0+

**Short Description**
Samsung phones (Note9, Galaxy s8, s10) are not able to get stereo microphone signal when having a built-in mic selected (either of them). Only leaving the mic selection as "Auto" (for AAudio or OpenSL ES) gives us stereo, but if you have a TRRS or Bluetooth headset plugged in, then "Auto" will select the external mics and NOT the built-in phone stereo mics..

**Steps To Reproduce**
This can be tested using the LiveEffect sample app. Note these settings are required to get a stereo signal on the Note9: "->setInputPreset(oboe::InputPreset::Camcorder)->setPerformanceMode(oboe::PerformanceMode::None)". Select the first microphone in the list for "Recording device" and plug a pair of headphones.

**Expected behavior**
Should get a stereo signal of phone's built-in microphones.
Requesting a stereo microphone stream with the "setDeviceId()" of one of the built-in microphones should work when TRRS headphones are plugged in.

**Actual behavior**
The same data of only one of the phone's microphones appears in both channels.
Stereo can only be gotten with TRS headphones.

**Additional context**
Note that the "Samsung Voice Recorder" cannot record in "interview" mode when TRRS cable is plugged in.  
Pixel 1, 3, 3a do not have such issues. A stereo mic signal can be gotten with TRRS headphones when selecting either of the phone's build-in mics.

Any ideas of how to get around this are appreciated!

**Comment by philburk** [comment]
I will test on Pixel 3a and on S10 and file a bug with Samsung if it is specific to their devices.

**Comment by Artaches** [comment]
This behaviour is specific to Samsung devices from my testing. Pixel devices get stereo signals for the built-in mic ids when using "Generic" input preset; and connecting TRRS headphones does not cause problems.

I've played around with OboeTester on the Samsung Note 9, and here are my findings:
I cannot get stereo using the default "VoiceRec" input preset. "Generic" preset gives stereo, but only when "Device" selection is set to "Auto select". Selecting either of the built-in mic ids with "Generic" preset gives dual-mono. But leaving the device selection to "Auto select" is a problem since when plugging in TRRS headphones the external mic is picked (a dual-mono signal).

**Comment by Artaches** [comment]
Note that the issue appears to be in "Samsung Voice Recorder" as well. That is, their "Interview" recording mode is disabled if TRRS or BT headphones are connected. They state "To record in Interview model, you need to unplug External mic.". Is there no way around this?

**Comment by Artaches** [comment]
Some new information regarding this issue that could be helpful. Turns out some Samsung phone do have a mic ID that can get stereo, but it isn't one of the known microphones. The mic ID that tends to work follows the following pattern: "Highest_Known_Mic_ID + 1".
On the Note9 for example, there are two mics: ID=13, and ID=14. However opening a stereo stream with mic ID=15 gives us stereo. No audio APIs are aware of a mic with ID=15.
The same "Highest_Known_Mic_ID + 1" tricks also works for Galaxy S9, S10, and A10, BUT NOT on the S8 or J3.
The S8 and the J3 fail to open a stream with ID="Highest_Known_Mic_ID + 1", and no other IDs in proximity worked either.

**Comment by philburk** [comment]
That is very interesting about the "Highest_Known_Mic_ID + 1" giving you stereo!

BTW, I tried OboeTester on a S10e (Exynos) and I **always** get dual mono even when there is no headset and I use "Auto Select" device.

**Comment by philburk** [comment]
It is unfortunate that you are not able to get a stereo recording. But it does not violate the CDD, which only requires mono recording. So it cannot be considered a bug by Samsung.

https://source.android.com/compatibility/11/android-11-cdd#5_4_1_raw_audio_capture_and_microphone_information

I do not know of any way to work around this other than the trick you described.
