### ISSUE TITLE
callback numFrames not matching value from setFramesPerCallback()

### ISSUE THREAD

**Issue by nocola** [google/oboe#766]
Android Version(s): Android 8.0
Android Device(s): Samsung Galaxy S7.
Oboe Version: 1.3.0

Using audioStream.setFramesPerCallback(256) I assume In audioReady callback numFrames = 256. And so it is. But only not for Samsung Galaxy S7, for this device 1024 was returned. 
So sound very glitch.

But if checkout 1.2-stable all is correct.

**Comment by philburk** [comment]
It seems that setFramesPerCallback() is not being honored for OpenSL ES.
According to the docs, if setFramesPerCallback() is specified then the callback should have that number of frames. This allows the app to customize the way they are called.

https://github.com/google/oboe/blob/4615e0e81bd3fbda5d8993ea5f9cc82e360700f6/include/oboe/AudioStreamBuilder.h#L89

I believe some [recent changes](https://github.com/google/oboe/commit/fcbc0043109cb99ffb4d3702a3f46e481c1280a2#diff-f8cc6f9ec789bb0577f734c49faf6cbeR99) to the way buffer sizes are managed, may have broken this API.

We need to add a test for this API and then make sure it works for both OpenSL ES and AAudio. It needs to work at different sample rates and at different performance modes.
