### ISSUE TITLE
Samsung S8: Xruns occur with Bluetooth headphones at maximum buffer size

### ISSUE THREAD

**Issue by smatt123** [google/oboe#769]
Android Version(s): Android 9
Android Device(s): Samsung S8 (SM-G950F)
Oboe Version: 1.3

**Short Description**
Xruns occur with Bluetooth headphones at maximum buffer size.

**Steps To Reproduce**
Connect Bluetooth headphones (tested with model Sennheiser PXC550)

**Expected behavior**
Output works without xruns, as it does with wired headphones. 

**Actual behavior**
For around 3 seconds after playback start, no xruns are reported. After that, a high number (1-10 per second) are reported using a buffer size of 2X burst size (2X 882 samples@44.1 kHz). The app tries to increase the buffer size to 3X burst size, but it seems that 2X burst size is the maximum size supported. 

**Additional context**
The issue occurs with both AAudio and OpenSLES interface (in the latter case xruns are not reported via the API but audible). Unfortunately, no larger buffer size than 2X burst size can be set. The issue might be related to #654, but I think this might be a different case as the problem is occuring with 2X burst size. When using a wired headphone, playback is stable even when having a buffer of 1X burst size (which is 192 samples@48 kHz) with a single underrun occuring at intervals of more than 10 minutes. So I think the problem is not related to excessive computational load in the callback.

**Comment by smatt123** [comment]
Follow up: When using blocking writes instead of callbacks, no xruns occur but latency is much higher.

**Comment by dturner** [comment]
Apologies for the long delay in responding. 

Please could you try reproducing this in OboeTester using the Test Output test, then post your results here.

**Comment by Matze1** [comment]
Used OboeTester to test with **Samsung S8**, Android 9 connected to Sennheiser PXC550 bluetooth headphones, 2 channels. The output stream was opened with AAudio API, 44.1 kHz, disabled Low Latency Mode and 882 samples burst size. I set it to max buffer size: 1792 samples (just slightly above 2x burst size). Frequent xruns started with ~1% workload.  

On the Google **Pixel 3** the stream was opened with 48 kHz and enabled Low Latency Mode, so for comparison I forced it to use 44.1 (PXC550, AAudio, 2 ch, 882 samples burst size). Max available buffer size for the pixel device was at ~12x burst size. Testing with buffer size set to 2x burst size the audio playback was xrun free up to 10% workload, increasing further with higher buffer size.

The **Samsung S10** (Android 10) performed similar to the S8 but xruns started at ~3% workload.

**Comment by philburk** [comment]
> Unfortunately, no larger buffer size than 2X burst size can be set. 

You can request a larger buffer capacity. As an **experiment**, try setting:

    builder.setBufferCapacity(8*882);

Then the latency tuner can request a larger buffer size.

**Comment by Matze1** [comment]
_setBufferCapacityInFrames()_ works as expected and with increased capacity the problem does not occur anymore.
Tested with Samsung S8 again, buffer was increased by the affected app to 3*882 samples and stream was running without further xruns

Thanks for the support!

**Comment by philburk** [comment]
I'm glad this worked. Closing.
