### ISSUE TITLE
Add support for Full Duplex Stream in the library itself

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#775]
Currently oboe provides separate streams for input and output. If the app requires full duplex stream, the developer has to manage both the streams manually. It is not trivial.

We see some of the sample apps required support for full duplex stream and they were implemented in-place. The code for duplex stream even got duplicated between `OboeTester` and `LiveEffect` sample/apps.

As of now, we could consider simply copy and use this code. However, we're also not sure if it is a good idea as it is not part of the main library, so probably not robust or battle-tested.

Why not provide full duplex support directly in the library? Till then, what is the recommended practice to have full duplex streams in oboe?

**Comment by dturner** [comment]
This is a great suggestion, and has been requested a few times before. We are currently testing the duplex stream class in OboeTester with more hardware configurations and writing unit tests. The next stage will be to move it into the core Oboe library. 

I'll leave this issue open and update when the class is published.

**Comment by philburk** [comment]
We could add a class that you pass two already opened streams.
It could then start them, do the synchronization and callback when both streams are ready.
