### ISSUE TITLE
Oboe doesn't work on android API 19..21 emulators

### ISSUE THREAD

**Issue by vlkv** [google/oboe#790]
Android Version(s): API 19, 20, 21
Android Device(s): Nexus 4
Oboe Version: 1.3.2 (babddb0 ("Fix erroneous restart on initial device list notification", 2020-02-06))

**Short Description**
LiveEffect app segfaults when opening input stream with messages:
```
D/OboeAudio: openStream() INPUT -------- OboeVersion1.3.2 --------
I/OboeAudio: AAudioLoader::open() could not find libaaudio.so
W/OboeAudio: SharingMode [AudioStreamBuilder::setSharingMode()] is not supported on OpenSLES streams.
    PerformanceMode [AudioStreamBuilder::setPerformanceMode()] is not supported on OpenSLES streams running on pre-Android N-MR1 versions.
I/OboeAudio: AudioStreamOpenSLES::open(chans:2, rate:0)
W/OboeAudio: configurePerformanceMode() not supported until N_MR1
W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
E/AudioRecord: Could not get audio input for record source 6
E/libOpenSLES: android_audioRecorder_realize(0xb7ea77d0) error creating AudioRecord object
W/libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
E/OboeAudio: Realize recorder object result:SL_RESULT_CONTENT_UNSUPPORTED
A/libc: Fatal signal 11 (SIGSEGV) at 0x00000030 (code=1), thread 5909 (oboe.liveeffect)
Process 5909 terminated.
```

**Steps To Reproduce**
Build LiveEffect sample app. Run it on Nexus 4 API 19 (I used emulator). Select "Open SL ES". Click button "Start". Segfault.

**Expected behavior**
The app should work without segfault.

**Actual behavior**
The app segfaults...

**Additional context**
I'm developing an app https://play.google.com/store/apps/details?id=ru.vitvlkv.vocalizzo.full&hl=en_US and when I've switched from Java audio to Oboe, I've discovered that my app has lost support for the Android 5.0 API 21 (Huawei P8). Checked that on API 19, same thing.

**Comment by vlkv** [comment]
UPDATE: It looks like oboe works fine on those real devices, but fails on emulators. Cannot prove it myself, don't own such a device...

**Comment by philburk** [comment]
Maybe related to #232

**Comment by dturner** [comment]
Just tried running hello-oboe on the Nexus 4 API 19 emulator. App crashed on startup with the following output: 

   E/AUDIO-APP: Error creating playback stream. Error: ErrorInvalidFormat
   A/libc: Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 9643 (.oboe.hellooboe)

Question is, why is it giving `ErrorInvalidFormat`?

Seems that setting the stream format to `float` was causing this. Removing that and the app still crashes with: 

    A/libc: heap corruption detected by dlfree
        Fatal signal 6 (SIGABRT) at 0x00002605 (code=-6), thread 9733 (.oboe.hellooboe)

Audio does definitely work in the API 19 emulator as I tested it successfully with UAMP. It may be that OpenSL ES is broken on API 19 - 21. 

@philburk Perhaps we should add this to QuirksManager. [This SO question](https://stackoverflow.com/questions/2799097/how-can-i-detect-when-an-android-application-is-running-in-the-emulator) would allow us to detect whether we're running on an emulator (although it's using Java API so some hackery using JNI required).

**Comment by eliasku** [comment]
For me also. Pixel 3 API 30 emulator runs without crash but with no sounds. On real device I hear the playback. Static linking, oboe 1.6.1

**Comment by robertwu1** [comment]
Emulators below API level 22 are no longer available on AVD manager. Thus, closing this.
