### ISSUE TITLE
how to decode audio.

### ISSUE THREAD

**Issue by pawanpakalwar** [google/oboe#794]
Hi Oboe, a nice audio lib 

can u please help, how to decode audio to show waveform in android. of .aac and . wav files.

thanks.

**Comment by philburk** [comment]
Hello,

Oboe does not support decoding of compressed audio like AAC or MP3. It is only concerned with input and output of raw PCM audio.

The new DrumThumper sample app loads WAV files. It uses a new WAV file loader that is in the Oboe repository.
https://github.com/google/oboe/tree/master/samples/parselib/src/main/cpp/io/wav

Displaying a waveform is beyond the scope of the Oboe library. But there is a waveform View in OboeTester.
https://github.com/google/oboe/blob/06338781c515444627de6ddd1a6c38df81de4338/apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/WaveformView.java

**Comment by pawanpakalwar** [comment]
Thanks for your valuable reply.

Regards,
Pawan Pakalwar.
