### ISSUE TITLE
How to change audio volume

### ISSUE THREAD

**Issue by kevin-zheng12** [google/oboe#798]
Android Version(s):
Android Device(s):
Oboe Version:

**Short Description**

**Steps To Reproduce**

**Expected behavior**

**Actual behavior**

**Additional context**

If applicable, please attach a recording of the sound.

**Comment by kevin-zheng12** [comment]
Hello, how do I change the volume using oboe，It is more urgent. Thank you for your reply. Thank you

**Comment by dturner** [comment]
Oboe has no concept of volume. You will need to implement your own volume control. Or use the JVM APIs like `MediaPlayer` which do offer volume controls.

**Comment by philburk** [comment]
To change the volume of a stream, multiply each sample by the desired amplitude.

    amplitude = 0.5;
    data[i] *= 0.5;

**Comment by hajimehoshi** [comment]
I was wondering if this mean changing the volume can be delayed up to the size of the buffer. If the buffer size is 0.25[s], a volume change can be effective up to 0.25[s] after a user operates to change the volume. Is that correct? I feel like this is a little problematic.

**Comment by dturner** [comment]
`data` is an array of samples. All @philburk was suggesting is multiplying each sample by 0.25 in order to reduce its value, and hence volume. So inside the audio callback do: 

`for (int i = 0; i < numSamples; i++){ data[i] *= 0.5; }`

**Comment by hajimehoshi** [comment]
Yeah, adjusting the values in a callback worked. I was wondering how I should do if I used `write` instead of the callback at that time, but I'm fine as I don't use `write` so far.

**Comment by dturner** [comment]
It doesn't have to be inside the callback, that was just an example. You own the sample array so you can change the values whenever and wherever you like.

**Comment by hajimehoshi** [comment]
My question was whether the internal buffer size matters or not when I wanted to adjust volume in real time.

**Comment by philburk** [comment]
No, buffer size is unrelated to volume changes. You just have to multiply
every sample by your gain value.

**Comment by hajimehoshi** [comment]
My understanding is that if I want to change volume in real time (e.g., fading out), a data callback works fine since the Oboe's internal buffer size is small enough, but `write` might not. Is that correct?

**Comment by muhammadsaimhashmi** [comment]
> `data` is an array of samples. All @philburk was suggesting is multiplying each sample by 0.25 in order to reduce its value, and hence volume. So inside the audio callback do:
> 
> `for (int i = 0; i < numSamples; i++){ data[i] *= 0.5; }`

Where can I find this loop? I am trying to achieve fade in and fade out. Thanks.

**Comment by Tom-Chang-star** [comment]
I am also trying to achieve fade in and fade out.
Please let me know if it's solved.

**Comment by philburk** [comment]
Fading in or out, or applying volume changes is digital signal processing. It is not a function of Oboe.
You just need to do this in your app.
We cannot teach you how to synthesize audio. But there are many online tutorials.
Search the web for "volume ramps".
