### ISSUE TITLE
[DrumThumper] Needs a README

### ISSUE THREAD

**Issue by dturner** [google/oboe#801]
See https://github.com/google/oboe/tree/master/samples/RhythmGame for an example.

**Comment by dturner** [comment]
Also update the samples index page: https://github.com/google/oboe/tree/master/samples

**Comment by LordByron1788** [comment]
Please can you explain in the Readme file, how the sample can be adapted to play Stereo wav files. My understanding is the current sample is restricted to playing only mono files to keep the code simple. If playing stereo files is not possible, then please explain why. Thank you.

**Comment by android-usb** [comment]
Resolved.
