### ISSUE TITLE
(requesting clarification) Is the LiveEffect sample app's audio i/o happening in the UI thread?

### ISSUE THREAD

**Issue by mahaju** [google/oboe#802]
In the LiveEffect sample app, the audio output starts up when the toggleEffect() click handler is called. There is no other thread or timer involved as far as I can see, at least in Java. So does this mean the audio input/output is happening in the UI thread? When I have had to do audio I/O using Java and AudioRecord and AudioTrack it has always involved making another thread or starting a timer, but the LiveEffect sample doesn't seem to do that since the callback function gets called automatically when new data is available. Am I right in thinking all of this happens in the UI thread? If I call LiveEffectEngine.setEffectOn(true) from a new thread that I create, will it behave same way as it is doing now, or will it be different?

**Comment by dturner** [comment]
No, audio I/O happens on a separate thread. The audio thread (a high priority system thread) is started when you call `AudioStream::start`. Callbacks are called on that thread here: 

https://github.com/google/oboe/blob/master/samples/LiveEffect/src/main/cpp/FullDuplexStream.cpp#L19
