### ISSUE TITLE
parselib is in a folder called "io"

### ISSUE THREAD

**Issue by philburk** [google/oboe#803]
The code for iolib is in a folder called "player".
oboe/samples/iolib/src/main/cpp/player/

The code for **parselib** is in a folder called "**io**".
oboe/samples/parselib/src/main/cpp/io/

Is this a historical artifact of the original organization?

**Comment by android-usb** [comment]
yes. probably don't need/want the "io" folder and show move "stream" and "wav" up.

**Comment by android-usb** [comment]
This got fixed a long time ago.

Code for the Player System IS in folder "samples/iolib/src/main/cpp/player". Presumably there will be a Recorder System in a folder called "samples/iolib/src/main/cpp/recorder".

Code for parselib is now in folders called "samples/parselib/src/main/cpp/stream" and "samples/parselib/src/main/cpp/wav" for the Stream IO and WAV parser respectively.
