### ISSUE TITLE
Not playing sounds on Samsung S5

### ISSUE THREAD

**Issue by ekurdesov** [google/oboe#808]
Android Version(s):6.0
Android Device(s):Samsung Galaxy S5
Oboe Version: 1.3.3

**Short Description**
Install the DrumThumper on Samsung Galaxy S5 and click on Kick or Snare. The sample app works well on my other devices. 
**Steps To Reproduce**

**Expected behavior**
Sound is playing
**Actual behavior**
nothing is playing
**Additional context**
I attached the logs, It seems like something isn't supported yet. Would it be possible to fix it? 

If applicable, please attach a recording of the sound.
```
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper D/OboeAudio: openStream() OUTPUT -------- OboeVersion1.3.3 --------
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper D/OboeAudio: openStream() OUTPUT -------- OboeVersion1.3.3 --------
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper I/OboeAudio: AAudioLoader::open() could not find libaaudio.so
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper W/OboeAudio: SharingMode [AudioStreamBuilder::setSharingMode()] is not supported on OpenSLES streams.
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper W/OboeAudio: PerformanceMode [AudioStreamBuilder::setPerformanceMode()] is not supported on OpenSLES streams running on pre-Android N-MR1 versions.
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper I/OboeAudio: AudioStreamOpenSLES::open(chans:1, rate:0)
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper W/OboeAudio: configurePerformanceMode() not supported until N_MR1
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper D/OboeAudio: AudioStreamOpenSLES:configureBufferSizes(48000) initial mFramesPerBurst = 0, mFramesPerCallback = 0
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper D/OboeAudio: AudioStreamOpenSLES:configureBufferSizes(48000) final mFramesPerBurst = 192, mFramesPerCallback = 192
03-13 01:16:03.324 31351-31863/com.google.oboe.sample.drumthumper D/OboeAudio: openStream() create a FilterAudioStream for data conversion.
```

**Comment by philburk** [comment]
The logs about "could not find libaaudio.so" and other "not supported" logs are just because you are on an old version of Android. That is OK. You may not get low latency but you should still get a sound out.

Can you attach some logs after "openStream() create a FilterAudioStream for data conversion". That is where I would expect to see an error.

Also you might want to try OboeTester TEST OUTPUT. You can try lots of variations.
https://github.com/google/oboe/tree/master/apps/OboeTester/docs

**Comment by ekurdesov** [comment]
Those are full logs since starting the app and clicking on the drum button while no sound is playing. I'm going to try oboe tester and see where it gets. Thank you! 

03-17 23:27:57.708 19908-19908/? E/Zygote: v2
03-17 23:27:57.708 19908-19908/? I/libpersona: KNOX_SDCARD checking this for 10199
03-17 23:27:57.718 19908-19908/? W/SELinux: Function: selinux_compare_spd_ram, index[1], priority [2], priority version is VE=SEPF_SECMOBILE_6.0.1_0033
03-17 23:27:57.708 19908-19908/? I/libpersona: KNOX_SDCARD not a persona
03-17 23:27:57.718 19908-19908/? E/Zygote: accessInfo : 0
03-17 23:27:57.718 19908-19908/? W/SELinux: SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.google.oboe.sample.drumthumper 
03-17 23:27:57.718 19908-19908/? I/art: Late-enabling -Xcheck:jni
03-17 23:27:57.748 19908-19908/? D/TimaKeyStoreProvider: TimaSignature is unavailable
03-17 23:27:57.748 19908-19908/? D/ActivityThread: Added TimaKeyStore provider
03-17 23:27:57.798 19908-19908/com.google.oboe.sample.drumthumper W/ResourcesManager: getTopLevelResources: /data/app/com.google.oboe.sample.drumthumper-2/base.apk / 1.0 running in com.google.oboe.sample.drumthumper rsrc of package null
03-17 23:27:57.858 19908-19908/com.google.oboe.sample.drumthumper W/ResourcesManager: getTopLevelResources: /data/app/com.google.oboe.sample.drumthumper-2/base.apk / 1.0 running in com.google.oboe.sample.drumthumper rsrc of package null
03-17 23:27:57.868 19908-19908/com.google.oboe.sample.drumthumper W/ResourcesManager: getTopLevelResources: /data/app/com.google.oboe.sample.drumthumper-2/base.apk / 1.0 running in com.google.oboe.sample.drumthumper rsrc of package null
03-17 23:27:57.888 19908-19908/com.google.oboe.sample.drumthumper W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
03-17 23:27:57.948 19908-19908/com.google.oboe.sample.drumthumper I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
03-17 23:27:57.948 19908-19908/com.google.oboe.sample.drumthumper I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>
03-17 23:27:57.998 19908-19908/com.google.oboe.sample.drumthumper D/TextView: setTypeface with style : 0
03-17 23:27:57.998 19908-19908/com.google.oboe.sample.drumthumper D/TextView: setTypeface with style : 0
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper D/TextView: setTypeface with style : 0
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper I/DrumPlayerJNI: init()
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper I/SimpleMultiPlayer: openStream()
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper D/OboeAudio: openStream() OUTPUT -------- OboeVersion1.3.3 --------
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper D/OboeAudio: openStream() OUTPUT -------- OboeVersion1.3.3 --------
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper I/OboeAudio: AAudioLoader::open() could not find libaaudio.so
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper W/OboeAudio: SharingMode [AudioStreamBuilder::setSharingMode()] is not supported on OpenSLES streams.
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper W/OboeAudio: PerformanceMode [AudioStreamBuilder::setPerformanceMode()] is not supported on OpenSLES streams running on pre-Android N-MR1 versions.
03-17 23:27:58.028 19908-19908/com.google.oboe.sample.drumthumper I/OboeAudio: AudioStreamOpenSLES::open(chans:1, rate:0)
03-17 23:27:58.038 19908-19908/com.google.oboe.sample.drumthumper W/OboeAudio: configurePerformanceMode() not supported until N_MR1
03-17 23:27:58.048 19908-19908/com.google.oboe.sample.drumthumper D/OboeAudio: AudioStreamOpenSLES:configureBufferSizes(48000) initial mFramesPerBurst = 0, mFramesPerCallback = 0
03-17 23:27:58.048 19908-19908/com.google.oboe.sample.drumthumper D/OboeAudio: AudioStreamOpenSLES:configureBufferSizes(48000) final mFramesPerBurst = 192, mFramesPerCallback = 192
03-17 23:27:58.048 19908-19908/com.google.oboe.sample.drumthumper D/OboeAudio: openStream() create a FilterAudioStream for data conversion.
03-17 23:27:58.048 19908-19908/com.google.oboe.sample.drumthumper D/OboeAudio: configure() flowgraph converts channels: 1 to 1, format: 2 to 2, rate: 44100 to 48000, qual = 3
03-17 23:27:58.088 19908-19908/com.google.oboe.sample.drumthumper D/SecWifiDisplayUtil: Metadata value : none
03-17 23:27:58.098 19908-19908/com.google.oboe.sample.drumthumper D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{a671b93 I.E...... R.....ID 0,0-0,0}
03-17 23:27:58.098 19908-19967/com.google.oboe.sample.drumthumper D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
03-17 23:27:58.138 19908-19967/com.google.oboe.sample.drumthumper I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Ia10634f51b)
    OpenGL ES Shader Compiler Version: E031.29.00.00
    Build Date: 01/28/16 Thu
    Local Branch: ss
    Remote Branch: 
    Local Patches: 
    Reconstruct Branch: 
03-17 23:27:58.158 19908-19967/com.google.oboe.sample.drumthumper D/libEGL: eglInitialize EGLDisplay = 0x9f75f7c4
03-17 23:27:58.158 19908-19967/com.google.oboe.sample.drumthumper I/OpenGLRenderer: Initialized EGL, version 1.4
03-17 23:27:58.238 19908-19908/com.google.oboe.sample.drumthumper D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
03-17 23:27:58.258 19908-19908/com.google.oboe.sample.drumthumper W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
03-17 23:27:58.328 19908-19908/com.google.oboe.sample.drumthumper I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@e5d22f6 time:44917132
03-17 23:28:09.618 19908-19908/com.google.oboe.sample.drumthumper D/ViewRootImpl: ViewPostImeInputStage processPointer 0
03-17 23:28:09.738 19908-19908/com.google.oboe.sample.drumthumper D/ViewRootImpl: ViewPostImeInputStage processPointer 1
03-17 23:28:11.958 19908-19908/com.google.oboe.sample.drumthumper D/ViewRootImpl: ViewPostImeInputStage processPointer 0
03-17 23:28:12.078 19908-19908/com.google.oboe.sample.drumthumper D/ViewRootImpl: ViewPostImeInputStage processPointer 1

**Comment by ekurdesov** [comment]
I poke around the oboe tester on that Samsung S5, and keep seeing the app crashing. My logs are set on verbose level so it should include all we get, 

```
03-17 23:42:24.824 24966-24966/com.google.sample.oboe.manualtest I/TestOboe: create OboeAudioStream ---------
03-17 23:42:24.824 24966-24966/com.google.sample.oboe.manualtest I/TestOboe: create OboeAudioOutputStream ---------
03-17 23:42:24.824 24966-24966/com.google.sample.oboe.manualtest I/TestOboe: setToneType(1)
03-17 23:42:24.824 24966-24966/com.google.sample.oboe.manualtest D/OboeTester: setActivityType(1)
03-17 23:42:24.824 24966-24966/com.google.sample.oboe.manualtest D/OboeTester: setActivityType(4)
03-17 23:42:24.834 24966-24966/com.google.sample.oboe.manualtest D/SecWifiDisplayUtil: Metadata value : none
03-17 23:42:24.834 24966-24966/com.google.sample.oboe.manualtest D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{4682ad0 I.E...... R.....ID 0,0-0,0}
03-17 23:42:24.874 24966-24966/com.google.sample.oboe.manualtest W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
03-17 23:42:24.894 24966-24966/com.google.sample.oboe.manualtest D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
03-17 23:42:24.934 24966-24986/com.google.sample.oboe.manualtest D/OpenGLRenderer: endAllActiveAnimators on 0xb2bb7300 (RippleDrawable) with handle 0x9fcbfa40
03-17 23:42:24.934 24966-24966/com.google.sample.oboe.manualtest I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@92d7a93 time:45784126
03-17 23:42:25.734 24966-24966/com.google.sample.oboe.manualtest D/ViewRootImpl: ViewPostImeInputStage processPointer 0
03-17 23:42:25.874 24966-24966/com.google.sample.oboe.manualtest D/ViewRootImpl: ViewPostImeInputStage processPointer 1
03-17 23:42:25.884 24966-24966/com.google.sample.oboe.manualtest D/OboeTester: OboeAudioStream_openNative: sampleRate = 0, framesPerBurst = 960
03-17 23:42:25.884 24966-24966/com.google.sample.oboe.manualtest I/OboeAudio: loadLibrary() could not find libaaudio.so
03-17 23:42:25.884 24966-24966/com.google.sample.oboe.manualtest A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 24966 (oboe.manualtest)
```

The fault addr seems to change but it's always following that message on lib audio...

`
03-17 23:35:04.094 22551-22551/com.google.sample.oboe.manualtest D/OboeAudio: ActivityContext::open() set callback to use oboeCallbackProxy, callback size = 0
03-17 23:35:04.104 22551-22551/com.google.sample.oboe.manualtest I/OboeAudio: loadLibrary() could not find libaaudio.so
03-17 23:35:04.104 22551-22551/com.google.sample.oboe.manualtest A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 22551 (oboe.manualtest)


03-17 23:36:44.594 22986-22986/com.google.sample.oboe.manualtest A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 22986 (oboe.manualtest)
03-17 23:40:31.624 24671-24671/com.google.sample.oboe.manualtest A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 24671 (oboe.manualtest)

`

**Comment by dturner** [comment]
Able to reproduce on Samsung Galaxy S5 build MMB29M.G900FXXS1CPLV

**Comment by philburk** [comment]
Does the fault generate a stack trace?

**Comment by dturner** [comment]
Root cause was that `setBufferSizeInFrames` was being called and if that call failed, which it does when using OpenSL ES and a callback (with `ErrorUnimplemented`) then `stream->requestStart()` was not called, so the stream was never started.

@android-usb FYI

**Comment by dturner** [comment]
@ekurdesov Should be fixed now. Please could you verify.

**Comment by ekurdesov** [comment]
woot woot!! :) retested and it all working, I mean drumming :) thank you for the quick response!
