### ISSUE TITLE
Build fails with "No compatible library found for //oboe/oboe. Rejected the following libraries..."

### ISSUE THREAD

**Issue by hypothermic** [google/oboe#812]
I've followed the Getting Started guide and I've done the following steps:

1. Create a new Android Studio project with the "Native C++" template
2. Add `implementation 'com.google.oboe:oboe:1.3.0'` to `app/build.gradle` dependencies
3. Enable prefab in gradle.properties and set prefab version to 1.0.0-alpha5
4. Link oboe library to `native-lib` in `CMakeLists.txt`

However, my build fails with the following error:
```
Build command failed.
Error while executing java process with main class com.google.prefab.cli.AppKt with arguments {--build-system cmake --platform android --abi x86 --os-version 16 --stl c++_static --ndk-version 21 --output /home/xxx/AndroidStudioProjects/xxx/app/.cxx/cmake/debug/prefab/x86/prefab /home/xxx/.gradle/caches/transforms-2/files-2.1/321430487ac8458d84de0bccab3069cf/jetified-oboe-1.3.0/prefab}

No compatible library found for //oboe/oboe. Rejected the following libraries:
android.arm64-v8a: User is targeting x86 but library is for arm64-v8a
android.armeabi-v7a: User is targeting x86 but library is for armeabi-v7a
android.x86: User is using a static STL but library requires a shared STL
android.x86_64: User is targeting x86 but library is for x86_64
```

I'm running Android Studio 4.1 Canary 3 with Gradle 6.2.1 and NDK 21.0.6113669 and CMake 3.10.2

Any idea what I've done wrong? Thanks.

**Comment by atsushieno** [comment]
This also reproduces with Android Studio 4.0 Beta 3 (I also tried Canary and then fell back to 4.0).

**Comment by philburk** [comment]
@dturner - does the pre-built on maven include an x86 target? I assume so.
The static vs shared STL may be the issue.

**Comment by felipecsl** [comment]
Having the same problem trying to migrate ktnes to prefab oboe.
Diff is here https://github.com/felipecsl/ktnes/compare/felipecsl--oboe-prefab

**Comment by dturner** [comment]
Thanks for raising this. Phil is correct. 

The issue is that apps are configured to use the static STL by default. You cannot link against both the static and shared STL so you need to change your app to use the shared STL. 

To do this open your `app/build.gradle` and add: 

    android { 
        defaultConfig { 
              externalNativeBuild {
                   cmake {
                        arguments "-DANDROID_STL=c++_shared"
    }}}}

**Comment by dturner** [comment]
I will update the docs

**Comment by hypothermic** [comment]
Fixed. Thank you.
