### ISSUE TITLE
Use Oboe LiveEffect with AudioRecord

### ISSUE THREAD

**Issue by ksc91u** [google/oboe#813]
Android Version(s): 10, Oreo
Android Device(s): Pixel 3, Sony XZ
Oboe Version: 

**Short Description**
I try to start Oboe LiveEffect in my app, to let user hear his own voice when headphone is plugged in.
Another thread using AudioRecord to record  and send to remote rtmp server.

On android 10, Oboe AudioInputStreamOpenSLES and AudioRecord can capture audio at the same time. On Android below 9, only one works at the time. 

**Steps To Reproduce**
Launch any audio recorder, start recording.

Launch LiveEffect sample on Oreo, start effect using input = Internal Microphone, output = Bluetooth headset, API = OpenSL.

**Expected behavior**
LiveEffect  working.

**Actual behavior**

**Additional context**
If I let LiveEffect app run in the background (by not calling stopEffect in onPause )
Launch LiveEffect first and switch to recording audio app, that app could not record anything.

If I launch LiveEffect first and than audio recording, Audio Record app would say another app is using microphone. I know that is limitation of old android versions. 

But is accessing microphone with AudioRecord and Oboe in the same app also limited?

**Comment by philburk** [comment]
> I try to start Oboe LiveEffect in my app, to let user hear his own voice when headphone is plugged in.

Are you actually starting a second app? Or did you just use code from LiveEffect in your one app? You should have everything in one app.

In a single app, you should only open one input stream to avoid conflicts.
If you need the low latency of Oboe, but you need to use Java, then route the audio from the callback to Java through a FIFO. Maybe use a JavaByteBuffer to implement the FIFO.

If you are doing blocking reads then you can split the audio and send one copy back through a JNI array, and a copy to an output stream using Oboe.
