### ISSUE TITLE
Sample Rate Converter is giving the noisy output 

### ISSUE THREAD

**Issue by sudhakar41** [google/oboe#815]
Android Version(s): 10.0 (API lEVEL 29)
Android Device(s): Oneplus 6
Oboe Version: 1.3.0

I am using the OBOE sample rate converter just like how it is mentioned in 
https://github.com/google/oboe/tree/master/src/flowgraph/resampler.
I am using this to convert sample rate of mp4 file from 44100Hz to 48000Hz.

I am passing floatBuffer(received from decoder) to the MultiChannelResampler and getting the resampled floatBuffer and using that data in the encoding. After resampling, the output audio has some noticeable noise even If I use MultiChannelResampler::Best option in the MultiChannelResampler.

**Comment by philburk** [comment]
If you want to use the SRC with Oboe then just enable it using:

    builder.setSampleRate(44100);
    builder.setSampleRateConversionQuality(SampleRateConversionQuality::Medium);

What does the noise sound like? It it a hiss? Or choppy sound? Or gaps? Or high frequency distortion?  I suspect the issue is with the buffer sizes.

MultiChannelResampler::Best should sound close to perfect.

**Comment by sudhakar41** [comment]
Hi **@philburk** 
Thank you for your response. I am using the MultiChannelResampler and passing the data as shown below,


```
extern "C" {
JNIEXPORT void JNICALL Java_com_thesilverlabs_rumbl_videoProcessing_CustomUpSampler_getSampledByteBuffer(
        JNIEnv *env,
        jobject instance,
        jobject inputBuffer,
        jobject outputBuffer,
        jint inputSize,
        jint outputSize) {
    MultiChannelResampler *mResampler = MultiChannelResampler::make(
            2, // channel count
            44100, // input sampleRate
            48000, // output sampleRate
            MultiChannelResampler::Quality::Medium);
    auto *inputBufferPointer = (float *) env->GetDirectBufferAddress(inputBuffer);  // multi-channel buffer to be filled
    auto *outputBufferPointer = (float *) env->GetDirectBufferAddress(outputBuffer);  // multi-channel buffer to be filled
    int numOutFrames = outputSize;
    int numInFrames = inputSize;
    int32_t channelCount = 2;

    while (numOutFrames > 0) {
        if (mResampler->isWriteNeeded()) {
            mResampler->writeNextFrame(inputBufferPointer);
            inputBufferPointer += channelCount;
            numInFrames--;
        } else {
            mResampler->readNextFrame(outputBufferPointer);
            outputBufferPointer += channelCount;
            numOutFrames--;
        }
    }
}
}
```


Here, every time I am passing the inoutBuffer of size 1880 (940 samples) and I am taking the output buffer with size of 2048 (1024 samples) (940*(48000/44100) = 1024)
I am taking the bufferData from decoder and passing it as inputBuffer and the outputBuffer data will be used in the encoder.
**noise type in output :** It's continuous hiss.
Please help, If I am doing anything wrong in the implementation.

**Comment by philburk** [comment]
I see a couple problems in the code.

1. You are creating a resampler on every buffer call. You should make only one resampler at the beginning and then use it multiple times. Don't forget to delete it when done.
2. The number of output frames generated will vary from 1023 to 1024. You need to account for that.

I just updated the README for the resampler to explain these issues better. Please try the new instructions here:

https://github.com/google/oboe/blob/master/src/flowgraph/resampler/README.md

Thanks for trying out the resampler.

**Comment by sudhakar41** [comment]
Hi @philburk , I will try out and get back to you, Thanks.

**Comment by sudhakar41** [comment]
Hi @philburk, Thank you very much for the solution, It solved my issue.

**Comment by devjuc** [comment]
Hi @sudhakar41 , can you share some snippet how did you implement the resampler in android (java or kotlin) application?
