### ISSUE TITLE
AAudio playback goes silent connecting/disconnecting headphones/bluetooth

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#823]
Steps:

1. Open oboe tester
2. Ensure "Enable oboe work arounds" is checked
3. Open TEST OUTPUT
4. Select AAudio as API
5. Open, then Start the stream
6. While the stream is playing, connect wired headphones or bluetooth speaker

The playback falls silent. Stopping and starting the same stream does not help. We have to close and open the stream again to get the playback working.

It is expected that the playback seamlessly continue in headphone or bluetooth speaker. In case of OpenSL ES, we get proper behavior.

Specifics:

This is tested on oboe tester from master branch
Nokia 3.1 Plus (Android 10 Pie)

This does not seem to be issue just with oboe tester. In our app, when integrating oboe we find the same behavior with AAudio which is forcing us to stick to OpenSL.

**Comment by philburk** [comment]
When a headset is plugged in or unplugged then the current AAudio stream may be "disconnected". This will cause the sound to stop. That is what is happening in OboeTester. It is expected.

The disconnect does not happen in OpenSL ES. But that is a problem. With OpenSL ES, when you connect bluetooth headphones, the buffer sizes and many other stream properties can change. But it is difficult for the app to respond to this and it often results in glitchy broken audio. To solve this problem in AAudio we disconnect the stream and let the app restart a new stream. The new stream may have different properties such as burst size.

The best place to reopen a stream is in the AudioStreamCallback::onErrorAfterClose() method.

https://google.github.io/oboe/reference/classoboe_1_1_audio_stream_callback.html#a57a1b21efc764e8bbf8d92008a993bfd

>  In our app, when integrating oboe we find the same behavior with AAudio
> which is forcing us to stick to OpenSL.

Sorry about the confusion. We need to document this issue better. #828

**Comment by philburk** [comment]
See https://github.com/google/oboe/edit/master/docs/notes/disconnect.md

**Comment by renetik** [comment]
> See https://github.com/google/oboe/edit/master/docs/notes/disconnect.md

dead link

**Comment by philburk** [comment]
We changed master to main. Should be:
https://github.com/google/oboe/blob/main/docs/notes/disconnect.md

**Comment by renetik** [comment]
Lord Vader, Yes Master.. pardon.. Yes Main, Rise !
