### ISSUE TITLE
Audio input pitched down 1 octave on Samsung S9, broken mono

### ISSUE THREAD

**Issue by mazbox** [google/oboe#824]
Android Version(s): 10
Android Device(s): Samsung S9 (SM-G960F)
Oboe Version: 1.3.3 and 1.2.4

**Short Description**
Using Oboe in full-duplex, the sound from the microphone sounds pitched down by one octave. This is on a stock version of android 10 (i.e. samsung's official version), on a newly wiped phone. 

**Steps To Reproduce**
Compile and run the FXLab demo app, and press the speaker button in the top right to unmute (happens both with headphones plugged in and without)

**Expected behavior**
Should pass through the signal normally.

**Actual behavior**
The sound sounds as if it is pitched down one octave, additionally, there are discontinuities in the waveform recorded at 3072 frame intervals (buffer size is 96 frames, so that's 32 buffers). Also, very suspiciously, the input buffer is a series of doubled up numbers, as if it's a stereo signal consisting of a mono signal interleaved with itself.

e.g.

-0.062038030475378
-0.062038030475378
-0.055203106254339
-0.055203106254339
-0.052048526704311
-0.052048526704311

I'm guessing the discontinuity is happening because the input buffer hasn't finished being pulled through the app yet (because it's playing at half speed) before it gets overwritten by incoming audio from the system

**Additional context**

(Sound file attached)

I'm happy to keep testing this and other stuff on the S9 if I can be of any help

**Comment by dturner** [comment]
Thanks for filing this detailed bug report. 👍 

The problem seems to be exactly as you describe: the mono stream contains duplicate samples, so when these samples are played back consecutively (which is what FXLab does) it'll sound like it's playing at half speed. 

Please can you try the LiveEffect sample which will open a stereo input stream: https://github.com/google/oboe/tree/master/samples/LiveEffect

If you do then it appears that the S9 is not correctly opening a mono stream. We can probably add a workaround to this in Oboe.

**Comment by dturner** [comment]
Thanks for filing this detailed bug report. 👍 

The problem seems to be exactly as you describe: the mono stream contains duplicate samples, so when these samples are played back consecutively (which is what FXLab does) it'll sound like it's playing at half speed. 

Please can you try the LiveEffect sample which will open a stereo input stream: https://github.com/google/oboe/tree/master/samples/LiveEffect

If you do then it appears that the S9 is not correctly opening a mono stream. We can probably add a workaround to this in Oboe.

**Comment by mazbox** [comment]
Just tried out LiveEffect and it worked as expected (i.e. didn't pitch down and glitch). One thing I noticed though, is that the microphone of the phone is listed twice in the inputs:
![Screenshot_20200423-164205_LiveEffect](https://user-images.githubusercontent.com/194121/80119675-ebb4ee00-8581-11ea-82bf-7c7a35a2ca53.jpg)

Might that have something to do with it? Please let me know if there's anything else I can do or anything else I can do to help!

**Comment by dturner** [comment]
@philburk I think the solution here is to add something to `QuirksManager` along the lines of: 

If you try to open a mono stream on a Galaxy S9 then under-the-hood oboe opens a stereo stream and passes the caller only a single channel. 

WDYT?

**Comment by philburk** [comment]
I agree that the problem sounds like the DSP is in stereo and the app is in mono.
There was a fix related to this problem in Q with:
https://android-review.googlesource.com/c/platform/frameworks/av/+/836186
But is does not seem to have worked for the S9.
Thanks for reporting this.

**Comment by mazbox** [comment]
Also, just tried on the S9 to open stereo input stream instead of mono, that seemed to work fine. 

Can I ask what happens if I ask for a stereo input and there's only mono available? Is this something I can control the behaviour of with `setChannelConversionAllowed()`?

**Comment by philburk** [comment]
@mazbox - yes, setChannelConversionAllowed() may fix this.

I have confirmed with Samsung that this issue exists on the Exynos S9 and Note9.
We can look for property "ro.hardware.chipname=exynos9810"

I will add a workaround for this to the QuirksManager. Thanks for reporting this!

**Comment by mazbox** [comment]
Nice! Really glad I could help.

Since my app is live at the moment, the best immediate fix I found was just to open up a stereo input if available, rather than mono, and it seems to work for all my test phones.

**Comment by philburk** [comment]
@mazbox - Could you do us a huge favor? Don and I do not have S9s!
So could you please try #890 on a S9?
If you try to open a mono stream then it should actually create a stereo stream internally.

You can build OboeTester from that branch.
Launch OboeTester
check the box "enable Oboe workarounds"
tap "RECORD PLAY"
Select Channels: 1
tap RECORD
make sure you get a mono MMAP stream
say "1-2-3-4"
tap STOP
tap PLAY
You should hear a good mono recording.

If you repeat the test but **disable** the Oboe workarounds then it should sound broken.

**Comment by mazbox** [comment]
It works!

I followed the instructions, - enable oboe workarounds, mono channel recording, mmap enabled, all sounds great.

Then tried unticking enable oboe workarounds, and it sounds broken again, so whatever it was, it's fixed the problem!

Please let me know if you need any more testing, happy to help...

**Comment by manymingge** [comment]
seems **fxlab** sample does not support stereo input.
`void DuplexEngine::openInStream() {
    defaultBuilder().setDirection(oboe::Direction::Input)
            ->setFormat(oboe::AudioFormat::Float) // For now
            ->setChannelCount(1) // Mono in for effects processing
            ->openManagedStream(inStream);
}`
if change ->setChannelCount(1)  to ->setChannelCount(2). The same down 1 octave effect will appear(Tested on Galaxy s8).

While the **liveEffect** sample declares that inout stream create order is important that we should open output stream first then use properties from the output stream to create input stream, 
`oboe::Result  LiveEffectEngine::openStreams() {
    // Note: The order of stream creation is important. We create the playback
    // stream first, then use properties from the playback stream
    // (e.g. sample rate) to create the recording stream. `


but **fxlab** does the reverse order.
`void DuplexEngine::beginStreams() {
    // This ordering is extremely important
    openInStream();
    if (inStream->getFormat() == oboe::AudioFormat::Float) {
        functionList.emplace<FunctionList<float *>>();
        createCallback<float_t>();
    } else if (inStream->getFormat() == oboe::AudioFormat::I16) {
        createCallback<int16_t>();
    } else {
        stopStreams();
    }
    SAMPLE_RATE = inStream->getSampleRate();
    openOutStream();

    oboe::Result result = startStreams();
    if (result != oboe::Result::OK) stopStreams();
}`

a little bit confused about the order to create duplex inout streams😔

**Comment by philburk** [comment]
@manymingge - You have an interesting comment. But it is not specific to this bug on S8. The entire fxlab app is designed to support a mono input, like from a guitar. If you change it to stereo it will break and you get the "octave down" effect. But that is a different issue. Please open a new Issue if you want to ask questions about duplex streams.
