### ISSUE TITLE
Make sure the sample code restarts audio after disconnect

### ISSUE THREAD

**Issue by philburk** [google/oboe#827]
The sample code should start a new stream in the AudioStreamCallback::onErrorAfterClose() method.

DrumThumper and FXLab already do this.
HelloOboe does this using the DefaultAudioStreamCallback class.

**Comment by ggfan** [comment]
On-hold for now, will come back to it after callback mechanism is reviewed

**Comment by robertwu1** [comment]
Done in most of our samples. Closing
