### ISSUE TITLE
How can I create a recorder?

### ISSUE THREAD

**Issue by yangwuan55** [google/oboe#83]
How can I create a recorder use oboe?
Can I create both a player and recorder work together?

**Comment by dturner** [comment]
We don't currently have a synchronous input and output code sample but it's planned. There is one for AAudio which just needs porting to Oboe - the APIs are very similar. https://github.com/googlesamples/android-audio-high-performance/tree/master/aaudio/echo

**Comment by yangwuan55** [comment]
Can I use do this 
```
builder.setDirection(oboe::Direction::Output);
```
to create a recorder?
Can there be two oboestream at the same time?

**Comment by dturner** [comment]
You can do this: `builder.setDirection(oboe::Direction::Input)` to create an input (recording) stream. Yes, you can have more than one audio stream at the same time.

**Comment by yangwuan55** [comment]
Thanks very much.
