### ISSUE TITLE
Performance regression (or measurement improvement?)

### ISSUE THREAD

**Issue by emilieroberts** [google/oboe#839]
Android Version(s): Chrome OS M81
Android Device(s): Google Pixelbook
Oboe Version: OboeTester 1.5.23

**Short Description**
I noticed a performance regression in latency values in OboeTester between commit fcec5713fa9f833623b2abe9ec6441e04941c849 and current head.  This is true with round-trip latency with loopback plug and tap-to-tone.

**Steps To Reproduce**
- Install fcec5713fa9f833623b2abe9ec6441e04941c849
- Do AAudio, Low-latency, round trip audio test with a loopback plug with buffer of 256 bytes
- Results: 28, 26, 35, 35, 28

- Install master
- Do AAudio, Low-latency, round trip audio test with a loopback plug with buffer of 256 bytes
- Results: 60, 70, 54, 58, 57

**Expected behavior**
- Results are the same or better

**Actual behavior**
- Results are worse

**Additional context**
- In both cases MMAP Exclusive is requested but not given. Output looks the same, but slower.

Is this a regression
Yes

**Comment by philburk** [comment]
> Android Version(s): Chrome OS M81

Is that Android P? Or O_MR1 (8.1)?

> buffer of 256 bytes

is that burst size or bufferSize?

What is the reported burstSize, bufferSize and bufferCapacity in each case?
If different, is it enough to account for the difference in latency?

Do they versions get the LOW_LATENCY or NONE performance Mode?

**Comment by emilieroberts** [comment]
Hi, this is Android P.

The bufferSize defaults to 0 which results in constant xRuns. At 256, there are 0 xRuns.

Output burst = 256, capacity = 2048 in both versions.

Both versions report LOWLAT for output.

Upon retesting, I noticed that in the new version, the input stream is getting NONE for performance mode. This is probable causing the discrepancy.

I can't seem to get a set of settings that gives LOWLAT.

**Comment by philburk** [comment]
NONE vs LOWLAT would cause an increase in latency.
So why do we now get NONE?
Try the TEST INPUT Activity. You can experiment to see what causes NONE mode.
Related parameters would be data format = FLOAT, sample rate,  Convert:Format.

**Comment by emilieroberts** [comment]
I am able to get LOWLAT with the Test Input activity, Record and Play, and the Disconnect test - ie. all the tests when only the input stream is requested.

With round trip or echo (with both input and output), the input stream receives NONE, regardless of settings.
