### ISSUE TITLE
USB vs Audio cable latency

### ISSUE THREAD

**Issue by ekurdesov** [google/oboe#840]
Android Version(s): Android 7+
Android Device(s): Google Pixel 1
Oboe Version : 1.3.3
**Short Description** 
fxlab - tested with a guitar audio cable. The cable basically takes mic input from the guitar and returns audio back to the headphone line. 

If I run this via usb-c cable that transforms the line to 3.5mm audio jack there is a longer latency. 
 
**Steps To Reproduce**
plugging the phone to a guitar adapter like iRig and attach a guitar. Run it via aux then compare it to latency via usb-c port 

**Expected behavior**
no latency
**Actual behavior**
~50-100ms delay 
**Additional context**
There are more and more devices in the android world coming out without aux in line. 
If applicable, please attach a recording of the sound.

**Comment by dturner** [comment]
Just tested on Pixel XL using OboeTester. Latency was 80ms. 

Unfortunately the Pixel XL doesn't have a fast path for USB audio devices (this was introduced on Pixel 2 onwards) so the latency will be much higher than over the 3.5mm headphone jack. 

Working as intended.

**Comment by OscarVanL** [comment]
Hi @ekurdesov. I'm looking to support the iRig Pro IO in my Android app. 

Out of curosity, which iRig device did you use, and what did you have to do to get it to work in Android?
