### ISSUE TITLE
DrumThumper: landscape layout missing elements, causes crash

### ISSUE THREAD

**Issue by emilieroberts** [google/oboe#853]
App name used for testing (please try to reproduce the issue using the Oboe samples and apps): 
DrumThumper

Repro:
- Launch drum thumper
- Rotate to landscape
- Notice crash

Cause:
 - Mixer and slider elements have not been added to the landscape layout file.

This also crashes on Chrome OS by default as it loads the landscape layout for large screens.

**Comment by android-usb** [comment]
This has been fixed and merged.
