### ISSUE TITLE
equalizer not work

### ISSUE THREAD

**Issue by hakendog** [google/oboe#854]
in java MainActivity

>        AudioManager audioManager = (AudioManager) getApplicationContext().getSystemService(Context.AUDIO_SERVICE);
>         int audioSessionId = audioManager.generateAudioSessionId();
>         LiveEffectEngine.setSessionId(audioSessionId);
>         eq=new Equalizer(0,audioSessionId);

in jni

> JNIEXPORT void JNICALL
> Java_com_google_sample_oboe_liveEffect_LiveEffectEngine_setSessionId(
>         JNIEnv *env, jclass, jint sessionId) {
>     if (engine == nullptr) {
>         LOGE(
>                 "Engine dasdas must call createEngine before calling this "
>                 "method");
>         return;
>     }
>     engine->setSessionId(sessionId);
> }

> void LiveEffectEngine::setSessionId(int32_t sessionId) {
>     mSessionId = static_cast<oboe::SessionId>(sessionId);
> }
> 

and I call
`inBuilder.setSessionId(mSessionId);`

but it always nothing change,please help

**Comment by dturner** [comment]
Are you actually changing the [`Equalizer`](https://developer.android.com/reference/android/media/audiofx/Equalizer) settings? What are you expecting to hear?

**Comment by philburk** [comment]
Here is an example of changing the knobs in OboeTester:

https://github.com/google/oboe/blob/d008ab660a9059a1b69ae870f853afd2d8e0cd0e/apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java#L66

**Comment by hakendog** [comment]
> 您實際上是在更改[`Equalizer`](https://developer.android.com/reference/android/media/audiofx/Equalizer)設置嗎？您希望聽到什麼？

`short maxEQLevel = eq.getBandLevelRange()[1];

        int num_bands = eq.getNumberOfBands();
        for (int i = 0; i < num_bands; i++) {
            eq.setBandLevel((short) i, (short) maxEQLevel);
        }
        eq.setEnabled(true);`

I turned all the bands to maximum

**Comment by hakendog** [comment]
and when I call
`outBuilder.setSessionId(oboe::SessionId::Allocate);`
and
outBuilder.getSessionId();
It's always return 0

**Comment by hakendog** [comment]
> 這是在OboeTester中更改旋鈕的示例：
> 
> https://github.com/google/oboe/blob/d008ab660a9059a1b69ae870f853afd2d8e0cd0e/apps/OboeTester/app/src/main/java/com/google/sample/oboe/manualtest/TestOutputActivityBase.java#L66

After testing, either setting the equalizer SessionId to the same as oboe or directly using SessionId = 0 it's all not work.

**Comment by philburk** [comment]
oboe::SessionId::Allocate is defined as 0.
The ID will allocated when you create the stream.
try stream->getSessionId();

> I turned all the bands to maximum

That will just make the sound louder. Try setting the turning all the bands down low except for one band set high. Then you may hear a difference in the spectrum.

**Comment by hakendog** [comment]
> oboe :: SessionId :: Allocate定義為0。
> 創建流時將分配ID。
> 嘗試stream-> getSessionId（）;
> 
> > 我把所有樂隊調到最大
> 
> 那隻會使聲音更大聲。嘗試將所有頻段調低，除非將一個頻段設置為高。然後您可能會聽到頻譜差異。

In the LiveEffect example I added the following code to openStreams

`LOGD("mPlayStream %d",mPlayStream->getSessionId());
`
But I get -1.

The simulator works normally after testing ,but my device can't.
My device is SM-G930F and I flash third party ROM to android pie

**Comment by philburk** [comment]
Try this in OboeTester:
Tap TEST OUTPUT
Check the box for "Effect"
Tap OPEN and START

You should see a non-zero number next to the Effect checkbox. That is the Session ID.

>  I flash third party ROM to android pie

Then there is no way of knowing that changes they made or what they broke. I don't think we can support you on that device. Do you have a device with an official factory ROM?

**Comment by zipcom500** [comment]
In the LiveEffect example,  I added the following code to setupCommonStreamParameters:
builder->setSessionId(oboe::SessionId::Allocate);
and I get mPlayStream SessionId is 8785 in "AAudio" mode and get  mPlayStream SessionId is -1 in "OpenSL ES" mode.
Is it right?

I try to set Equalizer in MainActivity.java with mPlayStream SessionId.
mEqualizer = new Equalizer(0, 8785);
but get error:
Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3

please help, thanks

**Comment by robertwu1** [comment]
Closing since this is a custom ROM
