### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by jerearaujo03** [google/oboe#859]
Is there a way to implement this library in a Flutter project?

**Comment by dturner** [comment]
[Reading the docs](https://flutter.dev/docs/development/platform-integration/c-interop) it seems like it should be fairly straightforward. You can either include the oboe source, or you can use the .aar found on the [releases page](https://github.com/google/oboe/releases).

**Comment by dturner** [comment]
We have no plans to officially support Flutter at present so closing.
