### ISSUE TITLE
Ninja error - build command failed

### ISSUE THREAD

**Issue by griffinperry** [google/oboe#860]
Oboe version: 1.3
Right after the first steps in configuring my app to use the Oboe library, I am receiving the error:

Build command failed.
Error while executing process /Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /AndroidStudioProjects/"app name"/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target clean}

ninja: error: loading 'build.ninja': No such file or directory

I can't seem to find any information on this. It occurs every time I try to rebuild my project even after I refresh the linked C++ Projects.

**Comment by philburk** [comment]
When I have mysterious build errors I always try "Build >> Clean Project".

Also try:
https://www.google.com/search?q=%22loading+%27build.ninja%27%3A+No+such+file+or+directory%22

**Comment by philburk** [comment]
@griffinperry - Let us know if you want to keep this open. Otherwise we will close this next week.
