### ISSUE TITLE
Gradle build stuck at the task "calculate graph"

### ISSUE THREAD

**Issue by jean25marc** [google/oboe#865]
I have this problem , when I try the both options documented to use Oboe in an android project. In both cases  gradle wont achieve to build, and runs everlastingly the "calculate task graph"...Strangely I cannot select the "refresh linked c++ projects" in the build menu....
What should I do ?
[CMakeLists.txt](https://github.com/google/oboe/files/4673415/CMakeLists.txt)

**Comment by philburk** [comment]
I haven't seen this particular problem. But I often find build problems are solved by using the menu item:     "Build >> Clean Project"

Also does this help?
https://stackoverflow.com/questions/41116926/android-studio-gradles-calculate-task-graph-takes-too-long

Please let us know if it works. I am assigning this to our build expert, Gerry Fan.

**Comment by jean25marc** [comment]
So I found that the android NDK was missing, starting a new project after installing it solved the problem ( I should have seen this yesterday but I was assuming it was installed on my configuration) thanks for your quick response anyway
