### ISSUE TITLE
Passing mp3 asset from Flutter to Oboe

### ISSUE THREAD

**Issue by ffarall** [google/oboe#872]
I'm trying to use oboe for a 3D audio processing app due to it's low latency. The app will have a C++ backend, which does the processing, and the frontend is done with Flutter. I'm running a couple of tests to see if it'll work but I'm having issues loading assets from Flutter to Oboe. I checked what you did in RhythmGame with Java, but couldn't quiet find a way of doing that straight from Dart to C++.
The connection between front and backend is through dart::ffi

**Comment by philburk** [comment]
I think the main question is how do you transfer **any** data between Dart and native code. This is not really an Oboe issue. You will get better answers from a Dart or Flutter forum. We just don't know the answer. Sorry.

And BTW, Oboe cannot play MP3 files directly, they need to be decoded first.
