### ISSUE TITLE
HelloOboe ignores playback device and other user settings

### ISSUE THREAD

**Issue by chrbsg** [google/oboe#879]
Android version(s):10
Android device(s): Galaxy S20 Ultra 5G
Oboe version:master
App name used for testing (please try to reproduce the issue using the Oboe samples and apps): HelloOboe

**Short description**
Playback device dropdown appears to be ignored

**Steps to reproduce**
Reproducer 1
Run demo
Select "SM-G988B built-in earphone speaker"
touch screen, listen
select "SM-G988B built-in speaker"
touch screen, listen

Reproducer 2
Run demo
select "built-in earphone speaker"
touch screen
= hear two tones
select channel count 1
touch screen
= hear one tone
select "built-in speaker"
touch screen
= hear one tone
select "built-in earphone speaker"
touch screen
= hear two tones, even though channel count is still 1

**Expected behavior**
Heard audio should change due to different speaker
Channel count should be respected across changing output device

**Actual behavior**
Audio remains the same. I think it's always playing back on earphone speaker.
Channel count goes wrong

**Any additional context**
The same tests on Pixel 2 XL results in a clear audible difference between earphone speaker and non-earphone speaker, with channel count resulting in correct tones.

**Comment by chrbsg** [comment]
> We're struggling to understand exactly the behaviour you're describing, and it sounds like there might be more than one bug here.

Yes, this could be two separate bugs.

> If we ignore anything to do with channel count for now, does the output device change when you change it in the UI?

No. There are two playback devices in the dropdown:
  - SM-G988B built-in earphone speaker
  - SM-G988B built-in speaker
Both of these appear to select the same device (built-in speaker, not earphone speaker).
 
> > = hear two tones, even though channel count is still 1
> 
> Do you mean that you expect to hear 2 tones, or that you are hearing 2 tones and you only expect to hear 1?

That means that I hear two tones, but expect to hear one (because the channel count is 1).
On the Pixel 2 XL, with channel count=1, I can toggle between "built-in earphone speaker" and "built-in speaker", press the screen, and hear one tone. (I'm assuming this is the correct behaviour)

On the S20, with channel count=1, there is initially 1 tone, but toggling between the two speakers results in 2 tones playing.  But if I select channel_count=2, then channel_count=1, then only one tone plays again. It's like the app/phone forgets that it's only supposed to be playing one channel when the playback device is changed, and this is forced to reset by changing the channel count from 1 to 2 then back to 1.

**Comment by philburk** [comment]
I am also seeing similar problems on a Pixel 3a so I don't think this is an S20 issue. I think the problems are in Hello-Oboe.

Launch Hello-Oboe
Touch screen - hear two tones
Select 1 channel
Touch screen hear one tone
Plug in headphones

EXPECT - sound switch to headphones
ACTUAL - sound still coming from speakers

Switch API to OpenSL ES
Hear single tone from headphones
Switch API to AAudio
Hear single from headphones
Unplug headphones

EXPECT - hear single tone from speakers
ACTUAL - hear two tones from speakers

**Comment by philburk** [comment]
There was a problem in Hello-Oboe. 
When the user selected a new channelCount it would open a new stream with that channelCount plus the default settings.
When the user selected a new deviceId it would open a new stream with that deviceId plus the default settings. It would ignore the previously set channelCount. The same would happen with audioApi.
If the user plugged in headphones it would just reopen a new stream with all defaults and ignore all the settings.
The result was a very confusing experience for the user, and unexpected results when plugging in headphones.

This fix involves storing the desired properties in the HelloOboeEngine and using the current properties when opening any stream.

**Comment by dturner** [comment]
Let's keep this open as a reminder to check the other samples for this issue as well.
