### ISSUE TITLE
Device menu should be disabled for OpenSL ES in apps

### ISSUE THREAD

**Issue by philburk** [google/oboe#881]
OpenSL ES does not support selecting a device.
So in our sample apps, we should disable the device selection menu
when OpenSL ES API is selected.

**Comment by philburk** [comment]
@robertwu1 - Was this fixed by #1583 ?

**Comment by robertwu1** [comment]
Fixed for Hello Oboe in #1583. Live Effect had this already. For other samples, we don't let the users pick the device.

We shouldn't implement this in OboeTester.

Thus, closing.
