### ISSUE TITLE
LiveEffect demo corrupt audio with internal mic and speakers on Samsung S20 Ultra 5G

### ISSUE THREAD

**Issue by chrbsg** [google/oboe#892]
Android version(s): 10
Android device(s): Samsung S20 Ultra 5G
Oboe version: master
App name used for testing: LiveEffect
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
Select built-in microphone and built-in earphone speaker. Audio sounds corrupted, like a deep rumbling. On Pixel 2 XL, the same test (built-in microphone and built-in earphone speaker) sounds crystal clear.

**Steps to reproduce**
Load LiveEffect, select bult-in microphone, built-in earphone speaker
Select aaudio or OpenSL ES (happens on both)
Hold phone to ear and talk

**Expected behavior**
audio should be clear

**Actual behavior**
audio is not clear

**Any additional context**

**Comment by philburk** [comment]
Thanks for reporting this. We don't have an S20 so this is hard for us to test.

> Select aaudio or OpenSL ES (happens on both)

OK, then this is NOT related to MMAP because OpenSL ES does not use MMAP.
And it is not related to #824 "broken mono" because LiveEffect uses stereo input and output.

@chrbsg - can you hear your voice behind the rumbling or do you only hear the rumbling?
Is your voice distorted, chopped up, raised or lowered in pitch?
Is there rumbling when you don't speak?

Could you please try some tests in OboeTester, like RECORD AND PLAY?
https://github.com/google/oboe/tree/master/apps/OboeTester/docs

After you make a recording, you can click SHARE to send it to GDrive or GMail.
Then you could attach a short recording to this bug. That will tell us a lot.

Can you please enter:

    adb shell getprop ro.hardware.chipname
    adb shell getprop ro.build.description

and paste the results?

**Comment by chrbsg** [comment]
I can hear my voice - if I whisper it sounds clearer, if I' speak louder then it's more distorted. There is a rumbling when not speaking, and this seems to be louder when speaking. It sounds from the recording like the played back audio is slowed down?

I tried OboeTester "Record and Play". Results:

(OpenSL, 48kHz, 2ch, perf=LOW_LATENCY)  = ok
(AAudio, 48kHz, 2ch, perf=LOW_LATENCY) = bad
(AAudio, 48kHz, 2ch, perf=NONE) = ok
(AAudio, 48kHz, 2ch, perf=POWER_SAVING) = ok
(AAudio, 44100Hz, 2ch, perf=LOW_LATENCY) = ok
(AAudio, 16kHz, 2ch, perf=LOW_LATENCY) = ok
(AAudio, 16kHz, 2ch, perf=NONE) = ok
(AAudio, 8kHz, 2ch, perf=LOW_LATENCY) = ok
(AAudio, 8kHz, 1ch, perf=LOW_LATENCY) = ok
(AAudio, 16kHz, 1ch, perf=LOW_LATENCY) = ok
(AAudio, 24kHz, 1ch, perf=LOW_LATENCY) = ok
(AAudio, 44100Hz, 1ch, perf=LOW_LATENCY) = ok
(AAudio, 48kHz, 1ch, perf=LOW_LATENCY) = bad

So it looks like this is caused by using AAudio 48kHz with LOW_LATENCY. 
What seems odd is that I couldn't reproduce this with OpenSL ES in "Record and Play" but it happens with OpenSL ES selected in the LiveEffect demo. 

Recording with perf=NONE: [oboe_recording-none.wav.gz](https://github.com/google/oboe/files/4781900/oboe_recording-none.wav.gz)
Recording with perf=LOW_LATENCY: [oboe_recording-lowlatency.wav.gz](https://github.com/google/oboe/files/4781901/oboe_recording-lowlatency.wav.gz)

**Comment by chrbsg** [comment]
```
$ adb shell getprop ro.hardware.chipname
exynos990
$ adb shell getprop ro.build.description
z3sxxx-user 10 QP1A.190711.020 G988BXXU1ATCD release-keys
```

**Comment by philburk** [comment]
@chrbsg - thank you so much for the info. That is super helpful.

I have passed this information along to Samsung at b/159066712

**Comment by taemincho** [comment]
Same here, heavy glitches on Samsung S20

Unlike @chrbsg 's result above, the problem happens for both OpenSLES and AAudio in all cases if they run in **SL_ANDROID_PERFORMANCE_LATENCY** or **PerformanceMode::LowLatency**  modes, respectively.

If they run in **SL_ANDROID_PERFORMANCE_NONE** or **PerformanceMode::None**, all cases work fine.

**Device info:**
adb shell getprop ro.hardware.chipname
exynos990

adb shell getprop ro.build.description
y2sxx-user 10 QP1A.190711.020 G985FXXU1ATB3 release-keys

**Comment by philburk** [comment]
I have heard from Samsung that a fix for this has been released to the market.
One UI 2.5 update , G98xxXXU4BTH5
I think that works for Q.

I do not have an S20.

@chrbsg If you have that update, can you please try your test again?
@taemincho Can you also test this?

**Comment by chrbsg** [comment]
@philburk I no longer have the S20.
