### ISSUE TITLE
Which to use now: openManagedStream() or openStream()?

### ISSUE THREAD

**Issue by rpattabi** [google/oboe#894]
[Release notes of 1.4.2](https://github.com/google/oboe/releases/tag/1.4.2) is suggesting to use `openStream()` in conjunction with `shared_ptr`. Documentation elsewhere mentions about using `ManagedStream` which is just an alias for stream `unique_ptr` through `openManagedStream()`.

Since both exist, I would like to know which is to be preferred.

**Comment by dturner** [comment]
Good question. `openStream` with `shared_ptr` is the preferred method now. The docs need updating to reflect this.

**Comment by rpattabi** [comment]
Thanks for the clarification.

**Comment by alexrdclement** [comment]
@dturner I think this may have gotten lost since the ticket was closed but I wanted to call out that the Getting Started docs still recommend ManagedStreams.

**Comment by philburk** [comment]
GettingStarted guide was updated in
https://github.com/google/oboe/commit/d1376b0399d0ca1c389bee29d1afdd2dd21a6ceb
