### ISSUE TITLE
LiveEffect demo feature request: AEC button

### ISSUE THREAD

**Issue by chrbsg** [google/oboe#898]
The LiveEffect demo suffers from echo feedback when using phone microphone and speakers. Would it be possible to add a UI button to enable AEC? (such a demo was also previously requested by others in #85 ). And also, if possible, a text widget to show whether AEC is hardware or software.

(The motivation for this is that it is not clear how to query and enable hardware AEC from Oboe - suggestion seems to be to use the Java API AcousticEchoCanceler which implies that this can't be done from within C++, and it's not clear whether AcousticEchoCanceler requires usage of AudioRecord, which means microphone audio has to be read in Java code?)

**Comment by philburk** [comment]
It might be good to have a local AEC that can be compared with the OS AEC.
Using the OS AEC causes very high latency.

**Comment by robertwu1** [comment]
Added to OboeTester. Not adding this to samples as it increases latency too much
