### ISSUE TITLE
Ableton Link test app

### ISSUE THREAD

**Issue by jbloit** [google/oboe#90]
Hi,
I started a test app showing a way to integrate Ableton Link on Android, and it uses Oboe. The (not yet fulfilled) goal is to have some springboard code similar to LinkHut, on Android platforms. Hopefully it can help others working on Android. Feedback is welcome, and contributions even more so!

https://github.com/jbloit/AndroidLinkAudio

**Comment by dturner** [comment]
Many thanks for creating and sharing this repo. This looks really great! 

OK if I add the link to the Oboe homepage?

**Comment by jbloit** [comment]
Yes of course!

**Comment by dturner** [comment]
Thanks. Done.
