### ISSUE TITLE
How to get support for resampling using NDKExtractor?

### ISSUE THREAD

**Issue by rafagan** [google/oboe#903]
Inside NDKExtractor the audio skip decoding if the sample rate doesn't match. In Oboe recent releases we have AudioStreamBuilder methods like **setSampleRateConversionQuality** and **setSampleRate**.

How can I play audio with different sample rate from specified without experience "pitch shift" effects?

**Comment by philburk** [comment]
Use setSampleRate() in the stream builder to match the recorded sample rate of the audio content.

AAudio and OpenSL ES both support sample rate conversion. But not for low latency streams.
You can use the Oboe sample rate converter with setSampleRateConversionQuality() to get a low latency stream with sample rate conversion.

If your stream is recorded at a rate different from the the hardware output rate then you need sample rate conversion for it to sound normal. If you just play it directly with no sample rate conversion then it will change the pitch and the speed of the playback.

If you want to change the speed or the pitch of the playback independently then you need a "phase vocoder". That is an advanced technique that is not provided by Oboe. You probably don't want that.

**Comment by rafagan** [comment]
Actually, I have a sound with 44100hZ sample rate and I want to play it in my audio stream configured with 48000hZ sample rate without pitch shift effects. I need to use Phase Vocoder algorithms?

**Comment by philburk** [comment]
>  I have a sound with 44100hZ sample rate and I want to play it in my audio stream configured with 48000hZ sample rate

The simplest approach is just to open the stream with a sampleRate=44100.

But if you are mixing 44100 Hz and 48000 Hz audio then opening a 48000 Hz stream makes sense.
You don't need a phase vocoder. Just use the resample directly to convert your 44100 Hz data to 48000 Hz and then mix it with your other 48000 Hz data.

  https://github.com/google/oboe/blob/master/src/flowgraph/resampler/README.md

**Comment by rafagan** [comment]
Ok, I'll try to use that. There's some reference to understand the algorithm behind resampling?

**Comment by philburk** [comment]
It is based on the sinc function. 

https://ccrma.stanford.edu/~jos/resample/resample.pdf
