### ISSUE TITLE
How to remove "Larssen Effect" from input stream?

### ISSUE THREAD

**Issue by rafagan** [google/oboe#905]
When I run the Android FXLab, the speaker generates noise (like larssen effects) to input recorder. How can I filter these noise?

**Comment by dturner** [comment]
Simple: wear headphones :) You're always going to get feedback when the microphone can "hear" the speaker output.

**Comment by philburk** [comment]
The fxlab app is designed to use with an interface. For guitars, you could use something like the IK Multimedia iRig 2 Guitar Interface. Note that some models use the 3.5 mm headphone jack and some use USB. The 3.5 mm model is better if your phone has a 3.5 mm jack.

Almost any USB audio interface will also work.
