### ISSUE TITLE
fxlab unmute button gives echo when no sound

### ISSUE THREAD

**Issue by lucaszanella** [google/oboe#906]
Android version(s): 8
Android device(s): Moto Z

**Short description**
When we unmute the oboe fxlab app, even if there's no audio, we hear an echo.

My current fix for this problem was to call `NativeInterface.enable(true)` only when we have at least 1 effect, but this still brings the echo on (I guess)

**Steps to reproduce**
Open fxlab, unmute, hear echo (try to make noises)

**Expected behavior**
No effects unless I add an effect

**Actual behavior**
Echo right after unmute

I don't know if this has anything to do with this: https://github.com/google/oboe/issues/905

**Comment by philburk** [comment]
Same issue. See new comment in https://github.com/google/oboe/issues/905#issuecomment-648954183
