### ISSUE TITLE
Play 3D audio？

### ISSUE THREAD

**Issue by chenzhaohui00** [google/oboe#907]
Does the library provide the ability to play 3D audio, like OpenAl, by setting the location of the playback source?
I saw Oboe while looking at the OpenSL ES documentation. But I have read the guidelines and API documents, but I can't find any relevant API. Do I still need to use OpenSL ES?
Not good at English , sorry.

**Comment by philburk** [comment]
OpenSL ES on Android does not support 3D audio. AAudio also does not support it.

The only thing that OpenSL ES on Android does that AAudio does not is MP3 playback and streaming from a URL.

> Do I still need to use OpenSL ES?

Only on Android before version 8.1. We recommend using Oboe for all native audio. It will automatically use either AAudio or OpenSL ES depending on Android version.
