### ISSUE TITLE
Input stream sample code?

### ISSUE THREAD

**Issue by jbloit** [google/oboe#91]
Hi, 
I'm trying to copy an input stream into an output stream. I'm looking at the code snippet from the "full guide" page, but I can't manage to implement it correctly. The main problem seems to be that the input stream is not created. Here are the 2 methods I use to create it:

void PlayAudioEngine::setupRecStreamParameters(oboe::AudioStreamBuilder *builder) {
    builder->setAudioApi(mAudioApi);
    builder->setDeviceId(mRecDeviceId);
    builder->setChannelCount(mChannelCount);
    builder->setDirection(oboe::Direction::Input);
    builder->setSharingMode(oboe::SharingMode::Exclusive);
    builder->setPerformanceMode(oboe::PerformanceMode::LowLatency);
}
void PlayAudioEngine::createRecStream() {
    oboe::AudioStreamBuilder builder;
    setupRecStreamParameters(&builder);
    oboe::Result result = builder.openStream(&mRecStream);
    if (result == oboe::Result::OK && mRecStream != nullptr) {
        result = mRecStream->requestStart();
        if (result != oboe::Result::OK) {
            LOGE("Error starting stream. %s", oboe::convertToText(result));
        }
    }

But after:
oboe::Result result = builder.openStream(&mRecStream);

mRecStream is still nullptr. 

I'm using the latest Oboe code for master btw.

Thank you

**Comment by philburk** [comment]
What is result after the open?

Opening an input can fail if another app is doing recording or if you did not request permission to use the microphone.

An example of requesting permission is here:

https://github.com/googlesamples/android-audio-high-performance/blob/master/aaudio/echo/src/main/java/com/google/sample/aaudio/echo/MainActivity.java#L159

The same technique should work with any app that does recording.

Let us know if that fixes the problem.

**Comment by jbloit** [comment]
This was indeed the problem, thank you!
