### ISSUE TITLE
DrumThumper app doesn't play other wav files clearly

### ISSUE THREAD

**Issue by LordByron1788** [google/oboe#912]
Android version(s): 9
Android device(s): Samsung Galaxy A10
Oboe version: 1.4.2
App name used for testing: DrumThumper

**Problem**
If I replace one of the drum wav files with a different wav file, the app does not play this file correctly.

**Steps to reproduce**
In the DrumThumper sample, I replaced the "Crash" wav file with a "Piano" sample wav file. No coding changes were made.
Attached is a recording of the sound on a Galaxy A10, as well as the wav file. The two sounds do not sound the same.  

**Expected behavior**
The sound in DrumThumper app should match the sound of the wav file when played in a normal player.

**Actual behavior**
The sound appears dampened, it also sounds an octave lower than its pitch. There is feint cackling sound when the sound starts
and stops.

**Any additional context**
I raised this issue before on #768, but my understanding now is that this sample now supports stereo wav files. So what is the issue?

If applicable, please attach a recording of the sound.

[recording.zip](https://github.com/google/oboe/files/4832322/recording.zip)

**Comment by android-usb** [comment]
The source samples MUST BE Mono, 4.1K samples. Stereo playback is supported by panning the mono samples in the mixing stage.
Please understand that this app is not intended to be the ultimate sample player. It is intended to show best practices for optimal playback. Handling different source sample formats is out of the scope of the application.

**Comment by philburk** [comment]
I think a lot of people will use DrumThumper as a starting point for their own apps.
So this will probably happen again. Maybe display an error if the sample is stereo.

**Comment by LordByron1788** [comment]
DrumThumper app is useless. 

Wasn't it supposed to be a beginner app to help people become familiar with wav files as per #548 ?

It seems can't be adapted for anything.  Is being able to play a stereo wave file such an unreasonable request, that no mention of how to do it is warranted anywhere?

You didn't even bother to mention this limitation in the Readme (but you are happy to waste time making glib references to 90's Pop bands).

How about an explanation as to why? Or even providing a link to a resource where people can understand and adapt this for themselves? Is it so hard, for you to actually try and be helpful to beginners that want to try and use this library?

Every time an issue is raised on this app it is closed prematurely without thought. Just like #784. It is annoying when you disregard feedback about the app in such dismissive manner. Is the cackling sound after rapid pressing a button on a different MONO sample also a deliberate feature of this app!?!

Really poor all round.

**Comment by philburk** [comment]
> DrumThumper app is useless.

Ouch.

It is challenging to find out the right amount of features to put in sample code. If we put in too many features then it can obscure the more important ones. Also I find it harder to remove code from a sample app than to add it. So we aim to provide a minimal app that demonstrates the critical techniques and doesn't do much more.

Mono samples in a drum box app are very common so we focussed on that. Mostly we wanted people to see that they can mix multiple sounds into one stream.  Mixing stereo files is quite complicated and is really outside the scope of Oboe. There are many "right" ways to do that. I recommend visiting DSP sites to get some ideas on how to mix stereo sources.

> You didn't even bother to mention this limitation in the Readme

Good point. For each sample app we should provide pointers about how to extend or modify the app. People use these apps as starting points for their own code and we could make them more usable. Thanks for the advice.  I added #913 

> Every time an issue is raised on this app it is closed prematurely without thought.

We have a problem with inactive Issues just staying Open forever. So we are starting to close Issues when they seem complete. You can always reopen them you want to pursue it further.

>  Is the cackling sound after rapid pressing a button on a different MONO sample also a deliberate feature of this app!?!

That sounds more like a bug than a feature. I cannot reproduce that on Pixel 3a. If you have time, please file a separate issue with steps and a recording.

Thanks for the feedback.

**Comment by philburk** [comment]
@android-usb - Paul, can you add an error Toast if DrumThumper opens a stereo file? That may save developers some time in the future.

**Comment by android-usb** [comment]
We now display a toast if a WAV resource with an incompatible format is detected.
