### ISSUE TITLE
How to achieve pitch shift?

### ISSUE THREAD

**Issue by rafagan** [google/oboe#918]
I trying to work in an algorithm for pitch shift effects, but it's not seems trivial.

I could achieve some results with https://github.com/breakfastquay/rubberband, but with so much noise and clicks as side effects.
There's some work done with Oboe to make pitch?

**Comment by philburk** [comment]
If you are willing to also change the duration of the sound then just use the resampler as answered here:
https://github.com/google/oboe/issues/903#issuecomment-650622487

For a polyphonic synthesizer, that should work fine. Linear interpolation should also be fine.

If you want pitch shift without changing time then you need a phase vocoder like "rubberband".
That is outside the scope of Oboe. If you are having trouble with rubberband, then they will be better able to help you.

**Comment by rafagan** [comment]
The algorithm from #903 is very good and solved my problem for resampling using NDK. But for pitch shift, the same algorithm works in real time inside the audio thread?

**Comment by philburk** [comment]
You keep saying "pitch shift" but I still don't know what you mean.

Resampling will cause a **pitch shift** and will also speed up or slow down the sample in time.
The phase vocoder, eg. "rubberband", will also cause a **pitch shift** and provides independent control of the time stretching.

You can do resampling in a real-time thread.
You might or might not be able to do a phase vocoder in real-time. It is much harder and outside the scope of Oboe.
