### ISSUE TITLE
How to open a file descriptor instead of AAsset in FFMpegExtractor?

### ISSUE THREAD

**Issue by rafagan** [google/oboe#919]
In examples, is available the class FFMpegExtractor, with callback methods `int read(void *opaque, uint8_t *buf, int buf_size)` and `int64_t seek(void *opaque, int64_t offset, int whence)`. How can I replace the logic using AAsset to something more generic, like the std FILE type?

**Comment by robertwu1** [comment]
You may be able to use ExoPlayer Media3 Transformer to convert an MP3 file or URI to a WAV or PCM.

https://developer.android.com/guide/topics/media/transformer/getting-started
