### ISSUE TITLE
OboeTester does not respect settings after activity pause and resume

### ISSUE THREAD

**Issue by ananthp** [google/oboe#921]
Android version(s): Not specific.
Android device(s): Not specific. Reproducible on multiple devices.
Oboe version: Not specific. Tested with [latest commit](https://github.com/google/oboe/commit/de9047d8a1fbf56db849388de78cc54ffa76af96)
App name used for testing: OboeTester

**Short description**
OboeTester does not consider settings chosen by the user after resuming from activity pause.

**Steps to reproduce**
1. Open OboeTester -> Record and Play
1. Without changing any settings on the top, press RECORD, and STOP in a moment. This should show the API, channel count, samplerate etc. used by the stream, in grayed out text to the right of GUI controls. As we haven't changed any settings, these are the default values for our device.
1. Change *Channels* from 0 to a number other than the default number shown in the right. For instance, if default channel count is 2, set Channels to 1. (Don't press RECORD button yet).
1. Lock the screen. (This should put the activity on pause)
1. Unlock the screen. Channels drop box still has the value we set.
1. Tap RECORD.
1. Observe the actual stream parameters, especially Channels.

**Expected behavior**

Channels should have been set according to our selection. (= 1).

**Actual behavior**

Channel count set as per device default. (2 in my case).

**Any additional context**

* To get the desired channel count, we have to kind of force refresh it, by selecting a different value (say, 3), and selecting the correct value again.
* The issue is not limited to only `Channels` setting here. All GUI controls across all OboeTester activities exhibit this behavior. The issue is apparent when the controls let us select and also display the actual value used, as in this case. This mismatch between the UI and the actual value in the app will be difficult to detect when such feedback is missing. (I have seen `enableOboe workarounds` checkbox misbehaving in the past. We can never know if workarounds are enabled or not unless we have a glitchy device).
* This could be related to #879

**Comment by dturner** [comment]
App needs updating to support Activity lifecycle changes (see [viewmodel](https://developer.android.com/topic/libraries/architecture/viewmodel))
