### ISSUE TITLE
Audio Click noise happens when the audio reaches the end

### ISSUE THREAD

**Issue by rafagan** [google/oboe#929]
Every time my audio track reaches the end, a click noise is happening. I'm using the OboePlayer from examples. Maybe there's something with the renderSilence call when we don't have samples available to fill the buffer?

**Comment by rafagan** [comment]
When I play the file in loop, the click never behaves. Making the same experiment with the same audio, but in a wave format, i can't hear the click.

**Comment by philburk** [comment]
At the end of the file, you may have a buffer that can only be partially filled. You should then fill the remainder of the sample with zeros.

You can then return a stop code to stop the stream or just keep playing and filling the buffer with zeros.

> but in a wave format, i can't hear the click.

Are you saying it depends on the file format? Maybe there is a problem with the file parser.

Closing for now. Reopen if you have more questions.
