### ISSUE TITLE
use `<cstdint>` instead of `<stdint.h>`

### ISSUE THREAD

**Issue by philburk** [google/oboe#946]
We might want to use `<cstdint>` instead of `<stdint.h>` as this seems to be the RightWay™. Source: https://stackoverflow.com/questions/13642827/cstdint-vs-stdint-h

_Originally posted by @dturner in https://github.com/google/oboe/pull/945_

**Comment by philburk** [comment]
We also need to add:

using std::int32_t;
using std::uint32_t;
etc.

**Comment by philburk** [comment]
Here is a summary based on a lengthy discussion in Android Chatty:

We have three options:

1) Include **<cstdint>** and change all our code to use **std::int32_t**.
This is modern, and guaranteed to work. But it requires a lot of edits.

2) Include **<cstdint>** and continue to use **int32_t**.
This is not 100% guaranteed to always work because an implementation can legally not support it.But practically speaking, this will probably continue to be supported by whatever is used to build Android because it is now common practice.

3) Include **<stdint.h>** and continue to use **int32_t**.
This is old-school. But it is guaranteed to work so we might as well use it.

It seems like (3) is the safest and easiest option.

**Comment by dturner** [comment]
Thanks for investigating and the write up. Good to know.
