### ISSUE TITLE
Huawei P30: AAudio a sound is corrupted and OpenSL has a high latency

### ISSUE THREAD

**Issue by banburubi** [google/oboe#952]
Android version(s): 10 (10.1.0.123 (C431E22R2P5))
Android device(s): Huawei P30 (ELE-L29)
Oboe version: 1.4.2
App name used for testing: Similar to LiveEffect
 
**Short description**
**Steps to reproduce**
In voice related application, I'm working on, I'm having some issues on Huawei P30 related to how AAudio and OpenSL behave. On other tested phones of different vendors it works without any issues.

The application has almost the same setup as LiveEffect. There are 2 streams: one for input and another for output, both a requested in Exclusive, Low-latency, I16 mode. Input stream has 1 channel, Output stream has 2 channels. Callback is attached to the output stream. Sample rate and frames per callback are set using this method: https://github.com/google/oboe/blob/master/docs/GettingStarted.md#obtaining-optimal-latency

After requesting streams I'm getting such parameters:

========
AAudio:

Output:
- Frames per burst: 240
- Buffer size in frames: 480
- Channels: 2
- Sample rate: 48000
- Sharing mode: Shared
- Performance mode: Low-latency

Input:
- Frames per burst: 240
- Buffer size in frames: 3840
- Channels: 1
- Sample rate: 48000
- Sharing mode: Shared
- Performance mode: Low-latency

========
OpenSL:

Output:
- Frames per burst: 960
- Buffer size in frames: 1920
- Channels: 2
- Sample rate: 48000
- Sharing mode: Shared
- Performance mode: None

Input:
- Frames per burst: 960
- Buffer size in frames: 15360
- Channels: 1
- Sample rate: 48000
- Sharing mode: Shared
- Performance mode: None

========

**Expected behavior**
On Huawei P30: With AAudio the sound is not corrupted. With OpenSL the latency is low. 

**Actual behavior**
On Huawei P30: With AAudio the sound is corrupted. With OpenSL the latency is high.

Looking forward to your feedback.

Thank you very much.

P.S. Probably these issues are related:
https://github.com/google/oboe/issues/525
https://github.com/google/oboe/issues/386

Best,
Vladymyr.

**Comment by philburk** [comment]
Some Huawei devices do not support mono recording properly. Try recording in stereo and then just use the first channel.

Some Huawei devices disable the FAST mixer so they will have higher than expected latency for OpenSL ES.

We can try to workaround the mono input issue. Can you please tell me what you get for these properties?

    adb shell getprop ro.product.manufacturer
    adb shell getprop ro.hardware.chipname
    adb shell getprop ro.arch

**Comment by banburubi** [comment]
Thank you very much for the reply. 

I will try to use stereo mic. - will tell you tomorrow.

Regarding the properties:
- **Huawei**
- [it was empty] but it is: **kirin980_cs**
- [it was empty] but from abi property:  **arm64-v8a**

**Comment by banburubi** [comment]
I have tried to use 2 channels for the input stream as you suggested before. For Huawei P30 it still does not work, on other phones it works fine. Is there anything else I can do?
Thank you very much.

**Comment by philburk** [comment]
The mono recording problem was fixed in Q for Mate 20 and possibly for P30 as well. They both use the Kirin 980.
This is tracked internally at b/119549057

> I have tried to use 2 channels for the input stream as you suggested before. For Huawei P30 it still does not work,

So this may be a different issue. It may be related to the CPU performance.

@banburubi - Is there any improvement if you tap on the screen while running? That can boost the CPU frequencies on some devices.

Does LiveEffect have the same problem on the P30?

Have you tried the "ECHO INPUT to OUTPUT" test in OboeTester?

To find more information about the device you can run this ADB script on Linux or Mac.

    for p in \
        ro.product.brand ro.product.manufacturer ro.product.model \
        ro.product.device ro.product.cpu.abi ro.build.description \
        ro.hardware ro.hardware.chipname ro.arch "| grep aaudio";
        do echo "$p = $(adb shell getprop $p)"; done

**Comment by banburubi** [comment]
Hey, update from my side. I've tested it on also on Huawei P Smart 2019, with default Android 9.0. It has the same issue with the sound corruption. Looking through the code on my side and after several tries the issues was fixed, still having low-latency, in such a way:

**Comment by philburk** [comment]
User has solved their problem.
OpenSL ES buffering improving.
Closing as Fixed.
