### ISSUE TITLE
avformat_open_input failing for wav file

### ISSUE THREAD

**Issue by ashfaq1701** [google/oboe#959]
In RhythmGame sample there is a class called FFMpegExtractor. I want to reuse this class (by modifying a bit) in my project. It is working for mp3 files (compressed) but not working for uncompressed wav files. It is failing in this line,

https://github.com/google/oboe/blob/master/samples/RhythmGame/src/main/cpp/audio/FFMpegExtractor.cpp#L82

This means that `avformat_open_input` is not working for wav data. I tried to probe the InputFormat by using `av_probe_input_format`, but it is returning null.

`int result = avformat_open_input(&avFormatContext,
                                     "", /* URL is left empty because we're providing our own I/O */
                                     nullptr /* AVInputFormat *fmt */,
                                     nullptr /* AVDictionary **options */`

I want to reuse this because in that case I could use the resampling code without any modification. Can you suggest me how I can reuse this code for wav file?

@dturner You wrote this code, can you kindly help? I am stuck here from last few days.

**Comment by dturner** [comment]
It could be that you need to enable the WAV demuxer when configuring FFmpeg. [Here's the script I used.](https://gist.github.com/dturner/11fe5c8e420c2a73e15537274aafbd3a). 

Try adding `--enable-demuxer=wav`

**Comment by ashfaq1701** [comment]
@dturner Thank you! I added wav demuxer and pcm_16le decoder and encoder. It worked.
