### ISSUE TITLE
Add example of calling AAudio from a background thread

### ISSUE THREAD

**Issue by philburk** [google/oboe#960]
If multiple threads are opening and closing stream then there can be race conditions that result in a crash. #953

The use of a single threaded audio "manager" can be used to avoid this.
The Java code can send start/stop messages to the thread when the app goes through its lifecycle, or in response to user input.
Error callbacks can occur when a device is disconnected. The callback can send a command to this thread.
The thread can have delays so that the app has time to respond to device changes from both Java and the error callback and then decide what to do.

Maybe we could put this in LiveEffect or Hello Oboe.

**Comment by dturner** [comment]
![image](https://user-images.githubusercontent.com/873212/104492836-1e00f280-55cc-11eb-9f93-0a48eacbb13e.png)

**Comment by philburk** [comment]
If we do decide to do a Command Thread then we should use the Android Handler and Looper classes.
It is probably enough to just use an AsyncTask.
