### ISSUE TITLE
How to handle headphone plugging and re-route i/o

### ISSUE THREAD

**Issue by ashfaq1701** [google/oboe#962]
How I can handle headphone plugging and re-route output to headphone speaker or input to headphone mic?

I am using Android 10 and the stream crashes when I connect headphone. I get some error messages like,

E/AudioTrack: processAudioBuffer(4154): EVENT_MORE_DATA requested 768 bytes but callback returned -1 bytes
E/AAudioStream: setState(11) tried to set to 9 but already DISCONNECTED
E/AudioStreamInternalCapture_Client: callbackLoop: read() returned -899
E/AAudioStream: setState(9) tried to set to 9 but already DISCONNECTED
E/AAudioStream: joinThread() - but has no thread
    setState(9) tried to set to 11 but already DISCONNECTED

I know I can write broadcast receiver to listen headphone plug-in or plug-out events. Then what can I do, close and create a new stream?

**Comment by ashfaq1701** [comment]
Actually no need to respond. I see that I can use onErrorAfterClose.

**Comment by philburk** [comment]
> I am using Android 10 and the stream crashes

Does it actually crash or do you just see some error logs?

More info on this topic at https://github.com/google/oboe/blob/master/docs/notes/disconnect.md

**Comment by ashfaq1701** [comment]
@philburk It was just showing error messages. But I had some problem in my code recreating the streams. I got them fixed now.

Thanks for sharing the document. :+1:
