### ISSUE TITLE
requestStart() doesn't start after removing BLE earbuds

### ISSUE THREAD

**Issue by jmzorko** [google/oboe#972]
I am experiencing an issue wrt headphone / earbud device attach / detach:

1. If I attach wired headphones and create a new ManagedStream using the wired headphone device and requestStart(), the onAudioReady callback is called and audio plays. If I remove the wired headphones, stop the old stream and create a new one using the phone speaker device and requestStart(), the onAudioReady callback is again called and audio plays. I can switch back and forth between wired headphones and phone speaker with no problem - requestStart() always starts the stream and the onAudioReady callback is called.

2. If I attach BLE headphones / Galaxy Buds / AirPods, stop the old managed stream and create a new one using the BLE audio device and requestStart(), the onAudioReady callback is called and audio plays. If I deactivate / disconnect the BLE audio device, stop the old (BLE Device) managed stream and create a new one using the phone speaker and requestStart(), Oboe does not seem to actually start the stream (even though createPlaybackStream() returns Result::OK), hence my onAudioReady callback is not called, hence audio does not play.

I've no idea why requestStart() doesn't actually start the managed steam in the 2nd case. What can I do to get to the root of this?

```C++
oboe::Result AudioEngine::createPlaybackStream(oboe::AudioStreamBuilder builder) {
    // get the OS API level, because some devices (Samsung S7, Nexus 5X) work better with OpenSLES even if they're on Oreo.
    char s[PROP_VALUE_MAX] = "0";
    __system_property_get("ro.build.version.sdk", s);
    int sdk_ver = atoi(s);
    LOGI("[OS API]: [%i]\n", sdk_ver);

    oboe::Result result = builder.setDirection(oboe::Direction::Output)
            ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
            ->setSharingMode(oboe::SharingMode::Exclusive)
            ->setFormat(oboe::AudioFormat::Float)
            ->setDeviceId(oboe::kUnspecified)
            ->setChannelCount(oboe::ChannelCount::Mono)
            ->setCallback(this)
            ->setSampleRate(8000)
            ->setAudioApi(sdk_ver > 27 ? oboe::AudioApi::AAudio : oboe::AudioApi::OpenSLES)
            ->openManagedStream(managedStream);

    if (result != oboe::Result::OK) {
        // try shared
        result = builder.setDirection(oboe::Direction::Output)
                ->setPerformanceMode(oboe::PerformanceMode::LowLatency)
                ->setSharingMode(oboe::SharingMode::Shared)
                ->setFormat(oboe::AudioFormat::Float)
                ->setDeviceId(oboe::kUnspecified)
                ->setChannelCount(oboe::ChannelCount::Mono)
                ->setCallback(this)
                ->setSampleRate(8000)
                ->setAudioApi(sdk_ver > 26 ? oboe::AudioApi::AAudio : oboe::AudioApi::OpenSLES)
                ->openManagedStream(managedStream);
    }

    managedStream->setBufferSizeInFrames(managedStream->getFramesPerBurst() * 2);
    return result;
}

void AudioEngine::resetAudio() {
    float s;
    while (samplesToPlay.size() > 0) {
        samplesToPlay.pop(s);
    }
}

void AudioEngine::startAudio() {
    resetAudio();
    managedStream->requestStart();
}

void AudioEngine::stopAudio() {
    managedStream->requestStop();
}

void AudioEngine::setAudioOutputDevice(int deviceID) {
    if (deviceID != audioOutputDevice) {
        oboe::StreamState inputState = oboe::StreamState::Stopping;
        oboe::StreamState nextState = oboe::StreamState::Uninitialized;
        int64_t timeoutNanos = 100 * oboe::kNanosPerMillisecond;
        stopAudio();
        LOGI("* * Stopping audio");
        oboe::Result waitResult = managedStream->waitForStateChange(inputState, &nextState,
                                                                    timeoutNanos);
        LOGI("* * Audio stopped");
        oboe::Result createResult = createPlaybackStream(
                *oboe::AudioStreamBuilder(*managedStream).setDeviceId(deviceID));

        if (oboe::Result::OK == createResult) {
            LOGI("* * New playback stream created");
            audioOutputDevice = deviceID;
            startAudio();
            LOGI("* * Restarting audio");
        } else {
            LOGE("* * Could not create playback stream, err: %s", convertToText(createResult));
        }
    } else {
        LOGI("* * audio output device already set to %i", deviceID);
    }
}

int AudioEngine::getAudioOutputDevice() {
    return audioOutputDevice;
}

oboe::DataCallbackResult AudioEngine::onAudioReady(oboe::AudioStream *audioStream, void *audioData, int32_t numFrames) {
    auto *outputData = static_cast<float *>(audioData);

    int numSamples = samplesToPlay.size();
    LOGI("numFrames: %i numSamples: %i", numFrames, numSamples);

    for (int i = 0; i < numFrames; i++) {
        float s = 0;

        if (samplesToPlay.size() > 0) {
            samplesToPlay.pop(s);
            outputData[i] = s;
        } else {
            outputData[i] = 0;
        }
    }

    return oboe::DataCallbackResult::Continue;
}
```

**Comment by philburk** [comment]
@jmzorko - We will try to reproduce this.

What Android devices have you seen this on?
Which Android versions have you seen this on?
Are you using Bluetooth A2DP or SCO? Probably A2DP. For SCO streams for telephony you need AudioManager.startBluetoothSco().

By the way, if you cannot get an EXCLUSIVE stream then you will automatically get a SHARED stream. You don't need to try again.  Also at 8000 Hz you will not get an EXCLUSIVE stream anyway.

Try checking to see if you are getting the same device ID back again. That might happen if you open a new stream too soon after a disconnect.

**Comment by jmzorko** [comment]
Hello,

I saw this most recently on my Pixel 4 (Android 10) as well as Samsuns S10+ (also on Android 10). I've other Android devices here on different versions, so I can try those. Yes, I'm using A2DP, as this isn't a telephony app.

I didn't know that Oboe itself will turn a shared stream if it can't provide an exclusive stream, nor did I know that 8khz will always result in a shared stream. Is this due to internal sample rate conversion to 44.1 or 48khz? What is the lowest sample rate (hopefully a multiple of 4) that I can specify that will result in an exclusive stream?

Regards,

John

**Comment by jmzorko** [comment]
Hey Phil,

On your suggestion, I changed my code to retry creating the ManagedStream if the deviceID I got back was the same as the old one. On my Pixel 4 (I'll try on the myriad of other Android devices I have around here), this worked. 

```C++
bool AudioEngine::setAudioOutputDevice(int deviceID) {
    if (deviceID != audioOutputDevice) {
        oboe::StreamState inputState = oboe::StreamState::Stopping;
        oboe::StreamState nextState = oboe::StreamState::Uninitialized;
        int64_t timeoutNanos = 100 * oboe::kNanosPerMillisecond;
        stopAudio();
        LOGI("* * Stopping audio");
        oboe::Result waitResult = managedStream->waitForStateChange(inputState, &nextState,
                                                                    timeoutNanos);
        LOGI("* * Audio stopped");
        oboe::Result createResult = createPlaybackStream(
                *oboe::AudioStreamBuilder(*managedStream).setDeviceId(deviceID));

        if (oboe::Result::OK == createResult) {
            if (managedStream->getDeviceId() == audioOutputDevice) {
                LOGE("* * output device of new Oboe stream matches old device %i - not starting new stream", audioOutputDevice);
                return false;
            } else {
                LOGI("* * New playback stream created");
                audioOutputDevice = deviceID;
                startAudio();
                LOGI("* * Restarting audio");
            }
        } else {
            LOGE("* * Could not create playback stream, err: %s", convertToText(createResult));
        }
    } else {
        LOGI("* * audio output device already set to %i, ignoring", deviceID);
    }

    return true;
}
```

```Java
 private void specifyAudioOutputDevice(int deviceID) {
        boolean audioOutputDeviceSetSuccessful = setAudioDevice(deviceID);

        // if we couldn't set the audio device, it may be too soon after the previous device stream was closed, so try again in 1s
        if (!audioOutputDeviceSetSuccessful) {
            Log.d("AudioService", "* * setting audio device unsuccessful (too soon after last device disconnected?), trying again in 1s");
            new Handler().postDelayed(() -> specifyAudioOutputDevice(deviceID), 1000);
        }
    }
```

However, when I eventually do get the new managed stream, it has a fairly high latency (perhaps 2-3s behind the audio it's receiving over BLE). You mentioned that configuring Oboe to create an 8khz stream isn't going to result in that stream being exclusive, so I'm wondering what I need to do to get an exclusive stream. Do I need to specify a 44.1 or 48khz sampling rate, doing the necessary upsampling of the source 4khz audio to provide this to Oboe?

Regards,

John

**Comment by philburk** [comment]
>  when I eventually do get the new managed stream, it has a fairly high latency (perhaps 2-3s behind 
> the audio being received over BLE) if the audio output device is BLE A2DP. 

I don't understand. Are you sending and receiving BLE audio at the same time? or are you comparing two output stream latencies. Please describe each stream in terms of its direction, latency and device.

> If it gets it the first time and doesn't need to retry (i.e. initial output audio device is BLE A2DP), then the latency is much lower. 

Hmm. I have seen latency increase after a rerouting. If you can give us exact steps (1,2,3) to reproduce this then we can investigate this more easily.

> I'm testing with various Apple / Samsung / Tozo / etc. AirBudsProPodsEtc. You mentioned that configuring Oboe
> to create an 8khz stream isn't going to result in that stream being exclusive, so I'm wondering what I need
> to do to get an exclusive stream. 

The term "exclusive" in AAudio refers to exclusive access to an MMAP buffer that is connected to the DSP. That only works for speakers or USB. Bluetooth will always go through a the legacy path. Exclusive can reduce the latency by 4-8 msec. Given that you are dealing with 2-3000 msec latency, exclusive access is not the issue.

> Do I need to specify a 44.1 or 48khz sampling rate, doing the necessary upsampling of the source
> 4khz audio to provide this to Oboe?

You may get lower latency if you do the resampling in Oboe. Just enable it using:

    builder.setSampleRateConversionQuality(SampleRateConversionQuality::Medium);

then set the sampleRate to match that of the content:

    builder.setSampleRate(myContentRate);

**Comment by jmzorko** [comment]
Phil,

Firstly, I sincerely appreciate your help :-)

Our application connects to our proprietary BLE 4.2 device, which sends us live 4khz 16-bit audio as well as other data. We unpack the audio as we receive it and play it out the speaker / analog headphones / BLE A2DP earbuds via Oboe, though since Oboe won't play 4khz audio, we set the sample rate on the Oboe ManagedStream to 8khz and upsample the 4khz audio to 8khz before feeding it to Oboe. So yes, we are receiving audio at 4khz from our device at the same time that we're playing it out at 8khz via Oboe.

Regarding latency, this is what we see:

Use case A: AirPods / Galaxy Buds / etc. are already paired and active:

1. App starts. We create the ManagedStream in Oboe using the deviceID of the already-active AirPods / Galaxy Buds / etc. Latency between the audio we receive from our proprietary device and the audio we hear via Oboe is 1s or less.

Use case B: AirPods / Galaxy Buds / etc. are paired but not active (i.e. still in their case):

1. App starts. We create the ManagedStream in Oboe using the phone speaker. Latency between the audio we receive from our proprietary BLE device and the audio we hear out the phone speaker is 1s or less.
2. User activates AirPods / Galaxy Buds / etc. by removing them from their case. We detect the new audio output device via AudioManager's audio device callback, stop the old (phone speaker) ManagedStream, wait for it to stop, and create a new ManagedStream using the device ID of the detected AirPods / Galaxy Buds / etc., retrying if necessary (if the new stream device ID is the same as the old). Latency between the audio that we receive and the newly-active AirPods / Galaxy Buds / etc. is 2-3s.

I am aware that the latency Oboe is trying to minimize does not include the audio we receive from our proprietary BLE device, nor the processing we do to unpack, decode and upsample it to 8khz before sending it to Oboe. I'm just trying to figure out what is causing the extra 1-2s of latency in use case B above (the route change? something else?), and if possible, how to minimize it.

Regards,

John

**Comment by philburk** [comment]
> I'm just trying to figure out what is causing the extra 1-2s of latency in use case B above

@jmzorko The original bug was that requestStart() did not start the stream. Is that still happening? If that is fixed then maybe there are two issues here. If the latency is separate then please start a new issue.

**Comment by philburk** [comment]
Closing as obsolete.
