### ISSUE TITLE
Using HFP bluetooth for output.

### ISSUE THREAD

**Issue by Artaches** [google/oboe#974]
Android version(s): 10
Android device(s): Note 9, Pixel 3a
Oboe version: 1.4 and master
App name used for testing: LiveEffect
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
We would like to run LifeEffect with the following "input --> output" devices configuration: built-in mic --> HFP bluetooth.
Note that we do NOT want the A2DP bluetooth protocol as that adds a lot of latency (300ms+ for round trip latency).

**Steps to reproduce**
Select either built-in mic for "Recording device". Select the bluetooth headphones with the "device typically used for telephony" description.
![image](https://user-images.githubusercontent.com/3443179/89822452-0e551d80-db05-11ea-899a-aa9cda01cbc1.png)

**Expected behavior**
Hearing yourself in the earbuds, with the signal recorded from the phone's mic.

**Actual behavior**
No output at all unless using A2DP profile option.

**Device**
Note 9, Pixel 3a. Both running Android 10.

**Comment by philburk** [comment]
For SCO devices you will need to call [startBluetoothSco()](https://developer.android.com/reference/android/media/AudioManager#startBluetoothSco()) in Java before opening the device.
There is an example in OboeTester, but we should add SCO support to LiveEffect.
