### ISSUE TITLE
AT&T Axia gives disconnect message when using AAudio

### ISSUE THREAD

**Issue by extreamsd** [google/oboe#978]
Android version(s): 8.1
Android device(s): Axia, QS5509A
Oboe version: 1.4.2
App name used for testing: 
Audio Evolution Mobile Studio
 
**Short description**
Directly after recording, onErrorAfterClose is called with -899, ErrorDisconnected
Only playing back does not give the problem. The user has headphones attached.
Enabling the 'Force OpenSLES' option in the app (which uses Oboe) solved the problem.

**Steps to reproduce**
Press record.

**Expected behavior**
Record.

**Actual behavior**
Recording does not start.

**Device**
QS5509A

2020:08:12 16:44:24.756 CREATE OBOE PLAY STREAM, i_nativeSampleRate = 48000 (main sr = 48000), i_nativeBufferSize = 240, i_oboeBufferSizeFactor = 2
2020:08:12 16:44:24.793 Play format = 4, usesAAudio = 1, frames/burst = 240, frames/cb = 480, buffersize = 960, capacity = 960, low latency = 1, factor = 2
2020:08:12 16:44:24.794 CREATE OBOE REC STREAM, #ch = 1, i_presetValue = 6
2020:08:12 16:44:24.822 Rec format = 2, usesAAudio = 1, frames per burst = 240, low latency = 1
2020:08:12 16:44:25.035 onErrorAfterClose -899, ErrorDisconnected
2020:08:12 16:44:25.036    was playback stream
2020:08:12 16:44:25.737 Failed to start Oboe transfer!

Although in theory, the user could have disconnected the headphones, there is only 200 milliseconds between creating the stream and the disconnect. It also happens on multiple occasions and switching to OpenSLES stops the problem from happening.

**Comment by philburk** [comment]
I do not understand the description. It says the disconnect occur after cording.
But the repro steps say the stream cannot start recording.
And the logs show a disconnect immediately after creating the stream.
What is the sequence of operations?

Are you able to reproduce this in your office?  Or are you only getting reports from users?

Can you provide a more complete log from the time the stream is opened until the disconnect occurs?
That may tell us why the disconnect occurs.

Is it possible the headset is unplugged between the open() and the start()?

Is it possible that a headphone was

**Comment by extreamsd** [comment]
> I do not understand the description. It says the disconnect occur after recording.

That's exactly the issue. I do not understand it either, but the disconnect event is fired directly after recording indeed.

m_oboeRecordingStream->start(); probably fails and results in 'Failed to start Oboe transfer!'

When recording, the app also plays back, so the 'onErrorAfterClose -899, ErrorDisconnected' is on the playback stream ('was playback stream')

I don't have the device, so I do not have more information unfortunately. If you look at the timestamps, I'd say it is very unlikely he pulled the plug and he also had this problem continuously.
builder.openStream() is called right after CREATE OBOE PLAY STREAM so that's 300 milliseconds to the disconnect.

**Comment by philburk** [comment]
There are audio modes that cause rerouting immediately after starting the stream.
That can cause a disconnect.
So this should have been solved by now.
Closing as obsolete.
