### ISSUE TITLE
Is opening 2 microphones truly supported?

### ISSUE THREAD

**Issue by lucaszanella** [google/oboe#979]
I've asked on stackoverflow and somebody said it's not: https://stackoverflow.com/a/63415915/6655884

I tried opening a built-in microphone + telephony microphone and only the first one succeds. I also tried to open a built-in microphone + headset microphone and the same happens.

The option for opening something in shared mode seems to suggest it's possible:

```
return *oboe::AudioStreamBuilder()
            .setPerformanceMode(oboe::PerformanceMode::LowLatency)
            ->setSharingMode(oboe::SharingMode::Shared);
```

but it wont work for me

**Comment by philburk** [comment]
You cannot open two microphones at once.
The oboe::SharingMode::Shared refers to whether streams can share an MMAP data path. 
It cannot grant sharing for microphones.
