### ISSUE TITLE
onAudioReady is called from two different threads, requeStstart call onAudioReady internally. Is this normal? By design，requestStart start the stream asynchronously. 

### ISSUE THREAD

**Issue by hankewei** [google/oboe#981]
Android version(s):Android7.1.1
Android device(s):
Oboe version: OboeVersion1.4.3
App name used for testing: 
(Please try to reproduce the issue using the OboeTester or an Oboe sample.)
 
**Short description**
(Please only report one bug per Issue. Do not combine multiple bugs.)

**Steps to reproduce**

**Expected behavior**

**Actual behavior**
08-17 14:41:29.517 17829 17829 I OboeAudio: openStream() OUTPUT -------- OboeVersion1.4.3 --------
08-17 14:41:29.519 17829 17829 I OboeAudio: AAudioLoader::open() could not find libaaudio.so
08-17 14:41:29.519 17829 17829 W OboeAudio: SharingMode [AudioStreamBuilder::setSharingMode()] is not supported on OpenSLES streams.
08-17 14:41:29.519 17829 17829 I OboeAudio: AudioStreamOpenSLES::open() chans=1, rate=16000
08-17 14:41:29.522 17829 17829 I OboeAudio: AudioStream format is I16
08-17 14:41:29.522 17829 17829 I OboeAudio: AudioStream sampleRate is 16000
08-17 14:41:29.522 17829 17829 I OboeAudio: AudioStream ChannelCount is 1
**08-17 14:41:33.688 17829 17891 I OboeAudio: requestStart**
**08-17 14:41:33.726 17829 17891 I OboeAudio: onAudioReady**
08-17 14:41:33.726 17829 17891 W OboeAudio: onStart
08-17 14:41:33.726 17829 17891 W OboeAudio: ret(0) < numFrames(384)
**08-17 14:41:33.727 17829 17892 I OboeAudio: onAudioReady**
08-17 14:41:33.727 17829 17892 W OboeAudio: ret(128) < numFrames(384)
08-17 14:41:33.743 17829 17892 I OboeAudio: onAudioReady
08-17 14:41:33.743 17829 17892 W OboeAudio: numFrames(384)

**Comment by philburk** [comment]
On 7.1 you will always get an OpenSL ES stream.
When starting, it will do one callback to fill a buffer then queue it to start the playback.

[code](https://github.com/google/oboe/blob/b86b0765277e6774dca1c9ae006269c951396973/src/opensles/AudioOutputStreamOpenSLES.cpp#L309)

So yes, it would be from your own thread!
