### ISSUE TITLE
A question on input preset

### ISSUE THREAD

**Issue by gavv** [google/oboe#982]
Hi, this is just a question, not a bug report.

My goal is low-latency unprocessed input from Bluetooth and wired headsets.

I've tried different input presets with the following results:

* `Generic`

  Always works.

* `VoiceRecognition`

  Always works.

* `VoiceCommunication`

  The sound is distorted.

* `Unprocessed`

  Android 9: always works.
  Android 10: works with Bluetooth headset, doesn't work with wired headset (the stream is opened successfully, but it produces silence).

* `VoicePerformance`

  Android 9: doesn't work.
  Android 10: always works.

All tests were made on the same device (Xiaomi Redmi Note 7), which initially had Android 9, but was recently upgraded to Android 10.

So it seems that the most reliable input presets are `Generic` and `VoiceRecognition`.

Actually I don't see any audible difference between `Generic`, `VoiceRecognition`, `Unprocessed` (if it works), and `VoicePerformance` (if it works) on *my device*. The latency seems to be the same or almost the same, and AUDIO_INPUT_FLAG_FAST is always present in logs (it means that FAST path is enabled, right?).

On my device `Generic` works well, but my concern is portability.

----

So here are the questions:

* Does `Generic` guarantees that FAST path is employed?

* Can `Unprocessed` and `VoicePerformance` have any difference compared to `Generic` (e.g. on different devices or Android versions)?

* Is it possible to detect what modes are actually supported? E.g. to detect that `VoicePerformance` is not supported on this device.

* In what modes `SCHED_FIFO` is used in AAudio threads?

**Comment by rpattabi** [comment]
Just want to mention our experience with input presets.

Android CDD details about how certain input presets should be handled such as  [Voice Recognition](https://source.android.com/compatibility/10/android-10-cdd#5_4_2_capture_for_voice_recognition) and [Unprocessed](https://source.android.com/compatibility/10/android-10-cdd#5_11_capture_for_unprocessed), but manufacturers don't seem to follow these specifications exactly. See issues #911 and #950.

The difference between `Generic` and `Unprocessed` is this: `Generic` may have AGC (Automatic Gain Control) and `Unprocessed` gives the raw signal without AGC and Noise Suppression.

**Comment by gavv** [comment]
For now I've worked it around by retrying different presets: Unprocessed, VoicePerformance, VoiceRecognition, and Generic. If open fails, or I don't receive any input during timeout, I switch to next preset until I find a working one. So far this approach worked good for both wired and wireless headsets on Android 9 and 10.

**Comment by philburk** [comment]
I am working on answers regarding InputPreset.

> In what modes SCHED_FIFO is used in AAudio threads?

SCHED_FIFO is needed to support small burst sizes. It is used for streams that have PerformanceMode::LowLatency.
Other streams will probably have SCHED_OTHER.
Note that the first callback from OpenSL ES may be on the app thread instead of the fast callback thread. So you should check the scheduler after a few callbacks have passed.

**Comment by philburk** [comment]
This patch improves the logging of the callback thread CPU scheduler in OboeTester.
   https://github.com/google/oboe/pull/1002

It shows the initial callback from OpenSL ES using SCHED_OTHER followed by the use of SCHED_FIFO.
