### ISSUE TITLE
Worth making a "production" build?

### ISSUE THREAD

**Issue by strommj** [google/oboe#985]
I'm wondering if it would be worth making a "production" repository/sub-module (etc.) that only includes the necessary items to run Oboe (minus all the examples).

I realize this might make it more annoying to push updates to Oboe, but It would be nice to only get important updates and not have to ignore the sub-module.

For example, what about making a sub-module/other repo called `oboe-prod`, or `oboe-light`, etc. Then users can clone the sub-module instead if they want a lighter weight (stable) repo with less updates.

**Comment by philburk** [comment]
We have been thinking of doing that.

We could extract the library into /oboe-library and leave the examples and docs in /oboe.
Or we could extract the examples and docs into /oboe-examples and leave the library in oboe.

Does anyone else think this would be helpful? Please leave a comment.

We have recently cloned Oboe into Android /external/oboe. This change would complicate that.

**Comment by dturner** [comment]
We have a "production" build already :) It's the binary release which is distributed via GMaven: https://maven.google.com/web/index.html?q=oboe#com.google.oboe:oboe

Install instructions are here: https://github.com/google/oboe/blob/master/docs/GettingStarted.md#option-1-using-pre-built-binaries-and-headers

Or you can just import the .aar file from the [releases page](https://github.com/google/oboe/releases)
