### ISSUE TITLE
Oboe stop playing audio in Xiaomi Redmi MI 8 PRO when start recording screen

### ISSUE THREAD

**Issue by rafagan** [google/oboe#986]
When user starts recording screen in Xiaomi Redmi MI 8 PRO using the native app, the audio stops playing and is necessary to restart the oboe stream to recover.

There's any hint of how to solve that?

**Comment by philburk** [comment]
There is not enough information in your bug report.

Which native app? Is it using Oboe?

What is the audio output that stops playing?

Are there any error messages in the log when the output stops?

Do you have Live Caption turned on?

**Comment by rafagan** [comment]
Hello, thank you for feedback!

1- My app is using Oboe, the Xiaomi screen recorder app probably doesn't. The screen recorder is the native one of Xiaomi Redmi MI 8 PRO.

2- Every audio played in oboe::ManagedStream. I have similar issue when user plugs in the headphones, but in this case I'm handling the broadcast receiver to recreate the ManagedStream every time user plugs in or out.

3- There isn't error messages, the sound just stops and keeps mute forever, even if I play anything after the recorder event

4- Sorry, what's Live Caption?

**Comment by philburk** [comment]
> keeps mute forever, even if I play anything after the recorder event

Does YouTube play after this? If it is also muted then this is not Oboe specific. Maybe file a bug on the public Android Bug Report page.  Then you could add a bugreport file and we could get more information.

**Comment by philburk** [comment]
See final comment of #1135 for an explanation.
