### ISSUE TITLE
Neither lowlatency PerformenceMode nor exclucive SharingMode can be obtained when using AAudio on HUAWEI P20.

### ISSUE THREAD

**Issue by HaHsu0** [google/oboe#996]
Android version(s): 10(10.0.0.176(C00E175R1P4))
Android device(s): HUAWEI P20 (EML-AL00)
Oboe version:  v1.4.2
App name used for testing: OboeTester, LiveEffect.
 
**Short description**
I set the  lowlatency PerformenceMode and exclucive SharingMode in LiveEffect , but get back the NONE PerformenceMode and shared SharingMode (not exclucive) when I choose AAudio on HUAWEI P20. On other android devices I can get the lowlatency PerformenceMode and exclucive SharingMode successfully.

**Steps to reproduce**
Open OboeTester TEST OUTPUT, choose Format PCM_I16, then click the OPEN button.
**Expected behavior**
on all the devices: get the Perf LOW_LATENCY and exclucive mode.
**Actual behavior**
On HUAWEI P20: get the Perf NONE and shared mode.
On HUAWEI P30 and ZTE A2017: get the Perf LOW_LATENCY and exclucive mode.
**Device**
HUAWEI P20 has this bug.

    
ro.product.brand HUAWEI
ro.product.manufacturer HUAWEI
ro.product.model EML-AL00
ro.product.device HWEML
ro.product.cpu.abi arm64-v8a
ro.build.description EML-AL00-user 10.0.0 HUAWEIEML-AL00 176-CHN-LGRP1 release-keys
ro.hardware kirin970
ro.hardware.chipname 
ro.arch 
"| grep aaudio"

![image](https://user-images.githubusercontent.com/70476219/91679308-8948ab80-eb7a-11ea-98e3-7e8162214ae9.png)

Looking forward to your feedback.

Thank you very much.

**Comment by philburk** [comment]
The Huawei P30 supports the LowLatency MMAP modes. But the P20 does not. 
Also Huawei has disabled the FAST mixer path on many of their devices.
If the Huawei device does not support MMAP then it probably cannot support LowLatency.

You may want to ask Huawei to enable the FAST audio path so that more devices can have low audio latency.

    https://developer.huawei.com
