### ISSUE TITLE
How stereo channel samples are organized?

### ISSUE THREAD

**Issue by ashfaq1701** [google/oboe#997]
I want to ask a silly question, please pardon if it is too basic. I want to get FFT transformation of the audio samples. My audio data is obtained just by getting the data from oboe stream (stereo) callback and storing to a file.

How the data in multiple channels are organized? Is it,

L1 R1 L2 R2 L3 R3 ... 

Like this? Or in some other manner?

I am planning to separate out the channels and apply FFT to each channel separately (to apply IIR filters, in a windowed approach).

**Comment by philburk** [comment]
Not silly. That is an important question.

Yes, the data is "interleaved". So stereo data is  "L1,R1, L2,R2" etc.
